### PR TITLE
Fix/set attributes cmd

### LINKED ISSUE #10960: Add ability to set attributes in `set` commands
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-47-generic
   * LXC version:
   * LXD version: 5.6
   * Storage backend in use: zfs

# Issue description

What I’m looking for is something like:

`
lxc <object> set description "My Nice Object"
`

that would generally work for all the objects: storage pools, networks, projects, profiles, containers…

# Steps to reproduce

Just run the above command, that fails.

# Information to attach

### PR DESCRIPTION
**Pull request by gabrielmougard**
closes #10960

### CODE REVIEW

**Comment by monstermunchkin** [comment]
@gabrielmougard could you please add some tests?

File: lxc/cluster.go [hunk 1]
```diff
@@ -303,6 +308,7 @@ func (c *cmdClusterGet) Command() *cobra.Command {
 	cmd.Short = i18n.G("Get values for cluster member configuration keys")
 	cmd.Long = cli.FormatSection(i18n.G("Description"), cmd.Short)
 
+	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Get the key as an cluster attribute"))
```
Comment (monstermunchkin) [inline lxc/cluster.go:311]:
```suggestion
	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Get the key as a cluster attribute"))
```

File: lxc/cluster.go [hunk 2]
```diff
@@ -402,6 +457,7 @@ func (c *cmdClusterUnset) Command() *cobra.Command {
 	cmd.Short = i18n.G("Unset a cluster member's configuration keys")
 	cmd.Long = cli.FormatSection(i18n.G("Description"), cmd.Short)
 
+	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Unset the key as an cluster attribute"))
```
Comment (monstermunchkin) [inline lxc/cluster.go:460]:
```suggestion
	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Unset the key as a cluster attribute"))
```

File: lxc/network.go [hunk 3]
```diff
@@ -1254,6 +1307,10 @@ func (c *cmdNetworkUnset) Run(cmd *cobra.Command, args []string) error {
 		return err
 	}
 
+	if c.flagIsAttribute {
+		c.networkSet.flagIsAttribute = true
+	}
```
Comment (monstermunchkin) [inline lxc/network.go:1312]:
```suggestion
	c.networkSet.flagIsAttribute = c.flagIsAttribute
```

File: lxc/network_acl.go [hunk 4]
```diff
@@ -255,13 +257,17 @@ func (c *cmdNetworkACLShowLog) Run(cmd *cobra.Command, args []string) error {
...
+	flagIsAttribute bool
 }
 
 func (c *cmdNetworkACLGet) Command() *cobra.Command {
 	cmd := &cobra.Command{}
 	cmd.Use = usage("get", i18n.G("[<remote>:]<ACL> <key>"))
 	cmd.Short = i18n.G("Get values for network ACL configuration keys")
 	cmd.Long = cli.FormatSection(i18n.G("Description"), i18n.G("Get values for network ACL configuration keys"))
+
+	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Get the key as an network ACL attribute"))
```
Comment (monstermunchkin) [inline lxc/network_acl.go:270]:
```suggestion
	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Get the key as a network ACL attribute"))
```

File: lxc/network_acl.go [hunk 5]
```diff
@@ -466,6 +519,10 @@ func (c *cmdNetworkACLUnset) Run(cmd *cobra.Command, args []string) error {
 		return err
 	}
 
+	if c.flagIsAttribute {
+		c.networkACLSet.flagIsAttribute = true
+	}
```
Comment (monstermunchkin) [inline lxc/network_acl.go:524]:
```suggestion
	c.networkACLSet.flagIsAttribute = c.flagIsAttribute
```

File: lxc/network_forward.go [hunk 6]
```diff
@@ -360,9 +367,21 @@ func (c *cmdNetworkForwardGet) Run(cmd *cobra.Command, args []string) error {
...
-	for k, v := range forward.Config {
-		if k == args[2] {
-			fmt.Printf("%s\n", v)
+	if c.flagIsAttribute {
+		fieldValue, ok := reflect.TypeOf(forward).FieldByNameFunc(func(fieldNameCmp string) bool {
+			field, _ := reflect.TypeOf(forward).FieldByName(fieldNameCmp)
+			return field.Tag.Get("json") == args[2]
+		})
+		if !ok {
+			return fmt.Errorf(i18n.G("The attribute %q does not exist on network forwardd %q"), args[2], resource.name)
```
Comment (monstermunchkin) [inline lxc/network_forward.go:376]:
```suggestion
			return fmt.Errorf(i18n.G("The attribute %q does not exist on network forward %q"), args[2], resource.name)
```

File: lxc/network_forward.go [hunk 7]
```diff
@@ -470,6 +524,10 @@ func (c *cmdNetworkForwardUnset) Run(cmd *cobra.Command, args []string) error {
 		return err
 	}
 
+	if c.flagIsAttribute {
+		c.networkForwardSet.flagIsAttribute = true
+	}
```
Comment (monstermunchkin) [inline lxc/network_forward.go:529]:
```suggestion
	c.networkForwardSet.flagIsAttribute = c.flagIsAttribute
```

File: lxc/network_load_balancer.go [hunk 8]
```diff
@@ -472,6 +525,10 @@ func (c *cmdNetworkLoadBalancerUnset) Run(cmd *cobra.Command, args []string) err
 		return err
 	}
 
+	if c.flagIsAttribute {
+		c.networkLoadBalancerSet.flagIsAttribute = true
+	}
```
Comment (monstermunchkin) [inline lxc/network_load_balancer.go:530]:
```suggestion
	c.networkLoadBalancerSet.flagIsAttribute = c.flagIsAttribute
```

File: lxc/network_peer.go [hunk 9]
```diff
@@ -463,6 +516,10 @@ func (c *cmdNetworkPeerUnset) Run(cmd *cobra.Command, args []string) error {
 		return err
 	}
 
+	if c.flagIsAttribute {
+		c.networkPeerSet.flagIsAttribute = true
+	}
```
Comment (monstermunchkin) [inline lxc/network_peer.go:521]:
```suggestion
	c.networkPeerSet.flagIsAttribute = c.flagIsAttribute
```

File: lxc/network_zone.go [hunk 10]
```diff
@@ -409,6 +463,10 @@ func (c *cmdNetworkZoneUnset) Run(cmd *cobra.Command, args []string) error {
 		return err
 	}
 
+	if c.flagIsAttribute {
+		c.networkZoneSet.flagIsAttribute = true
+	}
```
Comment (monstermunchkin) [inline lxc/network_zone.go:468]:
```suggestion
	c.networkZoneSet.flagIsAttribute = c.flagIsAttribute
```

File: lxc/network_zone.go [hunk 11]
```diff
@@ -964,6 +1072,10 @@ func (c *cmdNetworkZoneRecordUnset) Run(cmd *cobra.Command, args []string) error
 		return err
 	}
 
+	if c.flagIsAttribute {
+		c.networkZoneRecordSet.flagIsAttribute = true
+	}
```
Comment (monstermunchkin) [inline lxc/network_zone.go:1077]:
```suggestion
	c.networkZoneRecordSet.flagIsAttribute = c.flagIsAttribute
```

File: lxc/profile.go [hunk 12]
```diff
@@ -900,6 +953,10 @@ func (c *cmdProfileUnset) Run(cmd *cobra.Command, args []string) error {
 		return err
 	}
 
+	if c.flagIsAttribute {
+		c.profileSet.flagIsAttribute = true
+	}
```
Comment (monstermunchkin) [inline lxc/profile.go:958]:
```suggestion
	c.profileSet.flagIsAttribute = c.flagIsAttribute
```

File: lxc/project.go [hunk 13]
```diff
@@ -637,6 +688,10 @@ func (c *cmdProjectUnset) Run(cmd *cobra.Command, args []string) error {
 		return err
 	}
 
+	if c.flagIsAttribute {
+		c.projectSet.flagIsAttribute = true
+	}
```
Comment (monstermunchkin) [inline lxc/project.go:693]:
```suggestion
	c.projectSet.flagIsAttribute = c.flagIsAttribute
```

File: lxc/storage.go [hunk 14]
```diff
@@ -810,6 +862,7 @@ func (c *cmdStorageUnset) Command() *cobra.Command {
 		`Unset storage pool configuration keys`))
 
 	cmd.Flags().StringVar(&c.storage.flagTarget, "target", "", i18n.G("Cluster member name")+"``")
+	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Get the key as a storage attribute"))
```
Comment (monstermunchkin) [inline lxc/storage.go:865]:
```suggestion
	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Unset the key as a storage attribute"))
```

File: lxc/storage.go [hunk 15]
```diff
@@ -822,6 +875,10 @@ func (c *cmdStorageUnset) Run(cmd *cobra.Command, args []string) error {
 		return err
 	}
 
+	if c.flagIsAttribute {
+		c.storageSet.flagIsAttribute = true
+	}
```
Comment (monstermunchkin) [inline lxc/storage.go:880]:
```suggestion
	c.storageSet.flagIsAttribute = c.flagIsAttribute
```

File: lxc/storage_bucket.go [hunk 16]
```diff
@@ -672,6 +723,10 @@ func (c *cmdStorageBucketUnset) Run(cmd *cobra.Command, args []string) error {
 		return err
 	}
 
+	if c.flagIsAttribute {
+		c.storageBucketSet.flagIsAttribute = true
+	}
```
Comment (monstermunchkin) [inline lxc/storage_bucket.go:728]:
```suggestion
	c.storageBucketSet.flagIsAttribute = if c.flagIsAttribute
```

File: lxc/storage_volume.go [hunk 17]
```diff
@@ -1751,6 +1769,7 @@ lxc storage volume set default virtual-machine/data snapshots.expiry=7d
     Sets the snapshot expiration period for a virtual machine "data" in pool "default" to seven days.`))
 
 	cmd.Flags().StringVar(&c.storage.flagTarget, "target", "", i18n.G("Cluster member name")+"``")
+	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Get the key as an instance attribute"))
```
Comment (monstermunchkin) [inline lxc/storage_volume.go:1772]:
```suggestion
	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Set the key as a storage volume attribute"))
```

File: lxc/storage_volume.go [hunk 18]
```diff
@@ -1964,6 +2016,10 @@ func (c *cmdStorageVolumeUnset) Run(cmd *cobra.Command, args []string) error {
 		return err
 	}
 
+	if c.flagIsAttribute {
+		c.storageVolumeSet.flagIsAttribute = true
+	}
```
Comment (monstermunchkin) [inline lxc/storage_volume.go:2021]:
```suggestion
	c.storageVolumeSet.flagIsAttribute = c.flagIsAttribute
```

File: lxc/cluster.go [hunk 19]
```diff
@@ -350,6 +373,7 @@ func (c *cmdClusterSet) Command() *cobra.Command {
 	cmd.Short = i18n.G("Set a cluster member's configuration keys")
 	cmd.Long = cli.FormatSection(i18n.G("Description"), cmd.Short)
 
+	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Set the key as an instance attribute"))
```
Comment (monstermunchkin) [inline lxc/cluster.go:376]:
```suggestion
	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Set the key as a cluster attribute"))
```

File: lxc/cluster.go [hunk 20]
```diff
@@ -414,6 +470,10 @@ func (c *cmdClusterUnset) Run(cmd *cobra.Command, args []string) error {
 		return err
 	}
 
+	if c.flagIsAttribute {
+		c.clusterSet.flagIsAttribute = true
+	}
```
Comment (monstermunchkin) [inline lxc/cluster.go:475]:
```suggestion
	c.clusterSet.flagIsAttribute = if c.flagIsAttribute
```

**Review by monstermunchkin — CHANGES_REQUESTED** [review]

File: lxc/utils.go [hunk 21]
```diff
@@ -239,6 +242,21 @@ func getConfig(args ...string) (map[string]string, error) {
...
+// stringToTimeHookFunc is a custom decoding hook that converts string values to time.Time using the given layout.
+func stringToTimeHookFunc(layout string) mapstructure.DecodeHookFuncType {
+	return func(from reflect.Type, to reflect.Type, data interface{}) (interface{}, error) {
+		if from.Kind() == reflect.String && to == reflect.TypeOf(time.Time{}) {
+			strValue := data.(string)
+			t, err := time.Parse(layout, strValue)
+			if err != nil {
+				return nil, err
+			}
+			return t, nil
```
Comment (monstermunchkin) [inline lxc/utils.go:254]:
```suggestion
			}

			return t, nil
```

File: lxc/utils.go [hunk 22]
```diff
@@ -239,6 +242,21 @@ func getConfig(args ...string) (map[string]string, error) {
...
+		}
+		return data, nil
```
Comment (monstermunchkin) [inline lxc/utils.go:256]:
```suggestion
		}

		return data, nil
```

**Review by monstermunchkin — CHANGES_REQUESTED** [review]

**Comment by ru-fu** [comment]
Should this be property instead of attribute?
https://documentation.ubuntu.com/lxd/en/latest/explanation/instance_config/

We only have it explicitly documented for instances, but in the docs, we're trying to be consistent in calling everything under `config` options/configuration options and everything on top level properties.

**Comment by monstermunchkin** [comment]
> Should this be property instead of attribute? https://documentation.ubuntu.com/lxd/en/latest/explanation/instance_config/
> 

Yes, we should call it `property`.

**Comment by ru-fu** [comment]
Thanks!
Can you add a "Configure instance properties" section to https://documentation.ubuntu.com/lxd/en/latest/howto/instances_configure/ and update https://documentation.ubuntu.com/lxd/en/latest/explanation/instance_config/ to link to that section for instance properties?

We should probably also update the other configuration how-tos, but we can do that later if needed.

**Review by tomponline — CHANGES_REQUESTED** [review]
Please can we have some tests added for this functionality too please.

**Review by monstermunchkin — CHANGES_REQUESTED** [review]

**Review by tomponline — CHANGES_REQUESTED** [review]
Please can you use the normal [i18n: Update translation templates](https://github.com/canonical/lxd/commit/d4550f9178d0760e960eb641cff1a1ea67b9ffd6) message style (without typo ;) too) when updating i18n.

**Comment by tomponline** [comment]
@ru-fu I expect that we should update the docs for this new CLI feature, do you have a preference as to where?

**Comment by tomponline** [comment]
@ru-fu oh wait you already did in https://github.com/canonical/lxd/pull/11961#issuecomment-1630853254, @gabrielmougard please can you add. thanks.

**Review by tomponline — CHANGES_REQUESTED** [review]
Please can you split your Go commits by file so its possible to backport the ones that are supported by the LTS.

File: lxc/utils.go [hunk 23]
```diff
@@ -239,6 +243,178 @@ func getConfig(args ...string) (map[string]string, error) {
 	return values, nil
 }
 
+// stringToTimeHookFunc is a custom decoding hook that converts string values to time.Time using the given layout.
```
Comment (tomponline) [inline lxc/utils.go:246]: Can you move these functions into called something like utils_properties.go to help organise the utils a bit better.

File: lxc/utils.go [hunk 24]
```diff
@@ -239,6 +243,178 @@ func getConfig(args ...string) (map[string]string, error) {
...
+	}
+
+	if !ok {
+		return nil, fmt.Errorf("The property with tag %q does not exist", tag)
+	}
+
+	return res, nil
+}
+
+// setFieldByJsonTag sets the value of a struct field by its JSON tag.
```
Comment (tomponline) [inline lxc/utils.go:342]: These 3 functions below seem to be good candidates for having some unit tests as they are self-contained, especially as they are dealing with different data types using reflect.

**Comment by tomponline** [comment]
@gabrielmougard looks like this needs a rebase now.

**Review by tomponline — CHANGES_REQUESTED** [review]
As discussed lets add a test for setting/getting the instance snapshot and storage volume snapshot expiry times.

**Review by ru-fu — CHANGES_REQUESTED** [review]

File: test/suites/config.sh [hunk 25]
```diff
@@ -287,6 +287,72 @@ test_config_edit() {
...
+  lxc config unset foo/s1 expires_at --property
+  lxc config show foo/s1 | grep -q "expires_at: 0001-01-01T00:00:00Z"
+
+
+  # Create a storage pool, create a volume snapshot and set its expiration timestamp
+
+  # shellcheck disable=2039,3043
+  local LXD_STORAGE_DIR lxd_backend
+
+  lxd_backend=$(storage_backend "$LXD_DIR")
```
Comment (tomponline) [inline test/suites/config.sh:328]: I think a default pool for the active storage driver is created by default for all tests, so I dont see why we need to create one here.

File: doc/howto/instances_configure.md [hunk 26]
```diff
@@ -32,6 +32,21 @@ Others are updated only when the instance is restarted.
 See the "Live update" column in the {ref}`instance-options` tables for information about which options are applied immediately while the instance is running.
 ```
 
+(instances-configure-properties)=
+## Configure instance properties
+To update instance properties after the instance is created, use the `lxc config set` command with the `--property` flag.
+Specify the instance name and the key and value of the instance property:
+
+    lxc config set <instance_name> <option_key>=<option_value> <option_key>=<option_value> ... --property
```
[the remark this answers is not in the document]
Comment (gabrielmougard) [reply doc/howto/instances_configure.md:40]: Then the command will output an error saying that the `<option_key>` has not been found

**Review by ru-fu — APPROVED** [review]
Docs look good.

File: doc/howto/instances_configure.md (hunk 26 above)
[the remark this answers is not in the document]
Comment (ru-fu) [reply doc/howto/instances_configure.md]: > Then the command will output an error saying that the `<option_key>` has not been found

How much effort would it be to check if the key exists as an option, and in that case report that back to the user?

We're making a difference between properties and options in the docs, but we cannot necessarily expect users to be aware of the difference. And I could imagine users getting quite confused if we're telling them that one of the keys, which they have used before, suddenly can't be found anymore.

**Comment by tomponline** [comment]
static analysis failing

File: test/suites/config.sh [hunk 27]
```diff
@@ -287,6 +287,60 @@ test_config_edit() {
...
+  lxc storage volume snapshot "${storage_pool}" "${storage_volume}"
+
+  lxc storage volume set "${storage_pool}" "${storage_volume}"/snap0 expires_at="2024-03-23T17:38:37.753398689-04:00" --property
+  lxc storage volume show "${storage_pool}" "${storage_volume}/snap0" | grep 'expires_at: 2024-03-23T17:38:37.753398689-04:00'
+  lxc storage volume unset "${storage_pool}" "${storage_volume}"/snap0 expires_at --property
+  lxc storage volume show "${storage_pool}" "${storage_volume}/snap0" | grep 'expires_at: 0001-01-01T00:00:00Z'
+
+  lxc delete -f c1
+  lxc storage volume delete "${storage_pool}" "${storage_volume}"
+  lxc delete foo
```
Comment (tomponline) [inline test/suites/config.sh:341]: lets use `-f` here for consistency
