### PR TITLE
Use shorter virtiofsd and swtpm socket paths

### LINKED ISSUE #12539: Failure to start LXD VM due to long UNIX Socket Path
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04
 * The output of "lxc info":
```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
- clustering_update_cert
- storage_api_project
- server_instance_driver_operational
- server_supported_storage_drivers
- event_lifecycle_requestor_address
- resources_gpu_usb
- clustering_evacuation
- network_ovn_nat_address
- network_bgp
- network_forward
- custom_volume_refresh
- network_counters_errors_dropped
- metrics
- image_source_project
- clustering_config
- network_peer
- linux_sysctl
- network_dns
- ovn_nic_acceleration
- certificate_self_renewal
- instance_project_move
- storage_volume_project_move
- cloud_init
- network_dns_nat
- database_leader
- instance_all_projects
- clustering_groups
- ceph_rbd_du
- instance_get_full
- qemu_metrics
- gpu_mig_uuid
- event_project
- clustering_evacuation_live
- instance_allow_inconsistent_copy
- network_state_ovn
- storage_volume_api_filtering
- image_restrictions
- storage_zfs_export
- network_dns_records
- storage_zfs_reserve_space
- network_acl_log
- storage_zfs_blocksize
- metrics_cpu_seconds
- instance_snapshot_never
- certificate_token
- instance_nic_routed_neighbor_probe
- event_hub
- agent_nic_config
- projects_restricted_intercept
- metrics_authentication
- images_target_project
- cluster_migration_inconsistent_copy
- cluster_ovn_chassis
- container_syscall_intercept_sched_setscheduler
- storage_lvm_thinpool_metadata_size
- storage_volume_state_total
- instance_file_head
- resources_pci_vpd
- qemu_raw_conf
- storage_cephfs_fscache
- vsock_api
- storage_volumes_all_projects
- projects_networks_restricted_access
- cluster_join_token_expiry
- remote_token_expiry
- init_preseed
- cpu_hotplug
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICAjCCAYegAwIBAgIRAJrMJKkDW+Ad9tsMyXY1mAowCgYIKoZIzj0EAwMwMzEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEBzcXVp
    ZDAeFw0yMzExMjAwNzIyNDdaFw0zMzExMTcwNzIyNDdaMDMxHDAaBgNVBAoTE2xp
    bnV4Y29udGFpbmVycy5vcmcxEzARBgNVBAMMCnJvb3RAc3F1aWQwdjAQBgcqhkjO
    PQIBBgUrgQQAIgNiAAQcYTk+Me71KxfYD72/l7BxN6o5wSay5BZIt2g49zK5iGHM
    v1b1hh+O4lzAmXV4xEwSoT+B1VQ1/XYw+9M3k/W/YYS4MrjH5gBBooiRHFVuFVnt
    vSpdCHiKQERqiXF2QlmjXzBdMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMCgGA1UdEQQhMB+CBXNxdWlkhwR/AAABhxAA
    AAAAAAAAAAAAAAAAAAABMAoGCCqGSM49BAMDA2kAMGYCMQC+hnOZZ4MEpbgEhyS6
    MQqI72Px8NW+o2LdIWU78gJ/8THkvhFzU4U99b4WBYnTroMCMQC0EUqFzP77bOCp
    WJVQtF6HK146l/639ED5Gp8p10q8Up9uV0/bw6kUYXYSIERLIJs=
    -----END CERTIFICATE-----
  certificate_fingerprint: f336157139686162d891253af88a84f732ae2d6c029651e081306b2a563d27aa
  driver: lxc | qemu
  driver_version: 5.0.2 | 7.1.0
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.15.0-87-generic
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "22.04"
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_name: squid
  server_pid: 12638
  server_version: 5.0.2
  storage: dir
  storage_version: "1"
  storage_supported_drivers:
  - name: lvm
    version: 2.03.07(2) (2019-11-30) / 1.02.167 (2019-11-30) / 4.45.0
    remote: false
  - name: zfs
    version: 2.1.5-1ubuntu6~22.04.1
    remote: false
  - name: btrfs
    version: 5.4.1
    remote: false
  - name: ceph
    version: 15.2.17
    remote: true
  - name: cephfs
    version: 15.2.17
    remote: true
  - name: cephobject
    version: 15.2.17
    remote: true
  - name: dir
    version: "1"
    remote: false
```

# Issue description

When adding a disk to an LXD VM instance using a directory on the host with a rather long name, the instance fails to start because the UNIX socket path is too long:

```
ubuntu@ubuntu:~$ sudo cat /var/snap/lxd/common/lxd/logs/stg-ps6-small2-3-166d3e5f-ba4f-4cd0-817e-1ba1994e8c8d/qemu.log
qemu-system-x86_64:/var/snap/lxd/common/lxd/logs/stg-ps6-small2-3-166d3e5f-ba4f-4cd0-817e-1ba1994e8c8d/qemu.conf:254: UNIX socket path '/var/snap/lxd/common/lxd/devices/stg-ps6-small2-3-166d3e5f-ba4f-4cd0-817e-1ba1994e8c8d/virtio-fs.metrics.sock' is too long
Path must be less than 108 bytes
```
The problem occurred in an OpenStack VM (instance of a GitHub self-hosted runner charm), but could be reproduced locally inside a multipass vm.

# Steps to reproduce

1.  `lxc launch ubuntu:22.04 stg-ps6-small2-3-166d3e5f-ba4f-4cd0-817e-1ba1994e8c8d --vm`
2.  `lxc stop stg-ps6-small2-3-166d3e5f-ba4f-4cd0-817e-1ba1994e8c8d`
3. `mkdir /home/ubuntu/shared_fs`
4. `lxc config device add stg-ps6-small2-3-166d3e5f-ba4f-4cd0-817e-1ba1994e8c8d metrics disk source=/home/ubuntu/shared_fs/ path=/metrics-exchange`
5. `lxc start stg-ps6-small2-3-166d3e5f-ba4f-4cd0-817e-1ba1994e8c8d`
6. `sudo cat /var/snap/lxd/common/lxd/logs/stg-ps6-small2-3-166d3e5f-ba4f-4cd0-817e-1ba1994e8c8d/qemu.log`

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by hamistao**
Fixes #12539.
These changes generally include getting the file descriptor of the directory of a socket's file to use an alternative shorter path to the same socket. This same fix is applied during VM start (with disk virtiofsd sockets, qemu config virtiofsd sockets and the swtpm sockets), and when hotplugging a disk on a VM (with disk virtiofsd sockets)

### CODE REVIEW

File: lxd/instance/drivers/driver_qemu.go [hunk 1]
```diff
@@ -1468,7 +1468,7 @@ func (d *qemu) start(stateful bool, op *operationlock.InstanceOperation) error {
 	}
 
 	// Generate the QEMU configuration.
-	confFile, monHooks, err := d.generateQemuConfigFile(cpuInfo, mountInfo, qemuBus, vsockFD, devConfs, &fdFiles)
+	confFile, monHooks, err := d.generateQemuConfigFile(cpuInfo, mountInfo, qemuBus, unixListener, vsockFD, devConfs, &fdFiles)
```
Comment (roosterfish) [inline lxd/instance/drivers/driver_qemu.go:1471]: I thought we discussed using an `int` here to pass the fd to replicate the same that is already done for the vsock. Have you tried this?

File: lxd/instance/drivers/driver_qemu.go [hunk 2]
```diff
@@ -3338,6 +3338,14 @@ func (d *qemu) generateQemuConfigFile(cpuInfo *cpuTopology, mountInfo *storagePo
 	// This is used by the lxd-agent in preference to 9p (due to its improved performance) and in scenarios
 	// where 9p isn't available in the VM guest OS.
 	configSockPath, _ := d.configVirtiofsdPaths()
+
+	socketFile, err := listener.(*net.UnixListener).File()
```
Comment (roosterfish) [inline lxd/instance/drivers/driver_qemu.go:3342]: This can then be moved outside of `generateQemuConfigFile` by just passing the fd returned from `addFileDescriptor`.

File: lxd/instance/drivers/driver_qemu_templates.go [hunk 3]
```diff
@@ -681,6 +682,7 @@ func qemuHostDrive(opts *qemuHostDriveOpts) []cfgSection {
 			entries: []cfgEntry{
 				{key: "backend", value: "socket"},
 				{key: "path", value: opts.path},
+				{key: "fd", value: opts.fd},
```
Comment (roosterfish) [inline lxd/instance/drivers/driver_qemu_templates.go:685]: Wouldn't this write both the `path` and `fd` setting to the final config file? It looks that only one of them should be there at a given time. Otherwise you might still encounter the original bug as the too long socket path is still in there.

**Review by roosterfish — CHANGES_REQUESTED** [review]

**Comment by tomponline** [comment]
Has the idea of passing an FD been proved to work? Before we get too bogged down in code style etc?

File: lxd/instance/drivers/driver_qemu_templates.go (hunk 3 above)
Comment (hamistao) [reply lxd/instance/drivers/driver_qemu_templates.go:685]: Actually I should have just removed the line that includes the path because it serves no purpose(probably because in this case the path is empty). This is how the `chardev` section in `qemu.config` looks like.
```
# metrics drive (virtio-fs)
[chardev "lxd_metrics"]
backend = "socket"
fd = "6"
```

File: lxd/instance/drivers/driver_qemu.go (hunk 1 above)
Comment (hamistao) [reply lxd/instance/drivers/driver_qemu.go]: if you mean using `nextVsockID()`, I don't see how I can use it to point qemu to the socket created for viriofsd.

Comment (roosterfish) [reply lxd/instance/drivers/driver_qemu.go]: I meant passing the fd directly as `int` like it's done for the `vsockFD` variable instead of the listener. This would better fit to the arguments which are currently passed into `generateQemuConfigFile`.

But it's of course not related to the error you are facing now.

**Comment by roosterfish** [comment]
Another thing you could try is experimenting with the `server` setting for the `chardev` as this is set to `true` by default and I am not sure if qemu isn't the client in this case? 

See https://www.qemu.org/docs/master/interop/qemu-qmp-ref.html#qapidoc-1240.

**Comment by tomponline** [comment]
@hamistao once this is ready for review please can you mark it as ready for review and let me know. Thanks

**Comment by hamistao** [comment]
@tomponline I found that the same problem was ocurring in other situations(when attaching a device to a running instance and when adding a tpm device) so I changed back to draft to include those additional fixes, will be pushing the next version in a few minutes.

**Comment by hamistao** [comment]
@tomponline this is ready for review

File: lxd/instance/drivers/driver_qemu.go [hunk 4]
```diff
@@ -3097,6 +3097,19 @@ func (d *qemu) deviceBootPriorities(base int) (map[string]int, error) {
 	return sortedDevs, nil
 }
 
+// shortenedSocketPath creates an alternative path to a socketTrickery by using the file descriptor to the directoryof the socket file.
```
Comment (tomponline) [inline lxd/instance/drivers/driver_qemu.go:3119]: typo in the description `directoryof` also you mention > 107 chars here but earlier in this PR you also corrected a similar comment to > 108 chars, which is the correct one?

File: lxd/instance/drivers/driver_qemu.go [hunk 5]
```diff
@@ -3097,6 +3097,19 @@ func (d *qemu) deviceBootPriorities(base int) (map[string]int, error) {
...
+// Used to handle paths > 107 chars.
+func (d *qemu) shortenedSocketPath(originalSockPath string, openFiles *[]*os.File, fdFiles *[]*os.File) (string, error) {
```
Comment (roosterfish) [inline lxd/instance/drivers/driver_qemu.go:3121]: Isn't the slice always passed as reference? I am wondering if you need the extra pointer here for the two args.

File: lxd/instance/drivers/driver_qemu.go [hunk 6]
```diff
@@ -3097,6 +3097,19 @@ func (d *qemu) deviceBootPriorities(base int) (map[string]int, error) {
...
+	configSockDir, err := os.Open(filepath.Dir(originalSockPath))
+	if err != nil {
+		return "", fmt.Errorf("Couldn't open device socket directory %q: %s", filepath.Dir(originalSockPath), err)
```
Comment (roosterfish) [inline lxd/instance/drivers/driver_qemu.go:3124]: Make sure to also wrap the `err` from the `os.Open()` call using `%w`.

File: lxd/device/tpm.go [hunk 7]
```diff
@@ -217,13 +217,24 @@ func (d *tpm) startVM() (*deviceConfig.RunConfig, error) {
 		},
 	}
 
-	proc, err := subprocess.NewProcess("swtpm", []string{"socket", "--tpm2", "--tpmstate", fmt.Sprintf("dir=%s", tpmDevPath), "--ctrl", fmt.Sprintf("type=unixio,path=%s", socketPath)}, "", "")
+	configSockDir, err := os.Open(tpmDevPath)
```
Comment (tomponline) [inline lxd/device/tpm.go:220]: This section could do with a comment explaining why the complexity is here. (i.e to overcome longer path names)

File: lxd/instance/drivers/driver_qemu.go [hunk 8]
```diff
@@ -4708,7 +4718,7 @@ func (d *qemu) addUSBDeviceConfig(usbDev deviceConfig.USBDeviceItem) (monitorHoo
 	return monHook, nil
 }
 
-func (d *qemu) addTPMDeviceConfig(cfg *[]cfgSection, tpmConfig []deviceConfig.RunConfigItem) error {
+func (d *qemu) addTPMDeviceConfig(cfg *[]cfgSection, tpmConfig []deviceConfig.RunConfigItem, fdFiles *[]*os.File) error {
```
Comment (roosterfish) [inline lxd/instance/drivers/driver_qemu.go]: Same comment here regarding the pointer on the slice.

File: lxd/instance/drivers/driver_qemu.go [hunk 9]
```diff
@@ -1207,6 +1207,16 @@ func (d *qemu) start(stateful bool, op *operationlock.InstanceOperation) error {
 		}
 	}()
 
+	// Define a set of files to open that must wait until QEMU is called to be closed.
+	openFiles := make([]*os.File, 0)
```
Comment (tomponline) [inline lxd/instance/drivers/driver_qemu.go:1211]: Why do we need another list of os.Files, the existing fdFiles list is kept open until qemu is started and then closed afterwards?

https://github.com/canonical/lxd/blob/main/lxd/instance/drivers/driver_qemu.go#L1200-L1208

Comment (roosterfish) [reply lxd/instance/drivers/driver_qemu.go:1211]: @tomponline you are beating me in doing the review :) But I was also confused about the difference to `fdFiles`.

File: lxd/instance/drivers/driver_qemu.go [hunk 10]
```diff
@@ -1207,6 +1207,16 @@ func (d *qemu) start(stateful bool, op *operationlock.InstanceOperation) error {
 		}
 	}()
 
+	// Define a set of files to open that must wait until QEMU is called to be closed.
```
Comment (tomponline) [inline lxd/instance/drivers/driver_qemu.go:1210]: In general I would prefer to see the commits in this PR further broken down into smaller logical commits.

For example, this commit ` lxd/instance/drivers: Close files opened during socket path handling ` is altering the behaviour of both the config drive and TPM devices - it would be preferable to see these as separate commits so its easier to reason about.

Also the PR title `Use shorter virtiofsd socket paths` seems now to be out of date compared with the current implementation. 

Thanks

**Review by roosterfish — CHANGES_REQUESTED** [review]

File: lxd/instance/drivers/driver_qemu.go [hunk 11]
```diff
@@ -2195,7 +2195,16 @@ func (d *qemu) deviceAttachPath(deviceName string, configCopy map[string]string,
 		return fmt.Errorf("Failed to connect to QMP monitor: %w", err)
 	}
```
Comment (tomponline) [inline lxd/instance/drivers/driver_qemu.go:2197]: Keeping in mind that commits and their messages can be backported out of context of their original PR, messages like "Applying similar fix to ..." are not too helpful to the person backporting/reading them.

Please can you keep the commit messages descriptive to the specific logical change being made.

Thanks

File: lxd/instance/drivers/driver_qemu.go (hunk 5 above)
Comment (tomponline) [reply lxd/instance/drivers/driver_qemu.go:3121]: I've used a pointer to a slice here to be sure that when we are appending to it the resulting slice is stored back at the original location. I understand a Go slice is an internal struct that is copied when passed by value, but which internally has a pointer to a backing array. This is why updating the entry of a slice that is passed by value into a function can be seen in the original slice variable by the caller.

However if `append` internally creates a new array, the pointer will only be updated in the returned slice value from append, which unless assigned back to the original slice value will not be reflected in the caller.

This would have unpredictable consequences depending on when Go decides to expand the slice using a new backing array.

See https://go.dev/play/p/4u2zb7QVy_8

**Review by tomponline — CHANGES_REQUESTED** [review]
Please can you alter the PR based on the comments. Thanks!

File: lxd/instance/drivers/driver_qemu.go (hunk 4 above)
Comment (hamistao) [reply lxd/instance/drivers/driver_qemu.go:3119]: `> 108` is the correct one, I think I followed the existing comment and later found that 108 is the actual limit

Comment (hamistao) [reply lxd/instance/drivers/driver_qemu.go:3119]: I thought the tests caught typos in comments too, may be worth it to add this check in the future

File: lxd/instance/drivers/driver_qemu.go (hunk 9 above)
Comment (hamistao) [reply lxd/instance/drivers/driver_qemu.go:1211]: `fdFiles` includes all the files that qemu has to have file descriptors for, as can be seen [here](https://github.com/canonical/lxd/blob/main/lxd/instance/drivers/driver_qemu.go#L1658). `openFIles` are just the directories that are opened to get a shorter path to a socket. But indeed all the files that are included in `openFiles` are also included in `fdFIles` so it doesn't serve any purpose.

File: lxd/instance/drivers/driver_qemu.go (hunk 5 above)
Comment (hamistao) [reply lxd/instance/drivers/driver_qemu.go:3121]: Maybe I could add a comment so it is clearer for anyone who reads this secction from now on?

Comment (roosterfish) [reply lxd/instance/drivers/driver_qemu.go:3121]: @tomponline ah yes, thanks for the insights, quite a dangerous suggestion then from my side. 

@hamistao I guess we don't require a comment here.

File: lxd/instance/drivers/driver_qemu.go (hunk 11 above)
Comment (hamistao) [reply lxd/instance/drivers/driver_qemu.go:2197]: thanks for the insight, will keep that in mind

File: lxd/instance/drivers/driver_qemu.go (hunk 10 above)
Comment (hamistao) [reply lxd/instance/drivers/driver_qemu.go:1210]: `lxd/instance/drivers: Close files opened during socket path handling` was dropped but I broke down `lxd/instance: Use shortenedSocketPath when passing socket paths to qemu` into two commits, one for virtiofsd sockets and one for the swtpm socket

**Comment by hamistao** [comment]
@roosterfish @tomponline this is ready when you are ready :)

File: lxd/device/tpm.go [hunk 12]
```diff
@@ -217,13 +217,25 @@ func (d *tpm) startVM() (*deviceConfig.RunConfig, error) {
 		},
 	}
 
-	proc, err := subprocess.NewProcess("swtpm", []string{"socket", "--tpm2", "--tpmstate", fmt.Sprintf("dir=%s", tpmDevPath), "--ctrl", fmt.Sprintf("type=unixio,path=%s", socketPath)}, "", "")
+	// Method to handle paths longer than 108 characters.
```
Comment (roosterfish) [inline lxd/device/tpm.go:220]: Would it make sense to export `shortenedSocketPath()` in a way so that it can also be used here?

File: lxd/instance/drivers/driver_qemu.go [hunk 13]
```diff
@@ -3097,6 +3097,17 @@ func (d *qemu) deviceBootPriorities(base int) (map[string]int, error) {
 	return sortedDevs, nil
 }
 
+// shortenedSocketPath creates a shorter alternative path to a socket by using the file descriptor to the directory of the socket file.
+// Used to handle paths > 108 chars.
+func (d *qemu) shortenedSocketPath(originalSockPath string, fdFiles *[]*os.File) (string, error) {
+	configSockDir, err := os.Open(filepath.Dir(originalSockPath))
```
Comment (roosterfish) [inline lxd/instance/drivers/driver_qemu.go:3112]: Would it be worth adding a comment to the function saying that the opened file added to `fdFiles` has to be closed outside of this function if it isn't used anymore?

File: lxd/instance/drivers/driver_qemu.go [hunk 14]
```diff
@@ -2185,7 +2185,16 @@ func (d *qemu) deviceAttachPath(deviceName string, configCopy map[string]string,
 		return fmt.Errorf("Failed to connect to QMP monitor: %w", err)
 	}
 
-	addr, err := net.ResolveUnixAddr("unix", virtiofsdSockPath)
+	virtiofsdSocketDir, err := os.Open(filepath.Dir(virtiofsdSockPath))
```
Comment (roosterfish) [inline lxd/instance/drivers/driver_qemu.go:2188]: Can you also use `shortenedSocketPath()` here instead?

**Review by roosterfish — CHANGES_REQUESTED** [review]
Just some small comments to reuse the already existing `shortenedSocketPath()`. Rest looks good to me.

File: lxd/instance/drivers/driver_qemu.go (hunk 14 above)
Comment (hamistao) [reply lxd/instance/drivers/driver_qemu.go:2188]: It is almost the same process, but in this case the file descriptor I am using is from the lxd process itself, `shortenedSocketPath` includes the logic of using a file descriptor so that other process (qemu or swtpm) has access to that file.
In short, using it here would result in probably using the wrong `fd` in `/proc/self/fd`, pointing to some other random file (or no file at all) and not `virtiofsdSocketDir`.

Comment (hamistao) [reply lxd/instance/drivers/driver_qemu.go:2188]: That said, I could modify `shortenedSocketPath` to move this part of the logic outside the function or maybe using a flag to change its behavior in this case, either way I don't see how to do this cleanly. Feel free to make any sugggestions!

File: lxd/device/tpm.go (hunk 12 above)
Comment (hamistao) [reply lxd/device/tpm.go:220]: yes, it would work the same way. But are you suggesting I disassociate the function from the `qemu` type? And if so how would I handle the `d.addFileDescriptor` call inside `shortenedSocketPath`?

File: lxd/instance/drivers/driver_qemu.go (hunk 13 above)
Comment (hamistao) [reply lxd/instance/drivers/driver_qemu.go:3112]: It may not be necessary because `fdFiles` is used to make files visible to another process so it should be clear that the file should be closed after calling said process. But I am happy either way, just please confirm if you think I should add it.

**Comment by tomponline** [comment]
@hamistao ready for another review?

**Comment by hamistao** [comment]
@tomponline yes, it is

File: lxd/util/sys.go [hunk 15]
```diff
@@ -110,3 +110,14 @@ func AddFileDescriptor(fdFiles *[]*os.File, file *os.File) int {
 	*fdFiles = append(*fdFiles, file)
 	return 2 + len(*fdFiles) // Use 2+fdFiles count, as first user file descriptor is 3.
 }
+
+// ShortenedSocketPath creates a shorter alternative path to a socket by using the file descriptor to the directory of the socket file.
+// Used to handle paths > 108 chars.
+func ShortenedSocketPath(originalSockPath string, fdFiles *[]*os.File) (string, error) {
+	configSockDir, err := os.Open(filepath.Dir(originalSockPath)) // Files opened here must be closed outside this function once they are not needed anymore.
```
Comment (tomponline) [inline lxd/util/sys.go:117]: The comment on this line should be in the function description so that the caller doesnt need to read the implementation of the function to know this.

File: lxd/util/sys.go [hunk 16]
```diff
@@ -110,3 +110,14 @@ func AddFileDescriptor(fdFiles *[]*os.File, file *os.File) int {
...
+	if err != nil {
+		return "", fmt.Errorf("Couldn't open device socket directory %q: %w", filepath.Dir(originalSockPath), err)
```
Comment (tomponline) [inline lxd/util/sys.go:119]: Lets not use contracted words like "couldn't" in end user messages, and instead say "could not" or the shorter "Failed...".

File: lxd/util/sys.go [hunk 17]
```diff
@@ -110,3 +110,14 @@ func AddFileDescriptor(fdFiles *[]*os.File, file *os.File) int {
 	*fdFiles = append(*fdFiles, file)
 	return 2 + len(*fdFiles) // Use 2+fdFiles count, as first user file descriptor is 3.
 }
+
+// ShortenedSocketPath creates a shorter alternative path to a socket by using the file descriptor to the directory of the socket file.
```
Comment (tomponline) [inline lxd/util/sys.go:114]: Can this function only be used for unix sockets, or can it be used for other types of files?

If the former, then it would make sense to include "Unix" in the function description at least.

File: lxd/util/sys.go [hunk 18]
```diff
@@ -110,3 +110,14 @@ func AddFileDescriptor(fdFiles *[]*os.File, file *os.File) int {
...
+// Used to handle paths > 108 chars.
+func ShortenedSocketPath(originalSockPath string, fdFiles *[]*os.File) (string, error) {
+	configSockDir, err := os.Open(filepath.Dir(originalSockPath)) // Files opened here must be closed outside this function once they are not needed anymore.
+	if err != nil {
+		return "", fmt.Errorf("Couldn't open device socket directory %q: %w", filepath.Dir(originalSockPath), err)
+	}
+
+	return fmt.Sprintf("/proc/self/fd/%d/%s", AddFileDescriptor(fdFiles, configSockDir), filepath.Base(originalSockPath)), nil
```
Comment (tomponline) [inline lxd/util/sys.go:122]: I feel this would warrant a comment as to why you are opening the directory of the file path rather than the file path itself and then passing back a path to the opened directory's fd with the original file inside it.

File: lxd/device/tpm.go [hunk 19]
```diff
@@ -217,13 +217,20 @@ func (d *tpm) startVM() (*deviceConfig.RunConfig, error) {
 		},
 	}
 
-	proc, err := subprocess.NewProcess("swtpm", []string{"socket", "--tpm2", "--tpmstate", fmt.Sprintf("dir=%s", tpmDevPath), "--ctrl", fmt.Sprintf("type=unixio,path=%s", socketPath)}, "", "")
+	var fdFiles []*os.File
```
Comment (tomponline) [inline lxd/device/tpm.go:220]: You're not closing the files in here once the swtpm process has been started (which the comment in util.ShortenedSocketPath says to do).

File: lxd/instance/drivers/driver_qemu.go [hunk 20]
```diff
@@ -2185,7 +2185,16 @@ func (d *qemu) deviceAttachPath(deviceName string, configCopy map[string]string,
...
+	if err != nil {
+		return err
+	}
+
+	defer func() { _ = virtiofsdSocketDir.Close() }()
+
+	shortPath := fmt.Sprintf("/proc/self/fd/%d/%s", virtiofsdSocketDir.Fd(), filepath.Base(virtiofsdSockPath))
```
Comment (tomponline) [inline lxd/instance/drivers/driver_qemu.go:2195]: Can you use  util.ShortenedSocketPath here instead?

Comment (tomponline) [reply lxd/instance/drivers/driver_qemu.go:2195]: Like you did for swtpm?

Comment (hamistao) [reply lxd/instance/drivers/driver_qemu.go:2195]: I can't because of what I explained to @roosterfish [here](https://github.com/canonical/lxd/pull/13320#discussion_r1617027761). It is a subtle difference in behavior, in short, in this case the file descriptor used is an LXD process file descriptor and `ShortenedSocketPath` uses another proccess's file descriptor via `AddFileDescriptor`. So if I used it here the value used on `%d` in "/proc/self/fd/%d/%s" would probably be wrong.

File: lxd/util/sys.go [hunk 21]
```diff
@@ -110,3 +110,16 @@ func AddFileDescriptor(fdFiles *[]*os.File, file *os.File) int {
...
+// ShortenedSocketPath creates a shorter alternative path to a socket by using the file descriptor to the directory of the socket file.
+// Used to handle paths > 108 chars.
+// Files opened here must be closed outside this function once they are not needed anymore.
+func ShortenedSocketPath(originalSockPath string, fdFiles *[]*os.File) (string, error) {
+	configSockDir, err := os.Open(filepath.Dir(originalSockPath))
+	if err != nil {
+		return "", fmt.Errorf("Failed to open device socket directory %q: %w", filepath.Dir(originalSockPath), err)
+	}
+
+	// Open a file descriptor to the directory where socket lies to avoid accessing the file descriptor to the socket directly.
```
Comment (tomponline) [inline lxd/util/sys.go:123]: @mihalicyn please could you help us with why this approach is needed? Thanks

**Comment by tomponline** [comment]
How did you get on with this @hamistao ?

**Comment by hamistao** [comment]
@tomponline The approach of passing the file descriptor to QEMU works but is considerably more complicated than the current apporach so that withh remain the same. All the rest remais as discussed and I will be pushing the changes in a few minutes.

File: lxd/util/sys.go (hunk 21 above)
Comment (tomponline) [reply lxd/util/sys.go:123]: @hamistao not addressed yet. cc @mihalicyn

**Comment by tomponline** [comment]
> The approach of passing the file descriptor to QEMU works but is considerably more complicated than the current apporach so that withh remain the same. All the rest remais as discussed and I will be pushing the changes in a few minutes.

Please can I have some more details on this, also specifically what are you referring to?

**Comment by hamistao** [comment]
@tomponline Sure! I tried passing a file descriptor to the socket file when calling `swtpm socket` to make the code simpler and remove `util.ShortenedSocketPath` from TPM creation.
But since the file descriptor that swtpm receives must be to a socket file, it is needed to open the socket before calling `swtpm socket` and thus `util.ShortenedSocketPath` is still needed. This is why I stuck to the current approach.

**Review by tomponline — APPROVED** [review]

File: lxd/util/sys.go (hunk 21 above)
Comment (tomponline) [reply lxd/util/sys.go:123]: @hamistao please work with @mihalicyn to update this comment to explain why this approach is used in a follow up PR. Thanks

**Comment by tomponline** [comment]
@hamistao i was just about to merge this and but you've pushed a change?

**Comment by hamistao** [comment]
@tomponline yes, the pushed changes just include the `O_PATH` approach and the switch from `ShortenedSocketPath` to `ShornetedFIlePath`, as discussed.

**Comment by tomponline** [comment]
OK so ill re review again

**Comment by hamistao** [comment]
@tomponline Sorry if there was some confusion. If those changes aren't needed please let me know so I can remove them.

File: lxd/util/sys.go [hunk 22]
```diff
@@ -110,3 +110,16 @@ func AddFileDescriptor(fdFiles *[]*os.File, file *os.File) int {
 	*fdFiles = append(*fdFiles, file)
 	return 2 + len(*fdFiles) // Use 2+fdFiles count, as first user file descriptor is 3.
 }
+
+// ShortenedFilePath creates a shorter alternative path to a socket by using the file descriptor to the directory of the socket file.
+// Used to handle paths > 108 chars.
+// Files opened here must be closed outside this function once they are not needed anymore.
+func ShortenedFilePath(originalSockPath string, fdFiles *[]*os.File) (string, error) {
+	// Open a file descriptor to the directory where socket lies to avoid accessing the file descriptor to the sockfs inode.
```
Comment (tomponline) [inline lxd/util/sys.go:118]: comment is out of date  now

File: lxd/util/sys.go (hunk 21 above)
Comment (hamistao) [reply lxd/util/sys.go]: I used `// Open a file descriptor to the directory where socket lies to avoid accessing the file descriptor to the sockfs inode.` for now since we decided to switch to the `O_PATH` approach.

File: lxd/instance/drivers/driver_qemu.go (hunk 14 above)
Comment (tomponline) [inline lxd/instance/drivers/driver_qemu.go:2188]: Can we use O_PATH approach here as well?

**Comment by hamistao** [comment]
@tomponline done!

File: lxd/instance/drivers/driver_qemu.go (hunk 14 above)
Comment (hamistao) [reply lxd/instance/drivers/driver_qemu.go]: yes, it should be

Comment (hamistao) [reply lxd/instance/drivers/driver_qemu.go]: ran some manual tests to make sure and indeed worked as expected

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
Thanks!
