### PR TITLE
Ensure the remote connection using simplestreams is valid before adding it

### LINKED ISSUE #12414: `lxc remote add --protocol=simplestreams` doesn't test connectivity until the remote is actually used
Steps to reproduce:

Confirm no connectivity to `cloud-images.ubuntu.com:1234`:
```
$ nc -zv cloud-images.ubuntu.com 1234
nc: connect to cloud-images.ubuntu.com (2620:2d:4000:1::1a) port 1234 (tcp) failed: Connection refused
nc: connect to cloud-images.ubuntu.com (2620:2d:4000:1::17) port 1234 (tcp) failed: Connection refused
nc: connect to cloud-images.ubuntu.com (185.125.190.37) port 1234 (tcp) failed: Connection refused
nc: connect to cloud-images.ubuntu.com (185.125.190.40) port 1234 (tcp) failed: Connection refused
```

Add that as a remote:
```
$ lxc remote add ubuntu1 https://cloud-images.ubuntu.com:1234/buildd/releases --protocol=simplestreams
$ echo $?
0
```

Test the remote:
```
$ lxc image list ubuntu1:
Error: Failed parsing stream: Get "https://cloud-images.ubuntu.com:1234/buildd/releases/streams/v1/index.json": Unable to connect to: cloud-images.ubuntu.com:1234 ([dial tcp [2620:2d:4000:1::1a]:1234: connect: connection refused dial tcp [2620:2d:4000:1::17]:1234: connect: connection refused dial tcp 185.125.190.37:1234: connect: connection refused dial tcp 185.125.190.40:1234: connect: connection refused])
```

### PR DESCRIPTION
**Pull request by gabrielmougard**
closes #12414

### CODE REVIEW

File: test/suites/remote.sh [hunk 1]
```diff
@@ -14,6 +14,10 @@ test_remote_url() {
 
   # an invalid protocol returns an error
   ! lxc_remote remote add test "${url}" --accept-certificate --password foo --protocol foo || false
+  # a connectivity issue returns an error
```
Comment (tomponline) [inline test/suites/remote.sh:17]: Please move these down to the section starting at line 28, this way its wrapped in the LXD_OFFLINE check and doesn't interrupt the flow of the testing of the urls list here.

File: lxc/remote.go [hunk 2]
```diff
@@ -326,6 +327,38 @@ func (c *cmdRemoteAdd) Run(cmd *cobra.Command, args []string) error {
...
+		// Test address / port connectivity
+		dialAddr := remoteURL.Hostname()
+		if remoteURL.Port() == "" {
+			dialAddr = dialAddr + ":443"
+		} else {
+			dialAddr = dialAddr + ":" + remoteURL.Port()
+		}
+
+		timeout := 5 * time.Second
+		_, err = net.DialTimeout("tcp", dialAddr, timeout)
```
Comment (tomponline) [inline lxc/remote.go:340]: why do we need the DialTimeout here, rather than only doing the d.GetImages() call, which would also test the connectivity at the same time?

**Review by tomponline — APPROVED** [review]

File: test/suites/remote.sh [hunk 3]
```diff
@@ -26,6 +26,11 @@ test_remote_url() {
     lxc_remote remote add ubuntu2 https://cloud-images.ubuntu.com:443/releases --protocol=simplestreams
     lxc_remote remote remove ubuntu1
     lxc_remote remote remove ubuntu2
+
+    # a connectivity issue returns an error
+    ! lxc_remote remote add ubuntu1 https://cloud-images.ubuntu.com:1234/releases --protocol=simplestreams
+    # a malformed url path returns an error
+    ! lxc_remote remote add ubuntu2 https://cloud-images.ubuntu.com/buildd/releases/ --protocol=simplestreams --public
```
Comment (simondeziel) [inline test/suites/remote.sh:33]: If the issue is the trailing "/", I would update the comment to say that trailing "/" are not permitted, rather than it being a malformed URL.

Comment (tomponline) [reply test/suites/remote.sh:33]: Ive not had time to debug it much, but that line is one of the issues.

The other thing is that it broke adding valid simplestreams URLs without `--public` being specified as it then treated them as LXD image servers.
