### PR TITLE
client: Discard non-interactive stdout/stderr output if writer(s) not supplied in ExecInstance

### LINKED ISSUE #12636: ExecInstance does not execute a command if InstanceExecArgs is empty or nil
# Required information

 * Distribution: ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.2
   * LXC version:
   * LXD version: latest/stable:    5.19-8635f82  2023-11-22 (26200) 
   * Storage backend in use: dir

# Issue description
ExecInstance does not execute a command if the InstanceExecPost argument is empty or nil.

# Steps to reproduce

Use the LXD go API client and note &lxd.InstanceExecArgs{} which in `github.com/lxc/lxd v0.0.0-20221215165925-aa3cdeaec9a5` worked just fine and executed the required command with a return code 0. In `github.com/canonical/lxd v0.0.0-20230801204156-b1b45dae8781`, it finishes with a return code 137. If, instead, nil provided, it fails with a websocket timeout. 

```
func main() {
    if srv, err := lxd.ConnectLXDUnix(LxdSock, nil); err == nil {
        srv := srv.UseProject("default")

        op, err := srv.ExecInstance("exec-issue", api.InstanceExecPost{
            Command:     []string{"ls", "/"},
            WaitForWS:   true,
            Interactive: false,
        }, &lxd.InstanceExecArgs{})
        if err != nil {
            panic(err)
        }

        meta := op.Get().Metadata
        fmt.Printf("%v", meta)
        if err != nil {
            panic(err)
        }
        err = op.Wait()
        r := op.Get().Metadata
        fmt.Printf("%v", err)
        fmt.Printf("%v", r)
    }
}
```

### PR DESCRIPTION
**Pull request by tomponline**
Inspired by @MusicDin #12633 but with some changes.

Fixes #12636
Closes #12633

### CODE REVIEW

File: client/lxd_instances.go [hunk 1]
```diff
@@ -1213,7 +1217,10 @@ func (r *ProtocolLXD) ExecInstance(instanceName string, exec api.InstanceExecPos
 				_, _, _ = conn.ReadMessage() // Consume pings from server.
 			}()
 
-			go args.Control(conn)
+			if args.Control != nil {
```
Comment (MusicDin) [inline client/lxd_instances.go:1220]: Just wondering whether it would make sense to provide a default handler if it is not set? Otherwise, users need to write it for themselves because we do not expose it (it is part of lxc/exec command).

**Comment by MusicDin** [comment]
A few cosmetic changes:

Check for `args != nil` is no longer required, since args will never be nil: https://github.com/canonical/lxd/pull/12654/files#diff-38fe5105434e3aeb067660c04e71637bda88db534a3fbcc4a2c6b34d0e3c461aR1141

And I think there is typo in first commit message `EInstanceExecArgs` -> `InstanceExecArgs`

**Review by MusicDin — APPROVED** [review]
Otherwise, LGTM. Thanks.

File: client/lxd_instances.go (hunk 1 above)
Comment (MusicDin) [reply client/lxd_instances.go]: Thanks for clarification 👍

**Review by roosterfish — APPROVED** [review]
Looks good to me.
