### PR TITLE
Require destination name when copying an instance on the same server

### LINKED ISSUE #12338: `lxc copy` should be smarter when copying from a snapshot
`lxc copy` can take a `instance/snap` source just fine:

```
$ lxc init ubuntu-minimal:22.04 u1
Creating u1
$ lxc snapshot u1 foo
$ lxc copy u1/foo u2
$ lxc delete -f u2
$ lxc copy u1/foo local:u2
$ lxc delete -f u2
```

But when a remote target is provided, it complains about the `/` being used in the target instance name:

```
$ lxc copy u1/foo local:
Error: The character "/" is reserved for snapshots
```

IMHO, it should be smart in that case too and ignore `/...` in the target instance name. Of course the workaround is trivial:

```
$ lxc copy u1/foo local:u2
```

**Note**: `local:` doesn't make much sense in those `lxc copy` cases but it illustrates the problem one faces with a *remote* remote.

### PR DESCRIPTION
**Pull request by MusicDin**
Removes unused code that determines generated name on copy or move (using copy).
It requires destination name to be provided, with only exception being when moving an instance to another remote (for example: `lxc move c1 remote2:`). In such case, the destination name is set to the source name.

Fixes #12338

### CODE REVIEW

File: lxc/copy.go [hunk 1]
```diff
@@ -153,6 +154,9 @@ func (c *cmdCopy) copyInstance(conf *config.Config, sourceResource string, destR
 			return fmt.Errorf(i18n.G("--instance-only can't be passed when the source is a snapshot"))
 		}
 
+		// Remove snapshot suffix from destination name.
```
Comment (tomponline) [inline lxc/copy.go:157]: This comment say *what* but doesn't explain the *why*.

Comment (MusicDin) [reply lxc/copy.go]: Thanks for this one.

Snapshot suffix is removed to ensure consistency when copying/moving an instance (or snapshot) to a different remote (`lxc move c1 remote2:` or `lxc move c1/snap0 remote2:`).

However, I missed the fact, that this will trim the suffix even if the user provides the snapshot name in the destination name.

For example, the following commands produced the same error, although they should not: 
```
lxc copy c1/snap0 c1/snap1
lxc copy c1/snap0 c1

# Error: Failed creating instance record: Add instance info to the database: This "instances" entry already exists`
```

Now, the snapshot name is trimmed only when destName is set from the source.

---

A bit unrelated, but is there a reason we do not output the instance name in the above error? (something like `Database entry for instance "c1" already exists`)

**Comment by MusicDin** [comment]
@ru-fu I've checked the docs and to me everything seems up to date. It is most likely that the PR title is misleading.

This PR requires the destination name to be provided if remote is not specified, as the command would fail anyway because the instance with that name already exists.
```
lxc copy c1
```

And it fixes the situation where an instance is created from a snapshot on a different remote:
```
lxc copy c1/snap0 remote2:
```
The above command would previously fail with `Error: The character "/" is reserved for snapshots`, so now we trim the snapshot name when destination name is not provided.

**Comment by ru-fu** [comment]
OK, great!

So `lxc move c1 --target server1` is still going to work?

**Comment by MusicDin** [comment]
I've double checked and it is working

File: lxc/copy.go [hunk 2]
```diff
@@ -84,19 +84,21 @@ func (c *cmdCopy) copyInstance(conf *config.Config, sourceResource string, destR
...
 		return fmt.Errorf(i18n.G("--no-profiles cannot be used with --refresh"))
 	}
 
-	// If no destination name was provided, use the same as the source
-	if destName == "" && destResource != "" {
-		destName = sourceName
+	// If the instance is being copied to a different remote and no destination name is
+	// specified, use the source name with snapshot suffix trimmed (in case a new instance
+	// is being created from a snapshot).
+	if destName == "" && destResource != "" && c.flagTarget == "" {
```
Comment (tomponline) [inline lxc/copy.go:95]: Do we need to consider copying a snapshot with --target specified too?

**Review by tomponline — APPROVED** [review]
