### PR TITLE
Fix: Recover from phantom DB entries and orphaned storage after interrupted cluster migrations

### LINKED ISSUE #17787: LXD leaves phantom database records when migration fails midway
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

Ubuntu

### Distribution version

22.04 - Jammy Jellyfish

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
Name    Version      Rev    Tracking       Publisher   Notes
core20  20260105     2717   latest/stable  canonical✓  base
core20  20251031     2686   latest/stable  canonical✓  base,disabled
core22  20260128     2339   latest/stable  canonical✓  base
core24  20260107     1349   latest/stable  canonical✓  base
lxd     git-59e8acd  38134  latest/edge    canonical✓  disabled
lxd     git-14b1a08  38175  latest/edge    canonical✓  -
snapd   2.73         25935  latest/stable  canonical✓  snapd
```

### Output of "lxc info" or system info if it fails

```shell
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- backup_compression
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
- clustering_update_cert
- storage_api_project
- server_instance_driver_operational
- server_supported_storage_drivers
- event_lifecycle_requestor_address
- resources_gpu_usb
- clustering_evacuation
- network_ovn_nat_address
- network_bgp
- network_forward
- custom_volume_refresh
- network_counters_errors_dropped
- metrics
- image_source_project
- clustering_config
- network_peer
- linux_sysctl
- network_dns
- ovn_nic_acceleration
- certificate_self_renewal
- instance_project_move
- storage_volume_project_move
- cloud_init
- network_dns_nat
- database_leader
- instance_all_projects
- clustering_groups
- ceph_rbd_du
- instance_get_full
- qemu_metrics
- gpu_mig_uuid
- event_project
- clustering_evacuation_live
- instance_allow_inconsistent_copy
- network_state_ovn
- storage_volume_api_filtering
- image_restrictions
- storage_zfs_export
- network_dns_records
- storage_zfs_reserve_space
- network_acl_log
- storage_zfs_blocksize
- metrics_cpu_seconds
- instance_snapshot_never
- certificate_token
- instance_nic_routed_neighbor_probe
- event_hub
- agent_nic_config
- projects_restricted_intercept
- metrics_authentication
- images_target_project
- cluster_migration_inconsistent_copy
- cluster_ovn_chassis
- container_syscall_intercept_sched_setscheduler
- storage_lvm_thinpool_metadata_size
- storage_volume_state_total
- instance_file_head
- instances_nic_host_name
- image_copy_profile
- container_syscall_intercept_sysinfo
- clustering_evacuation_mode
- resources_pci_vpd
- qemu_raw_conf
- storage_cephfs_fscache
- network_load_balancer
- vsock_api
- instance_ready_state
- network_bgp_holdtime
- storage_volumes_all_projects
- metrics_memory_oom_total
- storage_buckets
- storage_buckets_create_credentials
- metrics_cpu_effective_total
- projects_networks_restricted_access
- storage_buckets_local
- loki
- acme
- internal_metrics
- cluster_join_token_expiry
- remote_token_expiry
- init_preseed
- storage_volumes_created_at
- cpu_hotplug
- projects_networks_zones
- network_txqueuelen
- cluster_member_state
- storage_pool_source_wipe
- zfs_block_mode
- instance_generation_id
- disk_io_cache
- amd_sev
- storage_pool_loop_resize
- migration_vm_live
- ovn_nic_nesting
- oidc
- network_ovn_l3only
- ovn_nic_acceleration_vdpa
- cluster_healing
- instances_state_total
- auth_user
- security_csm
- instances_rebuild
- numa_cpu_placement
- custom_volume_iso
- network_allocations
- storage_api_remote_volume_snapshot_copy
- zfs_delegate
- operations_get_query_all_projects
- metadata_configuration
- syslog_socket
- event_lifecycle_name_and_project
- instances_nic_limits_priority
- disk_initial_volume_configuration
- operation_wait
- cluster_internal_custom_volume_copy
- disk_io_bus
- storage_cephfs_create_missing
- instance_move_config
- ovn_ssl_config
- init_preseed_storage_volumes
- metrics_instances_count
- server_instance_type_info
- resources_disk_mounted
- server_version_lts
- oidc_groups_claim
- loki_config_instance
- storage_volatile_uuid
- import_instance_devices
- instances_uefi_vars
- instances_migration_stateful
- container_syscall_filtering_allow_deny_syntax
- access_management
- vm_disk_io_limits
- storage_volumes_all
- instances_files_modify_permissions
- image_restriction_nesting
- container_syscall_intercept_finit_module
- device_usb_serial
- network_allocate_external_ips
- explicit_trust_token
- shared_custom_block_volumes
- instance_import_conversion
- instance_create_start
- instance_protection_start
- devlxd_images_vm
- disk_io_bus_virtio_blk
- metrics_api_requests
- projects_limits_disk_pool
- ubuntu_pro_guest_attach
- metadata_configuration_entity_types
- access_management_tls
- network_allocations_ovn_uplink
- network_ovn_uplink_vlan
- state_logical_cpus
- vm_limits_cpu_pin_strategy
- gpu_cdi
- images_all_projects
- metadata_configuration_scope
- unix_device_hotplug_ownership_inherit
- unix_device_hotplug_subsystem_device_option
- storage_ceph_osd_pool_size
- network_get_target
- network_zones_all_projects
- vm_root_volume_attachment
- projects_limits_uplink_ips
- entities_with_entitlements
- profiles_all_projects
- storage_driver_powerflex
- storage_driver_pure
- cloud_init_ssh_keys
- oidc_scopes
- project_default_network_and_storage
- client_cert_presence
- clustering_groups_used_by
- container_bpf_delegation
- override_snapshot_profiles_on_copy
- resources_device_fs_uuid
- backup_metadata_version
- storage_buckets_all_projects
- network_acls_all_projects
- networks_all_projects
- clustering_restore_skip_mode
- disk_io_threads_virtiofsd
- oidc_client_secret
- pci_hotplug
- device_patch_removal
- daemon_storage_per_project
- ovn_internal_load_balancer
- auth_bearer_devlxd
- devlxd_volume_management
- storage_driver_alletra
- resources_disk_used_by
- ovn_dhcp_ranges
- operation_requestor
- import_custom_volume_tar
- projects_force_delete
- auth_oidc_sessions
- instance_snapshots_multi_volume
- vm_persistent_bus
- instance_placement_groups
- ovn_nic_acceleration_parent
- storage_and_profile_operations
- storage_source_recover
- instance_force_delete
- operation_metadata_entity_url
- instance_boot_mode
- auth_bearer
- vm_limits_max_bus_ports
- instances_state_selective_recursion
- project_delete_operation
- gpu_cdi_amd
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
- bearer
client_certificate: false
config:
  cluster.https_address: 10.10.10.93:8443
  core.https_address: 10.10.10.93:8443
  volatile.uuid: 019c9bab-f527-722f-a964-56242ec8011e
auth_user_name: ubuntu
auth_user_method: unix
environment:
  addresses:
  - 10.10.10.93:8443
  architectures:
  - x86_64
  - i686
  backup_metadata_version_range:
  - 1
  - 2
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIB5jCCAWygAwIBAgIQdQETme99yEyCwE2iMfoZ1zAKBggqhkjOPQQDAzAlMQww
    CgYDVQQKEwNMWEQxFTATBgNVBAMMDHJvb3RAbWV0YWwwMTAeFw0yNjAyMjYyMDE1
    MzlaFw0zNjAyMjQyMDE1MzlaMCUxDDAKBgNVBAoTA0xYRDEVMBMGA1UEAwwMcm9v
    dEBtZXRhbDAxMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE7PqKG48PEx5eFsQ7n7DX
    dWmZprkd6Zv7uZ92e43sTrY2zOrYnDWZ3O1WRqSuMNUHWG1zJ/TZ3m+NKZHmN+PT
    pt2YzT5NUnkiT0qX5Jr1pgPMsu/Q4F/9b18rHmQCB/y5o2EwXzAOBgNVHQ8BAf8E
    BAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAqBgNVHREE
    IzAhggdtZXRhbDAxhwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMAoGCCqGSM49BAMD
    A2gAMGUCMQD3HMrE7lNA186MorUyCUwVUBOBho+Q0tSSeUm2+t5qrL9vjo8gQ4TV
    DxACFVj5IuoCMELeJX8/qsycjJsEYj7C5qjw5nma3Wt2suGzfloBeTvt4XfKg8C6
    SPhSsp8S32G0/w==
    -----END CERTIFICATE-----
  certificate_fingerprint: 65c7ef05d7c05d4916dd8b3ed63a18f07fdea70d4fad8aefa6baf9ee70810392
  driver: lxc | qemu
  driver_version: 6.0.0 | 10.2.1
  instance_types:
  - container
  - virtual-machine
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    bpf_token: "false"
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    uevent_injection: "true"
    unpriv_binfmt: "false"
    unpriv_fscaps: "true"
  kernel_version: 5.15.0-1093-kvm
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "22.04"
  project: default
  server: lxd
  server_clustered: true
  server_event_mode: full-mesh
  server_name: metal01
  server_pid: 812
  server_version: "6.7"
  server_lts: false
  storage: zfs
  storage_version: 2.1.5-1ubuntu6~22.04.6
  storage_supported_drivers:
  - name: cephfs
    version: 19.2.3
    remote: true
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.16(2) (2022-05-18) / 1.02.185 (2022-05-18) / 4.45.0
    remote: false
  - name: powerflex
    version: 2.8 (nvme-cli)
    remote: true
  - name: cephobject
    version: 19.2.3
    remote: true
  - name: pure
    version: 2.1.5 (iscsiadm) / 2.8 (nvme-cli)
    remote: true
  - name: alletra
    version: 2.8 (nvme-cli) / 2.1.5 (iscsiadm)
    remote: true
  - name: zfs
    version: 2.1.5-1ubuntu6~22.04.6
    remote: false
  - name: btrfs
    version: 6.6.3
    remote: false
  - name: ceph
    version: 19.2.3
    remote: true
```

### Issue description

When performing a migration, if the network interface is brought down, the migration times out, and instead of cleaning the partial database entries/storage volumes, it leaves them as phantom entries, which cause any further migration attempts to fail with either:

database phantom entry:
```bash
Error: Migration operation failure: Instance move to destination failed on source: Failed migration on source: Error from migration control target: Failed creating instance on target: Volume exists in database but not on storage
```

storage volume phantom entry:
```bash
Error: Migration operation failure: Instance move to destination failed on source: Failed migration on source: Error from migration control target: Failed creating instance on target: Volume already exists on storage but not in database
```

I was able to reproduce the phantom database entry in the following LXD versions:
`latest/edge`
`5.21/edge`
`5.21/stable`

The phantom storage volume is harder to reproduce since the migration must fail at precisely the right time to leave partial ZFS entries, but still be an incomplete migration. Once the DB surgery is done in order to fix the phantom database entry, the phantom ZFS volume causes the opposite issue, making it necessary to also manually remove it.

I've also managed to reproduce the issue by forcefully ending the migration with `sudo killall -9 lxd && sudo killall -9 zfs`; however, arbitrarily resetting the TCP connection with things like `tcpkill` doesn't cause the same behaviour. Instead, it gracefully stops the migration and leaves no phantom entries.

## Steps to reproduce:

1. Create a working LXD cluster with at least 2 nodes.
2. Initialise a VM or container:
`lxc init ubuntu:22.04 test --vm --target node1`
3. Prepare (**do not run yet**) in an additional terminal or on the second node a command to bring down (and then restore) the network interface:
`sudo ip link set enp5s0 down && sleep 180 && sudo ip link set enp5s0 up`
4. Start the migration:
`lxc move test --target metal02`
5. Rapidly, switch to the other prompt and run the command on **step 3**.
6. The migration eventually times out and fails with the following error:
`Error: Migration operation failure: Instance move to destination failed on source: Failed migration on source: Error reading migration control target: read tcp <node_1_ip>:8443-><node_2_ip>:48868: read: connection timed out`
7. Confirm phantom entries where left with:
`lxd sql global "SELECT * FROM storage_volumes;"`
8. Further migration attempts fail with:
`Error: Migration operation failure: Instance move to destination failed on source: Failed migration on source: Error from migration control target: Failed creating instance on target: Volume exists in database but not on storage`

## Steps to fix:

1a. Manually delete the database phantom entry
`lxd sql global "DELETE FROM storage_volumes WHERE id = <phantom_id>;"`
1b. Manually delete the ZFS phantom entry
`sudo zfs destroy <phantom_entry>`
2. Migrations now work

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by tugbataluy**
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md) and attest that all commits in this PR are [signed off](https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md#including-a-signed-off-by-line-in-your-commits), [cryptographically signed](https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md#commit-signature-verification), and follow this project's [commit structure](https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md#commit-structure).
- [x] I have checked and added or updated relevant documentation.

## Problem
When a cluster migration is interrupted mid-transfer (network drop, kill -9 on target), phantom storage_volumes records can be left in the global database with no corresponding storage on disk (as mentioned in #17787).

On retry, the consistency checks in `CreateInstanceFromMigration` and `CreateCustomVolumeFromMigration` return "Volume exists in database but not on storage", permanently blocking migration for the affected instance.

Separately, dead migration connections were not detected promptly, leaving migrations hanging for minutes before timing out.

## Fix
- Fast dead-connection detection (`lxd/migration_connection.go`)
Enable `ws.StartKeepAlive()` on both incoming (`AcceptIncoming`) and outgoing (`WebSocket`) migration WebSocket connections. Dead connections are now detected in ~15 seconds instead of relying on TCP timeout defaults.

- Integration test (`test/suites/clustering_move.sh`)

Add a sub-test under `test_clustering_move that`:
- Injects a phantom storage_volumes row via `lxd sql global`
- Verifies the migration fails with the expected error.
- Removes the phantom row.
- Verifies migration then succeeds.

## What this does NOT do
This PR does not auto-repair storage inconsistencies. [A follow-up PR](https://github.com/canonical/lxd/pull/18101) will improve the error message with recovery guidance and add documentation for the manual cleanup steps.

Fixes #17787

### CODE REVIEW

File: lxd/storage/backend_lxd.go [hunk 1]
```diff
@@ -2397,12 +2397,28 @@ func (b *lxdBackend) CreateInstanceFromMigration(inst instance.Instance, conn io
...
 	// Check for inconsistencies between database and storage before continuing.
+	// These can be left behind from interrupted migrations where the target was killed mid-transfer
+	// and the in-memory revert chain could not execute. Clean them up and proceed.
 	if dbVol == nil && volExists {
-		return errors.New("Volume already exists on storage but not in database")
+		l.Warn("Removing orphaned storage volume from previous interrupted migration")
+
+		err = b.driver.DeleteVolume(vol, nil)
+		if err != nil {
+			return fmt.Errorf("Failed removing orphaned storage volume: %w", err)
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply lxd/storage/backend_lxd.go]: This isn't a concern in practice. The cleanup branches only trigger on inconsistent states `(dbVol == nil && volExists or dbVol != nil && !volExists)`. In refresh mode, the volume is expected to exist in both DB and storage, so neither cleanup branch would fire during a normal refresh.

If an inconsistency does exist during a refresh, it means the state is already broken, the refresh would fail anyway (e.g. nothing on disk to refresh into). Cleaning up and proceeding as a fresh creation is strictly better than returning a hard error that permanently blocks migration. Gating on `!args.Refresh` would leave refresh-mode migrations stuck on the same errors this fix is designed to solve.

File: lxd/storage/drivers/driver_dir_volumes.go [hunk 2]
```diff
@@ -192,15 +192,14 @@ func (d *dir) DeleteVolume(vol Volume, op *operations.Operation) error {
...
-	// Remove the project quota.
-	err = d.deleteQuota(volPath, volID)
-	if err != nil {
-		return err
+	if err == nil {
+		err = d.deleteQuota(volPath, volID)
+		if err != nil {
+			return err
+		}
 	}
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply lxd/storage/drivers/driver_dir_volumes.go:204]: Good catch. I should narrow the error check to only skip quota cleanup for not-found errors, and propagate unexpected DB errors. I'll update it to use `response.IsNotFoundError(err)`.

File: test/suites/clustering_move.sh [hunk 3]
```diff
@@ -201,3 +201,76 @@ test_clustering_move() {
   kill_lxd "${LXD_TWO_DIR}"
   kill_lxd "${LXD_THREE_DIR}"
 }
+
+# Test recovery from phantom DB entries and orphaned storage left behind after
+# interrupted cluster migrations.
+test_clustering_move_interrupted_recovery() {
+  echo "Test recovery from phantom DB/storage entries after interrupted cluster migration."
+  # shellcheck disable=SC2154
+  local bridge="${bridge}"
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply test/suites/clustering_move.sh]: bridge is used implicitly by `teardown_clustering_bridge` which is called at the end of the function. This is a common pattern across all clustering test functions in this file (see `test_clustering_move` at line 4 for the same usage).

File: lxd/storage/backend_lxd.go [hunk 4]
```diff
@@ -8421,3 +8453,86 @@ func (b *lxdBackend) GenerateInstanceCustomVolumeBackupConfig(inst instance.Inst
...
+
+			instances, err := cluster.GetInstances(ctx, tx.Tx(), filter)
+			if err != nil || len(instances) == 0 {
+				// Instance doesn't exist anywhere, not safe to delete.
+				return nil
+			}
+
+			instanceOnOtherNode = instances[0].Node != localNodeName
+			return nil
+		})
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply lxd/storage/backend_lxd.go]: Good point about the silent error. I'll capture and log the transaction error. However, context.TODO() is appropriate here since this function runs during daemon startup, not during shutdown.

File: lxd/storage/backend_lxd.go [hunk 5]
```diff
@@ -8421,3 +8453,86 @@ func (b *lxdBackend) GenerateInstanceCustomVolumeBackupConfig(inst instance.Inst
...
+
+		// A volume with a matching local DB entry is legitimate and actively managed.
+		_, err := VolumeDBGet(b, projectName, instanceName, volType)
+		if err == nil {
+			continue
+		}
+
+		if !response.IsNotFoundError(err) {
+			continue // Unexpected error, skip
+		}
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply lxd/storage/backend_lxd.go]: This runs once during daemon startup and only for local (non-remote) pools. The number of on-disk volumes on a single node is bounded and in practice small enough that per-volume DB lookups are not a bottleneck. Adding batch loading would increase complexity without a measurable benefit.

File: lxd/storage.go [hunk 6]
```diff
@@ -116,6 +116,22 @@ func storageStartup(s *state.State) error {
...
+			continue
+		}
+
+		pool, err := storagePools.LoadByName(s, poolName)
+		if err != nil {
+			continue
+		}
+
+		pool.CleanupOrphanedMigrationVolumes(s)
+	}
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply lxd/storage.go]: Fair point about the silent error. I'll add a log line for `LoadByName` failures. However, moving this to a background goroutine introduces a race window where a migration could start before cleanup finishes, which is exactly the scenario this fix prevents. Synchronous startup cleanup ensures a clean state before accepting any migration requests.

File: lxd/storage/backend_lxd.go [hunk 7]
```diff
@@ -8421,3 +8453,86 @@ func (b *lxdBackend) GenerateInstanceCustomVolumeBackupConfig(inst instance.Inst
...
+	for _, diskVol := range diskVols {
+		// Custom volume migration has its own consistency checks in CreateCustomVolumeFromMigration,
+		// so only instance volumes need to be handled here.
+		volType := diskVol.Type()
+		if volType != drivers.VolumeTypeContainer && volType != drivers.VolumeTypeVM {
+			continue
+		}
+
+		// Extract project and instance name from the storage volume name.
+		projectName, instanceName := project.StorageVolumeParts(diskVol.Name())
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply lxd/storage/backend_lxd.go]: Good catch. Switched to `project.InstanceParts()` which handles the default project case correctly for instance volumes and removes the need for the fallback.

File: lxd/instance_post.go [hunk 8]
```diff
@@ -963,11 +964,13 @@ func instancePostClusteringMigrate(s *state.State, srcPool storagePools.Pool, sr
...
 		err = srcOp.Wait(context.Background())
 		if err != nil {
+			cleanupPhantomVolume(s, targetProject, newInstName, srcPool.ID(), volDBType, newMember.Name)
 			return fmt.Errorf("Instance move to destination failed on source: %w", err)
 		}
 
 		err = destOp.Wait()
 		if err != nil {
+			cleanupPhantomVolume(s, targetProject, newInstName, srcPool.ID(), volDBType, newMember.Name)
 			return fmt.Errorf("Instance move to destination failed: %w", err)
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply lxd/instance_post.go:950]: In a cluster move, the pool is the same on both nodes. The pool ID is cluster-wide in the global database, so `srcPool.ID()` correctly identifies the pool where the phantom entry was created on the target member. Cross-pool migration is a separate operation.

File: lxd/storage_volumes.go [hunk 9]
```diff
@@ -1839,7 +1839,26 @@ func storageVolumePostClusteringMigrate(s *state.State, srcPool storagePools.Poo
...
 
 		if err != nil {
-			return fmt.Errorf("Failed requesting instance create on destination: %w", err)
+			// Track rows deleted to only log when a phantom entry was actually removed.
+			var rowsDeleted int64
+
+			cleanupErr := s.DB.Cluster.Transaction(context.Background(), func(ctx context.Context, tx *db.ClusterTx) error {
+				var txErr error
+				rowsDeleted, txErr = tx.RemoveStoragePoolVolumeInMember(ctx, srcProjectName, newVolumeName,
+					cluster.StoragePoolVolumeTypeCustom, srcPool.ID(), newMember.Name)
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply lxd/storage_volumes.go]: Same reasoning as the instance migration path. The pool ID is cluster-wide in the global database, so `srcPool.ID()` correctly identifies the pool on both source and target nodes. The phantom entry is created under this same pool ID on the destination member.

File: lxd/storage/drivers/driver_dir_volumes.go [hunk 10]
```diff
@@ -191,9 +192,14 @@ func (d *dir) DeleteVolume(vol Volume, op *operations.Operation) error {
...
 
-	// Get the volume ID for the volume, which is used to remove project quota.
 	volID, err := d.getVolID(vol.volType, vol.name)
 	if err != nil {
+		// If volume has no DB entry (e.g. orphaned from interrupted migration),
+		// there is no project quota to clean up.
+		if response.IsNotFoundError(err) {
+			return nil
+		}
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply lxd/storage/drivers/driver_dir_volumes.go]: Good catch. I'll restructure to only skip quota cleanup on not-found, while still running the snapshot directory cleanup.

File: lxd/storage/backend_lxd.go [hunk 11]
```diff
@@ -8421,3 +8453,87 @@ func (b *lxdBackend) GenerateInstanceCustomVolumeBackupConfig(inst instance.Inst
...
+			}
+
+			filter := cluster.InstanceFilter{
+				Project: &projectName,
+				Name:    &instanceName,
+			}
+
+			instances, err := cluster.GetInstances(ctx, tx.Tx(), filter)
+			if err != nil || len(instances) == 0 {
+				// Instance doesn't exist anywhere, not safe to delete.
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply lxd/storage/backend_lxd.go]: Good catch. Returning the error from GetInstances lets it propagate to the transaction error handler we already have, which logs it and skips the volume. This avoids making cleanup decisions based on unknown state.

File: test/suites/clustering_move.sh [hunk 12]
```diff
@@ -201,3 +201,76 @@ test_clustering_move() {
...
+
+  echo "Create orphaned storage directory on node2 (simulates leftover from interrupted migration)."
+  mkdir -p "${LXD_TWO_DIR}/storage-pools/data/containers/c1"
+
+  echo "Move c1 to node2 — should recover from orphaned storage and succeed."
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target node2
+  [ "$(LXD_DIR="${LXD_ONE_DIR}" lxc list --format csv --columns nL c1)" = "c1,node2" ]
+
+  echo "Verify cleanup warning was logged on node2."
+  grep -qF "Removing orphaned storage volume from previous interrupted migration" "${LXD_TWO_DIR}/lxd.log"
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply test/suites/clustering_move.sh]: The original issue was reported on ZFS, but the fix is in the storage backend layer which is shared across all drivers. The dir backend is used here because the clustering test infrastructure defaults to dir, and it lets us deterministically inject both phantom states (SQL INSERT for DB-only, mkdir for storage-only) without requiring ZFS/LVM/Ceph to be available in CI. The recovery code paths exercised are identical regardless of the underlying driver.

File: test/suites/clustering_move.sh [hunk 13]
```diff
@@ -201,3 +201,82 @@ test_clustering_move() {
...
+
+  echo "Verify only one storage_volumes entry remains for c1."
+  [ "$(LXD_DIR="${LXD_ONE_DIR}" lxd sql global --format csv "SELECT COUNT(*) FROM storage_volumes WHERE name='c1'")" = "1" ]
+
+  echo "Verify cleanup warning was logged on node2."
+  grep -qF "Removing phantom volume database record from previous interrupted migration" "${LXD_TWO_DIR}/lxd.log"
+
+  sub_test "Simulated storage-only orphan recovery"
+
+  echo "Move c1 back to node1."
```
Comment (kadinsayani) [inline test/suites/clustering_move.sh]: Let's drop these `echo` calls in favor of comments; we just organize tests using the `sub_test` helper now.

File: lxd/db/storage_volumes.go [hunk 14]
```diff
@@ -505,6 +505,32 @@ func (c *ClusterTx) RemoveStoragePoolVolume(ctx context.Context, projectName str
 	return nil
 }
 
+// RemoveStoragePoolVolumeInMember removes a storage volume entry associated with a
+// specific cluster member. Used for cleaning up database entries left behind after
+// interrupted cluster migrations. Returns the number of rows deleted.
+func (c *ClusterTx) RemoveStoragePoolVolumeInMember(ctx context.Context, projectName string, volumeName string, volumeType cluster.StoragePoolVolumeType, poolID int64, memberName string) (int64, error) {
```
Comment (kadinsayani) [inline lxd/db/storage_volumes.go]: Does this also clean up associated snapshots?

File: lxd/storage_volumes.go [hunk 15]
```diff
@@ -1839,7 +1839,26 @@ func storageVolumePostClusteringMigrate(s *state.State, srcPool storagePools.Poo
...
+			})
+			if cleanupErr != nil {
+				logger.Warn("Failed cleaning up phantom volume DB entry", logger.Ctx{
+					"project": srcProjectName, "volume": newVolumeName, "member": newMember.Name, "err": cleanupErr,
+				})
+			} else if rowsDeleted > 0 {
+				logger.Warn("Removed phantom volume DB entry after failed migration", logger.Ctx{
+					"project": srcProjectName, "volume": newVolumeName, "member": newMember.Name,
+				})
+			}
```
Comment (kadinsayani) [inline lxd/storage_volumes.go]: This duplicates existing logic in `cleanupPhantomVolume()`, perhaps we can extract a shared helper?

File: lxd/storage/backend_lxd.go [hunk 16]
```diff
@@ -5537,12 +5573,28 @@ func (b *lxdBackend) CreateCustomVolumeFromMigration(projectName string, conn io
 	}
 
 	// Check for inconsistencies between database and storage before continuing.
+	// These can be left behind from interrupted migrations where the target was killed mid-transfer
```
Comment (kadinsayani) [inline lxd/storage/backend_lxd.go]:
```suggestion
	// Storage volumes can be left behind from interrupted migrations where the target was killed mid-transfer
```

File: lxd/storage.go [hunk 17]
```diff
@@ -116,6 +116,23 @@ func storageStartup(s *state.State) error {
...
 
+	// Clean up orphaned storage volumes from interrupted cluster migrations on successfully initialized pools.
+	for _, poolName := range poolNames {
+		_, pending := initPools[poolName]
+		if pending {
+			// Skip pools that failed to initialize.
+			continue
+		}
+
+		pool, err := storagePools.LoadByName(s, poolName)
```
Comment (kadinsayani) [inline lxd/storage.go]: `initPool()` already calls `storagePools.LoadByName()`. Can we store the already loaded pools and reuse them here?

**Review by kadinsayani — COMMENTED** [review]
Looking good so far, thanks! Just a few questions and suggestions.

File: test/suites/clustering_move.sh (hunk 13 above)
Comment (tugbataluy) [reply test/suites/clustering_move.sh]: Thanks Kadin, I still haven't gotten used to not using `echo` when using `sub_test` in tests :sweat_smile: .

File: lxd/db/storage_volumes.go (hunk 14 above)
Comment (tugbataluy) [reply lxd/db/storage_volumes.go]: Yes, I think so. The `storage_volumes_snapshots` table has `ON DELETE CASCADE` on its foreign key to `storage_volumes`:

```
CREATE TABLE "storage_volumes_snapshots" (
    id INTEGER NOT NULL,
    storage_volume_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    expiry_date DATETIME,
    creation_date DATETIME NOT NULL DEFAULT "0001-01-01T00:00:00Z",
    UNIQUE (id),
    UNIQUE (storage_volume_id, name),
    FOREIGN KEY (storage_volume_id) REFERENCES "storage_volumes" (id) ON DELETE CASCADE
);
```
Same for storage_volumes_config:
```
FOREIGN KEY (storage_volume_id) REFERENCES "storage_volumes" (id) ON DELETE CASCADE
```

When `RemoveStoragePoolVolumeInMember` deletes a row from storage_volumes, the database automatically cascades the delete to any associated snapshot and config records.

But I think I should mention this behaviour as a comment. Thanks :sparkle:

File: lxd/storage_volumes.go (hunk 15 above)
Comment (tugbataluy) [reply lxd/storage_volumes.go]: I intentionally kept these separate. `cleanupPhantomVolume` is an unexported function in `instance_post.go` that handles instance volume migration cleanup, while this code handles custom volume migration cleanup in `storage_volumes.go`. Extracting a shared helper would require either exporting it or placing it in a third package, adding coupling between two otherwise independent migration paths for a small block of straightforward logic

I considered three alternatives before deciding on the current approach:

Export it from instance_post.go -> Exposes an internal cleanup detail in the package API.
Move it to the DB package -> Mixes application-level logging concerns into the data access layer.
Create a shared helper package -> Adds a whole package for a single small function.

None of these are cleaner than keeping each migration path self-contained with its own inline cleanup logic.

File: lxd/storage.go (hunk 17 above)
Comment (tugbataluy) [reply lxd/storage.go]: Good catch. I've stored the pools loaded during `initPool` in a separate `loadedPools` map and reused them in the cleanup loop, avoiding the redundant `LoadByName` call. The existing `initPools` map and its failure-tracking logic remain untouched.

File: lxd/storage/backend_lxd.go (hunk 16 above)
Comment (tugbataluy) [reply lxd/storage/backend_lxd.go]: Thanks :sparkle:

File: lxd/db/storage_volumes.go (hunk 14 above)
Comment (kadinsayani) [reply lxd/db/storage_volumes.go]: Nice, thanks for checking that.

File: lxd/storage_volumes.go (hunk 15 above)
Comment (kadinsayani) [reply lxd/storage_volumes.go]: Aren't both call-sites in the same `main` package? The `cleanupPhantomVolume` helper should be usable at both sites while being unexported.

Comment (tugbataluy) [reply lxd/storage_volumes.go]: You're right, both files are in package main so the unexported helper is directly accessible. I'll refactor the inline cleanup in storage_volumes.go to reuse cleanupPhantomVolume.
I was just overthinking :sweat_smile: . Change will be ready in an hour probably :)

File: lxd/db/storage_volumes.go [hunk 18]
```diff
@@ -505,6 +505,33 @@ func (c *ClusterTx) RemoveStoragePoolVolume(ctx context.Context, projectName str
 	return nil
 }
 
+// RemoveStoragePoolVolumeInMember removes a storage volume entry associated with a
+// specific cluster member. Used for cleaning up database entries left behind after
+// interrupted cluster migrations. Returns the number of rows deleted.
+// Associated snapshot and config records are automatically removed by ON DELETE CASCADE.
+func (c *ClusterTx) RemoveStoragePoolVolumeInMember(ctx context.Context, projectName string, volumeName string, volumeType cluster.StoragePoolVolumeType, poolID int64, memberName string) (int64, error) {
```
Comment (kadinsayani) [inline lxd/db/storage_volumes.go]: Consider using named return values:

```suggestion
func (c *ClusterTx) RemoveStoragePoolVolumeInMember(ctx context.Context, projectName string, volumeName string, volumeType cluster.StoragePoolVolumeType, poolID int64, memberName string) (rowsAffected int64, err error) {
```

File: lxd/storage/drivers/driver_dir_volumes.go [hunk 19]
```diff
@@ -191,16 +192,19 @@ func (d *dir) DeleteVolume(vol Volume, op *operations.Operation) error {
 		return fmt.Errorf("Failed removing %q: %w", volPath, err)
 	}
 
-	// Get the volume ID for the volume, which is used to remove project quota.
```
Comment (kadinsayani) [inline lxd/storage/drivers/driver_dir_volumes.go:194]: Is this comment intentionally dropped?

File: lxd/storage/backend_lxd.go [hunk 20]
```diff
@@ -2389,12 +2397,28 @@ func (b *lxdBackend) CreateInstanceFromMigration(inst instance.Instance, conn io
...
```
Comment (kadinsayani) [inline lxd/storage/backend_lxd.go]:
```suggestion
	// Storage volumes can be left behind from interrupted migrations where the target was killed mid-transfer
```

File: lxd/storage/backend_lxd.go [hunk 21]
```diff
@@ -8401,3 +8453,91 @@ func (b *lxdBackend) GenerateInstanceCustomVolumeBackupConfig(inst instance.Inst
 
 	return instanceBackupConf, nil
 }
+
+// CleanupOrphanedMigrationVolumes removes storage volumes that exist on disk
+// but have no corresponding DB entry on this node, and whose instance is assigned
+// to a different cluster member. These are leftover from interrupted migrations
+// where the source cleaned up DB entries but couldn't reach the target for
+// storage cleanup.
+func (b *lxdBackend) CleanupOrphanedMigrationVolumes(s *state.State) {
```
Comment (kadinsayani) [inline lxd/storage/backend_lxd.go]: `CleanupOrphanedMigrationVolumes` takes `s *state.State` as a parameter, but `lxdBackend` already holds `b.state *state.State`. Every use of `s.DB.Cluster` inside the implementation could be `b.state.DB.Cluster` instead, right?

**Review by kadinsayani — CHANGES_REQUESTED** [review]

File: lxd/storage/backend_lxd.go (hunk 21 above)
Comment (tugbataluy) [reply lxd/storage/backend_lxd.go]: Yes, you're absolutely right :+1:

File: lxd/storage/drivers/driver_dir_volumes.go (hunk 19 above)
Comment (tugbataluy) [reply lxd/storage/drivers/driver_dir_volumes.go:194]: Nope it was me, being clumsy :melting_face:, thanks.

File: lxd/storage/backend_lxd.go [hunk 22]
```diff
@@ -2389,12 +2397,28 @@ func (b *lxdBackend) CreateInstanceFromMigration(inst instance.Instance, conn io
...
-		return errors.New("Volume exists in database but not on storage")
+		l.Warn("Removing phantom volume database record from previous interrupted migration")
+
+		err = VolumeDBDelete(b, inst.Project().Name, inst.Name(), volType)
+		if err != nil {
+			return fmt.Errorf("Failed removing phantom volume database record: %w", err)
+		}
+
+		dbVol = nil
 	}
```
Comment (kadinsayani) [inline lxd/storage/backend_lxd.go:2398]: This logic is duplicated below, can we extract a helper function for this?

**Review by kadinsayani — CHANGES_REQUESTED** [review]

File: lxd/storage/backend_lxd.go (hunk 22 above)
Comment (tugbataluy) [reply lxd/storage/backend_lxd.go:2398]: Yes I can do that, thanks Kadin :sparkle:

Comment (tugbataluy) [reply lxd/storage/backend_lxd.go:2398]: Done :D

**Review by kadinsayani — DISMISSED** [review]
Thanks!

File: test/suites/clustering_move.sh [hunk 23]
```diff
@@ -201,3 +201,81 @@ test_clustering_move() {
...
+  grep -qF "Removing phantom volume database record from previous interrupted migration" "${LXD_TWO_DIR}/lxd.log"
+
+  sub_test "Simulated storage-only orphan recovery"
+
+  # Move c1 back to node1.
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target node1
+  [ "$(LXD_DIR="${LXD_ONE_DIR}" lxc list --format csv --columns nL c1)" = "c1,node1" ]
+
+  # Create orphaned storage directory on node2 (simulates leftover from interrupted migration).
+  mkdir -p "${LXD_TWO_DIR}/storage-pools/data/containers/c1"
```
Comment (simondeziel) [inline test/suites/clustering_move.sh]: Is `-p` really needed?

File: test/suites/clustering_move.sh [hunk 24]
```diff
@@ -201,3 +201,81 @@ test_clustering_move() {
...
+
+  # Move c1 to node2, expecting recovery from phantom DB entry.
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target node2
+  [ "$(LXD_DIR="${LXD_ONE_DIR}" lxc list --format csv --columns nL c1)" = "c1,node2" ]
+
+  # Verify only one storage_volumes entry remains for c1.
+  [ "$(LXD_DIR="${LXD_ONE_DIR}" lxd sql global --format csv "SELECT COUNT(*) FROM storage_volumes WHERE name='c1'")" = "1" ]
+
+  # Verify cleanup warning was logged on node2.
+  grep -qF "Removing phantom volume database record from previous interrupted migration" "${LXD_TWO_DIR}/lxd.log"
```
Comment (simondeziel) [inline test/suites/clustering_move.sh]: I'd prefer losing the `-q` to aid debugging. If the preamble logs are of any debug interest, you might want to add a `-B3` or some such.

File: test/suites/clustering_move.sh [hunk 25]
```diff
@@ -201,3 +201,81 @@ test_clustering_move() {
...
+
+  # Create orphaned storage directory on node2 (simulates leftover from interrupted migration).
+  mkdir -p "${LXD_TWO_DIR}/storage-pools/data/containers/c1"
+
+  # Move c1 to node2, expecting recovery from orphaned storage.
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target node2
+  [ "$(LXD_DIR="${LXD_ONE_DIR}" lxc list --format csv --columns nL c1)" = "c1,node2" ]
+
+  # Verify cleanup warning was logged on node2.
+  grep -qF "Removing orphaned storage volume from previous interrupted migration" "${LXD_TWO_DIR}/lxd.log"
```
Comment (simondeziel) [inline test/suites/clustering_move.sh]: Same suggestion re `grep`.

File: test/suites/clustering_move.sh [hunk 26]
```diff
@@ -201,3 +201,81 @@ test_clustering_move() {
...
+  # Inject phantom storage_volumes entry for c1 on node2 (simulates interrupted migration).
+  LXD_DIR="${LXD_ONE_DIR}" lxd sql global "INSERT INTO storage_volumes (name, storage_pool_id, node_id, type, description, project_id, content_type) \
+    SELECT 'c1', ${pool_id}, ${node2_id}, 0, '', id, 0 FROM projects WHERE name='default'"
+
+  # Verify phantom entry exists (expect 2 entries for c1).
+  [ "$(LXD_DIR="${LXD_ONE_DIR}" lxd sql global --format csv "SELECT COUNT(*) FROM storage_volumes WHERE name='c1'")" = "2" ]
+
+  # Move c1 to node2, expecting recovery from phantom DB entry.
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target node2
+  [ "$(LXD_DIR="${LXD_ONE_DIR}" lxc list --format csv --columns nL c1)" = "c1,node2" ]
```
Comment (simondeziel) [inline test/suites/clustering_move.sh]: Unless you envision adding more instance, I'd lose the `c1` filtering provided to `lxc list`:

```suggestion
  [ "$(LXD_DIR="${LXD_ONE_DIR}" lxc list --format csv --columns nL)" = "c1,node2" ]
```

File: test/suites/clustering_move.sh [hunk 27]
```diff
@@ -201,3 +201,81 @@ test_clustering_move() {
...
+  [ "$(LXD_DIR="${LXD_ONE_DIR}" lxd sql global --format csv "SELECT COUNT(*) FROM storage_volumes WHERE name='c1'")" = "1" ]
+
+  # Verify cleanup warning was logged on node2.
+  grep -qF "Removing phantom volume database record from previous interrupted migration" "${LXD_TWO_DIR}/lxd.log"
+
+  sub_test "Simulated storage-only orphan recovery"
+
+  # Move c1 back to node1.
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target node1
+  [ "$(LXD_DIR="${LXD_ONE_DIR}" lxc list --format csv --columns nL c1)" = "c1,node1" ]
```
Comment (simondeziel) [inline test/suites/clustering_move.sh]: Same `lxc list` filtering.

File: test/suites/clustering_move.sh [hunk 28]
```diff
@@ -201,3 +201,81 @@ test_clustering_move() {
...
+
+  # Create orphaned storage directory on node2 (simulates leftover from interrupted migration).
+  mkdir -p "${LXD_TWO_DIR}/storage-pools/data/containers/c1"
+
+  # Move c1 to node2, expecting recovery from orphaned storage.
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target node2
+  [ "$(LXD_DIR="${LXD_ONE_DIR}" lxc list --format csv --columns nL c1)" = "c1,node2" ]
```
Comment (simondeziel) [inline test/suites/clustering_move.sh]: Same `lxc list` filtering.

File: lxd/instance_post.go [hunk 29]
```diff
@@ -1129,6 +1132,32 @@ func instancePostClusteringMigrateWithRemoteStorage(s *state.State, srcPool stor
...
+	// Track rows deleted to only log when a phantom entry was actually removed.
+	var rowsDeleted int64
+
+	err := s.DB.Cluster.Transaction(context.Background(), func(ctx context.Context, tx *db.ClusterTx) error {
+		var err error
+		rowsDeleted, err = tx.RemoveStoragePoolVolumeInMember(ctx, projectName, volumeName, volDBType, poolID, memberName)
+		return err
+	})
+	if err != nil {
+		logger.Warn("Failed cleaning up phantom volume DB entry on target member", logger.Ctx{
```
Comment (simondeziel) [inline lxd/instance_post.go]: Isn't the `on target member` part implicit thanks to the context having a `member` field? I don't know what the convention in the rest of the code though.

File: lxd/instance_post.go [hunk 30]
```diff
@@ -1129,6 +1132,32 @@ func instancePostClusteringMigrateWithRemoteStorage(s *state.State, srcPool stor
...
+			"project": projectName, "volume": volumeName, "member": memberName, "err": err,
+		})
+		return
+	}
+
+	if rowsDeleted > 0 {
+		logger.Warn("Removed phantom volume DB entry on target member after failed migration", logger.Ctx{
```
Comment (simondeziel) [inline lxd/instance_post.go]: Same observation re `on target member`.

**Comment by tugbataluy** [comment]
> Thanks!

Thank you again Kadin, your suggestions helped me a lot :sparkle:

**Comment by tugbataluy** [comment]
Thanks Simon for the reviewing the test case and the log context, I modified the case regarding your recommendations and this is what I understand from you (in a nutshell):

- Drop the `c1` name filter from `lxc list` calls:  with only one instance in the test, the assertion on the exact CSV output is sufficient to verify placement without the redundant filter.

- Remove `-q` from `grep` and switch to `-C3` to show three lines of context around the expected log message. This makes failures easier to diagnose by revealing what was actually logged around the point
where the warning was expected.

- Drop the `-p` flag from `mkdir`: the parent directory already exists at this point since the storage pool is initialised on node2. Using `-p` would silently succeed even if the path were wrong, masking a genuine test setup issue.

- Drop "on target member" from the `cleanupPhantomVolume` log message strings; the "member" field in `logger.Ctx` already captures that information, so repeating it in the message string is redundant and goes against the convention of keeping message strings generic while relying on structured fields for specifics.

File: test/suites/clustering_move.sh (hunk 23 above)
Comment (tugbataluy) [reply test/suites/clustering_move.sh]: I addressed all of your concerns in a one comment below, thanks Simon :sparkle:

**Review by tomponline — CHANGES_REQUESTED** [review]
Hi @tugbataluy thanks for this.

I took a look at the original problem description:

> When performing a migration, if the network interface is brought down, the migration times out, and instead of cleaning the partial database entries/storage volumes, it leaves them as phantom entries

But the scope of this PR seems to have grown to also encompass:

> When a cluster migration is interrupted abruptly (e.g. kill -9 on target LXD...

This is quite a different scenario from a network issue, because the LXDs involved now cannot know what happened before they were killed.

I think we should focus on the first scenario in this PR and ensure that A) connectivity issues are detected in a timely manner (if not already) and B) having LXD cleanup on each side (sender and receiver) when an error in the original migration attempt occurs.

This way, for a non-crash scenario, we can avoid getting into an inconsistent state in the first place.

The reason I am concerned about also growing the scope of the PR to encompass silent crash recovery is that the implications of unintended data loss increase, as LXD is now making assumptions that if a volume exists on disk without its counterpart DB record then it should be deleted. 

I think in this case where LXD detects inconsistency it is right that it should fail out and ask the administrator to put it right, as LXD is unaware of the circumstances that lead to the inconsistency, and starting to delete volumes in that case is quite concerning for me.

So to summarise:

If the LXD process detects a migration failure while it is still running, it should clean up its state as best it can.

But I feel that it is outside of the scope of LXD and this issue to automatically repair storage inconsistencies.

Thanks

File: lxc/image.go [hunk 31]
```diff
@@ -15,7 +15,7 @@ import (
 	"github.com/spf13/cobra"
 	"go.yaml.in/yaml/v2"
 
-	"github.com/canonical/lxd/client"
+	lxd "github.com/canonical/lxd/client"
```
Comment (simondeziel) [inline lxc/image.go]: Probably unintended.

File: lxc/image.go [hunk 32]
```diff
@@ -881,7 +881,7 @@ func (c *cmdImageImport) run(cmd *cobra.Command, args []string) error {
 		return fmt.Errorf(`Invalid type %T for "fingerprint" key in operation metadata`, fingerprint)
 	}
 
-	progress.Done("Image imported with fingerprint: " + fingerprint)
+	progress.Done(fmt.Sprintf("Image imported with fingerprint: %s", fingerprint))
```
Comment (simondeziel) [inline lxc/image.go]: This seems to be a merge conflict resolution hiccup. Please drop all changes to this file.

File: test/suites/clustering_move.sh [hunk 33]
```diff
@@ -150,6 +150,35 @@ test_clustering_move() {
 
   LXD_DIR="${LXD_ONE_DIR}" lxc profile delete prof1
 
+  sub_test "Phantom volume DB entry error after failed migration"
+  # When a cluster move fails mid-transfer (e.g. due to network disruption), LXD may leave a
+  # phantom storage_volumes DB entry on the target node if the target's revert chain could not
+  # reach the distributed DB while the network was down. Simulate this by directly inserting an
+  # orphaned row on node2 (no corresponding storage backing exists there), then verify LXD
+  # returns an actionable error message telling the administrator how to fix it.
```
Comment (simondeziel) [inline test/suites/clustering_move.sh:158]: I take it that it's too unreliable to abruptly abort a migration midway by forcibly killing one of the LXDs?

File: test/suites/clustering_move.sh [hunk 34]
```diff
@@ -150,6 +150,35 @@ test_clustering_move() {
...
+
+  # Inject a phantom storage_volumes row for c1 on node2, mimicking what is left behind
+  # when a migration fails mid-transfer and the target cannot run its DB revert.
+  LXD_DIR="${LXD_ONE_DIR}" lxd sql global "INSERT INTO storage_volumes (name, storage_pool_id, node_id, type, description, project_id) SELECT 'c1', (SELECT id FROM storage_pools WHERE name='data'), (SELECT id FROM nodes WHERE name='node2'), 0, '', (SELECT id FROM projects WHERE name='default')"
+
+  # Attempting to migrate c1 to node2 must fail and report an actionable error identifying
+  # the phantom entry and the SQL command needed to remove it.
+  ! LXD_DIR="${LXD_ONE_DIR}" lxc move cluster:c1 --target node2 || false
+  err_msg="$(LXD_DIR="${LXD_ONE_DIR}" lxc move cluster:c1 --target node2 2>&1 || true)"
+  [[ "${err_msg}" == *"phantom entry from a previous failed migration"* ]]
```
Comment (simondeziel) [inline test/suites/clustering_move.sh]: The duplicated `lxc move` can be avoided with something like that:
```suggestion
  exit_code=0
  err_msg="$(LXD_DIR="${LXD_ONE_DIR}" lxc move cluster:c1 --target node2 2>&1)" || exit_code=$?
  [[ "${exit_code}" -ne 0 ]]
  [[ "${err_msg}" == *"phantom entry from a previous failed migration"* ]]
```

File: lxc/image.go (hunk 32 above)
Comment (tugbataluy) [reply lxc/image.go]: But it gives lint error if I don't do those changes about string concat. We can do exact same thing with concatenation I guess, that's why linter forcing me to do that.

File: lxc/image.go (hunk 31 above)
Comment (tugbataluy) [reply lxc/image.go]: Yes it was :sweat_smile:

File: test/suites/clustering_move.sh (hunk 33 above)
Comment (tugbataluy) [reply test/suites/clustering_move.sh:158]: Killing LXD mid-migration to create a phantom would be a timing game: I'd need to kill it at exactly the right moment during the data transfer, which is inherently racy and non-deterministic. The test would be flaky (and also more likely to be too much complex). That's why I decided to simulate the problematic state, and the effect.

Comment (simondeziel) [reply test/suites/clustering_move.sh:158]: That's what I suspected, thanks for confirming.

File: lxc/image.go (hunk 32 above)
Comment (tugbataluy) [reply lxc/image.go]: Oh now I get it :melting_face: , thanks Simon.

**Review by simondeziel — DISMISSED** [review]

File: lxd/storage/backend_lxd.go [hunk 35]
```diff
@@ -2394,7 +2394,11 @@ func (b *lxdBackend) CreateInstanceFromMigration(inst instance.Instance, conn io
...
 
 	if dbVol != nil && !volExists {
-		return errors.New("Volume exists in database but not on storage")
+		return fmt.Errorf(
+			"Volume %q exists in database on member %q but not on storage. "+
+				"This may be a phantom entry from a previous failed migration. "+
+				`To fix, run: lxd sql global "DELETE FROM storage_volumes WHERE name='%s' AND node_id=(SELECT id FROM nodes WHERE name='%s')"`,
```
Comment (tomponline) [inline lxd/storage/backend_lxd.go]: Hrm, I'm don't think we should start putting SQL into error messages, this won't age well and is exposing internals.

Perhaps instead create a documentation page covering manually removing volume DB entries and then refer them to that?

**Review by tomponline — CHANGES_REQUESTED** [review]
Apart from the SQL in the error messages this looks good. Thanks

File: lxd/storage/backend_lxd.go (hunk 35 above)
Comment (tugbataluy) [reply lxd/storage/backend_lxd.go]: Sure I think, it seems reasonable :)

Comment (tomponline) [reply lxd/storage/backend_lxd.go]: Can we get the first commit landed and then the improvements to error and docs can some separately, to allow more testing of the actual change. Ta

Comment (tomponline) [reply lxd/storage/backend_lxd.go]: yep agree

Comment (tugbataluy) [reply lxd/storage/backend_lxd.go]: Ok I accidentally deleted what I've written :melting_face:  , first commit and the test will be committed as first PR and I'll open a following PR for errors improvements and docs.

**Review by tomponline — APPROVED** [review]
ta
