### PR TITLE
lxd/init: Add support for storage volumes in preseed init

### LINKED ISSUE #10956: Add support for configuring volumes to the preseed file
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4
   * LXC version: 5.0.1
   * LXD version: 5.0.1
   * Storage backend in use: any

# Issue description

I am interested in configuring LXD using a preseed file. One of the things I want to set is `storage.images_volume` as outlined [here](https://discuss.linuxcontainers.org/t/why-lxd-store-some-squashfs-images-outside-the-main-storage/7678/2) to a custom location. I can define the storage pool within the preseed file, but I cannot define a storage volume. It seems that the volume must exist for `storage.images_volume` to be set (e.g. it isn’t created automatically), so I'd like to request that the ability to configure volumes be added to the preseed file.

# Steps to reproduce

 1. Create a preseed file with `storage.images_volume` set
 2. Attempt to load the preseed file with `cat /tmp/preseed.yml | lxd init --preseed`
 3. See the error:

```
Error: Failed to update server configuration: Unable to load storage volume "default/images": Storage pool volume not found
```

# Information to attach

Here is an example preseed file that can reproduce this issue:

```
config:
  storage.images_volume: default/images
storage_pools:
- config:
    size: 10GB
  name: default
  driver: dir
profiles:
- name: example
  devices:
    images:
      path: /tmp/images
      pool: default
      source: images
      type: disk
```

### PR DESCRIPTION
**Pull request by megheaiulian**
Add support for configuring storage volumes in preseed init.

Fixes #10956

### CODE REVIEW

File: shared/api/init.go [hunk 1]
```diff
@@ -64,3 +68,15 @@ type InitClusterPreseed struct {
 	// Example: BASE64-TOKEN
 	ClusterToken string `json:"cluster_token" yaml:"cluster_token"`
 }
+
+// InitStorageVolumesPost represents the fields of a new LXD storage volume along with its associated pool.
+//
```
Comment (tomponline) [inline shared/api/init.go:73]: Please can we call this `InitStorageVolumesProjectPost` to align with `InitNetworksProjectPost`

File: lxd/init.go [hunk 2]
```diff
@@ -131,6 +131,102 @@ func initDataNodeApply(d lxd.InstanceServer, config api.InitLocalPreseed) (func(
...
+			// Get the list of storageVolumes.
+			volumeNames, err := d.GetStoragePoolVolumeNames(poolName)
+			if err != nil {
+				return nil, fmt.Errorf("Failed to retrieve list of storage volumes: %w", err)
+			}
+
+			storageVolumeNames[poolName] = volumeNames
+		}
+
+		// StorageVolume creator
```
Comment (tomponline) [inline lxd/init.go:154]: missing full stop

File: shared/api/init.go [hunk 3]
```diff
@@ -64,3 +68,15 @@ type InitClusterPreseed struct {
...
+// swagger:model
+//
+// API extension: preseed.
+type InitStorageVolumesPost struct {
+	StorageVolumesPost `yaml:",inline"`
+	// Storage pool in which the volume will reside
+	// Example: "default"
+	Pool string
```
Comment (tomponline) [inline shared/api/init.go:81]: We also need Project string field as volumes can belong to projects.

**Review by tomponline — CHANGES_REQUESTED** [review]
Thanks for this!

Please can you add some tests to test_init_preseed function

File: shared/api/init.go (hunk 3 above)
Comment (megheaiulian) [reply shared/api/init.go:81]: I think that pools can also belong in projects. As such they would need to support a Project field too? 
If that's the case I think that I can try to add support for Project in StoragePool and StorageVolume in a separate PR.

Comment (tomponline) [reply shared/api/init.go]: No pools do not belong to projects.

File: lxd/init.go [hunk 4]
```diff
@@ -130,6 +130,77 @@ func initDataNodeApply(d lxd.InstanceServer, config api.InitLocalPreseed) (func(
...
 	}
 
+	// Apply storage volumes configuration.
+	applyStorageVolume := func(storageVolume api.InitStorageVolumesProjectPost) error {
+		// Get the current storageVolume.
+		currentStorageVolume, etag, err := d.UseProject(storageVolume.Project).GetStoragePoolVolume(storageVolume.Pool, storageVolume.Type, storageVolume.Name)
+
+		if err != nil {
+			// Create the storage volume if it doesn't exist.
+			err := d.UseProject(storageVolume.Project).CreateStoragePoolVolume(storageVolume.Pool, storageVolume.StorageVolumesPost)
```
Comment (megheaiulian) [inline lxd/init.go:140]: @tomponline Seems the storage volume creation is failing here.
Am I trying to create storage volumes in the default project too soon?
The storage pool should exist because we are creating it an earlier stage 114-129?

Comment (megheaiulian) [reply lxd/init.go:140]: Nevermind. Was missing type which is required.

**Comment by megheaiulian** [comment]
@tomponline I think should be ok now. Ran the tests also locally and they passed.
Can you please have another look at the code?

**Comment by megheaiulian** [comment]
Updated this again. The test was trying to delete the storage pool first and then the volume.

**Review by tomponline — CHANGES_REQUESTED** [review]
Thanks!

Please can you rebase this so that each commit makes up a single logical change, i.e we dont want to have multiple commits that make a change to, for example, lxd/init.go, and then later in the PR those initial changes are altered again.

**Review by tomponline — CHANGES_REQUESTED** [review]
https://github.com/canonical/lxd/pull/12426/commits/7a4c85b82d1939258c6e3fec8eeaf7d4c70bcbfa still looks like its including more than just tests.

File: shared/api/init.go [hunk 5]
```diff
@@ -48,6 +52,21 @@ type InitNetworksProjectPost struct {
 	Project string
 }
 
+// InitStorageVolumesProjectPost represents the fields of a new LXD storage volume along with its associated pool.
+//
+// swagger:model
+//
+// API extension: preseed.
```
Comment (MusicDin) [inline shared/api/init.go:59]: Just a question, here we are mentioning a `preseed` API extension, but it has not been added?

We already have a `init_preseed` extension, but I think we should add a new one?

Comment (tomponline) [inline shared/api/init.go]: This should be init_preseed_storage_volumes as it was introduced with that API extension.

Also please can you break the changes to shared/api into its own commit so they can be backported independently of the feature.

File: doc/api-extensions.md [hunk 6]
```diff
@@ -2329,3 +2329,7 @@ This introduces the configuration keys `cephfs.create_missing`, `cephfs.osd_pg_n
 
 This API extension provides the ability to use flags `--profile`, `--no-profile`, `--device`, and `--config`
 when moving an instance between projects and/or storage pools.
+
+## `init_preseed_storage_volumes`
```
Comment (tomponline) [inline doc/api-extensions.md:2333]: the commit message should start `api: ` like the others.

Thanks

**Comment by megheaiulian** [comment]
@tomponline Is the test failure relevant? It is very hard to figure where exactly the tests have failed since the stack trace is huge?

**Comment by tomponline** [comment]
You need to rebase your branch on upstream main to get the openfga revert changes

**Review by MusicDin — APPROVED** [review]

**Comment by tomponline** [comment]
Hi @megheaiulian please can you rebase this so the tests run again, we've recently changed the contributor requirements to require the Ubuntu CLA be signed for external contributors, see https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md#license-and-copyright so we need the CLA check to re-run. Thanks

**Comment by megheaiulian** [comment]
I've signed the CLA. Please retry the checks.

**Review by tomponline — APPROVED** [review]
LGTM thanks!
