### PR TITLE
Instance: Fix ZFS tests with exclusive lock on refresh

### LINKED ISSUE #10479: Fix ZFS migration test due to forkfile runnning for target instance
Since https://github.com/lxc/lxd/pull/10469 was merged the ZFS `migration` tests have been failing due to the increased run duration of forkfile.

```
lxc copy l1:c1 l2:c1 --refresh --verbose
INFO   [2022-05-27T23:15:40Z] Waiting for migration channel connections    
INFO   [2022-05-27T23:15:40Z] Migration channels connected                 
INFO   [2022-05-27T23:15:40Z] Creating container                            ephemeral=false instance=c1/snap0 instanceType=container project=default
INFO   [2022-05-27T23:15:40Z] Created container                             ephemeral=false instance=c1/snap0 instanceType=container project=default
Error: Failed instance creation: Error transferring instance data: Got error reading migration source: websocket: close 1000 (normal)
ERROR  [2022-05-27T23:15:51Z] Failed closing listener connection            err="use of closed network connection" listener=5b6b0b03-3024-4694-9880-e0977c6168ef
ERROR  [2022-05-27T23:15:51Z] Failed closing listener connection            err="use of closed network connection" listener=51a64bb3-7235-4ef3-9be9-31ae7144d44c
```

https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/7098/arch=arm64,backend=zfs,compiler=golang-1.18,section=standalone/console#console-section-0

This has been identified as caused by the ZFS optimized refresh mode being prevented from deleting the target volume because it is mounted (and in use by forkfile).

- [x] Properly propagate the storage error on the target as currently it is not displayed to user (https://github.com/lxc/lxd/pull/10480).
- [x] Ensure that exclusive access to the instance is gained before trying to receive a volume (https://github.com/lxc/lxd/pull/10484).

### PR DESCRIPTION
**Pull request by tomponline**
Fixes #10479

Ensures that forkfile is stopped before attempting to perform a refresh of the instance's root volume by utilising the `create` operation lock to provide an exclusive lock on the instance. This ensures the volume can be unmounted by the storage subsystem.

We were already using a `create` operation lock to prevent conflicting concurrent create requests if the instance didn't exist, so I decided to reuse this concept for instance refreshes as well. This way the existing operation lock infrastructure will be able to detect if a refresh is occurring and fail or wait until it has completed as needed.

### CODE REVIEW

File: lxd/instance/drivers/driver_lxc.go [hunk 1]
```diff
@@ -5697,6 +5695,7 @@ func (d *lxc) stopForkfile() {
 		return
 	}
 
+	d.logger.Info("Stopping forkfile", logger.Ctx{"pid": pid})
```
Comment (stgraber) [inline lxd/instance/drivers/driver_lxc.go:5698]: Shouldn't that be a Debug?

Comment (tomponline) [reply lxd/instance/drivers/driver_lxc.go]: OK makes sense, fixed now.

**Comment by tomponline** [comment]
Want a clear run on zfs

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
@stgraber good to go
