### PR TITLE
Storage: Fix redundant settings of zfs properties

### LINKED ISSUE #12278: Some zfs properties set multiple times
Running `lxc storage create ... zfs source=...` seems result in many duplicated `zfs set` calls. Steps to reproduce:

```
# Clear any existing/old events
zpool events -c
# Create the storage pool
lxc storage create disk zfs source=/dev/vdb
# Save the fresh events
zpool events -Hv > lxc-events.log
```

This will show a lot of events some appearing to be duplicates (setting the same property on the same DS):
```
# grep -F3 disk/deleted/virtual-machines lxc-events.log | grep -F3 volmode
        pool_context = 0x0
        history_hostname = "sdeziel01"
        history_dsname = "disk/deleted/virtual-machines"
        history_internal_str = "volmode=3"
        history_internal_name = "set"
        history_dsid = 0x28d
--
--
        pool_context = 0x0
        history_hostname = "sdeziel01"
        history_dsname = "disk/deleted/virtual-machines"
        history_internal_str = "volmode=3"
        history_internal_name = "set"
        history_dsid = 0x28d
--
--
        pool_context = 0x0
        history_hostname = "sdeziel01"
        history_dsname = "disk/deleted/virtual-machines"
        history_internal_str = "volmode=3"
        history_internal_name = "set"
        history_dsid = 0x28d
--
```

This also happens on the root DS (aka the dataset of the pool itself) but for different properties like `devices` or `atime`:

```
# grep -F3 '"atime=' lxc-events
        pool_context = 0x0
        history_hostname = "sdeziel01"
        history_dsname = "disk"
        history_internal_str = "atime=0"
        history_internal_name = "set"
        history_dsid = 0x36
        history_txg = 0x9
--
        pool_context = 0x0
        history_hostname = "sdeziel01"
        history_dsname = "disk"
        history_internal_str = "atime=0"
        history_internal_name = "set"
        history_dsid = 0x36
        history_txg = 0x72
--
        pool_context = 0x0
        history_hostname = "sdeziel01"
        history_dsname = "disk"
        history_internal_str = "atime=0"
        history_internal_name = "set"
        history_dsid = 0x36
        history_txg = 0xfa
```

[lxc-events.log](https://github.com/canonical/lxd/files/12666063/lxc-events.log)

### PR DESCRIPTION
**Pull request by hamistao**
Fixes #12278 by making It possible for LXD to get ZFS dataset properties before setting them and avoid resetting those that already have the desired value. Performs this operation on `ensureInitialDatasets`.

### CODE REVIEW

File: lxd/storage_pools_utils.go [hunk 1]
```diff
@@ -117,12 +117,6 @@ func storagePoolCreateLocal(state *state.State, poolID int64, req api.StoragePoo
 
 	revert.Add(func() { _ = pool.Delete(clientType, nil) })
 
-	// Mount the pool.
```
Comment (roosterfish) [inline lxd/storage_pools_utils.go:120]: I understand you can remove the call to `ensureInitialDatasets` from the zfs drivers `Create()` as this is already called when running `Mount()`. 

But this change seems rather powerful as if affects all of the drivers. Does the zfs driver even have to mount the pool if it's anyway done here after calling the drivers `Create()`?

Comment (hamistao) [reply lxd/storage_pools_utils.go]: Yes I agree this change might be too powerful, this is why I am leaving this as a draft. I just pushed some changes leaving `storagePoolCreate` unchanged and removing the `Mount()` call from `*lxdBackend.Create` and `ensureInitialDatasets()` from the zfs drivers `Create()`. If you agree this makes sense I will open the PR for review.

Comment (hamistao) [reply lxd/storage_pools_utils.go]: Also I thought it made sense to discard the cherry picked commit since now my changes are following a very different logic, please let me know if that was a mistake

Comment (roosterfish) [reply lxd/storage_pools_utils.go]: This breaks a few of the storage drivers if you check the pipeline.

I would not try to fix this in the pools backend, instead as the problem is only occuring for the zfs driver, putting in a fix that only affects the zfs driver seems more reasonable to me.

Can you maybe make `ensureInitialDatasets()` idempotent and skip its actions if already done?

File: lxd/storage/drivers/driver_zfs.go [hunk 2]
```diff
@@ -560,6 +560,30 @@ func (d *zfs) importPool() (bool, error) {
 	return false, fmt.Errorf("ZFS zpool exists but dataset is missing")
 }
 
+func (d *zfs) isSetup() (bool, error) {
+	setup, err := d.datasetExists(d.config["zfs.pool_name"])
+	if err != nil {
+		return false, err
+	}
+
+	if !setup {
```
Comment (roosterfish) [inline lxd/storage/drivers/driver_zfs.go:563]: Just a nit, to safe this extra condition here and below you can just do `if err != nil || !setup` when checking for existence of the dataset as in the latter case `err` equals `nil` anyway.

File: lxd/storage/drivers/driver_zfs.go [hunk 3]
```diff
@@ -560,6 +560,31 @@ func (d *zfs) importPool() (bool, error) {
 	return false, fmt.Errorf("ZFS zpool exists but dataset is missing")
 }
 
+func (d *zfs) isSetup() (bool, error) {
```
Comment (roosterfish) [inline lxd/storage/drivers/driver_zfs.go:557]: Could you please add a comment describing the purpose of the function?

Comment (roosterfish) [reply lxd/storage/drivers/driver_zfs.go:557]: Also could you add the name of the storage driver to the commit message so that it's clear which driver is affected by this commit. Something like `lxd/storage/drivers/zfs` will do.

**Review by roosterfish — CHANGES_REQUESTED** [review]
I am leaving https://github.com/canonical/lxd/pull/13218#discussion_r1551499006 up to you.

**Comment by hamistao** [comment]
@tomponline this implementation avoids creating duplicate events on zfs by setting dataset properties multiple times unnecessarily. I am still discussing with @roosterfish to agree on the best way to implement this.

**Comment by tomponline** [comment]
> @tomponline this implementation avoids creating duplicate events on zfs by setting dataset properties multiple times unnecessarily. I am still discussing with @roosterfish to agree on the best way to implement this.

Yes, but it does this by removing the mount time data set policy application, which is undesirable.

**Comment by hamistao** [comment]
Yes, I agree. This is why I haven't opened this PR for review yet. I will try to find a better solution as soon as possible.

**Comment by hamistao** [comment]
@tomponline @roosterfish What do you think of this approach?

File: lxd/storage/drivers/driver_zfs_utils.go [hunk 4]
```diff
@@ -194,16 +194,60 @@ func (d *zfs) getDatasets(dataset string, types string) ([]string, error) {
...
 
-func (d *zfs) setDatasetProperties(dataset string, options ...string) error {
+func (d *zfs) setDatasetProperties(dataset string, verifyCurrent bool, options ...string) error {
 	args := []string{"set"}
-	args = append(args, options...)
-	args = append(args, dataset)
 
-	_, err := shared.RunCommand("zfs", args...)
+	// Skip current property values verification.
+	if !verifyCurrent {
```
Comment (roosterfish) [inline lxd/storage/drivers/driver_zfs_utils.go:201]: As `setDatasetProperties` is now checking if the property matches the expected value, do we even need `verifyCurrent`?

In case the property is not yet there, the check below `currentProperties[keys[propertyIndex]] != values[propertyIndex]` would return false so the property gets set.

File: lxd/storage/drivers/driver_zfs_utils.go [hunk 5]
```diff
@@ -194,16 +194,60 @@ func (d *zfs) getDatasets(dataset string, types string) ([]string, error) {
...
+		property := strings.Split(option, "=")
+
+		if len(property) != 2 {
+			continue
+		}
+
+		keys = append(keys, property[0])
+
+		// Handle "posixacl" and "posix" equivalency to avoid duplicate events.
+		if property[0] == "acltype" && property[1] == "posixacl" {
```
Comment (roosterfish) [inline lxd/storage/drivers/driver_zfs_utils.go:222]: Can you please explain this a bit more? The question I am having is why can't we set `acltype=posixacl`?

Is it the same or should we instead update `zfsDefaultSettings` to use `posix` instead of `posixacl`?

File: lxd/storage/drivers/driver_zfs_utils.go [hunk 6]
```diff
@@ -227,7 +271,7 @@ func (d *zfs) setBlocksize(vol Volume, size int64) error {
 		return nil
 	}
 
-	err := d.setDatasetProperties(d.dataset(vol, false), fmt.Sprintf("recordsize=%d", size))
+	err := d.setDatasetProperties(d.dataset(vol, false), false, fmt.Sprintf("recordsize=%d", size))
```
Comment (roosterfish) [inline lxd/storage/drivers/driver_zfs_utils.go:274]: This line should probably be in the next commit where you update the usages of `setDatasetProperties`.

File: test/suites/storage_driver_zfs.sh [hunk 7]
```diff
@@ -269,8 +269,8 @@ do_storage_driver_zfs() {
   lxc storage unset lxdtest-"$(basename "${LXD_DIR}")" volume.zfs.block_mode
 
   # Regular (no block mode) custom storage block volumes shouldn't be allowed to set block.*.
-  ! lxc storage create lxdtest-"$(basename "${LXD_DIR}")" block.filesystem=ext4 || false
```
[the remark this answers is not in the document]
Comment (hamistao) [reply test/suites/storage_driver_zfs.sh:272]: Yes, so it was failing for the wrong reason. As for the comment, I think it was already aligned with what the command was supposed to be doing, I don't see why it needs changing.

File: lxd/storage/drivers/driver_zfs_utils.go (hunk 4 above)
Comment (hamistao) [reply lxd/storage/drivers/driver_zfs_utils.go:201]: this flag is there because a lot of the times the extra complexity of calling `getDatasetProperties` and checking the current values is not necessary. So `validateCurrent` makes the function more flexible and avoids doing that extra work when it is not needed. Without it I got some `timout` errors in the tests. Another option would be doing that verification on `ensureInitialDatasets` instead and leave `setDatasetProperties` unchanged, but I think it looks more clean this way.

File: lxd/storage/drivers/driver_zfs_utils.go (hunk 5 above)
Comment (hamistao) [reply lxd/storage/drivers/driver_zfs_utils.go:222]: setting it to `posixacl` is the same as setting it to `posix` so without this check it actually will set it twice because the current value will be `posix` and the new will be `posixacl`. But in any case updating `zfsDefaultSettings` is probably a better approach. I will change this, thanks!

File: lxd/storage/drivers/driver_zfs.go [hunk 8]
```diff
@@ -34,7 +34,7 @@ var zfsDefaultSettings = map[string]string{
 	"setuid":     "on",
 	"exec":       "on",
 	"devices":    "on",
-	"acltype":    "posixacl",
+	"acltype":    "posix", // acltype "posix" is equivalent to "posixacl". Set as "posix" to avoid setting it multiple times on ensureInitialDatasets.
```
Comment (roosterfish) [inline lxd/storage/drivers/driver_zfs.go:37]: Mhh I am wondering if it would be helpful also adding a link to the zfs docs? https://openzfs.github.io/openzfs-docs/man/master/7/zfsprops.7.html#acltype.
It makes it clear that `posixacl` is an alias for `posix`.

File: lxd/storage/drivers/driver_zfs_utils.go [hunk 9]
```diff
@@ -194,6 +194,40 @@ func (d *zfs) getDatasets(dataset string, types string) ([]string, error) {
...
+func (d *zfs) filterRedundantOptions(dataset string, options ...string) ([]string, error) {
+	keys := []string{}
+	values := []string{}
+
+	// Extract keys and values from options.
+	for _, option := range options {
+		property := strings.Split(option, "=")
+
+		if len(property) != 2 {
+			continue
```
Comment (roosterfish) [inline lxd/storage/drivers/driver_zfs_utils.go:206]: Wouldn't it be safer to return an error here instead of silently skipping the wrongly formatted property? What do you think?

**Review by roosterfish — CHANGES_REQUESTED** [review]
Thanks for changing it to checking the individual properties instead. Looks good to me just two more small comments from side.

File: lxd/storage/drivers/driver_zfs.go (hunk 8 above)
Comment (hamistao) [reply lxd/storage/drivers/driver_zfs.go:37]: I think it is not necessary for such a simple concept like an alias.

File: lxd/storage/drivers/driver_zfs_utils.go (hunk 9 above)
Comment (hamistao) [reply lxd/storage/drivers/driver_zfs_utils.go:206]: Yes, I think you are right. I will change that, thanks!

File: lxd/storage/drivers/driver_zfs.go (hunk 8 above)
Comment (roosterfish) [reply lxd/storage/drivers/driver_zfs.go:37]: Maybe you can put it in the commit message for reference.

File: lxd/storage/drivers/driver_zfs_utils.go [hunk 10]
```diff
@@ -194,6 +194,40 @@ func (d *zfs) getDatasets(dataset string, types string) ([]string, error) {
...
+func (d *zfs) filterRedundantOptions(dataset string, options ...string) ([]string, error) {
+	keys := []string{}
+	values := []string{}
+
+	// Extract keys and values from options.
+	for _, option := range options {
+		property := strings.Split(option, "=")
+
+		if len(property) != 2 {
+			return nil, fmt.Errorf("Wrongly formatted option \"%s\"", option)
```
Comment (roosterfish) [inline lxd/storage/drivers/driver_zfs_utils.go:206]: We normally use `%q` as it will take care of quoting the value:

```suggestion
			return nil, fmt.Errorf("Wrongly formatted option %q, option)
```

**Review by roosterfish — CHANGES_REQUESTED** [review]

**Review by roosterfish — COMMENTED** [review]
Looking good, just one more comment from my side :)

File: lxd/storage/drivers/driver_zfs.go [hunk 11]
```diff
@@ -166,12 +173,19 @@ func (d zfs) ensureInitialDatasets(warnOnExistingPolicyApplyError bool) error {
 		}
 
 		if exists {
-			err = d.setDatasetProperties(datasetPath, properties...)
+			properties, err = d.filterRedundantOptions(datasetPath, properties...)
```
[the remark this answers is not in the document]
Comment (hamistao) [reply lxd/storage/drivers/driver_zfs.go:176]: No problem! I think just using args(or properties) in both instances and leave the function name as it is makes the most sense. Calling it `filterRedundantProperties()` seems less appropriate.

[the remark this answers is not in the document]
Comment (roosterfish) [reply lxd/storage/drivers/driver_zfs.go:176]: Fine for me, please ping me when you have pushed the changes for either using `args` or `properties` as I'll then do the final review.

[the remark this answers is not in the document]
Comment (hamistao) [reply lxd/storage/drivers/driver_zfs.go]: @roosterfish done!

**Review by roosterfish — DISMISSED** [review]
LGTM!

@tomponline this one seems ready.

File: lxd/storage/drivers/driver_zfs.go (hunk 8 above)
Comment (tomponline) [inline lxd/storage/drivers/driver_zfs.go:37]: Is `posix` newer than `posixacl` and if so, when did it get introduced?

**Comment by tomponline** [comment]
@hamistao please can you update the PR description to explain what this PR changes.

**Comment by hamistao** [comment]
@tomponline Done!

File: lxd/storage/drivers/driver_zfs_utils.go [hunk 12]
```diff
@@ -194,6 +194,40 @@ func (d *zfs) getDatasets(dataset string, types string) ([]string, error) {
 	return children, nil
 }
 
+func (d *zfs) filterRedundantOptions(dataset string, options ...string) ([]string, error) {
+	keys := []string{}
```
Comment (tomponline) [inline lxd/storage/drivers/driver_zfs_utils.go:198]: You can just do `var keys, values []string` here as there's no need to initialise them, append will do this for you.

File: lxd/storage/drivers/driver_zfs.go [hunk 13]
```diff
@@ -356,12 +356,6 @@ func (d *zfs) Create() error {
 
 	revert.Add(func() { _ = d.Delete(nil) })
 
-	// Apply our default configuration.
-	err = d.ensureInitialDatasets(false)
```
Comment (tomponline) [inline lxd/storage/drivers/driver_zfs.go:360]: We need to keep this so that if the initial datasets cannot be created and configured then the pool creation will fail.

Mount() allows for warning if something goes wrong to allow for historically setup pools to not start failing if new requirements change in the future.

**Review by tomponline — CHANGES_REQUESTED** [review]
We need to ensure the initial datasets are created at pool creation time and fail pool creation if not.

File: lxd/storage/drivers/driver_zfs.go (hunk 8 above)
Comment (hamistao) [reply lxd/storage/drivers/driver_zfs.go:37]: `posixacl` is older but was kept as an alias when `posix` was added in September 16th, 2020

Comment (tomponline) [reply lxd/storage/drivers/driver_zfs.go:37]: which version was it added in?

Comment (tomponline) [reply lxd/storage/drivers/driver_zfs.go:37]: Can you check this doesn't break LXD 5.21/stable with this binary sideloaded on a ZFS 0.8 system (bionic with hwe kernel) please.

File: lxd/storage/drivers/driver_zfs_utils.go [hunk 14]
```diff
@@ -194,6 +194,39 @@ func (d *zfs) getDatasets(dataset string, types string) ([]string, error) {
 	return children, nil
 }
 
+func (d *zfs) filterRedundantOptions(dataset string, options ...string) ([]string, error) {
```
Comment (tomponline) [inline lxd/storage/drivers/driver_zfs_utils.go:197]: Missing doc block

File: lxd/storage/drivers/driver_zfs.go (hunk 8 above)
Comment (hamistao) [reply lxd/storage/drivers/driver_zfs.go:37]: Unfortunately it breaks. As can be seen [here](https://github.com/openzfs/zfs/blob/zfs-0.8.3/module/zcommon/zfs_prop.c#L157-L163) support for `posix` wasn't added until later. I am pushing a new version that solves this problem.

**Comment by tomponline** [comment]
@hamistao is this ready for review (please do ping me each time you are ready for another review).

File: lxd/storage/drivers/driver_zfs_utils.go [hunk 15]
```diff
@@ -194,6 +194,44 @@ func (d *zfs) getDatasets(dataset string, types string) ([]string, error) {
...
+	currentProperties, err := d.getDatasetProperties(dataset, keys...)
+	if err != nil {
+		return nil, err
+	}
+
+	var resultantOptions []string
+
+	// Change property values that are different from the current value.
+	for propertyIndex := range keys {
+		if currentProperties[keys[propertyIndex]] == "posix" && values[propertyIndex] == "posixacl" { // "posixacl" is an alias for "posix"
```
[the remark this answers is not in the document]
Comment (hamistao) [reply lxd/storage/drivers/driver_zfs_utils.go:223]: In newer versions it always comes back as "posix". In older versions it comes back as what was set.

File: lxd/storage/drivers/driver_zfs.go [hunk 16]
```diff
@@ -144,19 +144,26 @@ func (d zfs) ensureInitialDatasets(warnOnExistingPolicyApplyError bool) error {
...
+			}
+
 			d.logger.Warn("Failed applying policy to existing dataset", logger.Ctx{"dataset": d.config["zfs.pool_name"], "err": err})
-		} else {
-			return fmt.Errorf("Failed applying policy to existing dataset %q: %w", d.config["zfs.pool_name"], err)
 		}
 	}
 
 	for _, dataset := range d.initialDatasets() {
-		properties := []string{"mountpoint=legacy"}
```
[the remark this answers is not in the document]
Comment (roosterfish) [reply lxd/storage/drivers/driver_zfs.go:157]: I guess this is a result of my comment [here](https://github.com/canonical/lxd/pull/13218#discussion_r1574582118). The idea was to use the same variable name for the return values from `filterRedundantOptions()`. @hamistao am I right?

[the remark this answers is not in the document]
Comment (tomponline) [reply lxd/storage/drivers/driver_zfs.go:157]: sticking with properties would make more sense to me

[the remark this answers is not in the document]
Comment (hamistao) [reply lxd/storage/drivers/driver_zfs.go:157]: Yes, but in any case I am changing it back to `properties` since it is indeed more informative.

[the remark this answers is not in the document]
Comment (hamistao) [reply lxd/storage/drivers/driver_zfs.go]: @tomponline I pushed the new changes if you can give another review
