### PR TITLE
Revert to filepath traversal if subvolume list fails

### LINKED ISSUE #12555: lxd 5.18/stable security.nesting broken
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.2.0-26-generic
   * LXC version: 5.18/stable
   * LXD version: 5.18/stable
   * Storage backend in use: btrfs

# Issue description

Nested virtualization broken in lxd 5.18/stable.
It does not appear in version 5.17/stable.

# Steps to reproduce

1. Init a container in a btrfs backend with `security.nesting`, `security.syscalls.intercept.mknod`, and `security.syscalls.intercept.setxattr` to run lxd inside it.
2. Run `lxc init images:ubuntu/22.04 test3` in the container:
```
Creating test3
Error: Failed instance creation: Failed creating instance from image: Failed to run: btrfs subvolume list /var/snap/lxd/common/lxd/storage-pools/default: exit status 1 (ERROR: can't perform the search: Operation not permitted)
```

# Information to attach

### PR DESCRIPTION
**Pull request by markylaing**
#12258 Added an optimisation to the btrfs storage driver to use `btrfs subvolume list` instead of traversing the file structure when listing subvolumes. 

Unfortunately this may fail due to a permission error when using `btrfs` on `btrfs`. This commit reverts to using the previous method if `btrfs subvolume list` fails.

Closes #12555

### CODE REVIEW

**Review by tomponline — APPROVED** [review]
thanks @markylaing do you think it would be practical to add a test for this?

**Comment by markylaing** [comment]
> thanks @markylaing do you think it would be practical to add a test for this?

I'll give it a go

**Review by tomponline — CHANGES_REQUESTED** [review]
As discussed lets use d.state.OS.RunningInUserNS instead of falling back

**Comment by markylaing** [comment]
> As discussed lets use d.state.OS.RunningInUserNS instead of falling back

I've made this change. I'm finding testing it to be quite tricky, we need a set of utils for getting the LXD build running inside a container. The container itself can't be the busybox test image either. We don't seem to have any tests for nested containers as far as I can see. Shall I create a separate issue for it?

**Comment by tomponline** [comment]
> > As discussed lets use d.state.OS.RunningInUserNS instead of falling back
> 
> I've made this change. I'm finding testing it to be quite tricky, we need a set of utils for getting the LXD build running inside a container. The container itself can't be the busybox test image either. We don't seem to have any tests for nested containers as far as I can see. Shall I create a separate issue for it?

I wonder if we should rename https://github.com/canonical/lxd-ci/blob/main/tests/docker to test for both docker and LXD container nesting functionality.

Because this is based on using snap you are then free to install the snap inside the guest and use a full ubuntu container.

See https://github.com/canonical/lxd-ci/blob/main/tests/vm_nesting.sh for something similar but for VMs

File: lxd/storage/drivers/driver_btrfs_utils.go [hunk 1]
```diff
@@ -107,39 +108,70 @@ func (d *btrfs) hasSubvolumes(path string) (bool, error) {
...
 	}
 
-	path = strings.TrimPrefix(path, poolMountPath+"/")
+	var result []string
 
-	// Make sure the path has a trailing slash.
-	if !strings.HasSuffix(path, "/") {
-		path = path + "/"
-	}
+	if !d.state.OS.RunningInUserNS {
```
Comment (tomponline) [inline lxd/storage/drivers/driver_btrfs_utils.go:123]: This feels a bit "mixed up" now to me.
We have the comment about the permission error inside the stanza that is used for when containers arent being nested.
And the comment about "revert to walking..." doesn't mention why it is using this approach.

How about we swap this around and do something like:

```go
if d.state.OS.RunningInUserNS {
    // If using BTRFS in a nested container we cannot use "btrfs subvolume list" due to a permission error.
    // So instead walk the directory tree testing each directory to see if it is subvolume.
    err := filepath.Walk(path, func(fpath string, entry fs.FileInfo, err error) error {
    ...
} else {
    // If not running inside a nested container we can use "btrfs subvolume list" to get subvolumes which is
    // more performant than walking the directory tree.
    var stdout bytes.Buffer
    err := shared.RunCommandWithFds(d.state.ShutdownCtx, nil, &stdout, "btrfs", "subvolume", "list", poolMountPath)
    ...
}
```

Comment (markylaing) [reply lxd/storage/drivers/driver_btrfs_utils.go]: Ok looking clearer now thanks :)

**Comment by tomponline** [comment]
thanks!
