### PR TITLE
Task: Remove unnecessary calls to defer g.mu.Unlock()

### LINKED ISSUE #12540: Panic during test run
```
lxc info cluster:c2 --project foo
+ set +x
+ grep -q Location: node2
+ timeout --foreground 120 /home/runner/go/bin/lxc info cluster:c2 --project foo --verbose
+ lxc delete -f c1 c2 --project foo
+ set +x
+ timeout --foreground 120 /home/runner/go/bin/lxc delete -f c1 c2 --project foo --verbose
                                           
time="2023-11-21T13:41:18Z" level=info msg="Deleting instance" created="2023-11-21 13:41:17.63546786 +0000 UTC" ephemeral=false instance=c1 instanceType=container project=foo used="1970-01-01 00:00:00 +0000 UTC"
time="2023-11-21T13:41:18Z" level=info msg="Deleted instance" created="2023-11-21 13:41:17.63546786 +0000 UTC" ephemeral=false instance=c1 instanceType=container project=foo used="1970-01-01 00:00:00 +0000 UTC"
time="2023-11-21T13:41:18Z" level=info msg="Deleting instance" created="2023-11-21 13:41:18.008007205 +0000 UTC" ephemeral=false instance=c2 instanceType=container project=foo used="1970-01-01 00:00:00 +0000 UTC"
time="2023-11-21T13:41:18Z" level=info msg="Deleted instance" created="2023-11-21 13:41:18.008007205 +0000 UTC" ephemeral=false instance=c2 instanceType=container project=foo used="1970-01-01 00:00:00 +0000 UTC"
+ lxc project delete foo
+ set +x
+ timeout --foreground 120 /home/runner/go/bin/lxc project delete foo --verbose
Project foo deleted
+ LXD_DIR=/home/runner/work/lxd/lxd/test/tmp.9hT/6m2 lxd shutdown
time="2023-11-21T13:41:18Z" level=info msg="Asked to shutdown by API" force=false
time="2023-11-21T13:41:18Z" level=info msg="Starting shutdown sequence" signal="power failure"
fatal error: sync: unlock of unlocked mutex

goroutine 749 [running]:
sync.fatal({0x1e6c9b3?, 0xc000b99f20?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:1061 +0x18
sync.(*Mutex).unlockSlow(0xc00049c310, 0xffffffff)
	/opt/hostedtoolcache/go/1.21.4/x64/src/sync/mutex.go:229 +0x35
sync.(*Mutex).Unlock(0x100000000?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/sync/mutex.go:223 +0x25
github.com/canonical/lxd/lxd/task.(*Group).Start.func1(0xc000af7b80?)
	/home/runner/work/lxd/lxd/lxd/task/group.go:71 +0xe3
created by github.com/canonical/lxd/lxd/task.(*Group).Start in goroutine 288
	/home/runner/work/lxd/lxd/lxd/task/group.go:60 +0x2e5

goroutine 1 [select]:
main.(*cmdDaemon).Run(0xc000013d28, 0x0?, {0xc00048dd10, 0x0, 0x0?})
	/home/runner/work/lxd/lxd/lxd/main_daemon.go:83 +0x605
github.com/spf13/cobra.(*Command).execute(0xc000005200, {0xc000040090, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000005200)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/home/runner/work/lxd/lxd/lxd/main.go:217 +0x1e05

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/asm_amd64.s:1650 +0x1

goroutine 18 [syscall]:
os/signal.signal_recv()
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/sigqueue.go:152 +0x29
os/signal.loop()
	/opt/hostedtoolcache/go/1.21.4/x64/src/os/signal/signal_unix.go:23 +0x13
created by os/signal.Notify.func1.1 in goroutine 1
	/opt/hostedtoolcache/go/1.21.4/x64/src/os/signal/signal.go:151 +0x1f

goroutine 34 [select]:
database/sql.(*DB).connectionOpener(0xc000561860, {0x21e48b8, 0xc00051c410})
	/opt/hostedtoolcache/go/1.21.4/x64/src/database/sql/sql.go:1218 +0x87
created by database/sql.OpenDB in goroutine 1
	/opt/hostedtoolcache/go/1.21.4/x64/src/database/sql/sql.go:791 +0x165

goroutine 23 [select]:
database/sql.(*DB).connectionOpener(0xc000520680, {0x21e48b8, 0xc000385900})
	/opt/hostedtoolcache/go/1.21.4/x64/src/database/sql/sql.go:1218 +0x87
created by database/sql.OpenDB in goroutine 1
	/opt/hostedtoolcache/go/1.21.4/x64/src/database/sql/sql.go:791 +0x165

goroutine 22 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8edb8, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc000297080?, 0xc0004bfd00?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000297080)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:611 +0x2ac
net.(*netFD).accept(0xc000297080)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_unix.go:172 +0x29
net.(*UnixListener).accept(0x4ab946?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/unixsock_posix.go:172 +0x16
net.(*UnixListener).Accept(0xc000513380)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/unixsock.go:260 +0x30
net/http.(*Server).Serve(0xc00024e1e0, {0x21e0848, 0xc000513380})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:3056 +0x364
github.com/canonical/lxd/lxd/endpoints.(*Endpoints).serve.func1()
	/home/runner/work/lxd/lxd/lxd/endpoints/endpoints.go:433 +0x1f
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0003858b0, 0xc00051c5a0?)
	/home/runner/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go in goroutine 1
	/home/runner/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xe5

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8eeb0, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc000296e80?, 0xc002945200?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000296e80)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:611 +0x2ac
net.(*netFD).accept(0xc000296e80)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_unix.go:172 +0x29
net.(*UnixListener).accept(0x1dde0a0?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/unixsock_posix.go:172 +0x16
net.(*UnixListener).Accept(0xc0005132f0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/unixsock.go:260 +0x30
github.com/canonical/lxd/lxd/endpoints/listeners.(*StarttlsListener).Accept(0xc000513320)
	/home/runner/work/lxd/lxd/lxd/endpoints/listeners/starttls.go:36 +0x50
net/http.(*Server).Serve(0xc00024e000, {0x21e10e8, 0xc000513320})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:3056 +0x364
github.com/canonical/lxd/lxd/endpoints.(*Endpoints).serve.func1()
	/home/runner/work/lxd/lxd/lxd/endpoints/endpoints.go:433 +0x1f
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0003858b0, 0xc000548700?)
	/home/runner/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go in goroutine 1
	/home/runner/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xe5

goroutine 727 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8e218, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc000aa2280?, 0xc000b48000?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000aa2280, {0xc000b48000, 0x8000, 0x8000})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc000aa2280, {0xc000b48000?, 0x7ff020bafea8?, 0x0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc0001542b0, {0xc000b48000?, 0xc0004baea0?, 0xc0004baeb0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
io.copyBuffer({0x21d26a0, 0xc0000cd880}, {0x21d1980, 0xc0001542b0}, {0x0, 0x0, 0x0})
	/opt/hostedtoolcache/go/1.21.4/x64/src/io/io.go:430 +0x1a6
io.Copy(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/io/io.go:389
github.com/canonical/lxd/lxd/cluster.dqliteProxy.func2()
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:1169 +0x7b
created by github.com/canonical/lxd/lxd/cluster.dqliteProxy in goroutine 685
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:1168 +0x61e

goroutine 154 [syscall]:
syscall.Syscall(0x10?, 0x1a844e0?, 0x41f001?, 0x41ebba?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/syscall/syscall_linux.go:69 +0x25
golang.org/x/sys/unix.read(0x1b32920?, {0xc0004d5000?, 0x1e25ab3?, 0x9?})
	/home/runner/go/pkg/mod/golang.org/x/sys@v0.14.0/unix/zsyscall_linux.go:1376 +0x45
golang.org/x/sys/unix.Read(...)
	/home/runner/go/pkg/mod/golang.org/x/sys@v0.14.0/unix/syscall_unix.go:158
main.deviceNetlinkListener.func1(0xc000427440?, 0xc00011d920?, 0xc00011d980?, 0xc00011d9e0?)
	/home/runner/work/lxd/lxd/lxd/devices.go:100 +0x98
created by main.deviceNetlinkListener in goroutine 191
	/home/runner/work/lxd/lxd/lxd/devices.go:97 +0x1b3

goroutine 197 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8e9d8, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc000297c00?, 0x10?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000297c00)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:611 +0x2ac
net.(*netFD).accept(0xc000297c00)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_unix.go:172 +0x29
net.(*UnixListener).accept(0x0?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/unixsock_posix.go:172 +0x16
net.(*UnixListener).Accept(0xc000557470)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/unixsock.go:260 +0x30
github.com/canonical/lxd/lxd/seccomp.NewSeccompServer.func1()
	/home/runner/work/lxd/lxd/lxd/seccomp/seccomp.go:1072 +0x59
created by github.com/canonical/lxd/lxd/seccomp.NewSeccompServer in goroutine 1
	/home/runner/work/lxd/lxd/lxd/seccomp/seccomp.go:1070 +0x1f5

goroutine 193 [syscall]:
syscall.Syscall(0x0?, 0x0?, 0x0?, 0x1000000000000?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/syscall/syscall_linux.go:69 +0x25
golang.org/x/sys/unix.read(0x0?, {0xc00010c600?, 0xc000609448?, 0x44e7b1?})
	/home/runner/go/pkg/mod/golang.org/x/sys@v0.14.0/unix/zsyscall_linux.go:1376 +0x45
golang.org/x/sys/unix.Read(...)
	/home/runner/go/pkg/mod/golang.org/x/sys@v0.14.0/unix/syscall_unix.go:158
github.com/canonical/lxd/lxd/fsmonitor/drivers.(*fanotify).getEvents(0xc00049f680, {0x21e48b8, 0xc000385810}, 0x2efdfd0?)
	/home/runner/work/lxd/lxd/lxd/fsmonitor/drivers/driver_fanotify.go:86 +0x78
created by github.com/canonical/lxd/lxd/fsmonitor/drivers.(*fanotify).load in goroutine 1
	/home/runner/work/lxd/lxd/lxd/fsmonitor/drivers/driver_fanotify.go:71 +0x306

goroutine 191 [select]:
main.deviceEventListener(0xc000562050)
	/home/runner/work/lxd/lxd/lxd/devices.go:669 +0x20f
created by main.(*Daemon).init in goroutine 1
	/home/runner/work/lxd/lxd/lxd/daemon.go:1463 +0x4a39

goroutine 724 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8e5f8, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc0001b9700?, 0xc000b0e000?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0001b9700, {0xc000b0e000, 0x8000, 0x8000})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc0001b9700, {0xc000b0e000?, 0x7ff020baf428?, 0x7ff06b17a108?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc00006bd78, {0xc000b0e000?, 0x1a84820?, 0xc000a5e301?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
io.copyBuffer({0x21d26a0, 0xc000a5e380}, {0x21d1980, 0xc00006bd78}, {0x0, 0x0, 0x0})
	/opt/hostedtoolcache/go/1.21.4/x64/src/io/io.go:430 +0x1a6
io.Copy(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/io/io.go:389
github.com/canonical/lxd/lxd/cluster.dqliteProxy.func2()
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:1169 +0x7b
created by github.com/canonical/lxd/lxd/cluster.dqliteProxy in goroutine 673
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:1168 +0x61e

goroutine 3324 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8e8e0, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc002893380?, 0xc0020d6f00?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc002893380, {0xc0020d6f00, 0x500, 0x500})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc002893380, {0xc0020d6f00?, 0xc0020d6f05?, 0x20?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc000155e18, {0xc0020d6f00?, 0xc0007d8680?, 0xc0021ef338?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc002721ea8, {0xc0020d6f00?, 0xc002721ea8?, 0x0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:805 +0x3b
bytes.(*Buffer).ReadFrom(0xc0021ef428, {0x21d4080, 0xc002721ea8})
	/opt/hostedtoolcache/go/1.21.4/x64/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0021ef180, {0x21d29e0?, 0xc000155e18}, 0x500?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:827 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc0021ef180, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:625 +0x250
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc0021ef180, {0xc0027bc000, 0x1000, 0x4104a5?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:1369 +0x158
bufio.(*Reader).fill(0xc0027acde0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:113 +0x103
bufio.(*Reader).Peek(0xc0027acde0, 0x2)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:151 +0x53
github.com/gorilla/websocket.(*Conn).read(0xc002443e40, 0xc0027bc006?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:378 +0x26
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc002443e40)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:824 +0x6d
github.com/gorilla/websocket.(*Conn).NextReader(0xc002443e40)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1034 +0x13e
github.com/canonical/lxd/lxd/events.(*websockListenerConnection).Reader.func3()
	/home/runner/work/lxd/lxd/lxd/events/connections.go:99 +0x5b
created by github.com/canonical/lxd/lxd/events.(*websockListenerConnection).Reader in goroutine 3319
	/home/runner/work/lxd/lxd/lxd/events/connections.go:82 +0x1f9

goroutine 723 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8ebc8, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc0001b9500?, 0xc000ad6000?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0001b9500, {0xc000ad6000, 0xa000, 0xa000})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc0001b9500, {0xc000ad6000?, 0xc000ad6005?, 0x3101?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc00006bd58, {0xc000ad6000?, 0x0?, 0xc000a5e538?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc001f2d440, {0xc000ad6000?, 0xc001f2d440?, 0x0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:805 +0x3b
bytes.(*Buffer).ReadFrom(0xc000a5e628, {0x21d4080, 0xc001f2d440})
	/opt/hostedtoolcache/go/1.21.4/x64/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000a5e380, {0x21d29e0?, 0xc00006bd58}, 0xa000?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:827 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc000a5e380, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:625 +0x250
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc000a5e380, {0xc000b80000, 0x8000, 0xc000953c20?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:1369 +0x158
io.copyBuffer({0x21d19a0, 0xc00006bd78}, {0x21d26c0, 0xc000a5e380}, {0x0, 0x0, 0x0})
	/opt/hostedtoolcache/go/1.21.4/x64/src/io/io.go:430 +0x1a6
io.Copy(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/io/io.go:389
github.com/canonical/lxd/lxd/cluster.dqliteProxy.func1()
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:1164 +0x7b
created by github.com/canonical/lxd/lxd/cluster.dqliteProxy in goroutine 673
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:1163 +0x588

goroutine 685 [select]:
github.com/canonical/lxd/lxd/cluster.dqliteProxy({0x1e14ce4, 0x4}, 0xc0005a8420, {0x21efbb8, 0xc0000cd880}, {0x21efb60, 0xc0001542b0?})
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:1175 +0x6c8
created by github.com/canonical/lxd/lxd/cluster.(*Gateway).init.(*Gateway).raftDial.func3 in goroutine 17
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:427 +0x2c5

goroutine 3319 [select]:
github.com/canonical/lxd/lxd/events.(*websockListenerConnection).Reader(0xc0028c6b40, {0x21e48b8?, 0xc0028e60a0?}, 0x0)
	/home/runner/work/lxd/lxd/lxd/events/connections.go:126 +0x3a5
github.com/canonical/lxd/lxd/events.(*listenerCommon).start(0xc0005426e0)
	/home/runner/work/lxd/lxd/lxd/events/common.go:36 +0x1f5
created by github.com/canonical/lxd/lxd/events.(*Server).AddListener in goroutine 3315
	/home/runner/work/lxd/lxd/lxd/events/events.go:105 +0x510

goroutine 673 [select]:
github.com/canonical/lxd/lxd/cluster.dqliteProxy({0x1e18d26, 0x6}, 0xc0005a8420, {0x21efbb8, 0xc000a5e380}, {0x21efb60, 0xc00006bd78?})
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:1175 +0x6c8
created by github.com/canonical/lxd/lxd/cluster.runDqliteProxy in goroutine 720
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:1137 +0x125

goroutine 726 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8e6f0, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc000296f80?, 0xc0009aeb00?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000296f80, {0xc0009aeb00, 0x580, 0x580})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc000296f80, {0xc0009aeb00?, 0xc000151410?, 0xc0004b9a18?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc0005a64d8, {0xc0009aeb00?, 0x0?, 0x3fb6?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc0008de870, {0xc0009aeb00?, 0xc0008de870?, 0x0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:805 +0x3b
bytes.(*Buffer).ReadFrom(0xc0000cdb28, {0x21d4080, 0xc0008de870})
	/opt/hostedtoolcache/go/1.21.4/x64/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0000cd880, {0x21d29e0?, 0xc0005a64d8}, 0xe3?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:827 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc0000cd880, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:625 +0x250
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc0000cd880, {0xc000b5c000, 0x8000, 0x1029160?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:1369 +0x158
io.copyBuffer({0x21d19a0, 0xc0001542b0}, {0x21d26c0, 0xc0000cd880}, {0x0, 0x0, 0x0})
	/opt/hostedtoolcache/go/1.21.4/x64/src/io/io.go:430 +0x1a6
io.Copy(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/io/io.go:389
github.com/canonical/lxd/lxd/cluster.dqliteProxy.func1()
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:1164 +0x7b
created by github.com/canonical/lxd/lxd/cluster.dqliteProxy in goroutine 685
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:1163 +0x588

goroutine 1901 [select]:
github.com/canonical/lxd/client.(*ProtocolLXD).getEvents.func1()
	/home/runner/work/lxd/lxd/client/lxd_events.go:78 +0xb8
created by github.com/canonical/lxd/client.(*ProtocolLXD).getEvents in goroutine 1895
	/home/runner/work/lxd/lxd/client/lxd_events.go:76 +0x43b

goroutine 6689 [runnable]:
github.com/mattn/go-sqlite3._Cfunc_free(0x7ff018020690)
	_cgo_gotypes.go:396 +0x3f
github.com/mattn/go-sqlite3.(*SQLiteConn).prepare.(*SQLiteConn).prepare.func1.func3()
	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.18/sqlite3.go:1800 +0x35
github.com/mattn/go-sqlite3.(*SQLiteConn).prepare(0xc00053d020, {0x0?, 0x0?}, {0x1e19458?, 0xc0006b8f80?})
	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.18/sqlite3.go:1813 +0x1ba
github.com/mattn/go-sqlite3.(*SQLiteConn).exec(0x1a8ab60?, {0x21e47a0, 0x355d900}, {0x1e19458?, 0x1b34660?}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.18/sqlite3.go:853 +0x8d
github.com/mattn/go-sqlite3.(*SQLiteTx).Commit(0xc001fd8258)
	/home/runner/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.18/sqlite3.go:496 +0x45
database/sql.(*Tx).Commit.func1()
	/opt/hostedtoolcache/go/1.21.4/x64/src/database/sql/sql.go:2275 +0x29
database/sql.withLock({0x21dc918, 0xc0005321b0}, 0xc0006b9170)
	/opt/hostedtoolcache/go/1.21.4/x64/src/database/sql/sql.go:3502 +0x82
database/sql.(*Tx).Commit(0xc002b15900)
	/opt/hostedtoolcache/go/1.21.4/x64/src/database/sql/sql.go:2274 +0xfd
github.com/canonical/lxd/lxd/db/query.Transaction({0x21e4768?, 0x355d900?}, 0x7ff02034ca20?, 0xc0006b9270)
	/home/runner/work/lxd/lxd/lxd/db/query/transaction.go:34 +0x1b1
github.com/canonical/lxd/lxd/db.(*Node).Transaction(0xc000511278, {0x21e4768, 0x355d900}, 0xc0006b92c0)
	/home/runner/work/lxd/lxd/lxd/db/db.go:102 +0x74
github.com/canonical/lxd/lxd/cluster.Enabled(0x21d1c60?)
	/home/runner/work/lxd/lxd/lxd/cluster/membership.go:1087 +0x47
main.handoverMemberRole(0xc002562b60, 0x1e5d83c?)
	/home/runner/work/lxd/lxd/lxd/api_cluster.go:2568 +0x39
main.(*Daemon).Stop(0xc00049c240, {0x21e48b8, 0xc002176d70}, {0x21db768?, 0x21cd148?})
	/home/runner/work/lxd/lxd/lxd/daemon.go:1666 +0x1e6
main.internalShutdown.func1({0x21e0ae8, 0xc0025628c0})
	/home/runner/work/lxd/lxd/lxd/api_internal.go:256 +0x99
github.com/canonical/lxd/lxd/response.(*manualResponse).Render(0x1f7b250?, {0x21e0ae8?, 0xc0025628c0?})
	/home/runner/work/lxd/lxd/lxd/response/response.go:546 +0x26
main.(*Daemon).createCmd.func1({0x21e0ae8, 0xc0025628c0}, 0xc0001d3000)
	/home/runner/work/lxd/lxd/lxd/daemon.go:628 +0x15d1
net/http.HandlerFunc.ServeHTTP(0xc0001d2f00?, {0x21e0ae8?, 0xc0025628c0?}, 0x0?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000536b40, {0x21e0ae8, 0xc0025628c0}, 0xc0001d2d00)
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1c5
main.(*lxdHttpServer).ServeHTTP(0xc000051cb0, {0x21e0ae8, 0xc0025628c0}, 0xc0001d2d00)
	/home/runner/work/lxd/lxd/lxd/api.go:379 +0xd0
net/http.serverHandler.ServeHTTP({0xc002da74d0?}, {0x21e0ae8?, 0xc0025628c0?}, 0x6?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc000da5cb0, {0x21e4880, 0xc002e21110})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 21
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:3086 +0x5cb

goroutine 376 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8ead0, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc000788800?, 0xe?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000788800)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:611 +0x2ac
net.(*netFD).accept(0xc000788800)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_unix.go:172 +0x29
net.(*TCPListener).accept(0xc0007ac440)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/tcpsock_posix.go:152 +0x1e
net.(*TCPListener).Accept(0xc0007ac440)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/tcpsock.go:315 +0x30
github.com/canonical/lxd/lxd/endpoints/listeners.(*FancyTLSListener).Accept(0xc00055ce60)
	/home/runner/work/lxd/lxd/lxd/endpoints/listeners/fancytls.go:37 +0x4d
net/http.(*Server).Serve(0xc00024e000, {0x21e1088, 0xc00055ce60})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:3056 +0x364
github.com/canonical/lxd/lxd/endpoints.(*Endpoints).serve.func1()
	/home/runner/work/lxd/lxd/lxd/endpoints/endpoints.go:433 +0x1f
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0003858b0, 0x0?)
	/home/runner/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go in goroutine 366
	/home/runner/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xe5

goroutine 6810 [runnable]:
database/sql.(*Rows).initContextClose.func1()
	/opt/hostedtoolcache/go/1.21.4/x64/src/database/sql/sql.go:2949
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/asm_amd64.s:1650 +0x1
created by database/sql.(*Rows).initContextClose in goroutine 6689
	/opt/hostedtoolcache/go/1.21.4/x64/src/database/sql/sql.go:2949 +0x185

goroutine 6762 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8e120, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc002945200?, 0xc000539000?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc002945200, {0xc000539000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc002945200, {0xc000539000?, 0xc0006d6f10?, 0x10290f3?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc00052c260, {0xc000539000?, 0x0?, 0x1029160?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
bufio.(*Reader).Read(0xc0007f95c0, {0xc002da74e1, 0x1, 0x102c202?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:244 +0x197
github.com/canonical/lxd/lxd/endpoints/listeners.BufferedUnixConn.Read(...)
	/home/runner/work/lxd/lxd/lxd/endpoints/listeners/starttls.go:94
net/http.(*connReader).backgroundRead(0xc002da74d0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:683 +0x37
created by net/http.(*connReader).startBackgroundRead in goroutine 6689
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:679 +0xba

goroutine 720 [chan receive]:
github.com/canonical/lxd/lxd/cluster.runDqliteProxy(0xc0005a8420, {0xc00062dd56, 0x6}, 0xc0004ce140?)
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:1131 +0x45
created by github.com/canonical/lxd/lxd/cluster.(*Gateway).init in goroutine 288
	/home/runner/work/lxd/lxd/lxd/cluster/gateway.go:800 +0x5af

goroutine 1698 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8e7e8, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc00216d680?, 0xc0006fd000?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00216d680, {0xc0006fd000, 0x3800, 0x3800})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc00216d680, {0xc0006fd000?, 0x0?, 0xc002c3a9b8?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc000154e28, {0xc0006fd000?, 0xc0006ad728?, 0x46024b?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc002144738, {0xc0006fd000?, 0xc002144738?, 0x0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:805 +0x3b
bytes.(*Buffer).ReadFrom(0xc0021157a8, {0x21d4080, 0xc002144738})
	/opt/hostedtoolcache/go/1.21.4/x64/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc002115500, {0x21d29e0?, 0xc000154e28}, 0x35b4?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:827 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc002115500, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:625 +0x250
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc002115500, {0xc0021be000, 0x1000, 0xc0006adc88?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:1369 +0x158
bufio.(*Reader).fill(0xc0021b93e0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:113 +0x103
bufio.(*Reader).Peek(0xc0021b93e0, 0x2)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:151 +0x53
github.com/gorilla/websocket.(*Conn).read(0xc0020954a0, 0x0?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:378 +0x26
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0020954a0)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:824 +0x6d
github.com/gorilla/websocket.(*Conn).NextReader(0xc0020954a0)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1034 +0x13e
github.com/gorilla/websocket.(*Conn).ReadMessage(0x1b39d20?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1120 +0x13
github.com/canonical/lxd/client.(*ProtocolLXD).getEvents.func2()
	/home/runner/work/lxd/lxd/client/lxd_events.go:108 +0x5c
created by github.com/canonical/lxd/client.(*ProtocolLXD).getEvents in goroutine 1705
	/home/runner/work/lxd/lxd/client/lxd_events.go:106 +0x4b9

goroutine 1610 [select]:
github.com/canonical/lxd/lxd/events.(*listenerCommon).Wait(0xc0007fdae0, {0x21e4880?, 0xc0020a1860?})
	/home/runner/work/lxd/lxd/lxd/events/common.go:52 +0x85
main.eventsSocket(0xc0020d10a0, 0xc0020dc100, {0x21e0ae8, 0xc0020d0ee0})
	/home/runner/work/lxd/lxd/lxd/events.go:165 +0xd2f
main.(*eventsServe).Render(0x1f7af78?, {0x21e0ae8?, 0xc0020d0ee0?})
	/home/runner/work/lxd/lxd/lxd/events.go:37 +0x30
main.(*Daemon).createCmd.func1({0x21e0ae8, 0xc0020d0ee0}, 0xc0007abf00)
	/home/runner/work/lxd/lxd/lxd/daemon.go:628 +0x15d1
net/http.HandlerFunc.ServeHTTP(0xc0007abe00?, {0x21e0ae8?, 0xc0020d0ee0?}, 0x1e13993?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000536b40, {0x21e0ae8, 0xc0020d0ee0}, 0xc0007abd00)
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1c5
main.(*lxdHttpServer).ServeHTTP(0xc000051cb0, {0x21e0ae8, 0xc0020d0ee0}, 0xc0007abd00)
	/home/runner/work/lxd/lxd/lxd/api.go:379 +0xd0
net/http.serverHandler.ServeHTTP({0xc0020a1140?}, {0x21e0ae8?, 0xc0020d0ee0?}, 0x6?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc001ff7320, {0x21e4880, 0xc001ffaea0})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 376
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:3086 +0x5cb

goroutine 1697 [select]:
github.com/canonical/lxd/client.(*ProtocolLXD).getEvents.func1()
	/home/runner/work/lxd/lxd/client/lxd_events.go:78 +0xb8
created by github.com/canonical/lxd/client.(*ProtocolLXD).getEvents in goroutine 1705
	/home/runner/work/lxd/lxd/client/lxd_events.go:76 +0x43b

goroutine 976 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8e500, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc0003fda80?, 0xc00075b400?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0003fda80, {0xc00075b400, 0x500, 0x500})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc0003fda80, {0xc00075b400?, 0xc00075b405?, 0x20?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc00052c630, {0xc00075b400?, 0x9?, 0xc000728fb8?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc0008dfcf8, {0xc00075b400?, 0xc0008dfcf8?, 0x0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:805 +0x3b
bytes.(*Buffer).ReadFrom(0xc0007290a8, {0x21d4080, 0xc0008dfcf8})
	/opt/hostedtoolcache/go/1.21.4/x64/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000728e00, {0x21d29e0?, 0xc00052c630}, 0x500?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:827 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc000728e00, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:625 +0x250
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc000728e00, {0xc001f9e000, 0x1000, 0x1d08100?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:1369 +0x158
bufio.(*Reader).fill(0xc001f9c540)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:113 +0x103
bufio.(*Reader).Peek(0xc001f9c540, 0x2)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:151 +0x53
github.com/gorilla/websocket.(*Conn).read(0xc001fa6160, 0xc001f9e006?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:378 +0x26
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc001fa6160)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:824 +0x6d
github.com/gorilla/websocket.(*Conn).NextReader(0xc001fa6160)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1034 +0x13e
github.com/gorilla/websocket.(*Conn).ReadJSON(0x0?, {0x1b18340, 0xc000bcc6c0})
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/json.go:50 +0x25
github.com/canonical/lxd/lxd/events.(*websockListenerConnection).Reader.func3()
	/home/runner/work/lxd/lxd/lxd/events/connections.go:88 +0xc9
created by github.com/canonical/lxd/lxd/events.(*websockListenerConnection).Reader in goroutine 972
	/home/runner/work/lxd/lxd/lxd/events/connections.go:82 +0x1f9

goroutine 906 [select]:
github.com/canonical/lxd/client.(*ProtocolLXD).getEvents.func1()
	/home/runner/work/lxd/lxd/client/lxd_events.go:78 +0xb8
created by github.com/canonical/lxd/client.(*ProtocolLXD).getEvents in goroutine 900
	/home/runner/work/lxd/lxd/client/lxd_events.go:76 +0x43b

goroutine 915 [select]:
github.com/canonical/lxd/client.(*ProtocolLXD).getEvents.func1()
	/home/runner/work/lxd/lxd/client/lxd_events.go:78 +0xb8
created by github.com/canonical/lxd/client.(*ProtocolLXD).getEvents in goroutine 899
	/home/runner/work/lxd/lxd/client/lxd_events.go:76 +0x43b

goroutine 916 [IO wait]:
internal/poll.runtime_pollWait(0x7ff0200ab3e8, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc000297480?, 0xc002500000?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000297480, {0xc002500000, 0x4000, 0x4000})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc000297480, {0xc002500000?, 0x0?, 0xc002c3bf18?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc00006bdf0, {0xc002500000?, 0xc0006a8728?, 0x46024b?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc002144f00, {0xc002500000?, 0xc002144f00?, 0x0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:805 +0x3b
bytes.(*Buffer).ReadFrom(0xc000a5ed28, {0x21d4080, 0xc002144f00})
	/opt/hostedtoolcache/go/1.21.4/x64/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000a5ea80, {0x21d29e0?, 0xc00006bdf0}, 0x3ed4?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:827 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc000a5ea80, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:625 +0x250
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc000a5ea80, {0xc001f12000, 0x1000, 0xc0006a8c88?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:1369 +0x158
bufio.(*Reader).fill(0xc001f10840)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:113 +0x103
bufio.(*Reader).Peek(0xc001f10840, 0x2)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:151 +0x53
github.com/gorilla/websocket.(*Conn).read(0xc0008e6580, 0x0?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:378 +0x26
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0008e6580)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:824 +0x6d
github.com/gorilla/websocket.(*Conn).NextReader(0xc0008e6580)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1034 +0x13e
github.com/gorilla/websocket.(*Conn).ReadMessage(0x1b39d20?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1120 +0x13
github.com/canonical/lxd/client.(*ProtocolLXD).getEvents.func2()
	/home/runner/work/lxd/lxd/client/lxd_events.go:108 +0x5c
created by github.com/canonical/lxd/client.(*ProtocolLXD).getEvents in goroutine 899
	/home/runner/work/lxd/lxd/client/lxd_events.go:106 +0x4b9

goroutine 930 [select]:
github.com/canonical/lxd/lxd/events.(*websockListenerConnection).Reader(0xc000aff1a0, {0x21e48b8?, 0xc000959ae0?}, 0xc001ebd780)
	/home/runner/work/lxd/lxd/lxd/events/connections.go:126 +0x3a5
github.com/canonical/lxd/lxd/events.(*listenerCommon).start(0xc000382e60)
	/home/runner/work/lxd/lxd/lxd/events/common.go:36 +0x1f5
created by github.com/canonical/lxd/lxd/events.(*Server).AddListener in goroutine 952
	/home/runner/work/lxd/lxd/lxd/events/events.go:105 +0x510

goroutine 1638 [select]:
github.com/canonical/lxd/lxd/events.(*websockListenerConnection).Reader(0xc0022042a0, {0x21e48b8?, 0xc001f7e6e0?}, 0xc001f73ab0)
	/home/runner/work/lxd/lxd/lxd/events/connections.go:126 +0x3a5
github.com/canonical/lxd/lxd/events.(*listenerCommon).start(0xc0007fdae0)
	/home/runner/work/lxd/lxd/lxd/events/common.go:36 +0x1f5
created by github.com/canonical/lxd/lxd/events.(*Server).AddListener in goroutine 1610
	/home/runner/work/lxd/lxd/lxd/events/events.go:105 +0x510

goroutine 1642 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8e028, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc001f99a00?, 0xc0020d6000?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc001f99a00, {0xc0020d6000, 0x500, 0x500})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc001f99a00, {0xc0020d6000?, 0xc0020d6005?, 0x20?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc001fd81f0, {0xc0020d6000?, 0xc001f3b1a0?, 0xc000a5f338?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc002204360, {0xc0020d6000?, 0xc002204360?, 0x0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:805 +0x3b
bytes.(*Buffer).ReadFrom(0xc000a5f428, {0x21d4080, 0xc002204360})
	/opt/hostedtoolcache/go/1.21.4/x64/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000a5f180, {0x21d29e0?, 0xc001fd81f0}, 0x500?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:827 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc000a5f180, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:625 +0x250
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc000a5f180, {0xc00207a000, 0x1000, 0x1d08100?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:1369 +0x158
bufio.(*Reader).fill(0xc002073680)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:113 +0x103
bufio.(*Reader).Peek(0xc002073680, 0x2)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:151 +0x53
github.com/gorilla/websocket.(*Conn).read(0xc0020949a0, 0xc00207a006?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:378 +0x26
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0020949a0)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:824 +0x6d
github.com/gorilla/websocket.(*Conn).NextReader(0xc0020949a0)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1034 +0x13e
github.com/gorilla/websocket.(*Conn).ReadJSON(0x0?, {0x1b18340, 0xc0022082a0})
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/json.go:50 +0x25
github.com/canonical/lxd/lxd/events.(*websockListenerConnection).Reader.func3()
	/home/runner/work/lxd/lxd/lxd/events/connections.go:88 +0xc9
created by github.com/canonical/lxd/lxd/events.(*websockListenerConnection).Reader in goroutine 1638
	/home/runner/work/lxd/lxd/lxd/events/connections.go:82 +0x1f9

goroutine 981 [IO wait]:
internal/poll.runtime_pollWait(0x7ff021d8e408, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc0003fda00?, 0xc00075af00?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0003fda00, {0xc00075af00, 0x500, 0x500})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc0003fda00, {0xc00075af00?, 0xc00075af05?, 0x20?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc00052c628, {0xc00075af00?, 0x9?, 0xc000728c38?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc0008dfc38, {0xc00075af00?, 0xc0008dfc38?, 0x0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:805 +0x3b
bytes.(*Buffer).ReadFrom(0xc000728d28, {0x21d4080, 0xc0008dfc38})
	/opt/hostedtoolcache/go/1.21.4/x64/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000728a80, {0x21d29e0?, 0xc00052c628}, 0x500?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:827 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc000728a80, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:625 +0x250
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc000728a80, {0xc000bfc000, 0x1000, 0x1d08100?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:1369 +0x158
bufio.(*Reader).fill(0xc0007f8ae0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:113 +0x103
bufio.(*Reader).Peek(0xc0007f8ae0, 0x2)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:151 +0x53
github.com/gorilla/websocket.(*Conn).read(0xc000a1bb80, 0xc000bfc006?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:378 +0x26
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc000a1bb80)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:824 +0x6d
github.com/gorilla/websocket.(*Conn).NextReader(0xc000a1bb80)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1034 +0x13e
github.com/gorilla/websocket.(*Conn).ReadJSON(0xc0006c60c0?, {0x1b18340, 0xc001f9c8a0})
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/json.go:50 +0x25
github.com/canonical/lxd/lxd/events.(*websockListenerConnection).Reader.func3()
	/home/runner/work/lxd/lxd/lxd/events/connections.go:88 +0xc9
created by github.com/canonical/lxd/lxd/events.(*websockListenerConnection).Reader in goroutine 930
	/home/runner/work/lxd/lxd/lxd/events/connections.go:82 +0x1f9

goroutine 972 [select]:
github.com/canonical/lxd/lxd/events.(*websockListenerConnection).Reader(0xc0008dfc68, {0x21e48b8?, 0xc000b0aff0?}, 0xc001f9a680)
	/home/runner/work/lxd/lxd/lxd/events/connections.go:126 +0x3a5
github.com/canonical/lxd/lxd/events.(*listenerCommon).start(0xc0003ad5e0)
	/home/runner/work/lxd/lxd/lxd/events/common.go:36 +0x1f5
created by github.com/canonical/lxd/lxd/events.(*Server).AddListener in goroutine 953
	/home/runner/work/lxd/lxd/lxd/events/events.go:105 +0x510

goroutine 907 [IO wait]:
internal/poll.runtime_pollWait(0x7ff0200ab4e0, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc0003fd580?, 0xc002314000?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0003fd580, {0xc002314000, 0x3800, 0x3800})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc0003fd580, {0xc002314000?, 0x0?, 0xc002c3ac88?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc00052c5a0, {0xc002314000?, 0xc000b65728?, 0x46024b?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc002144750, {0xc002314000?, 0xc002144750?, 0x0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:805 +0x3b
bytes.(*Buffer).ReadFrom(0xc0007289a8, {0x21d4080, 0xc002144750})
	/opt/hostedtoolcache/go/1.21.4/x64/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000728700, {0x21d29e0?, 0xc00052c5a0}, 0x3285?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:827 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc000728700, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:625 +0x250
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc000728700, {0xc000b59000, 0x1000, 0xc000b65c88?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:1369 +0x158
bufio.(*Reader).fill(0xc000b73f80)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:113 +0x103
bufio.(*Reader).Peek(0xc000b73f80, 0x2)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:151 +0x53
github.com/gorilla/websocket.(*Conn).read(0xc000a1b4a0, 0x0?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:378 +0x26
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc000a1b4a0)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:824 +0x6d
github.com/gorilla/websocket.(*Conn).NextReader(0xc000a1b4a0)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1034 +0x13e
github.com/gorilla/websocket.(*Conn).ReadMessage(0x1b39d20?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1120 +0x13
github.com/canonical/lxd/client.(*ProtocolLXD).getEvents.func2()
	/home/runner/work/lxd/lxd/client/lxd_events.go:108 +0x5c
created by github.com/canonical/lxd/client.(*ProtocolLXD).getEvents in goroutine 900
	/home/runner/work/lxd/lxd/client/lxd_events.go:106 +0x4b9

goroutine 3315 [select]:
github.com/canonical/lxd/lxd/events.(*listenerCommon).Wait(0xc0005426e0, {0x21e4880?, 0xc0027d14a0?})
	/home/runner/work/lxd/lxd/lxd/events/common.go:52 +0x85
main.eventsSocket(0xc00249fce0, 0xc00279b600, {0x21e0ae8, 0xc00249fb20})
	/home/runner/work/lxd/lxd/lxd/events.go:165 +0xd2f
main.(*eventsServe).Render(0x1f7af78?, {0x21e0ae8?, 0xc00249fb20?})
	/home/runner/work/lxd/lxd/lxd/events.go:37 +0x30
main.(*Daemon).createCmd.func1({0x21e0ae8, 0xc00249fb20}, 0xc00279b400)
	/home/runner/work/lxd/lxd/lxd/daemon.go:628 +0x15d1
net/http.HandlerFunc.ServeHTTP(0xc00279b300?, {0x21e0ae8?, 0xc00249fb20?}, 0x1e13993?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000536b40, {0x21e0ae8, 0xc00249fb20}, 0xc00279b200)
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1c5
main.(*lxdHttpServer).ServeHTTP(0xc000051cb0, {0x21e0ae8, 0xc00249fb20}, 0xc00279b200)
	/home/runner/work/lxd/lxd/lxd/api.go:379 +0xd0
net/http.serverHandler.ServeHTTP({0xc0027d0d80?}, {0x21e0ae8?, 0xc00249fb20?}, 0x6?)
Error: Put "http://unix.socket/internal/shutdown?force=false": EOF
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0028d1d40, {0x21e4880, 0xc0028de930})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 376
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:3086 +0x5cb

goroutine 952 [select]:
github.com/canonical/lxd/lxd/events.(*listenerCommon).Wait(0xc000382e60, {0x21e4880?, 0xc001f8cd20?})
	/home/runner/work/lxd/lxd/lxd/events/common.go:52 +0x85
main.eventsSocket(0xc0006c56c0, 0xc000a1f000, {0x21e0ae8, 0xc0006c5500})
	/home/runner/work/lxd/lxd/lxd/events.go:165 +0xd2f
main.(*eventsServe).Render(0x1f7af78?, {0x21e0ae8?, 0xc0006c5500?})
	/home/runner/work/lxd/lxd/lxd/events.go:37 +0x30
main.(*Daemon).createCmd.func1({0x21e0ae8, 0xc0006c5500}, 0xc000a1ee00)
	/home/runner/work/lxd/lxd/lxd/daemon.go:628 +0x15d1
net/http.HandlerFunc.ServeHTTP(0xc000a1ed00?, {0x21e0ae8?, 0xc0006c5500?}, 0x1e13993?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000536b40, {0x21e0ae8, 0xc0006c5500}, 0xc000a1ec00)
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1c5
main.(*lxdHttpServer).ServeHTTP(0xc000051cb0, {0x21e0ae8, 0xc0006c5500}, 0xc000a1ec00)
	/home/runner/work/lxd/lxd/lxd/api.go:379 +0xd0
net/http.serverHandler.ServeHTTP({0xc001f8c630?}, {0x21e0ae8?, 0xc0006c5500?}, 0x6?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0008dd170, {0x21e4880, 0xc0008dbec0})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 376
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:3086 +0x5cb

goroutine 953 [select]:
github.com/canonical/lxd/lxd/events.(*listenerCommon).Wait(0xc0003ad5e0, {0x21e4880?, 0xc001f8dcb0?})
	/home/runner/work/lxd/lxd/lxd/events/common.go:52 +0x85
main.eventsSocket(0xc0006c5a40, 0xc000a1f600, {0x21e0ae8, 0xc0006c5880})
	/home/runner/work/lxd/lxd/lxd/events.go:165 +0xd2f
main.(*eventsServe).Render(0x1f7af78?, {0x21e0ae8?, 0xc0006c5880?})
	/home/runner/work/lxd/lxd/lxd/events.go:37 +0x30
main.(*Daemon).createCmd.func1({0x21e0ae8, 0xc0006c5880}, 0xc000a1f400)
	/home/runner/work/lxd/lxd/lxd/daemon.go:628 +0x15d1
net/http.HandlerFunc.ServeHTTP(0xc000a1f300?, {0x21e0ae8?, 0xc0006c5880?}, 0x1e13993?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000536b40, {0x21e0ae8, 0xc0006c5880}, 0xc000a1f200)
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1c5
main.(*lxdHttpServer).ServeHTTP(0xc000051cb0, {0x21e0ae8, 0xc0006c5880}, 0xc000a1f200)
	/home/runner/work/lxd/lxd/lxd/api.go:379 +0xd0
net/http.serverHandler.ServeHTTP({0xc001f8d5c0?}, {0x21e0ae8?, 0xc0006c5880?}, 0x6?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0008dd200, {0x21e4880, 0xc0008dbf50})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 376
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/http/server.go:3086 +0x5cb

goroutine 6809 [runnable]:
database/sql.(*DB).beginDC.func2()
	/opt/hostedtoolcache/go/1.21.4/x64/src/database/sql/sql.go:1887
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/asm_amd64.s:1650 +0x1
created by database/sql.(*DB).beginDC in goroutine 6689
	/opt/hostedtoolcache/go/1.21.4/x64/src/database/sql/sql.go:1887 +0x20d

goroutine 1902 [IO wait]:
internal/poll.runtime_pollWait(0x7ff0200ab1f8, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc0021de500?, 0xc002486000?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0021de500, {0xc002486000, 0x4000, 0x4000})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc0021de500, {0xc002486000?, 0x0?, 0xc0001f93d8?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc000154fc8, {0xc002486000?, 0xc001f3f728?, 0x46024b?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc001f2d2f0, {0xc002486000?, 0xc001f2d2f0?, 0x0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:805 +0x3b
bytes.(*Buffer).ReadFrom(0xc0021ee2a8, {0x21d4080, 0xc001f2d2f0})
	/opt/hostedtoolcache/go/1.21.4/x64/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0021ee000, {0x21d29e0?, 0xc000154fc8}, 0x3ee0?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:827 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc0021ee000, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:625 +0x250
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc0021ee000, {0xc0021f8000, 0x1000, 0xc001f3fc88?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:1369 +0x158
bufio.(*Reader).fill(0xc0021f3c80)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:113 +0x103
bufio.(*Reader).Peek(0xc0021f3c80, 0x2)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:151 +0x53
github.com/gorilla/websocket.(*Conn).read(0xc0021ec160, 0x0?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:378 +0x26
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0021ec160)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:824 +0x6d
github.com/gorilla/websocket.(*Conn).NextReader(0xc0021ec160)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1034 +0x13e
github.com/gorilla/websocket.(*Conn).ReadMessage(0x1b39d20?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1120 +0x13
github.com/canonical/lxd/client.(*ProtocolLXD).getEvents.func2()
	/home/runner/work/lxd/lxd/client/lxd_events.go:108 +0x5c
created by github.com/canonical/lxd/client.(*ProtocolLXD).getEvents in goroutine 1895
	/home/runner/work/lxd/lxd/client/lxd_events.go:106 +0x4b9

goroutine 1653 [IO wait]:
internal/poll.runtime_pollWait(0x7ff0200ab2f0, 0x72)
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc001f39800?, 0xc002031800?, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc001f39800, {0xc002031800, 0xc00, 0xc00})
	/opt/hostedtoolcache/go/1.21.4/x64/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc001f39800, {0xc002031800?, 0x0?, 0xc0001f9b28?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc000154de0, {0xc002031800?, 0xc001ed5728?, 0x46024b?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc001f2d470, {0xc002031800?, 0xc001f2d470?, 0x0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:805 +0x3b
bytes.(*Buffer).ReadFrom(0xc0021150a8, {0x21d4080, 0xc001f2d470})
	/opt/hostedtoolcache/go/1.21.4/x64/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc002114e00, {0x21d29e0?, 0xc000154de0}, 0xa1c?)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:827 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc002114e00, 0x0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:625 +0x250
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc002114e00, {0xc0022a6000, 0x1000, 0xc001ed5c88?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/crypto/tls/conn.go:1369 +0x158
bufio.(*Reader).fill(0xc002295da0)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:113 +0x103
bufio.(*Reader).Peek(0xc002295da0, 0x2)
	/opt/hostedtoolcache/go/1.21.4/x64/src/bufio/bufio.go:151 +0x53
github.com/gorilla/websocket.(*Conn).read(0xc001fa6b00, 0x0?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:378 +0x26
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc001fa6b00)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:824 +0x6d
github.com/gorilla/websocket.(*Conn).NextReader(0xc001fa6b00)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1034 +0x13e
github.com/gorilla/websocket.(*Conn).ReadMessage(0x1b39d20?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1120 +0x13
github.com/canonical/lxd/client.(*ProtocolLXD).getEvents.func2()
	/home/runner/work/lxd/lxd/client/lxd_events.go:108 +0x5c
created by github.com/canonical/lxd/client.(*ProtocolLXD).getEvents in goroutine 1546
	/home/runner/work/lxd/lxd/client/lxd_events.go:106 +0x4b9

goroutine 1652 [select]:
github.com/canonical/lxd/client.(*ProtocolLXD).getEvents.func1()
	/home/runner/work/lxd/lxd/client/lxd_events.go:78 +0xb8
created by github.com/canonical/lxd/client.(*ProtocolLXD).getEvents in goroutine 1546
	/home/runner/work/lxd/lxd/client/lxd_events.go:76 +0x43b
time="2023-11-21T13:41:18Z" level=info msg="Dqlite proxy stopped" local="10.1.1.101:8443" name=dqlite remote="10.1.1.1:55604"
time="2023-11-21T13:41:18Z" level=info msg="Dqlite proxy stopped" local="10.1.1.101:37348" name=raft remote="10.1.1.103:8443"
time="2023-11-21T13:41:18Z" level=info msg="Dqlite proxy stopped" local="10.1.1.101:8443" name=dqlite remote="10.1.1.1:55614"
```

Noticed from https://github.com/canonical/lxd/actions/runs/6944517919/job/18891832516?pr=12515

### PR DESCRIPTION
**Pull request by tomponline**
Hopefully fixes #12540 by simplifying the calls to unlocking the mutex.

Even if it doesn't fix it, it should make it easier to reason about, rather than using defer unnecessarily.

Closes #12540

### CODE REVIEW

File: lxd/task/group.go [hunk 1]
```diff
@@ -60,16 +58,17 @@ func (g *Group) Start(ctx context.Context) {
 		go func(i int) {
 			task.loop(ctx)
 
-			// Ensure running map is updated before wait group Done() is called.
-			g.mu.Lock()
-			defer g.mu.Unlock()
-
 			if g.running != nil {
```
Comment (MusicDin) [inline lxd/task/group.go:61]: AFAIK checking if map is not nil should be concurrent-safe, because this is essentially just checking whether the pointer to a map is not nil. 

However, I just wanted to point that out in case I have missed some edge case that may occur (maybe initializing a map while some routine is reading from the map)?

Otherwise, LGTM.

**Review by MusicDin — APPROVED** [review]

File: lxd/task/group.go (hunk 1 above)
Comment (tomponline) [reply lxd/task/group.go]: To be safe I've refactored this to add a NewGroup function that always initialises the running map so we don't have to worry about concurrently checking if its initialised or not.

**Review by MusicDin — APPROVED** [review]
