### PR TITLE
Encrypt OIDC cookies

### LINKED ISSUE #12531: OIDC implementation discussion
# Issue description

I looked into the oidc implementation and I have a couple of comments/questions. I didn't run the UI and I am not 100% clear on your use-cases, so I may be missing something:
- The oidc handler uses the zitadel library with encrypted cookies, but the cookies don't have `Secure` set (https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L269). AFAICT lxd will always use https, so I don't see a reason that `Secure` is not set.
- LXD requires that the tokens it accepts have a configurable audience (https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L238). This makes sense in cases where the token is issued for another client and it is used to authenticate with the LXD API (CLI authentication), but it does not make sense for the case of UI authentication because in that case the tokens should always have the LXD client_id as an audience (see https://openid.net/specs/openid-connect-core-1_0.html#IDToken, `aud` claim) as they were issued for that client.
- LXD requests for the `aud` claim in the authorization request (https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L148). Even though it is common practice to request for an audience this way, it is not described in the auth2/oidc standard so it will not work for _any_ provider (but it will probably work for the major ones).
- The `email` scope is not requested (https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L276), even though the `email` claim is expected by the backend (https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L133)
- After the oidc flow has finished, the `access_token` and the `refresh_token` are stored unencrypted in session cookies (https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L187). These cookies have `HttpOnly` set to `False`, I am not sure why that is needed. IMHO This is not secure as an attacker can gain those tokens through MITM attacks, by sending the refresh token through the cookies an attacker can gain long lasting access to user resources. Also perhaps I am missing something, but storing refresh tokens in session cookies beats the purpose (refresh tokens are long lived, session cookies are short lived).

Thoughts/Suggestions:
- The `aud` checking logic in https://github.com/canonical/lxd/blob/main/lxd/auth/oidc/oidc.go#L238 should be: `if !(o.audience in audience or o.client_id in audience) return error` (or you maybe can require that the audience must include the `client_id`, if you expect that you will always have one).
- The audience parameter in the authorization request is not needed, unless you plan to use the access_tokens to access other resources.
- The `email` scope should be requested.
- If you wish to store tokens in the cookies, they should be encrypted. (I am not a security person, but intuitively this makes sense to me)
- Semantically speaking, I am not sure if you should use the access token or ID token for managing the browser session. Access tokens are used for authorization, ID tokens are used for identification. In the case of CLI, access tokens make sense as you are checking if the client is authorized to access the server (through the audience). In the case of UI, you are only using the token to get the user's claims (identify the user). Authorization is always offloaded to another system (openfga or internal server logic). Also access tokens are not always JWTs.

cc @massigori @markylaing

### PR DESCRIPTION
**Pull request by markylaing**
This PR encrypts the OIDC cookies that are set in the response after logging in to LXD. It finishes the implementation of changes to handling of OIDC authentication as discussed in #12531.

To ensure that the encryption key is the same on all cluster members, we are deriving the key from the cluster private key using [HKDF](https://pkg.go.dev/golang.org/x/crypto/hkdf). 

Closes #12531

### CODE REVIEW

File: lxd/auth/oidc/oidc.go [hunk 1]
```diff
@@ -302,13 +305,18 @@ func getAccessTokenVerifier(issuer string) (op.AccessTokenVerifier, error) {
...
-		return nil, fmt.Errorf("Failed to create UUID: %w", err)
+	cookieHashKey := securecookie.GenerateRandomKey(32)
+	cookieBlockKey := securecookie.GenerateRandomKey(32)
+	secureCookie := securecookie.New(cookieHashKey, cookieBlockKey)
+
+	verifier := &Verifier{
+		issuer:         issuer,
+		clientID:       clientid,
+		audience:       audience,
+		cookieHashKey:  securecookie.GenerateRandomKey(32),
```
[the remark this answers is not in the document]
Comment (markylaing) [reply lxd/auth/oidc/oidc.go:379]: No I meant to use the same one. It doesn't cause an error because the cookie hash and block keys are used as part of the login flow (/oidc/login, /oidc/callback), whereas the secure cookie field is used for encrypting the user id and refresh tokens when authenticating afterwards.

I'll change it now to use the same one in any case.

File: lxd/auth/oidc/oidc.go [hunk 2]
```diff
@@ -152,6 +153,50 @@ func (o *Verifier) Auth(ctx context.Context, w http.ResponseWriter, r *http.Requ
 	return claims.Subject, nil
 }
 
+// authenticateIDToken verifies the identity token and returns the ID token subject. If no identity token is given (or
+// verification fails) it will attempt to refresh the ID token.
+func (o *Verifier) authenticateIDToken(ctx context.Context, w http.ResponseWriter, idToken string, refreshToken string) (string, error) {
```
[the remark this answers is not in the document]
Comment (markylaing) [reply lxd/auth/oidc/oidc.go:111]: As far as am aware there aren't any cases like this. Is that correct @nsklikas?

[the remark this answers is not in the document]
Comment (nsklikas) [reply lxd/auth/oidc/oidc.go:111]: I don't think that there are such cases. 

Only case that I can think of is if the ID Token provided is not there or if it is malformed (not properly signed, issued for another client, etc), then you shouldn't try to refresh the token as the refresh token would also be invalid and you can avoid doing that extra http call (perhaps this could be a possible attack?). Having said that I think that it is fine to try to refresh the token every time the id token verification fails.

File: lxd/auth/oidc/oidc.go [hunk 3]
```diff
@@ -302,13 +305,18 @@ func getAccessTokenVerifier(issuer string) (op.AccessTokenVerifier, error) {
 
 // NewVerifier returns a Verifier.
 func NewVerifier(issuer string, clientid string, audience string) (*Verifier, error) {
-	cookieKey, err := uuid.New().MarshalBinary()
-	if err != nil {
-		return nil, fmt.Errorf("Failed to create UUID: %w", err)
+	cookieHashKey := securecookie.GenerateRandomKey(32)
```
Comment (tomponline) [inline lxd/auth/oidc/oidc.go:371]: I'd like to see some discussion & comment around why the number 32 was chosen here.

CC @simondeziel

Comment (tomponline) [reply lxd/auth/oidc/oidc.go:371]: Will this change break any existing oidc logics btw @markylaing ?

File: lxd/auth/oidc/oidc.go [hunk 4]
```diff
@@ -17,6 +17,11 @@ import (
 	"github.com/canonical/lxd/shared"
 )
 
+const (
+	CookieNameIDToken      = "oidc_identity"
```
Comment (tomponline) [inline lxd/auth/oidc/oidc.go:24]: These are exported symbols so I'd have expected a linter to complain about missing comments here.

File: lxd/auth/oidc/oidc.go [hunk 5]
```diff
@@ -303,6 +303,89 @@ func getAccessTokenVerifier(issuer string) (op.AccessTokenVerifier, error) {
...
+		if delete {
+			idTokenCookie.Value = ""
+			idTokenCookie.Expires = time.Unix(0, 0)
+		}
+
+		http.SetCookie(w, &idTokenCookie)
+	}
+
+	if refreshToken != "" || delete {
+		encodedRefreshToken, err := o.secureCookie.Encode(CookieNameRefreshToken, refreshToken)
```
Comment (tomponline) [inline lxd/auth/oidc/oidc.go:344]: Why do we do this if delete is true?

File: lxd/auth/oidc/oidc.go (hunk 3 above)
Comment (markylaing) [reply lxd/auth/oidc/oidc.go:371]: Yes. Users will need to log in again.

Comment (tomponline) [reply lxd/auth/oidc/oidc.go:371]: OK, that really should be highlighted clearly in the PR description as its potentially an issue we need to consider.

Comment (simondeziel) [reply lxd/auth/oidc/oidc.go:371]: @tomponline 32 bytes seems to be the required length for AES-256 according to https://github.com/gorilla/securecookie/blob/main/README.md?plain=1#L36C30-L37C60

Comment (tomponline) [reply lxd/auth/oidc/oidc.go:371]: Thanks we should have a comment explaining that for the benefit of future readers to avoid "magic numbers" in code.

Comment (simondeziel) [reply lxd/auth/oidc/oidc.go:371]: Oops, I didn't notice this was the hash part. For the hash part, 32 or 64 is supported. I'd go with 64 there since you picked AES-256 anyway.

Comment (simondeziel) [reply lxd/auth/oidc/oidc.go:371]: Either way, I think that's a good idea to use `securecookie` mechanism, thanks for doing that!

File: lxd/auth/oidc/oidc.go [hunk 6]
```diff
@@ -257,53 +208,178 @@ func (o *Verifier) IsRequest(r *http.Request) bool {
...
+	return nil
 }
 
 // NewVerifier returns a Verifier.
 func NewVerifier(issuer string, clientid string, audience string) (*Verifier, error) {
-	cookieKey, err := uuid.New().MarshalBinary()
-	if err != nil {
-		return nil, fmt.Errorf("Failed to create UUID: %w", err)
+	cookieHashKey := securecookie.GenerateRandomKey(32)
+	cookieBlockKey := securecookie.GenerateRandomKey(32)
```
Comment (nsklikas) [inline lxd/auth/oidc/oidc.go:372]: Not sure if lxd supports it, but this would not work in a clustered/distributed setup. AFAICT, each server would have its own key and they wouldn't be able to verify cookies that were signed by the other servers. Also all cookies will be invalidated upon restart, which would mean that all users will be logged out (not sure if you care about this).

Comment (tomponline) [reply lxd/auth/oidc/oidc.go:372]: @nsklikas a very good point indeed.

Comment (markylaing) [reply lxd/auth/oidc/oidc.go:372]: Hmm yeah, this is fine if you open the browser on a single cluster member but will fail if there is a load balancer in front...

I wonder if we can derive these keys from the cluster private key somehow.

File: lxd/auth/oidc/oidc.go [hunk 7]
```diff
@@ -303,6 +303,89 @@ func getAccessTokenVerifier(issuer string) (op.AccessTokenVerifier, error) {
...
+	}
+
+	return idToken, refreshToken, nil
+}
+
+// setCookies encrypts the ID and refresh tokens and sets them in the HTTP response. Cookies are only set if they are
+// non-empty. If delete is true, the values are set to empty strings and the cookie expiry is set to unix zero time.
+func (o *Verifier) setCookies(w http.ResponseWriter, idToken string, refreshToken string, delete bool) error {
+	if idToken != "" || delete {
+		encodedIDTokenCookie, err := o.secureCookie.Encode(CookieNameIDToken, idToken)
```
[the remark this answers is not in the document]
Comment (markylaing) [reply lxd/auth/oidc/oidc.go:321]: We shouldn't. I'll fix it.

File: lxd/auth/oidc/oidc.go (hunk 4 above)
Comment (markylaing) [reply lxd/auth/oidc/oidc.go:24]: These constants don't actually need to be exported. In any case, after some investigation today I've found that the `revive` linter isn't running in golangci-lint. I think we should turn it on. In addition, when the `revive` linter is run via golangci-lint, it doesn't seem to catch missing comments on exported methods, functions, variables, or constants and we need to run it separately to specifically find those cases. I'm working through it now but there is an awful lot to fix.

File: lxd/auth/oidc/oidc.go (hunk 6 above)
Comment (tomponline) [reply lxd/auth/oidc/oidc.go:372]: You could potentially use the cluster key to derive a random key.
That is how the API's certificate is the same across cluster members.

Comment (markylaing) [reply lxd/auth/oidc/oidc.go]: I'm now using a SHA512 (64 bytes) hash of the server private key (network cert private key in a cluster) for the cookie hash key and a SHA256 (32 bytes) hash for the cookie block key. This will be the same on all cluster members.

File: lxd/auth/oidc/oidc.go (hunk 4 above)
Comment (markylaing) [reply lxd/auth/oidc/oidc.go]: I've unexported these but added comments for them in any case. I'm working on a separate PR to fix the linter config.

File: lxd/auth/oidc/oidc.go (hunk 3 above)
Comment (markylaing) [reply lxd/auth/oidc/oidc.go]: There are now comments to explain the cookie keys, how they are derived, and the required length for security.

File: lxd/auth/oidc/oidc.go [hunk 8]
```diff
@@ -169,30 +169,15 @@ func (o *Verifier) Login(w http.ResponseWriter, r *http.Request) {
...
-		SameSite: http.SameSiteStrictMode,
-		Expires:  time.Unix(0, 0),
+	err := o.setCookies(w, "", "", true)
+	if err != nil {
+		_ = response.ErrorResponse(http.StatusInternalServerError, fmt.Errorf("Failed to delete login information: %w", err).Error()).Render(w)
+		return
 	}
 
-	http.SetCookie(w, &refreshCookie)
+	http.Redirect(w, r, fmt.Sprintf("https://%s/ui/login", r.Host), http.StatusFound)
```
Comment (roosterfish) [inline lxd/auth/oidc/oidc.go:183]: I was wondering if the specific login URL could be sourced from a variable or made into a constant for later reference/change?

File: lxd/auth/oidc/oidc.go [hunk 9]
```diff
@@ -158,6 +158,50 @@ func (o *Verifier) Auth(ctx context.Context, w http.ResponseWriter, r *http.Requ
...
+	// Verify the refreshed ID token.
+	claims, err = rp.VerifyIDToken[*oidc.IDTokenClaims](ctx, idToken, o.relyingParty.IDTokenVerifier())
+	if err != nil {
+		return "", AuthError{Err: fmt.Errorf("Failed to verify refreshed ID token: %w", err)}
+	}
+
+	// Update the cookies.
+	err = o.setCookies(w, idToken, tokens.RefreshToken, false)
+	if err != nil {
+		return "", fmt.Errorf("Failed to update login data: %w", err)
```
Comment (roosterfish) [inline lxd/auth/oidc/oidc.go:157]: Maybe something like "Failed to update login cookies" to make it clear what exactly failed?

File: lxd/auth/oidc/oidc.go [hunk 10]
```diff
@@ -61,102 +61,39 @@ func (e AuthError) Unwrap() error {
...
-				Value:    tokens.RefreshToken,
-				Path:     "/",
-				Secure:   true,
-				HttpOnly: false,
-				SameSite: http.SameSiteStrictMode,
-			}
+		// Cookies are present but we failed to decrypt them. They may have been tampered with, so delete them to force
+		// the user to log in again.
+		_ = o.setCookies(w, "", "", true)
+		return "", fmt.Errorf("Failed to retrieve login information: %w", err)
```
Comment (roosterfish) [inline lxd/auth/oidc/oidc.go:80]: Does this again trigger a redirect to the `/ui/login` page in the calling functions?

**Review by roosterfish — COMMENTED** [review]
Hi, looks very good overall. Just a few smaller suggestions.

File: lxd/auth/oidc/oidc.go (hunk 10 above)
Comment (markylaing) [reply lxd/auth/oidc/oidc.go:81]: Unfortunately not. The UI will automatically redirect there when it realises the user is not authenticated though.

File: lxd/auth/oidc/oidc.go (hunk 8 above)
Comment (markylaing) [reply lxd/auth/oidc/oidc.go:184]: I'm not sure. `/ui/login` is only used in this one place but `/ui/` is used as a magic string in multiple places. This might be better addressed in a later PR if we decide to parameterise URLs.

File: lxd/auth/oidc/oidc.go (hunk 6 above)
Comment (markylaing) [reply lxd/auth/oidc/oidc.go]: It's now using HDKF to derive keys from the server private key. I haven't used a salt because each cluster member needs the same value.

**Comment by markylaing** [comment]
@nsklikas In the OIDC login handler I have re-added the `audience` parameter. While it may not form part of the full OIDC specification, it is required if we want to add custom claims to tokens (e.g. group membership) which we will need.

**Review by roosterfish — APPROVED** [review]
Thanks for the clarifications, LGTM.

File: lxd/auth/oidc/oidc.go [hunk 11]
```diff
@@ -304,14 +311,32 @@ func getAccessTokenVerifier(issuer string) (op.AccessTokenVerifier, error) {
 }
 
 // NewVerifier returns a Verifier.
-func NewVerifier(issuer string, clientid string, audience string) (*Verifier, error) {
-	cookieKey, err := uuid.New().MarshalBinary()
+func NewVerifier(issuer string, clientid string, audience string, clusterCert *shared.CertInfo) (*Verifier, error) {
+	// Derive secret keys from the server cert (standalone) or network cert (cluster) to ensure all members use the
```
Comment (tomponline) [inline lxd/auth/oidc/oidc.go:388]: not "cert" but "key". The cert is public.

Comment (markylaing) [reply lxd/auth/oidc/oidc.go:388]: Whoops yep will fix now

Comment (markylaing) [reply lxd/auth/oidc/oidc.go]: Done.

**Comment by tomponline** [comment]
This is blocked awaiting for a security review from Canonical's security team.

@markylaing if you are able to break this PR down into parts that do not relate to the encrypted cookie then we can merge those separately without waiting for the security review.

**Comment by tomponline** [comment]
@markylaing please can you rebase and update PR title and description to reflect the changes in this PR now. Ta

**Comment by tobhe** [comment]
This does look like a nice improvement already. There are a few more changes the Security team would like to see to further harden the cookie encryption:

- Please include a salt in HKDF. This should be a a random value of suitable size (16 bytes should be fine) that is freshly generated for each new access token and communicated to the client, either as part of the cipher string or in a separate cookie. This will make sure that each generated key is unique which is important since the input seed is static.
- For each new access token, the salt and thus the symmetric encryption key should be regenerated. The cookie encryption seems to use AES-CTR so it is important not to reuse the same key + nonce pair. We should therefore regenerate the key regularly to reduce the risk of collisions.
- Since multiple HKDF keys are derived from the same input it would make sense to use context information to bind them to their function. In particular we'd like to two different `hkdf.New` calls with something like `[]byte("ENCRYPTION")` and `[]byte("INTEGRITY")`.

Feel free to ping me or @chrisccoulson for more questions!

File: lxd/auth/oidc/oidc.go [hunk 12]
```diff
@@ -360,13 +382,32 @@ func (*Verifier) setCookies(w http.ResponseWriter, idToken string, refreshToken
...
+	// Derive secret keys from the server private key (standalone) or network private key (cluster) to ensure all
+	// members use the same hash and block keys for encrypted cookies. Cookie hash and block keys are 64 and 32 bytes
+	// long respectively, as recommended by the securecookie library:
+	// https://github.com/gorilla/securecookie/blob/eae3c1840ec4adda88a4af683ad0f60bb690e7c2/README.md#examples
+	keyDerivationFunc := hkdf.New(sha512.New, clusterCert.PrivateKey(), nil, nil)
+	cookieHashKey := make([]byte, 64)
+	_, err := io.ReadFull(keyDerivationFunc, cookieHashKey)
 	if err != nil {
-		return nil, fmt.Errorf("Failed to create UUID: %w", err)
+		return nil, errors.New("Failed creating secure cookie hash key")
```
Comment (tomponline) [inline lxd/auth/oidc/oidc.go:394]: We should wrap the error here please.

File: lxd/auth/oidc/oidc.go [hunk 13]
```diff
@@ -360,13 +382,32 @@ func (*Verifier) setCookies(w http.ResponseWriter, idToken string, refreshToken
...
 	}
 
-	verifier := &Verifier{issuer: issuer, clientID: clientid, audience: audience, cookieKey: cookieKey}
+	cookieBlockKey := make([]byte, 32)
+	_, err = io.ReadFull(keyDerivationFunc, cookieBlockKey)
+	if err != nil {
+		return nil, errors.New("Failed creating secure cookie block key")
```
Comment (tomponline) [inline lxd/auth/oidc/oidc.go:400]: We should wrap the error here please

**Comment by markylaing** [comment]
@tomponline @tobhe I think I've made the requested changes. Can you please re-review? Thanks.

Also @tomponline after merging https://github.com/canonical/lxd/pull/12791 I've had to include some lint fixes. However, some of the revive rules seemed overly opinionated and I'm not sure how much help they'll be. I've sent a PR to change those rules (https://github.com/canonical/lxd/pull/12797) but in the meantime this PR will fail linting.

**Comment by tomponline** [comment]
@tobhe does this look acceptable to you? Thanks

File: lxd/auth/oidc/oidc.go [hunk 14]
```diff
@@ -371,14 +371,36 @@ func (*Verifier) setCookies(w http.ResponseWriter, idToken string, refreshToken
...
+		o.configExpiryInterval = interval
+	}
+}
+
 // NewVerifier returns a Verifier.
-func NewVerifier(issuer string, clientid string, audience string) (*Verifier, error) {
-	cookieKey, err := uuid.New().MarshalBinary()
-	if err != nil {
-		return nil, fmt.Errorf("Failed to create UUID: %w", err)
+func NewVerifier(issuer string, clientID string, audience string, clusterCert *shared.CertInfo, options ...func(*Opts)) (*Verifier, error) {
```
Comment (tomponline) [inline lxd/auth/oidc/oidc.go:482]: Can we pass the opts directly as an arg rather than a variadic so we can easily see the available options in the function definition?

File: lxd/auth/oidc/oidc.go [hunk 15]
```diff
@@ -371,6 +375,30 @@ func (*Verifier) setCookies(w http.ResponseWriter, idToken string, refreshToken
 	return nil
 }
 
+func (o *Verifier) secureCookieFromSession(sessionID uuid.UUID) (*securecookie.SecureCookie, error) {
```
Comment (tomponline) [inline lxd/auth/oidc/oidc.go:444]: missing doc block explaining what this function does

Comment (tomponline) [reply lxd/auth/oidc/oidc.go:444]: in general I think its prudent to add a lot more comments to this function explaining what each step does, and most importantly why. As well as a warning in the doc block that changing this implementation may cause existing users to be logged out.

File: lxd/auth/oidc/oidc.go [hunk 16]
```diff
@@ -308,70 +308,107 @@ func (o *Verifier) setAccessTokenVerifier() error {
 	return nil
 }
 
-// getCookies gets the ID and refresh tokens from the request cookies.
-func (*Verifier) getCookies(r *http.Request) (idToken string, refreshToken string, err error) {
+// getCookies gets the sessionID, identity and refresh tokens from the request cookies and decrypts them.
+func (o *Verifier) getCookies(r *http.Request) (sessionID uuid.UUID, idToken string, refreshToken string, err error) {
```
Comment (tomponline) [inline lxd/auth/oidc/oidc.go:341]: Lets return a pointer to a uuid.UUID here to allow returning nil when erroring rather than having to initialise and return empty structs.

**Review by tobhe — APPROVED** [review]
This looks pretty good to me now. I think you addressed all of the changes we requested:
- You are using salt and context information for the keys
- sessionId (the salt) is regenerated for each token refresh
- salt size of 64 is also sufficient

I agree with @tomponline that a few places could benefit from some more documentation.

File: lxd/auth/oidc/oidc.go [hunk 17]
```diff
@@ -292,81 +337,164 @@ func (o *Verifier) setAccessTokenVerifier() error {
...
+	keyDerivationFunc := hkdf.New(sha512.New, clusterPrivateKey, salt, []byte("ENCRYPTION"))
+	cookieHashKey := make([]byte, 64)
+	_, err = io.ReadFull(keyDerivationFunc, cookieHashKey)
 	if err != nil {
-		return nil, fmt.Errorf("Failed to create UUID: %w", err)
+		return nil, fmt.Errorf("Failed creating secure cookie hash key: %w", err)
 	}
 
-	verifier := &Verifier{issuer: issuer, clientID: clientid, audience: audience, cookieKey: cookieKey}
+	keyDerivationFunc = hkdf.New(sha512.New, clusterPrivateKey, salt, []byte("INTEGRITY"))
```
Comment (chrisccoulson) [inline lxd/auth/oidc/oidc.go:458]: As an optimisation here, you could directly use the `hkdf.Extract` and `hkdf.Expand` APIs (which is what `hkdf.New` is doing anyway) like this:

```
prk := hkdf.Extract(sha512.New, clusterPrivateKey, salt)
keyDerivationFunc := hkdf.Expand(sha512.New, prk, []byte("ENCRYPTION")
cookieBlockKey := make([]byte, 32)
if _, err = io.ReadFull(keyDerivationFunc, cookieBlockKey); err != nil {
    return nil, fmt.Errorf("Failed creating secure cookie block key: %w", err)
}
keyDerivationFunc = hkdf.Expand(sha512.New, prk, []byte("INTEGRITY")
cookieHashKey := make([]byte, 64)
if _, err = io.ReadFull(keyDerivationFunc, cookieBlockKey); err != nil {
    return nil, fmt.Errorf("Failed creating secure cookie hash key: %w", err)
}
```

File: lxd/auth/oidc/oidc.go [hunk 18]
```diff
@@ -292,81 +337,164 @@ func (o *Verifier) setAccessTokenVerifier() error {
...
-func NewVerifier(issuer string, clientid string, audience string) (*Verifier, error) {
-	cookieKey, err := uuid.New().MarshalBinary()
+func (o *Verifier) secureCookieFromSession(sessionID uuid.UUID) (*securecookie.SecureCookie, error) {
+	salt, err := sessionID.MarshalBinary()
+	if err != nil {
+		return nil, fmt.Errorf("Failed to generate a session ID: %w", err)
+	}
+
+	clusterPrivateKey := o.clusterCert.PrivateKey()
+	keyDerivationFunc := hkdf.New(sha512.New, clusterPrivateKey, salt, []byte("ENCRYPTION"))
```
Comment (chrisccoulson) [inline lxd/auth/oidc/oidc.go:451]: It looks like the `ENCRYPTION` and `INTEGRITY` labels are swapped round

**Review by chrisccoulson — COMMENTED** [review]
Thanks, I've left a couple of minor comments

File: lxd/auth/oidc/oidc.go (hunk 17 above)
Comment (markylaing) [reply lxd/auth/oidc/oidc.go]: Thanks, I've made this change.

File: lxd/auth/oidc/oidc.go [hunk 19]
```diff
@@ -284,7 +285,17 @@ func (o *Verifier) ensureConfig(host string) error {
 
 // setRelyingParty sets the relyingParty on the Verifier. The host argument is used to set a valid callback URL.
 func (o *Verifier) setRelyingParty(host string) error {
-	cookieHandler := httphelper.NewCookieHandler(o.cookieKey, o.cookieKey)
+	cookieHashKey := securecookie.GenerateRandomKey(64)
```
[the remark this answers is not in the document]
Comment (markylaing) [reply lxd/auth/oidc/oidc.go:301]: Done :+1:

File: lxd/auth/oidc/oidc.go (hunk 16 above)
Comment (markylaing) [reply lxd/auth/oidc/oidc.go]: Also done.

File: lxd/auth/oidc/oidc.go (hunk 15 above)
Comment (markylaing) [reply lxd/auth/oidc/oidc.go:462]: I've added a bunch of comments. Let me know if there is anything else worth adding or if it is unclear.

File: lxd/auth/oidc/oidc.go (hunk 14 above)
Comment (markylaing) [reply lxd/auth/oidc/oidc.go]: Done.

File: lxd/auth/oidc/oidc.go [hunk 20]
```diff
@@ -371,6 +375,51 @@ func (*Verifier) setCookies(w http.ResponseWriter, idToken string, refreshToken
...
+	}
+
+	// Get the current cluster private key.
+	clusterPrivateKey := o.clusterCert().PrivateKey()
+
+	// Extract a pseudo-random key from the cluster private key.
+	prk := hkdf.Extract(sha512.New, clusterPrivateKey, salt)
+
+	// Add "info" context information and perform expansion.
+	keyDerivationFunc := hkdf.Expand(sha512.New, prk, []byte("INTEGRITY"))
```
Comment (tomponline) [inline lxd/auth/oidc/oidc.go:476]: Could you add a comment here explaining the use of `INTEGRITY` ?

File: lxd/auth/oidc/oidc.go [hunk 21]
```diff
@@ -371,6 +375,51 @@ func (*Verifier) setCookies(w http.ResponseWriter, idToken string, refreshToken
...
+
+	// Read 64 bytes of the derived key. The securecookie library recommends 64 bytes for the hash key (https://github.com/gorilla/securecookie).
+	cookieHashKey := make([]byte, 64)
+	_, err = io.ReadFull(keyDerivationFunc, cookieHashKey)
+	if err != nil {
+		return nil, fmt.Errorf("Failed creating secure cookie hash key: %w", err)
+	}
+
+	// Add "info" context information and perform expansion.
+	keyDerivationFunc = hkdf.Expand(sha512.New, prk, []byte("ENCRYPTION"))
```
Comment (tomponline) [inline lxd/auth/oidc/oidc.go:486]: Could you add a comment here explaining the use of ENCRYPTION ?

**Review by tomponline — APPROVED** [review]

File: lxd/auth/oidc/oidc.go (hunk 21 above)
Comment (markylaing) [reply lxd/auth/oidc/oidc.go:492]: I've added comments for both and linked to the info section in the RFC :)

**Review by tomponline — APPROVED** [review]
Thanks!
