### PR TITLE
Patches: Fix patch system so that it respects the patch stages

### LINKED ISSUE #13860: Upgrading from 4.0 to 5.21 fails on patch `storage_prefix_bucket_names_with_project`
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "snap list --all lxd core20 core22 core24 snapd":

```
Name    Version         Rev    Tracking       Publisher   Notes
core20  20240416        2318   latest/stable  canonical✓  base
core22  20240408        1380   latest/stable  canonical✓  base
lxd     4.0.9-a29c6f1   24061  5.21/stable    canonical✓  disabled
lxd     5.21.2-34459c8  29568  5.21/stable    canonical✓  -
snapd   2.63            21759  latest/stable  canonical✓  snapd
```

 * The output of "lxc info" or if that fails:
   * Kernel version: `Linux rbasak-lxd 5.4.0-189-generic #209-Ubuntu SMP Fri Jun 7 14:05:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
   * LXC version: `5.21.2 LTS`
   * LXD version: `5.21.2 LTS`
   * Storage backend in use: dir

# Issue description

Following on from #13806 I tried updating the snap to `5.21/stable`. This caused lxc to fail entirely.

# Steps to reproduce

 1. Launch and log in to a Focal VM over ssh. I used: `uvt-kvm create --memory=1024 rbasak-lxd release=focal arch=amd64` with this image: `release=focal arch=amd64 label=release (20240710)`, then `uvt-kvm wait rbasak-lxd`, then `uvt-kvm ssh rbasak-lxd`.
 2. `sudo lxd init`, specifying all defaults except that I used the "dir" storage type.
 3. `lxc remote rm images`
 4. `lxc remote add images https://images.lxd.canonical.com --protocol=simplestreams`
 5. `lxc launch images:debian/sid/amd64 foo`
 6. `sudo snap refresh --channel=5.21/stable lxd`
 7. `lxc list`

Expected results: listing of the one container I created previously.

Actual results:

`Error: LXD unix socket not accessible: Get "http://unix.socket/1.0": EOF`

Logging out of the VM and back in again, and trying `lxc list` again, I get:

`Error: LXD unix socket "/var/snap/lxd/common/lxd/unix.socket" not accessible: Get "http://unix.socket/1.0": dial unix /var/snap/lxd/common/lxd/unix.socket: connect: connection refused`

Rebooting the VM doesn't help. After that, I get:

`Error: LXD unix socket not accessible: Get "http://unix.socket/1.0": EOF`

### PR DESCRIPTION
**Pull request by tomponline**
It appears that ever since I introduced the concept of a [patch stage in LXD 3.23](https://github.com/canonical/lxd/pull/7012) the patch stage argument hasn't actually been taking effect.

This hasn't been noticed as each time we've introduced an earlier stage the existing patches were either compatible with the earlier stage or had already been run and so we weren't getting reports of issues.

However with the introduction of the [`patchPreLoadClusterConfig` stage in LXD 6.1](https://github.com/canonical/lxd/pull/13567) it has now become apparent because of a new patch I am working on to remove specific volatile instance config keys from instances on the local member, and I noticed that `state.ServerName` was empty even though it was being set after the `patchPreLoadClusterConfig` stage and my new patch was supposed to be running after that, but in fact, wasn't.

Fixes #13860

### CODE REVIEW

**Review by roosterfish — DISMISSED** [review]
Nice catch!

File: lxd/patches.go [hunk 1]
```diff
@@ -941,116 +941,7 @@ func patchZfsSetContentTypeUserProperty(name string, d *Daemon) error {
...
-			err = s.DB.Cluster.Transaction(context.TODO(), func(ctx context.Context, tx *db.ClusterTx) error {
-				return tx.UpdateStoragePoolVolume(ctx, vol.Project, vol.Name, volType, pool, vol.Description, config)
-			})
-			if err != nil {
-				return fmt.Errorf("Failed updating volume %q in project %q on pool %q: %w", vol.Name, vol.Project, poolIDNameMap[pool], err)
-			}
-		}
-	}
-
+	// Superseded by patchStorageZfsUnsetInvalidBlockSettingsV2.
```
[the remark this answers is not in the document]
Comment (tomponline) [reply lxd/patches.go:944]: It has been applied on systems already so good to keep a log that it existed.

File: lxd/patches.go [hunk 2]
```diff
@@ -1266,14 +1266,16 @@ func patchStorageRenameCustomISOBlockVolumesV2(name string, d *Daemon) error {
...
-		if p.Driver().Info().Remote && !isSelectedPatchMember {
+		if isRemotePool && !isSelectedPatchMember {
 			continue
 		}
 
 		for _, vol := range volumes {
-			// In a non-clusted environment ServerName will be empty.
-			if s.ServerName != "" && vol.Location != s.ServerName {
+			// Skip volumes on local pools that are on other servers.
+			if !isRemotePool && s.ServerClustered && vol.Location != s.ServerName {
```
Comment (roosterfish) [inline lxd/patches.go:1278]: I was now looking at this for a bit.

Having only `!isRemotePool && vol.Location != s.ServerName` would evaluate to `true` every time because if LXD is not clustered `s.ServerName` is empty? So therefore we need the extra check for `s.ServerClustered` (or `s.ServerName != ""` but the other is more elegant :) ).

Maybe for the future it would help to have a `isSelectedVolPatchMember(pool, vol) bool` that can be used for decision making when patching volumes?

**Review by roosterfish — APPROVED** [review]

File: lxd/patches.go (hunk 2 above)
Comment (tomponline) [reply lxd/patches.go:1278]: > if LXD is not clustered `s.ServerName` is empty?

s.ServerName is "none" in those situations.

Comment (tomponline) [reply lxd/patches.go:1278]: > Maybe for the future it would help to have a `isSelectedVolPatchMember(pool, vol) bool` that can be used for decision making when patching volumes?

Yes standardising that logic into a helper function would be useful though.

Comment (roosterfish) [reply lxd/patches.go:1278]: Just thinking what will happen if you actually have a LXD cluster member called "none". I suspect this is allowed?

Maybe worth having another story that checks this too in the other places this pattern is used.

Comment (tomponline) [reply lxd/patches.go:1278]: I dont think you are allowed to do that, but if you can then it should be blocked.

Comment (roosterfish) [reply lxd/patches.go:1278]: Looks to be possible:

```
root@m1:~# lxc cluster ls
+------+-----------------------------+------------------+--------------+----------------+-------------+--------+-------------------+
| NAME |             URL             |      ROLES       | ARCHITECTURE | FAILURE DOMAIN | DESCRIPTION | STATE  |      MESSAGE      |
+------+-----------------------------+------------------+--------------+----------------+-------------+--------+-------------------+
| m1   | https://10.165.133.53:8443  | database-leader  | x86_64       | default        |             | ONLINE | Fully operational |
|      |                             | database         |              |                |             |        |                   |
+------+-----------------------------+------------------+--------------+----------------+-------------+--------+-------------------+
| none | https://10.165.133.128:8443 | database-standby | x86_64       | default        |             | ONLINE | Fully operational |
+------+-----------------------------+------------------+--------------+----------------+-------------+--------+-------------------+
```

I'll open up a PR to block it.
