### PR TITLE
Live migration with attached storage volumes (from Incus)

### LINKED ISSUE #12694: Support live migration of VMs with attached volumes
Following cluster:

```
root@mc10:~# lxc cluster ls
+------+---------------------------+-----------------+--------------+----------------+-------------+--------+-------------------+
| NAME |            URL            |      ROLES      | ARCHITECTURE | FAILURE DOMAIN | DESCRIPTION | STATE  |      MESSAGE      |
+------+---------------------------+-----------------+--------------+----------------+-------------+--------+-------------------+
| mc10 | https://192.168.1.10:8443 | database-leader | x86_64       | default        |             | ONLINE | Fully operational |
|      |                           | database        |              |                |             |        |                   |
+------+---------------------------+-----------------+--------------+----------------+-------------+--------+-------------------+
| mc11 | https://192.168.1.11:8443 | database        | x86_64       | default        |             | ONLINE | Fully operational |
+------+---------------------------+-----------------+--------------+----------------+-------------+--------+-------------------+
| mc12 | https://192.168.1.12:8443 | database        | x86_64       | default        |             | ONLINE | Fully operational |
+------+---------------------------+-----------------+--------------+----------------+-------------+--------+-------------------+
root@mc10:~# 
```

I start one VM:

```
lxc launch ubuntu:22.04 v1 --vm --target mc10
```

I move it:

```
root@mc10:~# lxc exec v1 -- uptime
 11:45:17 up 0 min,  0 users,  load average: 0.59, 0.13, 0.04
root@mc10:~# 

root@mc10:~# lxc move v1 --target mc11
Error: Instance move to destination failed: Error transferring instance data: Failed migration on target: Failed getting migration target filesystem connection: websocket: bad handshake
root@mc10:~# 
```

### PR DESCRIPTION
**Pull request by markylaing**
Enables live-migration of an instance with volumes attached as long as those disks are also on a remote storage pool.

Created as draft while I finish writing tests.

Closes #12694

### CODE REVIEW

File: lxd/device/disk.go [hunk 1]
```diff
@@ -500,7 +500,7 @@ func (d *disk) validateConfig(instConf instance.ConfigReader) error {
 					return fmt.Errorf("Failed checking if custom volume is exclusively attached to another instance: %w", err)
 				}
 
-				if remoteInstance != nil {
+				if remoteInstance != nil && remoteInstance.ID != instConf.ID() {
 					return fmt.Errorf("Custom volume is already attached to an instance on a different node")
```
Comment (tomponline) [inline lxd/device/disk.go:504]: Please can you change the "node" reference here to "cluster member" in a separate commit.

File: lxd/instance/drivers/driver_qemu.go [hunk 2]
```diff
@@ -6857,6 +6857,39 @@ func (d *qemu) migrateSendLive(pool storagePools.Pool, clusterMoveSourceName str
 		return err
 	}
```
Comment (tomponline) [inline lxd/instance/drivers/driver_qemu.go:6859]: Please remove the "incus issue" reference in the commit message as not relevant.

File: lxd/instance/drivers/driver_qemu.go [hunk 3]
```diff
@@ -7338,6 +7371,39 @@ func (d *qemu) MigrateReceive(args instance.MigrateReceiveArgs) error {
...
+
+			// Setup the volume entry.
+			extraTargetArgs := migration.VolumeTargetArgs{
+				ClusterMoveSourceName: args.ClusterMoveSourceName,
+			}
+
+			vol := diskPool.GetVolume(storageDrivers.VolumeTypeCustom, storageDrivers.ContentTypeBlock, project.StorageVolume(storageProjectName, dev.Config["source"]), nil)
+			volCopy := storageDrivers.NewVolumeCopy(vol)
+
+			// Call MigrateVolume on the source.
```
Comment (tomponline) [inline lxd/instance/drivers/driver_qemu.go:7400]: Is this comment correct?

File: lxd/instance/drivers/driver_qemu.go [hunk 4]
```diff
@@ -6857,6 +6857,39 @@ func (d *qemu) migrateSendLive(pool storagePools.Pool, clusterMoveSourceName str
...
+	}
+
+	// Notify the shared disks that they're going to be accessed from another system.
+	for _, dev := range d.expandedDevices.Sorted() {
+		if dev.Config["type"] != "disk" || dev.Config["path"] == "/" {
+			continue
+		}
+
+		// Load the pool for the disk.
+		diskPool, err := storagePools.LoadByName(d.state, dev.Config["pool"])
```
Comment (tomponline) [inline lxd/instance/drivers/driver_qemu.go:6873]: An optimisation here would be to store the diskPool in a map keyed by name, so that if there are multiple disks from the same pool you dont have to load the pool from DB multiple times.

**Comment by markylaing** [comment]
I've addressed the comments and the test (https://github.com/canonical/lxd-ci/pull/250) is passing for me locally. It is also failing at the expected point in github actions, so I believe it will pass once this is merged and in latest/edge.

**Review by tomponline — APPROVED** [review]
