### PR TITLE
Fix info --resources for wwan devices

### LINKED ISSUE #12153: LXD 5.15 fails to determine resources
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.2.0-26-generic #26~22.04.1-Ubuntu 
   * LXC version: 5.0.2
   * LXD version: 5.15-002fa0f
   * Storage backend in use:

# Issue description

Trying to determine resources on a Thinkpad T14 Gen 2 fails with the following error:

```
$ lxc info --resources
Error: Failed to retrieve network information: Failed to add device information for "/sys/class/net/wwan0/device": Failed to read "/sys/class/net/wwan0/device/device": read /sys/class/net/wwan0/device/device: is a directory
```

# Steps to reproduce

 1. Run `lxc info --resource`

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by skatsaounis**
This PR recursively expands the device directory path of `sys/class/net` devices by appending `/device` until the it finds a `device` regular file as a child.

This is needed for devices like wwan which include sub-devices and they differ from typical `sys/class/net` devices. For such kind of devices, the net info is present at the top `./device` directory but rest information needed to fill `Card` struct is located at `./device/device`.

Please take a look below for more info:

```
# ll --time-style='+' /sys/class/net/wwan0/device/
total 0
drwxr-xr-x 7 root root    0  ./
drwxr-xr-x 3 root root    0  ../
lrwxrwxrwx 1 root root    0  device -> ../../../0000:08:00.0/
-r--r--r-- 1 root root 4096  index
drwxr-xr-x 3 root root    0  net/
drwxr-xr-x 2 root root    0  power/
lrwxrwxrwx 1 root root    0  subsystem -> ../../../../../../class/wwan/
-rw-r--r-- 1 root root 4096  uevent
drwxr-xr-x 3 root root    0  wwan0at0/
drwxr-xr-x 3 root root    0  wwan0at1/
drwxr-xr-x 3 root root    0  wwan0mbim0/

# ll --time-style='+' /sys/class/net/wwan0/device/device/
...
-r--r--r--  1 root root 4096  device
...
lrwxrwxrwx  1 root root    0  driver -> ../../../../bus/pci/drivers/iosm/
...
-rw-r--r--  1 root root 4096  numa_node
...
-r--r--r--  1 root root 4096  vendor
...

```

Fixes #12153

### CODE REVIEW

**Comment by tomponline** [comment]
@skatsaounis did you want a review of this? If so please can you mark it as ready for review. Thanks :)

**Comment by skatsaounis** [comment]
@tomponline PR is ready for review. Please take a look :)

**Comment by skatsaounis** [comment]
Before change:

```bash
$ lxc info --resources
Error: Failed to retrieve network information: Failed to add device information for "/sys/class/net/wwan0/device": Failed to read "/sys/class/net/wwan0/device/device": read /sys/class/net/wwan0/device/device: is a directory
```
After the change:

```bash
$ lxc info --resources
...
NICs:
...
  Card 1:
    NUMA node: 0
    Vendor: Intel Corporation (8086)
    PCI address: 0000:08:00.0
    Driver: iosm (6.2.0-33-generic)
...
```

File: lxd/resources/utils.go [hunk 1]
```diff
@@ -210,3 +215,21 @@ func usbAddress(devicePath string) (string, error) {
 		return fmt.Sprintf("%d:%d", bus, dev), nil
 	}
 }
+
+func getDeviceDir(devicePath string) (string, error) {
```
Comment (tomponline) [inline lxd/resources/utils.go:219]: @skatsaounis please can you add a comment explaining what this function does without needing to look at the implementation. Thanks

**Review by tomponline — CHANGES_REQUESTED** [review]
Please can you update the PR description with what has changed in this PR so I can understand and review. Thanks

File: lxd/resources/utils.go (hunk 1 above)
Comment (skatsaounis) [reply lxd/resources/utils.go:222]: done

**Comment by skatsaounis** [comment]
Comments and descriptions have been added

**Review by tomponline — APPROVED** [review]
Thanks!
