### PR TITLE
Fix goroutine crash on image import into non-existing project

### LINKED ISSUE #16485: Importing an image to project which doesn't exist makes API handler crash
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

Ubuntu

### Distribution version

24.04

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
6/edge
```

### Output of "lxc info" or system info if it fails

```shell
N/A
```

### Issue description

Image import to non-existing project crashes. This is because `imagesPost()` has no validation if the requested project actually exist. This project name is used to load the project-specific storage config key for temporary storage of the image on upload.

### Steps to reproduce

```
$ lxc monitor --pretty &
$ test/deps/import-busybox --alias testimage --project '(current),YES,YES,YES,YES,YES,YES,Default'
```

yields:
```
DEBUG  [2025-09-13T21:42:20-04:00] Handling API request                          ip=@ method=GET protocol=unix url="/1.0/images?project=(current),YES,YES,YES,YES,YES,YES,Default" username=sdeziel
DEBUG  [2025-09-13T21:42:20-04:00] Handling API request                          ip=@ method=POST protocol=unix url="/1.0/images?project=(current),YES,YES,YES,YES,YES,YES,Default" username=sdeziel
INFO   [2025-09-13T21:42:20-04:00] http: panic serving @: Attempt to access unknown key "storage.project.(current),YES,YES,YES,YES,YES,YES,Default.images_volume"
goroutine 68792 [running]:
net/http.(*conn).serve.func1()
    net/http/server.go:1947 +0xbe
panic({0x2149de0?, 0xc0017b20c0?})
    runtime/panic.go:792 +0x132
github.com/canonical/lxd/lxd/config.Schema.mustGetKey(0xc000b88a00?, {0xc000b88af0, 0x47})
    github.com/canonical/lxd/lxd/config/schema.go:44 +0x15c
github.com/canonical/lxd/lxd/config.Schema.assertKeyType(0x262cbb0?, {0xc000b88af0, 0x47}, 0x0)
    github.com/canonical/lxd/lxd/config/schema.go:53 +0x37
github.com/canonical/lxd/lxd/config.(*Map).GetString(0xc0004b47a0, {0xc000b88af0, 0x47})
    github.com/canonical/lxd/lxd/config/map.go:112 +0x57
github.com/canonical/lxd/lxd/node.(*Config).daemonStorageVolume(0xc0004b4798, {0xc000b88a19?, 0x2658762?}, {0x262cbb0, 0x6})
    github.com/canonical/lxd/lxd/node/config.go:122 +0x9b
github.com/canonical/lxd/lxd/node.(*Config).StorageImagesVolume(...)
    github.com/canonical/lxd/lxd/node/config.go:138
main.(*Daemon).State.func3({0xc000b88a19?, 0xc00081e8c0?})
    github.com/canonical/lxd/lxd/daemon.go:833 +0x38
main.imagesPost(0xc00154c7e0?, 0xc00081e8c0)
    github.com/canonical/lxd/lxd/images.go:1159 +0x349
main.(*Daemon).createCmd.func1.2({0x27e1878, 0x0, 0x1, {0x3de4400, 0x3, 0x3}})
    github.com/canonical/lxd/lxd/daemon.go:1031 +0x3c8
main.(*Daemon).createCmd.func1({0x2b31638, 0xc000ab8a80}, 0xc00081e8c0)
    github.com/canonical/lxd/lxd/daemon.go:1042 +0x11a7
net/http.HandlerFunc.ServeHTTP(0xc00081e780?, {0x2b31638?, 0xc000ab8a80?}, 0x26288ac?)
    net/http/server.go:2294 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000b8a540, {0x2b31638, 0xc000ab8a80}, 0xc00081e140)
    github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
main.(*lxdHTTPServer).ServeHTTP(0xc000814080, {0x2b31638, 0xc000ab8a80}, 0xc00081e140)
    github.com/canonical/lxd/lxd/api.go:423 +0xd0
net/http.serverHandler.ServeHTTP({0x2b2abe0?}, {0x2b31638?, 0xc000ab8a80?}, 0x1?)
    net/http/server.go:3301 +0x8e
net/http.(*conn).serve(0xc0013e5200, {0x2b36e08, 0xc001b40f30})
    net/http/server.go:2102 +0x625
created by net/http.(*Server).Serve in goroutine 90
    net/http/server.go:3454 +0x485 
```

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by skozina**
This fixes #16485.
Additionally this unifies the error message on loading non-existing projects.

### CODE REVIEW

File: lxd/images.go [hunk 1]
```diff
@@ -1155,6 +1155,19 @@ func imagesPost(d *Daemon, r *http.Request) response.Response {
...
+		}
+
+		return nil
+	})
+	if err != nil {
+		return response.SmartError(err)
+	}
+
 	// create a directory under which we keep everything while building
 	builddir, err := os.MkdirTemp(s.ImagesStoragePath(projectName), "lxd_build_")
```
Comment (tomponline) [inline lxd/images.go]: We should where possible use the raw user input (`projectName := request.ProjectParam(r)`) to look up database entries, and then from that point onwards use the trusted input from the DB record itself.

So now we have the record from `dbCluster.GetProject` all requirements for project name after that point should use the `.Name` property rather than the raw input data.

This helps to appease CodeQL too.

**Review by tomponline — CHANGES_REQUESTED** [review]
LGTM, one additional suggestion.

File: lxd/images.go (hunk 1 above)
Comment (skozina) [reply lxd/images.go]: Thanks, makes sense. I've left only the `Authorizer.CheckPermission()` call to use the raw project name, to ensure we have unified behavior for unauthenticated clients. All the rest is now using the project name from the DB.

**Review by tomponline — DISMISSED** [review]
Thanks!

**Review by simondeziel — DISMISSED** [review]
LGTM. Would it be good to add a quick test?

**Comment by skozina** [comment]
Added a quick test that the `lxc image import` fails when importing to non-existing project.

File: test/suites/image.sh [hunk 2]
```diff
@@ -133,9 +133,15 @@ test_image_import_existing_alias() {
...
     lxc image export testimage testimage.file
     lxc image delete testimage
+
     # XXX: ensure_import_testimage imports a `.tar.xz` image which is why once exported, those extensions are appended
     # the image can be imported with an existing alias
     lxc image import testimage.file.tar.xz --alias newimage
+
+    # Test for proper error message when importing an image to a non-existing project
+    ! output="$(lxc image import testimage.file.tar.xz --project nonexistingproject 2>&1)" || false
+    echo "${output}" | grep "Project not found"
```
Comment (simondeziel) [inline test/suites/image.sh]:
```suggestion
    output="$(! lxc image import testimage.file.tar.xz --project nonexistingproject 2>&1 || false)"
    echo "${output}" | grep -F "Project not found"
```

This way, the `lxc image import` is required to fail as well as produce the right error string.

Comment (skozina) [reply test/suites/image.sh]: Ah, thanks! Fixed.

**Review by simondeziel — APPROVED** [review]

File: test/suites/image.sh (hunk 2 above)
Comment (simondeziel) [reply test/suites/image.sh]: Thanks for the quick fix and the additional test!
