### PR TITLE
Fix creating instances using a local image from another project

### LINKED ISSUE #17905: Unable to create an instance using local image from another project
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

Ubuntu

### Distribution version

24.04

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
Name    Version      Rev    Tracking       Publisher   Notes
core22  20260128     2339   latest/stable  canonical✓  base
core24  20260211     1499   latest/stable  canonical✓  base
lxd     git-12063c5  38525  6/edge         canonical✓  -
snapd   2.73         25935  latest/stable  canonical✓  snapd
```

### Output of "lxc info" or system info if it fails

```shell
-
```

### Issue description

It is currently impossible to create an instance in one project using a **local** image from a different project by using `--project` and `--target-project` flags.

There were issues in the past describing a similar problem (https://github.com/canonical/lxd/issues/13743, https://github.com/canonical/lxd/issues/10089), and it seems like they were addressed by this PR https://github.com/canonical/lxd/pull/17138. So perhaps this is a regression?

This issue seems to affect only local images.

### Steps to reproduce

```
> lxc project create p1
Project p1 created

> lxc image copy ubuntu:24.04 local: --target-project p1
Image copied successfully!

> lxc image ls --project p1
+-------+--------------+--------+---------------------------------------------+--------------+-----------+-----------+------------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |                 DESCRIPTION                 | ARCHITECTURE |   TYPE    |   SIZE    |         UPLOAD DATE          |
+-------+--------------+--------+---------------------------------------------+--------------+-----------+-----------+------------------------------+
|       | 48da73f5dbaa | no     | ubuntu 24.04 LTS amd64 (release) (20260225) | x86_64       | CONTAINER | 267.37MiB | Mar 17, 2026 at 6:38pm (UTC) |
+-------+--------------+--------+---------------------------------------------+--------------+-----------+-----------+------------------------------+

> lxc image ls --project default
+-------+-------------+--------+-------------+--------------+------+------+-------------+
| ALIAS | FINGERPRINT | PUBLIC | DESCRIPTION | ARCHITECTURE | TYPE | SIZE | UPLOAD DATE |
+-------+-------------+--------+-------------+--------------+------+------+-------------+

> fingerprint="$(lxc image list -f csv -c F --project p1)"

> lxc init local:"${fingerprint}" c1 --project p1 --target-project default
Creating c1
Error: Failed finding image "48da73f5dbaa33d365862df5c0798626cea4653a3a3cf41f557e32a8d878ef5e" on remote "local"

> lxc project create p2
Project p2 created

> lxc project switch p1

> lxc init local:"${fingerprint}" c1 -s default -n lxdbr0 --target-project p2
Creating c1
Error: Failed finding image "48da73f5dbaa33d365862df5c0798626cea4653a3a3cf41f557e32a8d878ef5e" on remote "local"
```

However, creating instance in project `p1` using image from project `p1` succeeds:
```
> lxc project switch p1

> lxc init local:"${fingerprint}" c1 -s default -n lxdbr0
Creating c1

> lxc ls --project p1
+------+---------+------+------+-----------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |
+------+---------+------+------+-----------+-----------+
| c1   | STOPPED |      |      | CONTAINER | 0         |
+------+---------+------+------+-----------+-----------+
```

What's interesting is that this issue seems to only affect the `local` remote. For example, using the `ubuntu` remote image succeeds:

```
> lxc project switch default

> lxc init ubuntu:25.04 c1 --target-project p1 -s default -n lxdbr0
Creating c1

> lxc ls --project p1
+------+---------+------+------+-----------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |
+------+---------+------+------+-----------+-----------+
| c1   | STOPPED |      |      | CONTAINER | 0         |
+------+---------+------+------+-----------+-----------+

> lxc image ls --project p1
+-------+--------------+--------+---------------------------------------------+--------------+-----------+-----------+------------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |                 DESCRIPTION                 | ARCHITECTURE |   TYPE    |   SIZE    |         UPLOAD DATE          |
+-------+--------------+--------+---------------------------------------------+--------------+-----------+-----------+------------------------------+
|       | 48da73f5dbaa | no     | ubuntu 24.04 LTS amd64 (release) (20260225) | x86_64       | CONTAINER | 267.37MiB | Mar 17, 2026 at 6:38pm (UTC) |
+-------+--------------+--------+---------------------------------------------+--------------+-----------+-----------+------------------------------+
|       | 795997a50541 | no     | ubuntu 25.04 amd64 (release) (20260114)     | x86_64       | CONTAINER | 279.73MiB | Mar 17, 2026 at 7:00pm (UTC) |
+-------+--------------+--------+---------------------------------------------+--------------+-----------+-----------+------------------------------+
```

As you can see, both the `c1` instance and the new image get stored in the project `p1`.

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by nmezhenskyi**
This PR fixes the behaviour of `--project` and `--target-project` flags for `lxc init`, `lxc rebuild`, and `lxc launch` commands, specifically when using local images.

It ensures that the `--project` flag overrides the image's source project, whereas the `--target-project` allows specifying target project for the new instance if it is different from the image.

The PR also fixes the `POST /1.0/instances` and `POST /1.0/instances/{name}/rebuild` API endpoints to correctly resolve source image project when creating an instance from a local image.

Fixes https://github.com/canonical/lxd/issues/17905.

### CODE REVIEW

File: lxc/utils.go [hunk 1]
```diff
@@ -378,45 +378,56 @@ func guessImage(conf *config.Config, d lxd.InstanceServer, instRemote string, im
...
+		if ok && imageProject != "" {
+			// Use the given project for the image source.
+			imageRemoteServer = server.UseProject(imageProject)
+		}
+
+		// Get the connection info to fetch the currently used project.
+		connInfo, err := imageRemoteServer.GetConnectionInfo()
+		if err != nil {
+			return nil, nil, fmt.Errorf("Failed getting connection information for remote %q", imageRemote)
+		}
```
[the remark this answers is not in the document]
Comment (nmezhenskyi) [reply lxc/utils.go:412]: Fixed

File: lxc/utils.go [hunk 2]
```diff
@@ -378,45 +378,56 @@ func guessImage(conf *config.Config, d lxd.InstanceServer, instRemote string, im
...
+		imageInfo = &api.Image{}
+		imageInfo.Fingerprint = imageRef
+		imageInfo.Public = true
 		source.Alias = imageRef
 	} else {
+		server, ok := imageRemoteServer.(lxd.InstanceServer)
+		if ok && imageProject != "" {
+			// Use the given project for the image source.
+			imageRemoteServer = server.UseProject(imageProject)
+		}
```
[the remark this answers is not in the document]
Comment (nmezhenskyi) [reply lxc/utils.go]: Ah, good point

[the remark this answers is not in the document]
Comment (nmezhenskyi) [reply lxc/utils.go]: I've updated the `getImgInfo()` to also accept and optional `remoteTarget` parameter.

File: lxd/instances_post.go [hunk 3]
```diff
@@ -1348,9 +1348,16 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
 			}
 
 		case api.SourceTypeImage:
+			// Resolve the source project for the image.
+			imageProject := targetProject.Name
+			if req.Source.Project != "" {
+				// If source project is explicitly provided, use it.
```
[the remark this answers is not in the document]
Comment (nmezhenskyi) [reply lxd/instances_post.go]: Makes sense, I've fixed it

File: lxd/instance_rebuild.go [hunk 4]
```diff
@@ -114,8 +114,15 @@ func instanceRebuildPost(d *Daemon, r *http.Request) response.Response {
 			return fmt.Errorf("Failed loading instance: %w", err)
 		}
 
+		// Resolve the source project for the image.
+		imageProject := targetProject.Name
+		if req.Source.Project != "" {
+			// If source project is explicitly provided, use it.
```
[the remark this answers is not in the document]
Comment (nmezhenskyi) [reply lxd/instance_rebuild.go]: Makes sense, I've fixed it

File: client/lxd_images.go [hunk 5]
```diff
@@ -722,7 +722,8 @@ func (r *ProtocolLXD) tryCopyImage(req api.ImagesPost, urls []string) (RemoteOpe
 // CopyImage copies an image from a remote server. Additional options can be passed using ImageCopyArgs.
 func (r *ProtocolLXD) CopyImage(source ImageServer, image api.Image, args *ImageCopyArgs) (RemoteOperation, error) {
 	// Quick checks.
-	if r.isSameServer(source) {
+	sameServer, sameProject := r.isSameServer(source)
+	if sameServer && sameProject {
 		return nil, errors.New("The source and target servers must be different")
```
[the remark this answers is not in the document]
Comment (nmezhenskyi) [reply client/lxd_images.go]: Fixed

File: lxc/utils.go [hunk 6]
```diff
@@ -378,45 +378,63 @@ func guessImage(conf *config.Config, d lxd.InstanceServer, instRemote string, im
...
+
+		if ok && remoteTarget != "" {
+			// Use the given target (cluster member) to locate the image.
+			imageRemoteServer = server.UseTarget(remoteTarget)
```
[the remark this answers is not in the document]
Comment (nmezhenskyi) [reply lxc/utils.go]: Fixed

File: test/suites/projects.sh [hunk 7]
```diff
@@ -544,6 +544,81 @@ test_projects_images_default() {
...
+  lxc project create img-proj
+  lxc project create inst-proj
+
+  # Import an image into the image project.
+  ensure_import_testimage img-proj
+
+  # Add a root device to the default profile of the instance project.
+  lxc profile device add default root disk path="/" pool="lxdtest-$(basename "${LXD_DIR}")" --project inst-proj
+
+  # 1. Test lxc init.
```
Comment (simondeziel) [inline test/suites/projects.sh]: Minor nit but those number prefixes are IMHO a maintenance nuisance and they don't bring much value. If I'm not alone annoyed by them, we might mention this in our Copilot instructions because LLMs love them apparently.

**Review by simondeziel — DISMISSED** [review]

File: client/lxd.go [hunk 8]
```diff
@@ -93,37 +93,41 @@ func (r *ProtocolLXD) GetConnectionInfo() (*ConnectionInfo, error) {
 }
 
 // isSameServer compares the calling ProtocolLXD object with the provided server object to check if they are the same server.
-// It verifies the equality based on their connection information (Protocol, Certificate, Project, and Target).
-func (r *ProtocolLXD) isSameServer(server Server) bool {
```
Comment (tomponline) [inline client/lxd.go:97]: This function needs to return an `error` so that we can return the error from `GetConnectionInfo()` because in those scenarios we cant ascertain if they are the same server.

File: client/lxd.go [hunk 9]
```diff
@@ -93,37 +93,41 @@ func (r *ProtocolLXD) GetConnectionInfo() (*ConnectionInfo, error) {
...
 	dstInfo, err := server.GetConnectionInfo()
 	if err != nil {
-		return false
+		return false, false
 	}
 
 	// Check whether we're dealing with the same server.
-	return srcInfo.Protocol == dstInfo.Protocol && srcInfo.Certificate == dstInfo.Certificate &&
-		srcInfo.Project == dstInfo.Project && srcInfo.Target == dstInfo.Target
+	sameServer = srcInfo.Protocol == dstInfo.Protocol && srcInfo.Certificate == dstInfo.Certificate && srcInfo.Target == dstInfo.Target
```
Comment (tomponline) [inline client/lxd.go]: feels like "is same project" should be answered by an "isSameProject" function rather than bundling into the "isSameServer" function.

File: lxd/instance_rebuild.go [hunk 10]
```diff
@@ -114,11 +115,26 @@ func instanceRebuildPost(d *Daemon, r *http.Request) response.Response {
...
 				return err
 			}
+
+			// If the image is locally available, private, and from a different project, check if the caller can view it.
+			if sourceImage != nil && localLookupProject != targetProject.Name && !sourceImage.Public {
+				err = s.Authorizer.CheckPermission(r.Context(), entity.ImageURL(localLookupProject, sourceImage.Fingerprint), auth.EntitlementCanView)
+				if err != nil {
+					return err
+				}
+			}
```
[the remark this answers is not in the document]
Comment (tomponline) [reply lxd/instance_rebuild.go]: @nmezhenskyi @markylaing needs considering?

[the remark this answers is not in the document]
Comment (nmezhenskyi) [reply lxd/instance_rebuild.go]: Yes, this seems like a valid point. I'll check how we handle this in other places.

File: client/lxd.go (hunk 8 above)
Comment (nmezhenskyi) [reply client/lxd.go:97]: Updated

File: client/lxd.go (hunk 9 above)
Comment (nmezhenskyi) [reply client/lxd.go]: Updated

File: test/suites/projects.sh (hunk 7 above)
Comment (nmezhenskyi) [reply test/suites/projects.sh]: Fair, I've removed these

**Review by simondeziel — DISMISSED** [review]

File: lxd/instances_post.go [hunk 11]
```diff
@@ -1348,13 +1357,28 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
...
 			if err != nil && !api.StatusErrorCheck(err, http.StatusNotFound) {
 				return err
 			}
 
+			// If the image is locally available, private, and from a different project, check if the caller can view it.
+			if sourceImage != nil && localLookupProject != targetProject.Name && !sourceImage.Public {
+				err = s.Authorizer.CheckPermission(r.Context(), entity.ImageURL(localLookupProject, sourceImage.Fingerprint), auth.EntitlementCanView)
+				if err != nil {
+					return err
+				}
```
[the remark this answers is not in the document]
Comment (nmezhenskyi) [reply lxd/instances_post.go]: Updated

File: lxd/instance_rebuild.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (nmezhenskyi) [reply lxd/instance_rebuild.go]: Updated

**Comment by tomponline** [comment]
@markylaing you ok with this one?

**Review by markylaing — DISMISSED** [review]
Smashed it 🥇 

Thanks Nikita

File: lxc/utils.go [hunk 12]
```diff
@@ -378,21 +378,19 @@ func guessImage(conf *config.Config, d lxd.InstanceServer, instRemote string, im
...
 }
 
-// getImgInfo returns an image server and image info for the given image name (given by a user)
-// an image remote and an instance remote.
-func getImgInfo(d lxd.InstanceServer, conf *config.Config, imgRemote string, instRemote string, imageRef string, source *api.InstanceSource) (lxd.ImageServer, *api.Image, error) {
+// getImgInfo returns an image server and image info for the given image name, image remote, and image project.
+// It also populates the passed in InstanceSource struct with the information about the image.
+// If imageProject is provided and the remote is a LXD server, it will be used to locate the image.
+// If remoteTarget is provided and the remote is a LXD server, it will be used to locate the image.
+func getImgInfo(conf *config.Config, imgRemote string, imageRef string, imageProject string, remoteTarget string, source *api.InstanceSource) (lxd.ImageServer, *api.Image, error) {
```
Comment (tomponline) [inline lxc/utils.go]: I'll go through rest of PR but `remoteTarget` caught my eye, as this shouldnt be needed...hrm

File: lxc/init.go [hunk 13]
```diff
@@ -351,8 +351,15 @@ func (c *cmdInit) create(conf *config.Config, args []string, launch bool) (lxd.I
 			image = "default"
 		}
 
+		// Resolve the target cluster member for the image remote.
```
Comment (tomponline) [inline lxc/init.go]: Why is this needed?

File: lxd/instances_post.go [hunk 14]
```diff
@@ -1348,9 +1348,16 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
 			}
 
 		case api.SourceTypeImage:
+			// Resolve the project used for local cache lookup to find the image.
+			localLookupProject := targetProject.Name
+			if req.Source.Server == "" && req.Source.Project != "" {
+				// For local images, if a source project is explicitly provided, use it to locate the image.
```
Comment (tomponline) [inline lxd/instances_post.go]: why do we need this special case handling for local images and not remote images when `req.Source.Project != ""`?

File: lxd/instance_rebuild.go [hunk 15]
```diff
@@ -114,8 +114,15 @@ func instanceRebuildPost(d *Daemon, r *http.Request) response.Response {
 			return fmt.Errorf("Failed loading instance: %w", err)
 		}
 
+		// Resolve the project used for local cache lookup to find the image.
+		localLookupProject := targetProject.Name
+		if req.Source.Server == "" && req.Source.Project != "" {
```
Comment (tomponline) [inline lxd/instance_rebuild.go]: I've my doubts this special case is needed, but if it turns out it does, we should de-dupe this logic into a separate function called from both sites.

File: lxd/instance_rebuild.go [hunk 16]
```diff
@@ -126,6 +128,23 @@ func instanceRebuildPost(d *Daemon, r *http.Request) response.Response {
 			if err != nil && !api.StatusErrorCheck(err, http.StatusNotFound) {
 				return err
 			}
+
+			// If the image is locally available, private, and from a different project, check if the caller can view it.
+			if sourceImage != nil && localLookupProject != targetProject.Name && !sourceImage.Public {
```
Comment (tomponline) [inline lxd/instance_rebuild.go]: can we de-dupe this logic into a function too?

**Review by tomponline — COMMENTED** [review]
Thanks for this @nmezhenskyi 

Aside from a couple of de-dupe suggestions, my main questions are:

1. Why do we need the client to specify the target for an image?
2. Why do we need the special case handling of local image projects, as opposed to general project handling for local and non-local alike?

File: lxc/utils.go (hunk 12 above)
Comment (nmezhenskyi) [reply lxc/utils.go]: You are right, this is unnecessary. I've removed this bit.

I got a little confused because we previously reused the same connection for both the instance server and the image server when referring to a local image, so I thought this bit was needed.

File: lxc/init.go (hunk 13 above)
Comment (nmezhenskyi) [reply lxc/init.go]: I've removed this

File: lxd/instances_post.go (hunk 14 above)
Comment (nmezhenskyi) [reply lxd/instances_post.go]: There are two functions in play that cause this: `getSourceImageFromInstanceSource()` and `createFromImage()`.

The `getSourceImageFromInstanceSource()` function resolves the image metadata for an image that is already cached. It also returns a hash to be used for instance creation. Remote images would use the instance target project to lookup if the image is available locally. As I understand, this is done to ensure that the associated image profiles would automatically get associated with the instance. If an image is not available in that target project, that's not a big deal because then `createFromImage()` function would simply download the image into that project using the specified image server.

The `createFromImage()` function expects either a remote server to be specified for image download, or an image metadata for finding and using the local image. 

So, when a local image is specified and the `getSourceImageFromInstanceSource()` fails to find and fetch the local image metadata (because it is searching in the wrong project), it will return `nil` which will end up all the way inside the `createFromImage()` function. As a result, `createFromImage()` would return the `Image not provided for instance creation` error.

**Review by tomponline — CHANGES_REQUESTED** [review]
Thanks - lets please de-dupe those 2 new special pieces of server side logic.

File: lxd/instance_rebuild.go (hunk 15 above)
Comment (nmezhenskyi) [reply lxd/instance_rebuild.go]: Updated, I moved this logic into the new function `resolveSourceImageFromCache()`.

File: lxd/instance_rebuild.go (hunk 16 above)
Comment (nmezhenskyi) [reply lxd/instance_rebuild.go]: Updated, I moved this logic into the new function `resolveSourceImageFromCache()`.

**Review by tomponline — APPROVED** [review]
Ta
