### PR TITLE
Check instance name early to fail fast on instance creation and prevent image download

### LINKED ISSUE #12554: `lxc launch` doesn't immediately fail on duplicated instance name if the source image is not cached
If you already have an instance named `foo`, trying to created another one with the same name will not immediately fail if the source is not cached.

Steps to reproduce:

```
$ fingerprint="$(lxc image list -f csv -c lf ubuntu-daily:24.04 type=container | head -n1 | cut -d, -f2)"

$ lxc init "ubuntu-daily:$fingerprint" foo   # create instance and populate local image cache
Creating foo
$ lxc init "ubuntu-daily:$fingerprint" foo   # fail early, good
Creating foo
Error: Failed creating instance record: Add instance info to the database: This "instances" entry already exists

$ lxc image delete "local:$fingerprint"    # remove the locally cached image


$ lxc init "ubuntu-daily:$fingerprint" foo  # fails late after retrieving the image
Creating foo
Retrieving image: metadata: 100% (1.21GB/s)
Retrieving image: rootfs: 1% (2.86MB/s)     
...
Error: Failed creating instance record: Add instance info to the database: This "instances" entry already exists
```

Ideally, the check for duplicated name should be done prior to doing the expensive image fetch.

### PR DESCRIPTION
**Pull request by kadinsayani**
Fixes #12554.

This fix uses uses `GetInstanceID()` so we don't fetch all instances and risk an expensive query on a non-leader node.

### CODE REVIEW

File: lxd/instances_post.go [hunk 1]
```diff
@@ -91,6 +91,26 @@ func createFromImage(ctx context.Context, s *state.State, p api.Project, profile
 		return response.BadRequest(err)
 	}
 
+	err = s.DB.Cluster.Transaction(ctx, func(ctx context.Context, tx *db.ClusterTx) error {
+		// Check that the name isn't already in use.
+		existingID, err := tx.GetInstanceID(ctx, p.Name, req.Name)
+		if err != nil {
```
Comment (tomponline) [inline lxd/instances_post.go]: api.StatusErrorCheck

**Review by tomponline — CHANGES_REQUESTED** [review]
Although cluster move tests failing - because the instance already exists for an intra-cluster move.

**Comment by simondeziel** [comment]
This seems to be lighter than what was initially proposed in #12626 but I'm still concerned by the additional DB query (see https://github.com/canonical/lxd/pull/12626#pullrequestreview-1830131051). Do I understand that currently, LXD only consults the DB once it is ready to expand an image into an instance?

If so, maybe the issue would be better closed as "won't fix, works as expected/designed"?

**Comment by tomponline** [comment]
> This seems to be lighter than what was initially proposed in #12626 but I'm still concerned by the additional DB query (see [#12626 (review)](https://github.com/canonical/lxd/pull/12626#pullrequestreview-1830131051)). Do I understand that currently, LXD only consults the DB once it is ready to expand an image into an instance?
> 
> If so, maybe the issue would be better closed as "won't fix, works as expected/designed"?

This is true, it will incur a cost, but is much reduced from the original proposal as it's reuses an existing transaction and only gets the ID.

So I'm ok with that cost for the benefit of better user experience.

File: lxd/instances_post.go [hunk 2]
```diff
@@ -1247,6 +1247,16 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
 			return err
 		}
 
+		// Check that the name isn't already in use.
+		if !req.Source.Refresh && !clusterNotification && req.Source.Source == "" {
+			existingID, err := tx.GetInstanceID(ctx, targetProjectName, req.Name)
+			if err != nil && !api.StatusErrorCheck(err, http.StatusNotFound) {
+				return fmt.Errorf("Failed checking for existing instance: %w", err)
+			} else if existingID > 0 {
+				return api.StatusErrorf(http.StatusConflict, "Failed creating instance record: Instance %q already exists", req.Name)
```
Comment (tomponline) [inline lxd/instances_post.go]: Can we drop the "Failed creating instance record" prefix?

File: lxd/instances_post.go [hunk 3]
```diff
@@ -1247,6 +1247,16 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
 			return err
 		}
 
+		// Check that the name isn't already in use.
+		if !req.Source.Refresh && !clusterNotification && req.Source.Source == "" {
```
Comment (tomponline) [inline lxd/instances_post.go:1252]: can you add a comment here explaining why the logic is here?

**Comment by tomponline** [comment]
DCO checks failing

**Comment by kadinsayani** [comment]
> DCO checks failing

Oops, hopping between dev environments. Should be good now.

**Review by tomponline — APPROVED** [review]
