### PR TITLE
lxd: Check project permissions when importing from backup

### LINKED ISSUE #11958: lxc import doesn't check project limits
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:

```
$ lxc info               
config:
  cluster.https_address: 10.11.15.24:8443
  core.https_address: 10.11.15.24:8443
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
- clustering_update_cert
- storage_api_project
- server_instance_driver_operational
- server_supported_storage_drivers
- event_lifecycle_requestor_address
- resources_gpu_usb
- clustering_evacuation
- network_ovn_nat_address
- network_bgp
- network_forward
- custom_volume_refresh
- network_counters_errors_dropped
- metrics
- image_source_project
- clustering_config
- network_peer
- linux_sysctl
- network_dns
- ovn_nic_acceleration
- certificate_self_renewal
- instance_project_move
- storage_volume_project_move
- cloud_init
- network_dns_nat
- database_leader
- instance_all_projects
- clustering_groups
- ceph_rbd_du
- instance_get_full
- qemu_metrics
- gpu_mig_uuid
- event_project
- clustering_evacuation_live
- instance_allow_inconsistent_copy
- network_state_ovn
- storage_volume_api_filtering
- image_restrictions
- storage_zfs_export
- network_dns_records
- storage_zfs_reserve_space
- network_acl_log
- storage_zfs_blocksize
- metrics_cpu_seconds
- instance_snapshot_never
- certificate_token
- instance_nic_routed_neighbor_probe
- event_hub
- agent_nic_config
- projects_restricted_intercept
- metrics_authentication
- images_target_project
- cluster_migration_inconsistent_copy
- cluster_ovn_chassis
- container_syscall_intercept_sched_setscheduler
- storage_lvm_thinpool_metadata_size
- storage_volume_state_total
- instance_file_head
- instances_nic_host_name
- image_copy_profile
- container_syscall_intercept_sysinfo
- clustering_evacuation_mode
- resources_pci_vpd
- qemu_raw_conf
- storage_cephfs_fscache
- network_load_balancer
- vsock_api
- instance_ready_state
- network_bgp_holdtime
- storage_volumes_all_projects
- metrics_memory_oom_total
- storage_buckets
- storage_buckets_create_credentials
- metrics_cpu_effective_total
- projects_networks_restricted_access
- storage_buckets_local
- loki
- acme
- internal_metrics
- cluster_join_token_expiry
- remote_token_expiry
- init_preseed
- storage_volumes_created_at
- cpu_hotplug
- projects_networks_zones
- network_txqueuelen
- cluster_member_state
- instances_placement_scriptlet
- storage_pool_source_wipe
- zfs_block_mode
- instance_generation_id
- disk_io_cache
- amd_sev
- storage_pool_loop_resize
- migration_vm_live
- ovn_nic_nesting
- oidc
- network_ovn_l3only
- ovn_nic_acceleration_vdpa
- cluster_healing
- instances_state_total
- auth_user
- security_csm
- instances_rebuild
- numa_cpu_placement
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
auth_user_name: <removed>
auth_user_method: tls
environment:
  addresses:
  - 10.11.15.24:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
<removed>
    -----END CERTIFICATE-----
  certificate_fingerprint: <removed>
  driver: lxc
  driver_version: 5.0.2
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.15.0-73-generic
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "22.04"
  project: bug-test
  server: lxd
  server_clustered: true
  server_event_mode: hub-server
  server_name: compartilhado01
  server_pid: 369392
  server_version: "5.15"
  storage: btrfs
  storage_version: 5.16.2
  storage_supported_drivers:
  - name: zfs
    version: 2.1.5-1ubuntu6~22.04.1
    remote: false
  - name: btrfs
    version: 5.16.2
    remote: false
  - name: ceph
    version: 17.2.5
    remote: true
  - name: cephfs
    version: 17.2.5
    remote: true
  - name: cephobject
    version: 17.2.5
    remote: true
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.11(2) (2021-01-08) / 1.02.175 (2021-01-08) / 4.45.0
    remote: false
```

# Issue description

When launching a new container, project limits are checked and new instance creation over project limits is blocked. When this happens, one can use `lxc import` to create new instances over the project limits. Limits should be checked for import as well.

# Steps to reproduce

 1. Create project and set limits (tested with limits.cpu and limits.memory)
 2. Create images until limit is reached
 3. Use 'lxc export' to create an image for one of the containers
 4. Use 'lxc import' as many times as needed to import many containers over project limits

# Information to attach
 
 - [ ] 
 ```
$ lxc project show bug-test
config:
  features.images: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
  limits.cpu: "3"
  limits.memory: 3GiB
  limits.virtual-machines: "0"
  restricted: "true"
  restricted.backups: allow
  restricted.cluster.groups: compartilhado
  restricted.cluster.target: allow
  restricted.devices.nic: allow
description: ""
name: bug-test
used_by:
- /1.0/instances/a0?project=bug-test
- /1.0/instances/a1?project=bug-test
- /1.0/instances/a2?project=bug-test
- /1.0/instances/a3?project=bug-test
- /1.0/instances/a4?project=bug-test
- /1.0/instances/a5?project=bug-test
- /1.0/instances/a6?project=bug-test
- /1.0/profiles/default?project=bug-test
- /1.0/images/bea263b3678d3f4500c1ebad9f1198ccad20f6a9065847400cd35e2c144aaa06?project=bug-test
 ```
 - [ ] 
```
$ lxc profile show default 
config:
  cloud-init.vendor-data: |-
    #cloud-config
    package_update: true
    package_upgrade: true
    timezone: America/Fortaleza
  limits.cpu: "1"
  limits.memory: 1GiB
description: Default LXD profile for project compartilhado
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: local
    type: disk
name: default
used_by:
- /1.0/instances/a0?project=bug-test
- /1.0/instances/a1?project=bug-test
- /1.0/instances/a2?project=bug-test
- /1.0/instances/a3?project=bug-test
- /1.0/instances/a4?project=bug-test
- /1.0/instances/a5?project=bug-test
- /1.0/instances/a6?project=bug-test
```
 - [ ] 
```
$ lxc config show a0
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine 3.18 amd64 (20230706_13:00)
  image.os: Alpine
  image.release: "3.18"
  image.requirements.secureboot: "false"
  image.serial: "20230706_13:00"
  image.type: squashfs
  image.variant: cloud
  volatile.base_image: bea263b3678d3f4500c1ebad9f1198ccad20f6a9065847400cd35e2c144aaa06
  volatile.cloud-init.instance-id: 8d06d584-bc1a-43d3-8d9b-8836e6ed0312
  volatile.eth0.host_name: veth3c54e220
  volatile.eth0.hwaddr: 00:16:3e:db:88:1e
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: d3b327a4-b5d9-46f1-8961-2154db096603
  volatile.uuid.generation: d3b327a4-b5d9-46f1-8961-2154db096603
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [ ] 
```
$ lxc config show a1
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine 3.18 amd64 (20230706_13:00)
  image.os: Alpine
  image.release: "3.18"
  image.requirements.secureboot: "false"
  image.serial: "20230706_13:00"
  image.type: squashfs
  image.variant: cloud
  volatile.base_image: bea263b3678d3f4500c1ebad9f1198ccad20f6a9065847400cd35e2c144aaa06
  volatile.cloud-init.instance-id: b5a95073-94a3-4994-aec3-0fa6d9d0ed4d
  volatile.eth0.host_name: vethc1db90e6
  volatile.eth0.hwaddr: 00:16:3e:63:2b:7f
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 053885ba-ab45-45a7-a641-3fc987e3b4cb
  volatile.uuid.generation: 053885ba-ab45-45a7-a641-3fc987e3b4cb
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [ ] 
```
$ lxc config show a2
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine 3.18 amd64 (20230706_13:00)
  image.os: Alpine
  image.release: "3.18"
  image.requirements.secureboot: "false"
  image.serial: "20230706_13:00"
  image.type: squashfs
  image.variant: cloud
  volatile.base_image: bea263b3678d3f4500c1ebad9f1198ccad20f6a9065847400cd35e2c144aaa06
  volatile.cloud-init.instance-id: fd700abf-303d-47f5-b737-90b857b714a7
  volatile.eth0.host_name: vethcba23f5b
  volatile.eth0.hwaddr: 00:16:3e:b9:c5:f2
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 30806a2e-43c7-4c92-8344-cd888eefc372
  volatile.uuid.generation: 30806a2e-43c7-4c92-8344-cd888eefc372
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [ ] 
```
$ lxc config show a3
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine 3.18 amd64 (20230706_13:00)
  image.os: Alpine
  image.release: "3.18"
  image.requirements.secureboot: "false"
  image.serial: "20230706_13:00"
  image.type: squashfs
  image.variant: cloud
  volatile.base_image: bea263b3678d3f4500c1ebad9f1198ccad20f6a9065847400cd35e2c144aaa06
  volatile.cloud-init.instance-id: 8d06d584-bc1a-43d3-8d9b-8836e6ed0312
  volatile.eth0.host_name: vethe07ab0c6
  volatile.eth0.hwaddr: 00:16:3e:db:88:1e
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: d3b327a4-b5d9-46f1-8961-2154db096603
  volatile.uuid.generation: d3b327a4-b5d9-46f1-8961-2154db096603
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [ ] 
```
$ lxc config show a4
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine 3.18 amd64 (20230706_13:00)
  image.os: Alpine
  image.release: "3.18"
  image.requirements.secureboot: "false"
  image.serial: "20230706_13:00"
  image.type: squashfs
  image.variant: cloud
  volatile.base_image: bea263b3678d3f4500c1ebad9f1198ccad20f6a9065847400cd35e2c144aaa06
  volatile.cloud-init.instance-id: 8d06d584-bc1a-43d3-8d9b-8836e6ed0312
  volatile.eth0.host_name: veth39cbf153
  volatile.eth0.hwaddr: 00:16:3e:db:88:1e
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: d3b327a4-b5d9-46f1-8961-2154db096603
  volatile.uuid.generation: d3b327a4-b5d9-46f1-8961-2154db096603
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [ ] 
```
$ lxc config show a5
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine 3.18 amd64 (20230706_13:00)
  image.os: Alpine
  image.release: "3.18"
  image.requirements.secureboot: "false"
  image.serial: "20230706_13:00"
  image.type: squashfs
  image.variant: cloud
  volatile.base_image: bea263b3678d3f4500c1ebad9f1198ccad20f6a9065847400cd35e2c144aaa06
  volatile.cloud-init.instance-id: 8d06d584-bc1a-43d3-8d9b-8836e6ed0312
  volatile.eth0.host_name: veth8a986d61
  volatile.eth0.hwaddr: 00:16:3e:db:88:1e
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: d3b327a4-b5d9-46f1-8961-2154db096603
  volatile.uuid.generation: d3b327a4-b5d9-46f1-8961-2154db096603
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [ ] 
```
$ lxc config show a6
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine 3.18 amd64 (20230706_13:00)
  image.os: Alpine
  image.release: "3.18"
  image.requirements.secureboot: "false"
  image.serial: "20230706_13:00"
  image.type: squashfs
  image.variant: cloud
  volatile.base_image: bea263b3678d3f4500c1ebad9f1198ccad20f6a9065847400cd35e2c144aaa06
  volatile.cloud-init.instance-id: 8d06d584-bc1a-43d3-8d9b-8836e6ed0312
  volatile.eth0.host_name: vethfbae70b8
  volatile.eth0.hwaddr: 00:16:3e:db:88:1e
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: d3b327a4-b5d9-46f1-8961-2154db096603
  volatile.uuid.generation: d3b327a4-b5d9-46f1-8961-2154db096603
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [ ] 
```
$ lxc list
+------+---------+---------------------+------+-----------+-----------+-----------------+
| NAME |  STATE  |        IPV4         | IPV6 |   TYPE    | SNAPSHOTS |    LOCATION     |
+------+---------+---------------------+------+-----------+-----------+-----------------+
| a0   | RUNNING | 10.11.12.26 (eth0)  |      | CONTAINER | 0         | compartilhado02 |
+------+---------+---------------------+------+-----------+-----------+-----------------+
| a1   | RUNNING | 10.11.12.188 (eth0) |      | CONTAINER | 0         | compartilhado03 |
+------+---------+---------------------+------+-----------+-----------+-----------------+
| a2   | RUNNING | 10.11.12.177 (eth0) |      | CONTAINER | 0         | compartilhado01 |
+------+---------+---------------------+------+-----------+-----------+-----------------+
| a3   | RUNNING | 10.11.12.26 (eth0)  |      | CONTAINER | 0         | compartilhado01 |
+------+---------+---------------------+------+-----------+-----------+-----------------+
| a4   | RUNNING | 10.11.12.26 (eth0)  |      | CONTAINER | 0         | compartilhado01 |
+------+---------+---------------------+------+-----------+-----------+-----------------+
| a5   | RUNNING | 10.11.12.26 (eth0)  |      | CONTAINER | 0         | compartilhado01 |
+------+---------+---------------------+------+-----------+-----------+-----------------+
| a6   | RUNNING | 10.11.12.26 (eth0)  |      | CONTAINER | 0         | compartilhado01 |
+------+---------+---------------------+------+-----------+-----------+-----------------+
```
 - [ ] Containers a0, a1 and a2 were created with `lxc launch`. The remaining ones were imported from an exported copy of a0.

### PR DESCRIPTION
**Pull request by monstermunchkin**
Fixes #11958

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

### CODE REVIEW

File: lxd/instances_post.go [hunk 1]
```diff
@@ -627,6 +627,21 @@ func createFromBackup(s *state.State, r *http.Request, projectName string, data
 		return response.BadRequest(err)
 	}
 
+	// Check project permissions.
+	err = s.DB.Cluster.Transaction(s.ShutdownCtx, func(ctx context.Context, tx *db.ClusterTx) error {
```
Comment (roosterfish) [inline lxd/instances_post.go:631]: I see `r.Context()` more often for the transactions. Any specific reason for picking one over the other? Just curious.

**Review by roosterfish — APPROVED** [review]
Looks good!

File: lxd/instances_post.go (hunk 1 above)
Comment (tomponline) [reply lxd/instances_post.go:631]: In cases where the original request is ended quickly and a background operation is created it is not possible to use r.Context() and so s.ShutdownCtx is the next best thing.

Comment (tomponline) [reply lxd/instances_post.go:631]: A possible future improvement is to be able to get a context.Context from the operation itself and pass it here, so that if the operation is cancelled it cancels this transaction etc.

Comment (roosterfish) [reply lxd/instances_post.go:631]: I see, thanks for the clarifications.
