### PR TITLE
lxd/storage/drivers/zfs: Fix content type detection for custom block volumes

### LINKED ISSUE #11984: lxd recover : 'mountpoint' does not apply to datasets of this type.
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 20.04 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-153-generic
   * LXC version: 5.15-002fa0f
   * LXD version: 5.15-002fa0f
   * Storage backend in use: ZFS

# Issue description

I lost my os disk recently, so I reinstall ubuntu with lxd on a new disk. I was trying to use `lxd recover` command to restore my data zfs pool. all containers, vm are here on the zfs pool named `data`.

```
root@rvh-1:/var/snap/lxd/common/lxd/storage-pools/data/containers# lxd recover
This LXD server currently has the following storage pools:
Would you like to recover another storage pool? (yes/no) [default=no]: yes
Name of the storage pool: data
Name of the storage backend (btrfs, ceph, cephfs, cephobject, dir, lvm, zfs): zfs
Source of the storage pool (block device, volume group, dataset, path, ... as applicable): data
Additional storage pool configuration property (KEY=VALUE, empty when done): zfs.pool_name=data
Additional storage pool configuration property (KEY=VALUE, empty when done): 
Would you like to recover another storage pool? (yes/no) [default=no]: 
The recovery process will be scanning the following storage pools:
 - NEW: "data" (backend="zfs", source="data")
Would you like to continue with scanning for lost volumes? (yes/no) [default=yes]: 
Scanning for unknown volumes...
Error: Failed validation request: Failed checking volumes on pool "data": Failed to run: zfs set mountpoint=legacy canmount=noauto data/custom/default_rvh2-epbackup: exit status 1 (cannot set property for 'data/custom/default_rvh2-epbackup': 'mountpoint' does not apply to datasets of this type)
```

`data/custom/default_rvh2-epbackup` is a custom volume of zfs, I use this volume to attach to one of my vm.

It seems that LXD is trying to execute a command which is not supported by ZFS? 

my `zfs list`: 
image

### PR DESCRIPTION
**Pull request by monstermunchkin**
This fixes an issue where custom block volumes would be listed as
datasets instead of volumes.

Fixes #11984

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

### CODE REVIEW

File: lxd/storage/drivers/driver_zfs_volumes.go [hunk 1]
```diff
@@ -1842,16 +1842,19 @@ func (d *zfs) ListVolumes() ([]Volume, error) {
 			continue // Ignore unrecognised volume.
 		}
 
-		// Detect if a volume is block content type using both the defined suffix and the dataset type.
-		isBlock := strings.HasSuffix(volName, zfsBlockVolSuffix) && zfsContentType == "volume"
+		// Detect if a volume is block content type using only the dataset type.
+		isBlock := zfsContentType == "volume"
```
Comment (tomponline) [inline lxd/storage/drivers/driver_zfs_volumes.go:1846]: @monstermunchkin did custom block volumes not use the .block suffix ever? or did that change recently?

Comment (monstermunchkin) [reply lxd/storage/drivers/driver_zfs_volumes.go:1846]: They never have. That's only for VMs as they have two datasets/volumes.

Comment (monstermunchkin) [reply lxd/storage/drivers/driver_zfs_volumes.go:1846]: > Does this function support detecting filesystem volumes with zfs.block_mode=true?

No, this function only takes the output of `zfs list`. `zfs.block_mode` is a LXD config key and is therefore unknown by this function. There's also no need for this config key as it wouldn't change anything.

Comment (monstermunchkin) [reply lxd/storage/drivers/driver_zfs_volumes.go:1846]: What this function does not support is listing custom ISO volumes. That is because they follow the same naming schema as custom block volumes. We might want to change this in the future, by suffixing ISOs with `.iso` or something.

Comment (tomponline) [reply lxd/storage/drivers/driver_zfs_volumes.go:1846]: > No, this function only takes the output of `zfs list`. `zfs.block_mode` is a LXD config key and is therefore unknown by this function. There's also no need for this config key as it wouldn't change anything.

But those filesystem block volumes would be unusable after recovery though right?

Comment (tomponline) [reply lxd/storage/drivers/driver_zfs_volumes.go:1846]: > What this function does not support is listing custom ISO volumes. That is because they follow the same naming schema as custom block volumes. We might want to change this in the future, by suffixing ISOs with `.iso` or something.

hrm yeah can you open an issue and assign that to you to sort out please.

Comment (monstermunchkin) [reply lxd/storage/drivers/driver_zfs_volumes.go:1846]: > But those filesystem block volumes would be unusable after recovery though right?

Oh, I see what you mean, and you're right. As a workaround, we could do `lxc storage volume set zfs vol1 zfs.block_mode=true`, right?

Comment (tomponline) [reply lxd/storage/drivers/driver_zfs_volumes.go:1846]: I dont think you can do that on a volume once it created - if you can thats a bug.

Comment (tomponline) [reply lxd/storage/drivers/driver_zfs_volumes.go:1846]: We probably need to have a content type suffix for those volumes too

**Comment by tomponline** [comment]
@monstermunchkin would it be possible to update the lxd recover tests to check for block volume support?

**Comment by monstermunchkin** [comment]
> would it be possible to update the lxd recover tests to check for block volume support?

Yes, that should be possible.

I just came across [User Properties](https://openzfs.github.io/openzfs-docs/man/7/zfsprops.7.html#User_Properties) which might be interesting in the way we name our datasets and volumes. We could add the `lxd:content_type` (`filesystem`, `block`, `iso`) and `lxd:block_filesystem` properties to annotate our datasets and volumes. This would allow us to distinguish between custom block volumes and custom ISO volumes, and also detect `zfs.block_mode`.

**Comment by tomponline** [comment]
> 

Sounds very interesting indeed! Just need to check it works with the versions of ZFS we support.

**Comment by tomponline** [comment]
Is this awaiting review or should it be in draft? ZFS tests seem to have failed.

**Comment by monstermunchkin** [comment]
This is ready for review. ZFS tests are failing in migration. Don't know why though.

@tomponline Could you restart the tests?

**Comment by tomponline** [comment]
Please can you rebase and that will trigger it too

**Review by tomponline — APPROVED** [review]
Thanks!
