### PR TITLE
Set `lxd:content_type` user property on zfs volumes

### LINKED ISSUE #11997: lxd recover: Unable to recover custom block volumes with `zfs.block_mode` enabled
# Required information

 * Distribution: Ubuntu
 * Distribution version: 23.04 (Lunar Lobster)
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.2.0-24-generic
   * LXC version: 5.15
   * LXD version: 5.15
   * Storage backend in use: zfs

# Issue description

When recovering custom block volumes which have `zfs.block_mode` enabled, they are recovered as normal custom block volumes with content type `block` instead of `filesystem`.

# Steps to reproduce

 1. Create custom block volume with `zfs.block_mode=true`
 2. Delete database entry of custom block volume
 3. Run `lxd recover`
 4. The recovered custom block volume is listed with content type `block`

### PR DESCRIPTION
**Pull request by monstermunchkin**
Fixes #11997

### CODE REVIEW

**Comment by tomponline** [comment]
Tests failing

**Comment by tomponline** [comment]
Please can you rebase also

File: lxd/storage/drivers/driver_zfs_volumes.go [hunk 1]
```diff
@@ -1873,7 +1873,17 @@ func (d *zfs) ListVolumes() ([]Volume, error) {
 			v := NewVolume(d, d.name, volType, contentType, volName, make(map[string]string), d.config)
 
 			if isBlock {
-				v.SetMountFilesystemProbe(true)
+				// Get correct content type from lxd:content_type property.
+				contentType, err := d.getDatasetProperty(zfsVolName, "lxd:content_type")
```
Comment (tomponline) [inline lxd/storage/drivers/driver_zfs_volumes.go:1877]: Can we somehow pull that property as part of the list command, otherwise we are going to be running potentially a lot of commands if there are a lot of block volumes?

File: lxd/patches.go [hunk 2]
```diff
@@ -840,4 +841,73 @@ func patchStorageRenameCustomISOBlockVolumes(name string, d *Daemon) error {
...
+	err = s.DB.Cluster.Transaction(s.ShutdownCtx, func(ctx context.Context, tx *db.ClusterTx) error {
+		for _, pool := range pools {
+			// Get storage pool ID.
+			poolID, err := tx.GetStoragePoolID(ctx, pool)
+			if err != nil {
+				return fmt.Errorf("Failed getting storage pool ID of pool %q: %w", pool, err)
+			}
+
+			// Get the pool's custom storage volumes.
+			customVolumes, err := tx.GetStoragePoolVolumes(ctx, poolID, false, db.StorageVolumeFilter{Type: &volTypeCustom})
```
Comment (tomponline) [inline lxd/patches.go:866]: The earlier commit looked like you were setting the content type user property into all block backed volumes.
But this patch seems to be only applying it to all custom volumes (even filesystem ones), but not instance volumes.

So there looks like a bit if an inconsistency here. I'm not sure which part is wrong though.

Comment (monstermunchkin) [reply lxd/patches.go:866]: I've changed it so that only custom volumes will have the `lxd:content_type` user property.

**Review by tomponline — APPROVED** [review]
LGTM!
