### PR TITLE
api: On file push to containers, only change uid/gid if it fits within uidmap range

### LINKED ISSUE #15368: lxc file push fails with SSH_FX_FAILURE
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

Ubuntu

### Distribution version

24.04

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
Name    Version      Rev    Tracking       Publisher   Notes
core20  20241206     2496   latest/stable  canonical✓  base
core22  20250110     1748   latest/stable  canonical✓  base,disabled
core22  20250210     1802   latest/stable  canonical✓  base
core24  20241217     739    latest/stable  canonical✓  base
lxd     6.3-f22a395  33085  latest/stable  canonical✓  -
snapd   2.67         23545  latest/stable  canonical✓  snapd,disabled
snapd   2.67.1       23771  latest/stable  canonical✓  snapd
```

### Output of "lxc info" or system info if it fails

```shell
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- backup_compression
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
- clustering_update_cert
- storage_api_project
- server_instance_driver_operational
- server_supported_storage_drivers
- event_lifecycle_requestor_address
- resources_gpu_usb
- clustering_evacuation
- network_ovn_nat_address
- network_bgp
- network_forward
- custom_volume_refresh
- network_counters_errors_dropped
- metrics
- image_source_project
- clustering_config
- network_peer
- linux_sysctl
- network_dns
- ovn_nic_acceleration
- certificate_self_renewal
- instance_project_move
- storage_volume_project_move
- cloud_init
- network_dns_nat
- database_leader
- instance_all_projects
- clustering_groups
- ceph_rbd_du
- instance_get_full
- qemu_metrics
- gpu_mig_uuid
- event_project
- clustering_evacuation_live
- instance_allow_inconsistent_copy
- network_state_ovn
- storage_volume_api_filtering
- image_restrictions
- storage_zfs_export
- network_dns_records
- storage_zfs_reserve_space
- network_acl_log
- storage_zfs_blocksize
- metrics_cpu_seconds
- instance_snapshot_never
- certificate_token
- instance_nic_routed_neighbor_probe
- event_hub
- agent_nic_config
- projects_restricted_intercept
- metrics_authentication
- images_target_project
- cluster_migration_inconsistent_copy
- cluster_ovn_chassis
- container_syscall_intercept_sched_setscheduler
- storage_lvm_thinpool_metadata_size
- storage_volume_state_total
- instance_file_head
- instances_nic_host_name
- image_copy_profile
- container_syscall_intercept_sysinfo
- clustering_evacuation_mode
- resources_pci_vpd
- qemu_raw_conf
- storage_cephfs_fscache
- network_load_balancer
- vsock_api
- instance_ready_state
- network_bgp_holdtime
- storage_volumes_all_projects
- metrics_memory_oom_total
- storage_buckets
- storage_buckets_create_credentials
- metrics_cpu_effective_total
- projects_networks_restricted_access
- storage_buckets_local
- loki
- acme
- internal_metrics
- cluster_join_token_expiry
- remote_token_expiry
- init_preseed
- storage_volumes_created_at
- cpu_hotplug
- projects_networks_zones
- network_txqueuelen
- cluster_member_state
- instances_placement_scriptlet
- storage_pool_source_wipe
- zfs_block_mode
- instance_generation_id
- disk_io_cache
- amd_sev
- storage_pool_loop_resize
- migration_vm_live
- ovn_nic_nesting
- oidc
- network_ovn_l3only
- ovn_nic_acceleration_vdpa
- cluster_healing
- instances_state_total
- auth_user
- security_csm
- instances_rebuild
- numa_cpu_placement
- custom_volume_iso
- network_allocations
- storage_api_remote_volume_snapshot_copy
- zfs_delegate
- operations_get_query_all_projects
- metadata_configuration
- syslog_socket
- event_lifecycle_name_and_project
- instances_nic_limits_priority
- disk_initial_volume_configuration
- operation_wait
- cluster_internal_custom_volume_copy
- disk_io_bus
- storage_cephfs_create_missing
- instance_move_config
- ovn_ssl_config
- init_preseed_storage_volumes
- metrics_instances_count
- server_instance_type_info
- resources_disk_mounted
- server_version_lts
- oidc_groups_claim
- loki_config_instance
- storage_volatile_uuid
- import_instance_devices
- instances_uefi_vars
- instances_migration_stateful
- container_syscall_filtering_allow_deny_syntax
- access_management
- vm_disk_io_limits
- storage_volumes_all
- instances_files_modify_permissions
- image_restriction_nesting
- container_syscall_intercept_finit_module
- device_usb_serial
- network_allocate_external_ips
- explicit_trust_token
- shared_custom_block_volumes
- instance_import_conversion
- instance_create_start
- instance_protection_start
- devlxd_images_vm
- disk_io_bus_virtio_blk
- metrics_api_requests
- projects_limits_disk_pool
- ubuntu_pro_guest_attach
- metadata_configuration_entity_types
- access_management_tls
- network_allocations_ovn_uplink
- network_ovn_uplink_vlan
- state_logical_cpus
- vm_limits_cpu_pin_strategy
- gpu_cdi
- images_all_projects
- metadata_configuration_scope
- unix_device_hotplug_ownership_inherit
- unix_device_hotplug_subsystem_device_option
- storage_ceph_osd_pool_size
- network_get_target
- network_zones_all_projects
- vm_root_volume_attachment
- projects_limits_uplink_ips
- entities_with_entitlements
- profiles_all_projects
- storage_driver_powerflex
- storage_driver_pure
- cloud_init_ssh_keys
- oidc_scopes
- project_default_network_and_storage
- client_cert_presence
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
client_certificate: false
auth_user_name: uid=1522341876
auth_user_method: unix
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIB+jCCAX+gAwIBAgIRAOqhw9JGk9+WVx+uD8maGyMwCgYIKoZIzj0EAwMwKzEM
    MAoGA1UEChMDTFhEMRswGQYDVQQDDBJyb290QGNhbC1mcmFtZXdvcmswHhcNMjUw
    NDExMTYyNDI4WhcNMzUwNDA5MTYyNDI4WjArMQwwCgYDVQQKEwNMWEQxGzAZBgNV
    BAMMEnJvb3RAY2FsLWZyYW1ld29yazB2MBAGByqGSM49AgEGBSuBBAAiA2IABFUc
    iUpZMXnX2EqUWyGvfyf2c7bIEdHiezGQKi6TCsXC83uq8MRrAmPZJ/h4/N57XMFX
    qcgOKCrYIdgUisadPEc0O9+5vPU47HTtW8WONvh+fu/9ueRhKjx+VaCpJ45HkKNn
    MGUwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB
    /wQCMAAwMAYDVR0RBCkwJ4INY2FsLWZyYW1ld29ya4cEfwAAAYcQAAAAAAAAAAAA
    AAAAAAAAATAKBggqhkjOPQQDAwNpADBmAjEA4Q9mRoiUxatLJi3Sem7joWUR1JzM
    0k1/avwB2X6VtgFbeHMuBm2Q30uyXg5JZ1dyAjEAwJufxbJYejhbx17bniu2XoGg
    5gDD21RQn29a05YeyefuLnqcqBeLszYG1DmQDs2g
    -----END CERTIFICATE-----
  certificate_fingerprint: eb9103c317db2f853635117ebfa42888d72fed3a52b9d1e632dedc9fb20123d3
  driver: lxc | qemu
  driver_version: 6.0.3 | 8.2.2
  instance_types:
  - container
  - virtual-machine
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    uevent_injection: "true"
    unpriv_binfmt: "true"
    unpriv_fscaps: "true"
  kernel_version: 6.11.0-21-generic
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "24.04"
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_name: cal-framework
  server_pid: 3275
  server_version: "6.3"
  server_lts: false
  storage: zfs
  storage_version: 2.2.6-1ubuntu1
  storage_supported_drivers:
  - name: lvm
    version: 2.03.16(2) (2022-05-18) / 1.02.185 (2022-05-18) / 4.48.0
    remote: false
  - name: pure
    version: 2.8 (nvme-cli)
    remote: true
  - name: zfs
    version: 2.2.6-1ubuntu1
    remote: false
  - name: btrfs
    version: 6.6.3
    remote: false
  - name: dir
    version: "1"
    remote: false
  - name: cephobject
    version: 19.2.0
    remote: true
  - name: powerflex
    version: 2.8 (nvme-cli)
    remote: true
  - name: ceph
    version: 19.2.0
    remote: true
  - name: cephfs
    version: 19.2.0
    remote: true
```

### Issue description

When I push a file into a container, the file is successfully pushed, but lxc returns an error.  Subsequent pushes to the same destination don't produce an error.

```bash
~> lxc file push test-file c1/root/test-file-1
Error: sftp: "chown /root/test-file-1: invalid argument" (SSH_FX_FAILURE)`
~> lxc file push test-file c1/root/test-file-1
```

I'm using a corporate-provisioned laptop (from Canonical), so I have a high UID. I suspect it's related to the UID because I could only reproduce this when creating an account with a high UID.

### Steps to reproduce

```bash
multipass launch noble --name vm1
multipass shell vm1
> sudo snap install lxd --channel latest/stable
> getent group lxd | grep -qwF "$USER" || sudo usermod -aG lxd "$USER"
> lxd init --auto
> sudo adduser "callahan.kovacs@canonical.com" --allow-bad-names --uid 1522341876
> sudo usermod -aG sudo "callahan.kovacs@canonical.com"
> getent group lxd | grep -qwF "callahan.kovacs@canonical.com" || sudo usermod -aG lxd "callahan.kovacs@canonical.com"
> exit
multipass restart vm1
multipass shell vm1
> su callahan.kovacs@canonical.com
> lxc launch ubuntu:24.04 c1
> cd ~
> touch test.txt
> lxc file push test.txt c1/etc/test1
```

[logs.txt](https://github.com/user-attachments/files/19712351/logs.txt)

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [x] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by skozina**
Fixes #15368

### CODE REVIEW

File: lxd/instance_file.go [hunk 1]
```diff
@@ -501,6 +540,11 @@ func instanceFilePost(s *state.State, inst instance.Instance, path string, r *ht
 
 		// Set file ownership.
 		if !exists || headers.UIDModifyExisting || headers.GIDModifyExisting {
+			err = fixContainerUIDs(inst, headers)
```
Comment (tomponline) [inline lxd/instance_file.go:543]: suggest moving this call down to inside the if statement on line 548 so its not checked if -1 is passed to indicate no change to uid/gid.

File: lxd/instance_file.go [hunk 2]
```diff
@@ -368,6 +370,42 @@ func instanceFileHead(inst instance.Instance, path string) response.Response {
 	})
 }
 
+// For containers we can only run chown/chgrp if target uid/gid is within uidmap allowed range.
+func fixContainerUIDs(inst instance.Instance, headers *shared.LXDFileHeaders) error {
```
Comment (tomponline) [inline lxd/instance_file.go:374]: What do you think about modifying this function so that rather than taking a pointer to headers and modifying it, we accept a non-pointer of the headers, and then we return the effective uid and gid from this function, which can then be used in the `file.Chown` call.

Also the function name could then be changed to something like `effectiveFileOwnership()` ?

File: lxd/instance_file.go (hunk 1 above)
Comment (tomponline) [reply lxd/instance_file.go:543]: we should probably log an info message that we are altering the requested uid/gid too.

File: lxd/instance_file.go [hunk 3]
```diff
@@ -368,6 +370,42 @@ func instanceFileHead(inst instance.Instance, path string) response.Response {
...
+		if !ok {
+			return fmt.Errorf("Invalid instance type")
+		}
+
+		idmapset, err := c.CurrentIdmap()
+		if err != nil {
+			return err
+		}
+
+		if idmapset == nil {
```
Comment (tomponline) [inline lxd/instance_file.go:386]: this is presumably the case for privileged containers right?

File: lxd/instance_file.go [hunk 4]
```diff
@@ -368,6 +370,42 @@ func instanceFileHead(inst instance.Instance, path string) response.Response {
 	})
 }
 
+// For containers we can only run chown/chgrp if target uid/gid is within uidmap allowed range.
+func fixContainerUIDs(inst instance.Instance, headers *shared.LXDFileHeaders) error {
+	if inst.Type() == instancetype.Container {
+		c, ok := inst.(instance.Container)
+		if !ok {
+			return fmt.Errorf("Invalid instance type")
```
Comment (tomponline) [inline lxd/instance_file.go:378]: It'd be nice for support purposes if this ever occurs to logs the inst value with %T to log the type.

**Review by tomponline — CHANGES_REQUESTED** [review]
Please can you add some tests for this too thanks

File: lxd/instance_file.go (hunk 1 above)
Comment (skozina) [reply lxd/instance_file.go]: Thanks! Done both.

File: lxd/instance_file.go (hunk 2 above)
Comment (skozina) [reply lxd/instance_file.go]: I don't want to copy the whole structure, so I've left passing of the pointer. But the function doesn't modify it any more and instead returns the effective uid and gid. Renamed the function as you suggest. Thanks!

File: lxd/instance_file.go (hunk 4 above)
Comment (skozina) [reply lxd/instance_file.go]: Thanks! Added.

**Comment by skozina** [comment]
I'm still working on adding a test case for this, so I'll mark this as a draft meanwhile.

**Comment by skozina** [comment]
Added the test, this is now again ready for review.

File: test/suites/filemanip.sh [hunk 5]
```diff
@@ -19,6 +19,19 @@ test_filemanip() {
   err=$(my_curl -o /dev/null -w "%{http_code}" -X GET "https://${LXD_ADDR}/1.0/containers/filemanip/files?path=/tmp/foo")
   [ "${err}" -eq "404" ]
 
+  myuid=1522341878
+  useradd --uid "${myuid}" myuser
```
Comment (tomponline) [inline test/suites/filemanip.sh:23]: I'm a bit uncomfortable with modifying the system users in a permanent way.
Pretty much everything else in the test suite is either cleared on reboot or stored in the test run's temporary directory.

Did you explore the idea of using a container and copying the `lxc` CLI inside it with a `proxy` device of the LXD server's unix socket?

File: lxd/instance_file.go [hunk 6]
```diff
@@ -368,6 +369,46 @@ func instanceFileHead(inst instance.Instance, path string) response.Response {
 	})
 }
 
+// For containers we can only run chown/chgrp if target uid/gid is within uidmap allowed range.
+func effectiveFileOwnership(inst instance.Instance, headers *shared.LXDFileHeaders) (uid, gid int64, err error) {
+	uid = headers.UID
+	gid = headers.GID
+	if inst.Type() == instancetype.Container {
```
Comment (tomponline) [inline lxd/instance_file.go:377]: just a nit (not a blocker), and surprised the static analysis didnt pick it up, but we tend to prefer "happy path" coding style, e.g. here:

```go
if inst.Type() != instancetype.Container {
 return
}

...
```

Comment (skozina) [reply lxd/instance_file.go]: Thanks! I've changed the code as you suggest.

File: test/suites/filemanip.sh (hunk 5 above)
Comment (tomponline) [reply test/suites/filemanip.sh]: > I just realized that it doesn't matter under which user the `lxc` is called, the only thing which matters is who owns the file which is being pushed.

Hah, indeed, great observation :)

File: lxd/instance_file.go [hunk 7]
```diff
@@ -368,6 +369,48 @@ func instanceFileHead(inst instance.Instance, path string) response.Response {
...
+	}
+
+	idmapranges, err := idmapset.ValidRanges()
+	if len(idmapranges) != 2 {
+		return 0, 0, err
+	}
+
+	for _, idmaprange := range idmapranges {
+		if idmaprange.Isuid && !idmaprange.Contains(headers.UID) {
+			logger.Info(fmt.Sprintf("Requested uid %d not within idmaprange", uid))
```
Comment (tomponline) [inline lxd/instance_file.go:402]: I'm going to merge this PR (thanks!), but these 2 logging lines are problematic because they lack any context:

- Which instance is the error for?
- What operation/action is triggering this log event?

So from an support/admin's perspective its not very helpful.

You've got the `inst` available here, so suggest adding context like this:

```go
l := logger.AddContext(logger.Ctx{"project": inst.Project().Name, "instance": inst.Name()})
l.Info(fmt.Sprintf("Requested uid %d not within idmaprange", uid))
...
l.Info(fmt.Sprintf("Requested gid %d not within idmaprange", gid))
```

Also we tend to follow Go's mantra of upper casing acronyms, so these should be "UID" and "GID" in the log messages.

Finally, it would be great to include info about the file action taking place in the log lines, so I was thinking we pass in the client.File as an argument too, so we can do:

```
l := logger.AddContext(logger.Ctx{"project": inst.Project().Name, "instance": inst.Name(), "file": f.Name()})
```

And with this thought it then occurred to me that if `effectiveFileOwnership` had access to the `client.File`, we could also modify this function to perform the f.Chown call too (after working out the effective file ownership).

So it would be come:

```go
if headers.UID >= 0 || headers.GID >= 0 {
uid, gid, err := applyEffectiveFileOwnership(inst, headers, f)
if err != nil {
    return response.SmartError(err)
}
```

**Review by tomponline — APPROVED** [review]
Thanks, im going to merge, but please see follow up PR suggestion to improve logging context.

File: lxd/instance_file.go (hunk 7 above)
Comment (skozina) [reply lxd/instance_file.go:402]: Thanks for lot of good feedback! I've opened https://github.com/canonical/lxd/pull/15448 to follow up.
