### PR TITLE
lxd: Use instance lock when updating instance

### LINKED ISSUE #12189: `lxc config set` report successful but failed to update value when concurrent
# Required information

 * Distribution: Ubuntu
 * Distribution version: 23.04 / 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.2.0-27-generic
   * LXC version: 5.15
   * LXD version: 5.15
   * Storage backend in use: zfs

# Issue description

When concurrent update an instance configuration using `lxc config set`, it randomly return one command successes and one failed, but the two `config set` both failed to update the config.

# Steps to reproduce

 1. Set up two process repeat `config set` that increase the number, and check if the value is there after. 
 2. It suppose one of them failed to update with `ETag doesn't match`
 3. But randomly the one report successful did not able to update the value.

(We will try create a script to reproduce it, since the error happened in CI)

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by monstermunchkin**
This adds an instance lock when updating instances so that an instance
cannot be updated concurrently.

When trying to change the instance config concurrently, only one call
will succeed, the others will return an etag missmatch error.

Fixes #12189

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

### CODE REVIEW

File: lxd/instance.go [hunk 1]
```diff
@@ -730,3 +731,12 @@ func getSourceImageFromInstanceSource(ctx context.Context, s *state.State, tx *d
...
 	return sourceImage, nil
 }
+
+// instanceOperationLock acquires a lock for operating on an instance and returns the unlock function.
+func instanceOperationLock(instanceName string) locking.UnlockFunc {
+	l := logger.AddContext(logger.Ctx{"name": instanceName})
+	l.Debug("Acquiring lock for instance")
+	defer l.Debug("Lock acquired for instance")
+
+	return locking.Lock(context.TODO(), fmt.Sprintf("InstanceOperation_%s", instanceName))
```
Comment (tomponline) [inline lxd/instance.go:741]: Should accept a ctx argument too and pass it here.

File: lxd/instance.go [hunk 2]
```diff
@@ -730,3 +731,12 @@ func getSourceImageFromInstanceSource(ctx context.Context, s *state.State, tx *d
 
 	return sourceImage, nil
 }
+
+// instanceOperationLock acquires a lock for operating on an instance and returns the unlock function.
+func instanceOperationLock(ctx context.Context, projectName string, instanceName string) locking.UnlockFunc {
+	l := logger.AddContext(logger.Ctx{"project": projectName, "name": instanceName})
```
Comment (tomponline) [inline lxd/instance.go:737]: We normally use:

```
logger.Ctx{"project": inst.Project().Name, "instance": inst.Name()}
```

Rather than `name` for instance name.

**Review by tomponline — APPROVED** [review]
