### PR TITLE
lxd: remove legacy ZFS bucket datasets at startup and pool deletion

### LINKED ISSUE #18136: Local bucket feature removal prevents remove of ZFS pools
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

Ubuntu

### Distribution version

24.04

### Output of `snap list --all lxd core20 core22 core24 snapd`

```shell
Originally running: lxd 6.7-d814d89 from latest/stable
Upgraded to: git-01754d1 from latest/edge
```

### System info

N/A

### Instance log

N/A

### Expected behavior

LXD 6.8 removes MinIO local bucket support (https://github.com/canonical/lxd/pull/17673).

However the removal doesn't clean up some ZFS datasets which subsequently prevents removal of ZFS pools.

Please check to ensure other storage drivers are not similarly affected too.

### Actual behavior

`lxc storage remove <pool>` should work after upgrading to LXD 6.8 on latest/edge after having previously deployed pools on LXD 6.7.

### Steps to reproduce

1. Deploy LXD 6.7 and create a ZFS storage pool.
2. Refresh to latest/edge
3. Try to remove storage pool using `lxc storage remove <pool>`.

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance configuration (`lxc config show <instance> --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] If a lxc command fails, output of the command with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by simondeziel**
Fixes https://github.com/canonical/lxd/issues/18136 and add system tests.

### CODE REVIEW

File: test/suites/storage_driver_zfs.sh [hunk 1]
```diff
@@ -463,3 +464,54 @@ do_recursive_copy_snapshot_cleanup() {
...
+  local storage_pool
+  storage_pool="lxdtest-$(basename "${LXD_DIR}")"
+
+  sub_test "Verify pool deletion succeeds with legacy bucket datasets present"
+
+  lxc storage create "${storage_pool}-buckets-test" zfs
+
+  # Determine the underlying ZFS pool name used by LXD.
+  zfs_pool="$(lxc storage get "${storage_pool}-buckets-test" zfs.pool_name)"
+
```
[the remark this answers is not in the document]
Comment (simondeziel) [reply test/suites/storage_driver_zfs.sh]: OK for the `local` use but it's probably not worth using a fallback.

File: lxd/storage/drivers/driver_zfs.go [hunk 2]
```diff
@@ -422,13 +423,22 @@ func (d *zfs) Delete(progressReporter ioprogress.ProgressReporter) error {
 	}
 
 	initialDatasets := d.initialDatasets()
+
+	// Legacy datasets from before local storage bucket support was dropped.
+	// These are safe to ignore here as they will be destroyed by the zpool/zfs destroy call below.
+	legacyDatasets := []string{"buckets", "deleted/buckets"}
```
Comment (tomponline) [inline lxd/storage/drivers/driver_zfs.go]: We dont need this logic if the patch has removed them right?

File: lxd/patches.go [hunk 3]
```diff
@@ -124,6 +124,7 @@ var patches = []patch{
 	{name: "config_remove_maas_keys", stage: patchPreLoadClusterConfig, run: patchRemoveMAASConfigKeys},
 	{name: "storage_unset_ceph_source_setting", stage: patchPostDaemonStorage, run: patchUnsetCephSourceSetting},
 	{name: "clustering_event_hub_role_to_control_plane", stage: patchPreLoadClusterConfig, run: patchClusteringEventHubRoleToControlPlane},
+	{name: "storage_zfs_remove_local_bucket_datasets", stage: patchPostDaemonStorage, run: patchStorageZfsRemoveLocalBucketDatasets},
```
Comment (tomponline) [inline lxd/patches.go]: I think this should use the `patchGenericStorage` as the `run` hook.

And then you can add a driver specific patch to https://github.com/canonical/lxd/blob/main/lxd/storage/drivers/driver_zfs.go#L50-L57

Comment (tomponline) [reply lxd/patches.go]: This way the the `storage.Patch()` function will deal with loading the storage pool and checking availability of pools for you.

**Review by tomponline — CHANGES_REQUESTED** [review]
Do we need to remove buckets from the storage layer of any other drivers - dir, btrfs?

**Comment by simondeziel** [comment]
> Do we need to remove buckets from the storage layer of any other drivers - dir, btrfs?

No, it only affects ZFS

File: lxd/storage/drivers/driver_zfs.go (hunk 2 above)
Comment (simondeziel) [reply lxd/storage/drivers/driver_zfs.go]: Good point, indeed.

File: lxd/storage/drivers/driver_zfs.go [hunk 4]
```diff
@@ -434,6 +435,7 @@ func (d *zfs) Delete(progressReporter ioprogress.ProgressReporter) error {
 	}
 
 	initialDatasets := d.initialDatasets()
+
```
Comment (tomponline) [inline lxd/storage/drivers/driver_zfs.go]: seems unnecessary change

**Review by tomponline — APPROVED** [review]
LGTM thanks!

**Review by tomponline — CHANGES_REQUESTED** [review]
Wait, what about this logic:

https://github.com/canonical/lxd/blob/13f2df13ced7d209c6550ec2ff5183b659cebc41/lxd/storage/drivers/driver_common.go#L274-L277

This would explain why, for example, `storage_missing_snapshot_records` is defined against all drivers, with a nil value if not needed.

IIRC this was intentional to ensure that each pool driver was considered for a patch.

**Comment by simondeziel** [comment]
> This would explain why, for example, `storage_missing_snapshot_records` is defined against all drivers, with a nil value if not needed.
> 
> IIRC this was intentional to ensure that each pool driver was considered for a patch.

Right. Do you think it'd be good to add a lint script to catch the kind of mistake I made?

**Comment by tomponline** [comment]
> > This would explain why, for example, `storage_missing_snapshot_records` is defined against all drivers, with a nil value if not needed.
> > IIRC this was intentional to ensure that each pool driver was considered for a patch.
> 
> Right. Do you think it'd be good to add a lint script to catch the kind of mistake I made?

that would be nice, but for now just want to get this merged ASAP. ta

**Review by tomponline — APPROVED** [review]
ta
