### PR TITLE
VM: Fix AppArmor instance_qemu profile

### LINKED ISSUE #11149: LXD tries to access the host's /run/systemd/resolve/stub-resolv.conf
Starting a VM results in this Apparmor denial:

```
apparmor="DENIED" operation="open" profile="lxd-selected-dassie_</var/snap/lxd/common/lxd>" name="/var/lib/snapd/hostfs/run/systemd/resolve/stub-resolv.conf" pid=1111041 comm="lxd" requested_mask="r" denied_mask="r" fsuid=0 ouid=101
```
If I read this correctly, that's `lxd` itself trying to read that file rather than the expected `dnsmasq`.

Steps to reproduce:

```
$ lxc launch images:ubuntu/22.04 --vm
Creating the instance
Instance name is: upright-newt
Starting upright-newt
```

```
$ journalctl -k --grep 'apparmor="DENIED" operation="open" profile="lxd-'
... apparmor="DENIED" operation="open" profile="lxd-upright-newt_</var/snap/lxd/common/lxd>" name="/var/lib/snapd/hostfs/run/systemd/resolve/stub-resolv.conf" pid=1127144 comm="lxd" requested_mask>
```

Additional information:

```
$ snap list lxd
Name  Version      Rev    Tracking       Publisher   Notes
lxd   5.8-ee04373  23972  latest/stable  canonical✓  -

$ uname -a
Linux sdeziel-lemur 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -rd
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
```

### PR DESCRIPTION
**Pull request by Viktor-Yakovchuk**
lxd uses /var/lib/snapd/hostfs/run/systemd/resolve/stub-resolv.conf for launching qemu instances, so this path is added to AppArmor profile to prevent denials

fix #11149

Signed-off-by: Viktor Iakovchuk <viktor@yakovchuk.net>

### CODE REVIEW

**Review by tomponline — APPROVED** [review]

File: lxd/apparmor/instance_qemu.go [hunk 1]
```diff
@@ -74,8 +74,9 @@ profile "{{ .name }}" flags=(attach_disconnected,mediate_deleted) {
   /snap/lxd/*/share/qemu/**                 kr,
 
   # Snap-specific paths
-  /var/snap/lxd/common/ceph/**              r,
-  {{ .rootPath }}/etc/ceph/**               r,
+  /var/snap/lxd/common/ceph/**                         r,
+  {{ .rootPath }}/etc/ceph/**                          r,
+  {{ .rootPath }}/run/systemd/resolve/stub-resolv.conf r,
```
Comment (simondeziel) [inline lxd/apparmor/instance_qemu.go:79]: I'd probably add `/run/systemd/resolve/resolv.conf` in there for those not using `systemd-resolved` in stub mode.

**Review by simondeziel — APPROVED** [review]

**Comment by tomponline** [comment]
jenkins: test this please
