### PR TITLE
Auth: Improvements to network allocation used by URL checks

### LINKED ISSUE #15855: Project specifier ignored in network list-allocations cli and API
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

Ubuntu

### Distribution version

snap

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
Name    Version      Rev    Tracking       Publisher   Notes
core20  20250429     2582   latest/stable  canonical✓  base,disabled
core20  20250526     2599   latest/stable  canonical✓  base
core24  20250504     988    latest/stable  canonical✓  base,disabled
core24  20250526     1006   latest/stable  canonical✓  base
lxd     git-1d144a2  34173  latest/edge    canonical✓  disabled
lxd     git-a8d328a  34320  latest/edge    canonical✓  -
snapd   2.68.4       24505  latest/stable  canonical✓  snapd,disabled
snapd   2.68.5       24718  latest/stable  canonical✓  snapd
```

### Output of "lxc info" or system info if it fails

```shell
-
```

### Issue description

The project specifier on the cli for `lxc network list-allocations` is ignored. The api endpoint at `GET /1.0/network-allocations?project=foo` is ignoring the project parameter

### Steps to reproduce

1. Create a project `lxc project create foo --network lxdbr0 --storage default`
2. Create an instance: `lxc launch ubuntu:24.04 u1 --project foo`
3. Create another project: `lxc project create bar --network lxdbr0 --storage default`
4. Create an instance: `lxc launch ubuntu:24.04 u2 --project bar`
5. List network allocations in the first project: `lxc network list-allocations --project=foo`

Instances from both projects are shown, expected is only instances from the specified project `foo`:

```
+-------------------------------------------+--------------------------------------------+---------+----------+------+-------------------+
|                  USED BY                  |                  ADDRESS                   | NETWORK |   TYPE   | NAT  | HARDWARE ADDRESS  |
+-------------------------------------------+--------------------------------------------+---------+----------+------+-------------------+
| /1.0/networks/lxdbr0                      | 10.166.99.1/24                             | lxdbr0  | network  | true |                   |
+-------------------------------------------+--------------------------------------------+---------+----------+------+-------------------+
| /1.0/networks/lxdbr0                      | fd42:f8d8:8280:856a::1/64                  | lxdbr0  | network  | true |                   |
+-------------------------------------------+--------------------------------------------+---------+----------+------+-------------------+
| /1.0/instances/u1?project=foo             | fd42:f8d8:8280:856a:216:3eff:fee2:210c/128 | lxdbr0  | instance | true | 00:16:3e:e2:21:0c |
+-------------------------------------------+--------------------------------------------+---------+----------+------+-------------------+
| /1.0/instances/u2?project=bar             | fd42:f8d8:8280:856a:216:3eff:fef8:2925/128 | lxdbr0  | instance | true | 00:16:3e:f8:29:25 |
+-------------------------------------------+--------------------------------------------+---------+----------+------+-------------------+
| /1.0/instances/u2?project=bar             | 10.166.99.7/32                             | lxdbr0  | instance | true | 00:16:3e:f8:29:25 |
+-------------------------------------------+--------------------------------------------+---------+----------+------+-------------------+
| /1.0/instances/u1?project=foo             | 10.166.99.231/32                           | lxdbr0  | instance | true | 00:16:3e:e2:21:0c |
+-------------------------------------------+--------------------------------------------+---------+----------+------+-------------------+
```

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by markylaing**
Checks the URLs returned by the network allocations endpoint. This required jumping through a few feature flag related hoops (see comments).

I've confirmed the tests are failing before this change and passing afterwards.

Closes #15855

### CODE REVIEW

File: lxd/network_allocations.go [hunk 1]
```diff
@@ -155,7 +193,7 @@ func networkAllocationsGet(d *Daemon, r *http.Request) response.Response {
 
 		// Get all the networks, their attached instances, their network forwards and their network load balancers.
 		for _, networkName := range networkNames {
-			if !userHasPermission(entity.NetworkURL(authCheckProjectName, networkName)) {
+			if !canViewNetwork(entity.NetworkURL(authCheckProjectName, networkName)) {
```
Comment (tomponline) [inline lxd/network_allocations.go:172]: this should be a separate commit right as is not related to the lease filtering fix?

Comment (tomponline) [reply lxd/network_allocations.go:172]: oh wait, you renamed the check for clarity, fine.

File: lxd/network_allocations.go [hunk 2]
```diff
@@ -126,11 +126,49 @@ func networkAllocationsGet(d *Daemon, r *http.Request) response.Response {
...
 	if err != nil {
 		return response.SmartError(err)
 	}
 
+	canViewInstance, err := s.Authorizer.GetPermissionChecker(r.Context(), auth.EntitlementCanView, entity.TypeInstance)
+	if err != nil {
+		return response.SmartError(err)
+	}
+
+	// If a project query parameter is passed, but the given project does not have `features.networks` enabled, then
```
Comment (tomponline) [inline lxd/network_allocations.go]: Thanks for the comment.

How would you feel about introducing a `s.Authorizer.GetPermissionCheckWithoutEffectiveProject()` or similar that we could use here for the `canViewInstance` checker (or add an argument to `GetPermissinChecker` to do the same)?

And do we need to use `canViewIgnoreEffectiveProject` for the `canViewNetwork` check? As wouldn't all networks be in the effective project if using `project=foo` where `foo` has `features.networks=false`?

Comment (markylaing) [reply lxd/network_allocations.go]: I'll play with it a bit more. I initially changed the authorizer to stop getting the effective project from the request context and instead expect an "overrideProject" argument, but changing the call sites became quite large.

For the second question: I wasn't 100% sure on this. The networks that are checked with this function are derived from the network lease here https://github.com/canonical/lxd/blob/ce8fa3309da16a2d86af9f0845200ee819459d5c/lxd/network_allocations.go#L200-L201 - where the lease type is "uplink". So I wasn't certain if these networks would be in the same project.

Comment (markylaing) [reply lxd/network_allocations.go]: > How would you feel about introducing a s.Authorizer.GetPermissionCheckWithoutEffectiveProject() or similar that we could use here for the canViewInstance checker (or add an argument to GetPermissinChecker to do the same)?

This seems to be the best worst option.

Comment (tomponline) [reply lxd/network_allocations.go]: > For the second question: I wasn't 100% sure on this. The networks that are checked with this function are derived from the network lease here

For the ovn and bridge network's `Leases()` function they both have a comment:

> // If requested project matches network's project then include gateway...

https://github.com/canonical/lxd/blob/main/lxd/network/driver_bridge.go#L3590-L3635

https://github.com/canonical/lxd/blob/main/lxd/network/driver_ovn.go#L5362-L5376

So I think as we're passing empty string to `Leases()` in this function we're OK.

This is most likely there to handle the `lxc network list-leases` use-case instead.

Comment (markylaing) [reply lxd/network_allocations.go]: Great thank :) Updated PR to add new methods to the auth interface that ignore the effective project and have used those methods only for the instance auth check

File: lxd/network_allocations.go [hunk 3]
```diff
@@ -126,7 +126,12 @@ func networkAllocationsGet(d *Daemon, r *http.Request) response.Response {
 
 	result := make([]api.NetworkAllocations, 0)
 
-	userHasPermission, err := s.Authorizer.GetPermissionChecker(r.Context(), auth.EntitlementCanView, entity.TypeNetwork)
+	canViewNetwork, err := s.Authorizer.GetPermissionChecker(r.Context(), auth.EntitlementCanView, entity.TypeNetwork)
+	if err != nil {
+		return response.SmartError(err)
+	}
+
+	canViewInstanceIgnoringEffectiveProject, err := s.Authorizer.GetPermissionCheckerWithoutEffectiveProject(r.Context(), auth.EntitlementCanView, entity.TypeInstance)
```
Comment (tomponline) [inline lxd/network_allocations.go:143]: It'd be good to have a comment here explaining why we are using this.

Comment (markylaing) [reply lxd/network_allocations.go:143]: Ah yeah I'll reword the comment from the commit message.

Comment (markylaing) [reply lxd/network_allocations.go:143]: Added a comment with examples.

**Comment by markylaing** [comment]
@tomponline this is a pretty weird unit test failure: https://github.com/canonical/lxd/actions/runs/16020208379/job/45195111146?pr=15907#step:25:908

This is checking that when deleting an instance, values in `instance_config` are also deleted via cascade. The test sets up a test DQLite database. I'm wondering if there's been a regression. https://github.com/canonical/dqlite/pull/778 seems a likely candidate

**Comment by tomponline** [comment]
> @tomponline this is a pretty weird unit test failure: https://github.com/canonical/lxd/actions/runs/16020208379/job/45195111146?pr=15907#step:25:908
> 
> This is checking that when deleting an instance, values in `instance_config` are also deleted via cascade. The test sets up a test DQLite database. I'm wondering if there's been a regression. [canonical/dqlite#778](https://github.com/canonical/dqlite/pull/778) seems a likely candidate

Yep thats the regression indeed.
