### PR TITLE
Prevent cluster groups from being deleted when referenced by a projects' configuration

### LINKED ISSUE #15118: project config 'restricted.cluster.groups' not checked when deleting a cluster group
**problem**

spotted this while trying to restore a cluster member.
if you could make the error bit more verbose it would help. logs point into a more clear direction on the culprit

```
ubuntu@hpc-02:~$ lxc cluster restore hpc-01
Are you sure you want to restore cluster member "hpc-01"? (yes/no) [default=no]: yes
Error: Migration API failure: Project isn't allowed to use this cluster member: "hpc-01" 
```

ubuntu-desktop-remote is a stopped instance, on project `stable` which has a `restricted.cluster.groups` that does not exist anymore (it was deleted some days back)

```
ubuntu@hpc-02:~$ lxc monitor --pretty  | grep hpc-01
...
time="2025-03-06T08:56:23+01:00" level=debug msg="Handling API request" fingerprint=9198a46812cfa3434c18bf56f7e519bc083db03008a1527c5f9c003198e0ed73 ip="REDACTED.24.228:44572" method=POST protocol=cluster url="/1.0/instances/ubuntu-desktop-remote?project=stable&target=hpc-01"
time="2025-03-06T08:56:23+01:00" level=debug msg="Database error" err="Project isn't allowed to use this cluster member: \"hpc-01\""
time="2025-03-06T08:56:23+01:00" level=info msg="ID: 6b6f9060-306d-44a5-98ee-9c3003279461, Class: task, Description: Restoring cluster member" CreatedAt="2025-03-06 08:56:23.037108935 +0100 CET" Err="Migration API failure: Project isn't allowed to use this cluster member: \"hpc-01\"" Location=hpc-01 MayCancel=false Metadata="map[evacuation_progress:Migrating \"ubuntu-desktop-remote\" in project \"stable\" from \"hpc-02\"]" Resources="map[]" Status=Failure StatusCode=Failure UpdatedAt="2025-03-06 08:56:23.371603162 +0100 CET"


ubuntu@hpc-01:~$ lxc project show stable
name: stable
description: use-cases for validation purpose
config:
...
  restricted.cluster.groups: hardened-nodes
...
used_by:
...

ubuntu@hpc-01:~$ lxc cluster group list
+---------+-----------------------+---------+
|  NAME   |      DESCRIPTION      | MEMBERS |
+---------+-----------------------+---------+
| default | Default cluster group | 5       |
+---------+-----------------------+---------+
```

**howto reproduce**

- create a cluster group with a node
- create a project and assign group as `restricted.cluster.groups`
 - delete group and now project is corrupted, since it's not validating that is not in use

more specific reproduction of our use case ,though i did not test it fully:
- create a cluster group with a node
- create a project and assign group as `restricted.cluster.groups`
- create an instance in that project.
- stop it (did not check if problem happens also with running instances, or even without an instance)
- evacuate node
- delete group and now project is corrupted and will probably get the first error 
- try restore node

### PR DESCRIPTION
**Pull request by markylaing**
Adds an API extension `clustering_groups_used_by` and adds a `UsedBy` field to `api.ClusterGroup`. On GET requests, the `UsedBy` URLs are projects that contain the cluster group in `restricted.cluster.groups`. DELETE requests will fail if the cluster group is used by a project.

Closes #15118

### CODE REVIEW

File: lxd/db/cluster/cluster_groups.go [hunk 1]
```diff
@@ -51,3 +57,43 @@ func (c *ClusterGroup) ToAPI() (*api.ClusterGroup, error) {
...
 }
+
+// GetClusterGroupUsedBy collates references to the cluster group with the given name.
+// This currently only returns the URLs of projects whose `restricted.cluster.groups` configuration
+// contains the cluster group.
+func GetClusterGroupUsedBy(ctx context.Context, tx *sql.Tx, groupName string) ([]string, error) {
+	q := `
+SELECT projects.name, projects_config.value FROM projects 
+JOIN projects_config ON projects.id = projects_config.project_id 
+WHERE projects_config.key = 'restricted.cluster.groups' AND projects_config.value LIKE '%` + groupName + `%'`
```
Comment (tomponline) [inline lxd/db/cluster/cluster_groups.go:74]: This is a SQL injection security risk.

Comment (tomponline) [reply lxd/db/cluster/cluster_groups.go:74]: Also the use of LIKE here seems potentially incorrect as it might match partial group names.

Can we use JSON collation and direct matching with query parameters instead?

**Review by tomponline — CHANGES_REQUESTED** [review]
Looks good, except the SQL injection flaw ;)

**Comment by markylaing** [comment]
> Looks good, except the SQL injection flaw ;)

Whoopsie :laughing: Thank you CodeQL :pray: Not sure how I convinced myself that this was ok...

File: lxd/db/cluster/cluster_groups.go (hunk 1 above)
Comment (markylaing) [reply lxd/db/cluster/cluster_groups.go]: Unfortunately not, because the config key is a comma separated list.

Rather than doing anything clever, I'm now just querying for all projects that have the `restricted.cluster.groups` configuration key set. Then parsing the output to see if it contains the group.

Comment (tomponline) [reply lxd/db/cluster/cluster_groups.go]: makes sense because they may be spaces in the comma delimited list too

File: lxd/db/cluster/cluster_groups.go [hunk 2]
```diff
@@ -51,3 +57,39 @@ func (c *ClusterGroup) ToAPI() (*api.ClusterGroup, error) {
...
+	err = query.SelectObjects(ctx, stmt, func(scan func(dest ...any) error) error {
+		var projectName string
+		var configValue string
+		err := scan(&projectName, &configValue)
+		if err != nil {
+			return err
+		}
+
+		if shared.ValueInSlice(groupName, shared.SplitNTrimSpace(configValue, ",", -1, false)) {
+			projectURLs = append(projectURLs, entity.ProjectURL(projectName).String())
```
Comment (tomponline) [inline lxd/db/cluster/cluster_groups.go:91]: I'm interested why you convert the api.URL to a string here rather than return a slice of api.URLs themselves, I feel that would be clearer as to the contents of the slice rather than a string?

File: lxd/db/cluster/cluster_groups.go [hunk 3]
```diff
@@ -51,3 +57,39 @@ func (c *ClusterGroup) ToAPI() (*api.ClusterGroup, error) {
...
+// GetClusterGroupUsedBy collates references to the cluster group with the given name.
+// This currently only returns the URLs of projects whose `restricted.cluster.groups` configuration
+// contains the cluster group.
+func GetClusterGroupUsedBy(ctx context.Context, tx *sql.Tx, groupName string) ([]string, error) {
+	q := `
+SELECT projects.name, projects_config.value FROM projects 
+JOIN projects_config ON projects.id = projects_config.project_id 
+WHERE projects_config.key = 'restricted.cluster.groups'`
+
+	stmt, err := tx.Prepare(q)
```
[the remark this answers is not in the document]
Comment (tomponline) [reply lxd/db/cluster/cluster_groups.go:76]: SelectObjects is very similar to query.Scan, we should probably get rid of SelectObjects

File: lxd/api_cluster.go [hunk 4]
```diff
@@ -3817,26 +3817,24 @@ func clusterGroupsGet(d *Daemon, r *http.Request) response.Response {
 				return err
 			}
 
-			for i := range clusterGroups {
-				nodeClusterGroups, err := dbCluster.GetNodeClusterGroups(ctx, tx.Tx(), dbCluster.NodeClusterGroupFilter{GroupID: &clusterGroups[i].ID})
+			apiClusterGroups := make([]*api.ClusterGroup, len(clusterGroups))
```
Comment (tomponline) [inline lxd/api_cluster.go:3820]: please can you use the form `make([]*api.ClusterGroup, 0, len(clusterGroups))` to avoids accidents in the future.

File: lxd/db/cluster/cluster_groups.go (hunk 2 above)
Comment (markylaing) [reply lxd/db/cluster/cluster_groups.go:91]: I was just following the convention of other `UsedBy` methods but happy to change.

File: lxd/db/cluster/cluster_groups.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (markylaing) [reply lxd/db/cluster/cluster_groups.go:76]: Ahh I knew there was a method that didn't require preparation of the statement somewhere!

File: lxd/api_cluster.go (hunk 4 above)
Comment (markylaing) [reply lxd/api_cluster.go:3820]: Will fix in separate commits

**Comment by markylaing** [comment]
> Static analysis failure

Fixed.

**Review by tomponline — APPROVED** [review]
Thanks!
