### PR TITLE
Fix NetworksPostCluster is ignoring description 

### LINKED ISSUE #15962: networksPostCluster is ignoring description
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

ubuntu

### Distribution version

snap

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
Name    Version      Rev    Tracking       Publisher   Notes
core20  20250429     2582   latest/stable  canonical✓  base,disabled
core20  20250526     2599   latest/stable  canonical✓  base
core22  20250425     1981   latest/stable  canonical✓  base,disabled
core22  20250528     2010   latest/stable  canonical✓  base
core24  20250504     988    latest/stable  canonical✓  base,disabled
core24  20250526     1006   latest/stable  canonical✓  base
lxd     git-053eee9  34544  5.21/edge      canonical✓  disabled,in-cohort
lxd     git-076857b  34595  5.21/edge      canonical✓  in-cohort
snapd   2.68.4       24505  latest/stable  canonical✓  snapd,disabled
snapd   2.68.5       24718  latest/stable  canonical✓  snapd
```

### Output of "lxc info" or system info if it fails

```shell
-
```

### Issue description

On creating a bridge, macvlan or sriov network with the api in a cluster, the description in the payload is ignored. Nested config fields are persisted, but not the description itself on the root level.

### Steps to reproduce

1. Send a `POST /1.0/networks&target=micro1` with payload `{"name":"foo","type":"macvlan","description":"bar","config":{"parent":"enp5s0"}}` to create the pending network on each cluster member.
2. Send a `POST /1.0/networks&target=micro2` with payload `{"name":"foo","type":"macvlan","description":"bar","config":{"parent":"enp5s0"}}`
3. Send a `POST /1.0/networks&target=micro3` with payload `{"name":"foo","type":"macvlan","description":"bar","config":{"parent":"enp5s0"}}`
4. Send a `POST /1.0/networks` with payload `{"name":"foo","type":"macvlan","description":"bar","config":{"parent":"enp5s0"}}` to finally create the network across the cluster.
5. Fetch the network details `GET /1.0/networks/foo` and see the config (parent field) being set, while the description is empty.

Expectation is that the description is persisted at this point.

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by tugbataluy**
Fixes #15962

### CODE REVIEW

File: lxd/networks.go [hunk 1]
```diff
@@ -843,6 +843,11 @@ func networksPostCluster(ctx context.Context, s *state.State, projectName string
 
 	// Mark network global status as networkCreated now that all nodes have succeeded.
 	err = s.DB.Cluster.Transaction(ctx, func(ctx context.Context, tx *db.ClusterTx) error {
+		// Update only the description of the network right before creation
+		err := tx.UpdateNetworkDescription(ctx, projectName, req.Name, req.Description)
```
Comment (tomponline) [inline lxd/networks.go]: can we do this earlier just above `// Insert the global config keys.`?

Comment (tugbataluy) [reply lxd/networks.go]: Sure we can :)

Comment (tomponline) [reply lxd/networks.go]: im thinking this would be preferable to set it sooner rather than later

File: lxd/networks.go [hunk 2]
```diff
@@ -17,7 +17,7 @@ import (
 
 	"github.com/gorilla/mux"
 
-	"github.com/canonical/lxd/client"
+	lxd "github.com/canonical/lxd/client"
```
Comment (tomponline) [inline lxd/networks.go]: please remove this change, you can configure your IDE to not auto change this.

File: lxd/networks.go [hunk 3]
```diff
@@ -765,6 +765,12 @@ func networksPostCluster(ctx context.Context, s *state.State, projectName string
 			return err
 		}
 
+		// Update only the description of the network.
+		err = tx.UpdateNetworkDescription(ctx, projectName, req.Name, req.Description)
```
Comment (tomponline) [inline lxd/networks.go]: you have network ID above, so no need to look it up again inside `UpdateNetworkDescription`

File: test/suites/clustering.sh [hunk 4]
```diff
@@ -1139,9 +1139,20 @@ test_clustering_network() {
...
+    \"description\": \"bar\",
+    \"config\": {
+      \"ipv4.address\": \"none\",
+      \"ipv6.address\": \"none\"
+    }
+  }"
+
+  # Verify network is now created with description
   LXD_DIR="${LXD_ONE_DIR}" lxc network show "${net}" | grep -F status: | grep -wF Created
+  LXD_DIR="${LXD_ONE_DIR}" lxc network show "${net}" | grep -F "description: bar"
```
Comment (tomponline) [inline test/suites/clustering.sh]: lxc network get <network> --property description

File: test/suites/clustering.sh [hunk 5]
```diff
@@ -1139,9 +1139,20 @@ test_clustering_network() {
   # The bridge.external_interfaces config key is not legal for the final network creation
   ! LXD_DIR="${LXD_ONE_DIR}" lxc network create "${net}" bridge.external_interfaces=foo || false
 
-  # Create the network
-  LXD_DIR="${LXD_TWO_DIR}" lxc network create "${net}" ipv4.address=none ipv6.address=none
+  # Finalize the nwtwork creation using direct API with description
```
Comment (tomponline) [inline test/suites/clustering.sh]: please can you expand this comment explaining the *why* - to test finalising it with a description, which isn't possible via `lxc network create`.

**Comment by tomponline** [comment]
thanks, couple of nits then good to merge

File: test/suites/clustering.sh (hunk 5 above)
Comment (simondeziel) [inline test/suites/clustering.sh]: Tiny typo:
```suggestion
  # Finalize the network creation using direct API with description
```

File: test/suites/clustering.sh (hunk 4 above)
Comment (simondeziel) [reply test/suites/clustering.sh]: In general, we (now) try to use shell comparison as much as possible as it behaves more nicely than command pipelines.

This would look like:
```suggestion
  [ "$(LXD_DIR="${LXD_ONE_DIR}" lxc network get --property "${net}" description)" = "bar" ]
```

FYI, the surrounding `status` checks are not something we can lookup as a property.

File: test/suites/clustering.sh [hunk 6]
```diff
@@ -1139,9 +1139,20 @@ test_clustering_network() {
...
+  LXD_DIR="${LXD_ONE_DIR}" lxc query -X POST /1.0/networks --data "{
```
Comment (simondeziel) [inline test/suites/clustering.sh:1143]: I take it that `LXD_DIR="${LXD_TWO_DIR}" lxc network create "${net}" ipv4.address=none ipv6.address=none description="bar"` didn't cause any issue?

File: test/suites/clustering.sh (hunk 5 above)
Comment (tugbataluy) [reply test/suites/clustering.sh]: Thanks, I'll fix it :D

Comment (tugbataluy) [reply test/suites/clustering.sh]: I have updated the comment regarding your suggestion, thank you.

File: test/suites/clustering.sh (hunk 6 above)
Comment (tomponline) [reply test/suites/clustering.sh:1143]: description is a property not a config key.

**Review by tomponline — APPROVED** [review]
Thanks!
