### PR TITLE
Console: Explicitly close both ends of mirrored websockets

### LINKED ISSUE #16073: Concurrent (graphical) console connections to a VM
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

ubuntu

### Distribution version

snap

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
core24  20250618     1055   latest/stable  canonical✓  base
lxd     6.4-2336111  34099  6/stable       canonical✓  disabled
lxd     6.4-1c216d4  34285  6/stable       canonical✓  -
snapd   2.68.5       24718  latest/stable  canonical✓  snapd,disabled
snapd   2.70         24792  latest/stable  canonical✓  snapd
```

### Output of "lxc info" or system info if it fails

```shell
-
```

### Issue description

This is about the VM graphic console in the LXD-UI. When the console is open and a 2nd console is started, the 1st one stops working. But the WebSockets of the 1st one are not closed for the client.

Ideally, LXD should support multiple connections to the same VM in parallel. Or at least LXD should close the sockets for the 1st connection when a 2nd connection is started. That way, the UI can surface the error. Currently, the connections from the 1st console are still pending and not closed by the server. Though, the pending WebSockets do not react on user input, nor send graphic updates.

This was first reported to the UI in https://github.com/canonical/lxd-ui/issues/1390

### Steps to reproduce

1. Create a VM with a desktop environment in the LXD-UI
2. Open the graphic console for that VM
3. Open a 2nd tab and open the grpahic console for that VM
4. See the first console opened is now broken. It still show graphical output, but doesn't allow for interaction or send updates.

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by edlerd**
# Done
- explicitly close both ends of mirrored websockets
- avoid hanging websockets where one end disconnected

Fixes #16073

### CODE REVIEW

File: lxd/instance_console.go [hunk 1]
```diff
@@ -180,7 +180,11 @@ func (s *consoleWs) connectVGA(r *http.Request, w http.ResponseWriter) error {
 		go func() {
 			l := logger.AddContext(logger.Ctx{"address": conn.RemoteAddr().String()})
 
-			defer l.Debug("Finished mirroring websocket to console")
+			defer func() {
```
Comment (tomponline) [inline lxd/instance_console.go]: This should be happening here:

https://github.com/canonical/lxd/blob/4eb1e98b15c2dea98c9371a64f4b45fd00423316/lxd/instance_console.go#L386-L390

Any ideas why its not?

Comment (tomponline) [reply lxd/instance_console.go]: Perhaps the `// Wait until the control channel is done.` is happening?

Comment (edlerd) [reply lxd/instance_console.go]: The bug reproduces for me when opening a graphical console for the same instance twice, in parallel tabs from the UI.
Only one of the web sockets actually gets closed with this patch. But that is enough to surface an error in the UI.

Comment (edlerd) [reply lxd/instance_console.go]: I think the control channel is not closing under the circumstances, so that's why the other code branch is not triggering.

Comment (tomponline) [reply lxd/instance_console.go]: Do you know why the control channel isn't being closed by the client?

Comment (tomponline) [reply lxd/instance_console.go]: Maybe we just need to trigger this sort of logic for the control socket if readers from it fail?

Comment (edlerd) [reply lxd/instance_console.go]: From investing it last week there are several web sockets opened in parallel for one vga connection. With the patch one of them gets closed and surfaces an error in the web UI. The others stay open but don't receive any updates from the VM or send input to it.

Before the patch all sockets stayed open and don't transmit information to/from the VM. The problem was, no visible error for the user of the UI in that special case. So for the UI I think the change is ok.

I understand you may be looking for a wider fix here. I suspect the one socket closes with the patch, because the QEMU side is closing it with the second vga opened in parallel. I do not have a good idea how to raise the error to the control channel. Maybe we have someone with a deeper understanding of QEMU - or we could do some research into it. There might be options in how LXD uses it.

Comment (tomponline) [reply lxd/instance_console.go]: Can you reproduce using multiple invocations of `lxc console --type=vga`?

Comment (edlerd) [reply lxd/instance_console.go]: With running `lxc console --type=vga` a second time, the first console for the same instance gets closed.

Comment (tomponline) [reply lxd/instance_console.go]: OK cool, do you see which connection gets shutdown first when that happens?

Comment (edlerd) [reply lxd/instance_console.go]: Not sure how to figure that out, what I see is the first console, that got closed, when running with --debug is printing this after the 2nd console is opened:

```DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Got barrier message                address=/var/snap/lxd/common/lxd/unix.socket
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped write mirror               address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Got barrier message                address=/var/snap/lxd/common/lxd/unix.socket
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped write mirror               address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Got barrier message                address=/var/snap/lxd/common/lxd/unix.socket
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped write mirror               address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Got barrier message                address=/var/snap/lxd/common/lxd/unix.socket
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Got barrier message                address=/var/snap/lxd/common/lxd/unix.socket
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Got barrier message                address=/var/snap/lxd/common/lxd/unix.socket
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped write mirror               address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped write mirror               address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Got barrier message                address=/var/snap/lxd/common/lxd/unix.socket
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped write mirror               address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped write mirror               address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped read mirror                address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Sending barrier message            address=/var/snap/lxd/common/lxd/unix.socket
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped read mirror                address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Sending barrier message            address=/var/snap/lxd/common/lxd/unix.socket
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped read mirror                address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Sending barrier message            address=/var/snap/lxd/common/lxd/unix.socket
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped read mirror                address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped read mirror                address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Sending barrier message            address=/var/snap/lxd/common/lxd/unix.socket
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Sending barrier message            address=/var/snap/lxd/common/lxd/unix.socket
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped read mirror                address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Sending barrier message            address=/var/snap/lxd/common/lxd/unix.socket
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Stopped read mirror                address=/var/snap/lxd/common/lxd/unix.socket err="<nil>"
DEBUG  [2025-09-04T16:26:02+02:00] Websocket: Sending barrier message            address=/var/snap/lxd/common/lxd/unix.socket
```

Comment (tomponline) [reply lxd/instance_console.go]: @edlerd would you mind booking a call so we can go through this together please?

Comment (edlerd) [reply lxd/instance_console.go]: Thanks for helping in the session :)

Comment (tomponline) [reply lxd/instance_console.go]: You're welcome, glad we got to the bottom of it!

File: lxd/instance_console.go [hunk 2]
```diff
@@ -180,14 +184,26 @@ func (s *consoleWs) connectVGA(r *http.Request, w http.ResponseWriter) error {
 		go func() {
 			l := logger.AddContext(logger.Ctx{"address": conn.RemoteAddr().String()})
 
-			defer l.Debug("Finished mirroring websocket to console")
+			defer l.Debug("Finishing mirroring websocket")
```
Comment (tomponline) [inline lxd/instance_console.go]: Lets stick with "Finished" here

File: lxd/instance_console.go [hunk 3]
```diff
@@ -180,14 +184,26 @@ func (s *consoleWs) connectVGA(r *http.Request, w http.ResponseWriter) error {
...
 			readDone, writeDone := ws.Mirror(conn, console)
 
-			<-readDone
-			l.Debug("Finished mirroring console to websocket")
-			<-writeDone
+			for {
+				if readDone == nil && writeDone == nil {
+					break
+				}
+				select {
```
Comment (tomponline) [inline lxd/instance_console.go:193]: we'll need a line before the `select` as we require white space after a stanza
