### PR TITLE
Fix devlxd image export

### LINKED ISSUE #13167: Auth: Follow up on removal of `checkTrustedClient`.
Add comments to explain how authorization is being handled in public (`AllowUntrusted` endpoints).

See https://github.com/canonical/lxd/pull/13080#discussion_r1526551495_

### PR DESCRIPTION
**Pull request by markylaing**
This was caused by calling `CheckPermission` without considering that the handler is called internally by devlxd.

In this PR I have updated all image handlers that have `AllowUntrusted` set to true. The handling of authentication/authorization is clarified with comments indicating what should happen when the caller is:
- A guest instance.
- An untrusted client.
- An untrusted client with an image secret.
- An authenticated client.

Comments contextual of whether the image is public, private, or cached.

Closes #13678
Closes #13167

### CODE REVIEW

**Comment by markylaing** [comment]
@tomponline @MusicDin I'm guessing since devlxd image export was broken we don't have tests for it? I've tested it manually and from the speed of the image download in the guest it must have come from the host (the guest downloaded `ubuntu:22.04` in about 3 seconds - I wish my internet connection was that fast :laughing:). 

Another thing I wan't to be absolutely certain of is that an authenticated client can see public images in a project they don't have access to. 

Shall I mark as draft for now while I work on tests? Otherwise I can put up a separate PR.

**Comment by MusicDin** [comment]
Thanks for this 🚀 

I'm not sure how to reliably test it within CI. The instance needs internet access to fetch the fingerprint for the given image name/alias. Haven't tested, but maybe if fingerprint is provided, it will check for the image directly on the host. This would be handy as we can simply prevent instance's access to the internet and ensure image download does not fail.

Otherwise, I can think only of limiting the time for the image download to ensure it was fetched from the host (maybe this can be more reliable if we use some bigger images like Ubuntu).

---

For local development you can error out after this block:

https://github.com/canonical/lxd/blob/9df996e36bacb27a422a3c1654fe64a462c706f6/client/simplestreams_images.go#L70-L76

See the change in `client/simplestream_images` in this commit: https://github.com/canonical/lxd/pull/13678/commits/43fbdcc6b9d75cb64835bbc838cb88c03432aa3d. This throws an error if image is not found on the host.

---

Also merging this PR should clos this issue https://github.com/canonical/lxd/issues/13595

**Comment by markylaing** [comment]
> Thanks for this 🚀
> 
> I'm not sure how to reliably test it within CI. The instance needs internet access to fetch the fingerprint for the given image name/alias. Haven't tested, but maybe if fingerprint is provided instead of an alias, it will check for the image directly on the host. This would be handy as we can simply prevent instance's access to the internet and ensure image download does not fail.
> 
> Otherwise, I can think only of limiting the time for the image download to ensure it was fetched from the host (maybe this can be more reliable if we use some bigger images like Ubuntu).
> 
> For local development you can error out after this block:
> 
> https://github.com/canonical/lxd/blob/9df996e36bacb27a422a3c1654fe64a462c706f6/client/simplestreams_images.go#L70-L76
> 
> See the change in `client/simplestream_images` in this commit: [43fbdcc](https://github.com/canonical/lxd/commit/43fbdcc6b9d75cb64835bbc838cb88c03432aa3d). This throws an error if image is not found on the host.
> 
> Also merging this PR should close this issue #13595

I think we should avoid calling out to external remotes if at all possible. I'll investigate whether it is possible to trick the guest LXD by using `images:${test_image_full_fingerprint}`. I'm hoping it will first see that the image is not cached, then call the devlxd endpoint with the full fingerprint without first trying to resolve the fingerprint as an alias. We'll see :)

**Comment by markylaing** [comment]
> I think we should avoid calling out to external remotes if at all possible. I'll investigate whether it is possible to trick the guest LXD by using `images:${test_image_full_fingerprint}`. I'm hoping it will first see that the image is not cached, then call the devlxd endpoint with the full fingerprint without first trying to resolve the fingerprint as an alias. We'll see :)

My last comment was a bit shortsighted :laughing:. We can't run nested LXD in the busy box test image. We'll have to put tests for this into the lxd-ci repo instead.

**Comment by tomponline** [comment]
> My last comment was a bit shortsighted 😆. We can't run nested LXD in the busy box test image. We'll have to put tests for this into the lxd-ci repo instead.

This is fine by me

**Comment by markylaing** [comment]
@tomponline this is ready for review. The associated test PR is here: https://github.com/canonical/lxd-ci/pull/240

File: lxd/images.go [hunk 1]
```diff
@@ -973,6 +973,7 @@ func imagesPost(d *Daemon, r *http.Request) response.Response {
 
 	projectName := request.ProjectParam(r)
 
+	// If the client is not authenticated, CheckPermission will return false.
```
Comment (tomponline) [inline lxd/images.go:976]: false? You mean an error, it cant return false?

File: lxd/images.go [hunk 2]
```diff
@@ -2993,37 +2992,65 @@ func imageGet(d *Daemon, r *http.Request) response.Response {
...
+		info, err = doImageGet(ctx, tx, projectName, fingerprint, publicOnly)
 		if err != nil {
 			return err
 		}
 
 		return nil
 	})
-	if err != nil {
+	if err != nil && api.StatusErrorCheck(err, http.StatusNotFound) {
+		// Return a generic not found. This is so that the caller cannot determine the existence of an image by the
```
Comment (tomponline) [inline lxd/images.go:3013]: What is the non-generic error then?

File: lxd/images.go [hunk 3]
```diff
@@ -4010,43 +4043,82 @@ func imageExport(d *Daemon, r *http.Request) response.Response {
 		return response.SmartError(err)
 	}
 
-	// Get the image (expand the fingerprint).
+	isDevLXDQuery := r.RemoteAddr == "@devlxd"
```
Comment (tomponline) [inline lxd/images.go:4046]: Looks like we could do with a constant for `@devlxd`

File: lxd/images.go [hunk 4]
```diff
@@ -4010,43 +4043,82 @@ func imageExport(d *Daemon, r *http.Request) response.Response {
...
+		}
+	}
+
+	if isDevLXDQuery {
+		// A devlxd query must contain the full fingerprint of the image (no partials).
+		if fingerprint != imgInfo.Fingerprint {
+			return response.NotFound(nil)
+		}
+
+		// It must also be for a public or cached image.
```
Comment (tomponline) [inline lxd/images.go:4096]: This seems at odds with the earlier comment:

>Devlxd queries can be for private images but only if they are cached.

File: lxd/images.go [hunk 5]
```diff
@@ -4010,43 +4043,82 @@ func imageExport(d *Daemon, r *http.Request) response.Response {
 		return response.SmartError(err)
 	}
 
-	// Get the image (expand the fingerprint).
+	isDevLXDQuery := r.RemoteAddr == "@devlxd"
+	secret := r.FormValue("secret")
+	trusted := auth.IsTrusted(r.Context())
+
+	// Unauthenticated clients that do not provide a secret may only view public images.
+	// Devlxd queries can be for private images but only if they are cached.
```
Comment (tomponline) [inline lxd/images.go:4051]: Why are only private cached images allowed? I feel like this comment could do with expanding.

File: lxd/images.go (hunk 2 above)
Comment (markylaing) [reply lxd/images.go:3013]: The non-generic error would be the `response.SmartError` in the following `else if err != nil` block. It could contain any error that occurred during the transaction.

Comment (tomponline) [reply lxd/images.go:3013]: What made you hide this into a generic one?

Comment (markylaing) [reply lxd/images.go:3013]: The authorizer returns a generic not found error if the caller doesn't have permission to view a resource. In this case, because we have to expand the fingerprint before we can call the authorizer, we don't want to leak any errors indicating the existence of the image. I'm just trying to be defensive with it.

Comment (tomponline) [reply lxd/images.go:3013]: got you thanks

Comment (markylaing) [reply lxd/images.go:3013]: I'm not sure I've explained this clearly. 

Current behaviour (trusted without permission or untrusted):
- `GET /1.0/images/{non-existing-image}` = `Image not found`
- `GET /1.0/images/{existing-image}` = `Not found`

Both cases return a 404, but you can determine that the image does in fact exist because the error message when it really doesn't exist is different from the error message when you're not allowed to view it.

Comment (tomponline) [reply lxd/images.go:3013]: This is the explanation i was hoping for, thanks!

File: lxd/images.go (hunk 3 above)
Comment (markylaing) [reply lxd/images.go:4046]: Done.

File: lxd/images.go (hunk 5 above)
Comment (markylaing) [reply lxd/images.go]: I've updated the comments here but I'm still not sure I've made it super clear to be honest.

Devlxd queries can be for public images because the image is accessible to anyone. Devlxd queries can be for private images only when the image is cached from a public remote. E.g. if the host has `ubuntu:22.04` downloaded, we cache it but don't make it public.

File: lxd/images.go (hunk 1 above)
Comment (markylaing) [reply lxd/images.go]: Fixed comment.

File: lxd/images.go (hunk 5 above)
Comment (tomponline) [reply lxd/images.go]: Thanks, that makes sense.

We don't want to trigger a download of an image on the host.

BTW are we restricting which project images are accessible by /dev/lxd requests to only those of the instance's effective image project?

Comment (markylaing) [reply lxd/images.go]: Currently are devlxd requests are for the default project.

I think this warrants a separate issue though. As I understand it, all cached images are stored in the default project. If I launch an `ubuntu:22.04` container in project `test` say, and then create another `ubuntu:22.04` inside it, then restricting the `devlxd` request to only project `test` would miss the cached image and download it via the ubuntu remote instead.

Comment (markylaing) [reply lxd/images.go]: Another thing that doesn't make sense to me is how to actually make an image public on a host that is accessible to the nested LXD. The nested LXD doesn't have the host added as a remote, so it can't resolve the alias of the public image. As far as I can tell, this feature only works for cached images.

Comment (tomponline) [reply lxd/images.go]: OK thanks, yes please can you create a separate issue. 

I'm not sure that "all cached images are stored in the default project" but if /dev/lxd only servers from the default project currently then we dont need to change it in this PR.

Comment (tomponline) [reply lxd/images.go]: > Another thing that doesn't make sense to me is how to actually make an image public on a host that is accessible to the nested LXD. The nested LXD doesn't have the host added as a remote, so it can't resolve the alias of the public image. As far as I can tell, this feature only works for cached images.

Does `lxc import server:fingerprint` work?

Comment (markylaing) [reply lxd/images.go]: > OK thanks, yes please can you create a separate issue.
> 
> I'm not sure that "all cached images are stored in the default project" but if /dev/lxd only servers from the default project currently then we dont need to change it in this PR.

https://github.com/canonical/lxd/issues/13768

> > Another thing that doesn't make sense to me is how to actually make an image public on a host that is accessible to the nested LXD. The nested LXD doesn't have the host added as a remote, so it can't resolve the alias of the public image. As far as I can tell, this feature only works for cached images.
> 
> Does `lxc image import server:fingerprint` work?

In https://github.com/canonical/lxd-ci/pull/240 I experimented with creating an image on the host and making it public. This would prove that image export over devlxd was working because the image would not be present anywhere else. The problem is that you can't specify the host as a remote (e.g. what do you put as "server" in the command you posted), so I tried out a few things related to [this comment](https://github.com/canonical/lxd/pull/13730#issuecomment-2219703206). The methods I tried were:
1. (naively) `lxc init "ubuntu:{host_image_fingerprint}" c1`. This doesn't work because the client tries to resolve the image against the ubuntu remote.
2. Using `lxc query -X POST /1.0/instances` and providing an image source with the fingerprint of the public image on the host. For this you need to provide a remote URL, so I added the ubuntu URL. This fails because the guest LXD tries to get the image from the remote to perform architecture checks ([here](https://github.com/canonical/lxd/blob/2445ed1a8fc945bba2dddd8bb1cbcc3f66bfae0b/lxd/instance/instance_utils.go#L617)).
3. Downloading the image directly via cURL. This doesn't really work because the downloaded `octet-stream` needs to be split into `rootfs` and metadata files before you can do anything. I also didn't like this because it doesn't actually test that the guest will download an image from the host when requested, only that the socket itself works.

**Comment by markylaing** [comment]
Static analysis failing because I touched `lxd/devlxd.go` which has some pre-existing lint errors. Will fix shortly.

**Comment by markylaing** [comment]
> Static analysis failing because I touched `lxd/devlxd.go` which has some pre-existing lint errors. Will fix shortly.

Now fixed.

File: lxd/devlxd.go [hunk 6]
```diff
@@ -379,14 +379,15 @@ type ConnPidMapper struct {
 func (m *ConnPidMapper) ConnStateHandler(conn net.Conn, state http.ConnState) {
 	unixConn, _ := conn.(*net.UnixConn)
 	if unixConn == nil {
-		logger.Error("Invalid type for devlxd net conn", logger.Ctx{"conn_type": fmt.Sprintf("%T", conn)})
+		logger.Error("Invalid type for devlxd connection", logger.Ctx{"conn_type": fmt.Sprintf("%T", conn)})
+		return
```
Comment (tomponline) [inline lxd/devlxd.go:388]: Is this a bug fix, should it be its own commit?

Comment (markylaing) [reply lxd/devlxd.go:403]: Apologies, this should have been in the previous commit. I realised that we need to return here if the `net.Conn` is not a `*net.UnixConn` or the function will panic.

**Comment by markylaing** [comment]
@tomponline I've clarified the commits to `devlxd.go` and addressed your other comments.

**Review by tomponline — APPROVED** [review]
Thanks!
