### PR TITLE
Take architecture from source config while copying

### LINKED ISSUE #18100: lxc copy API requires architecture in request
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

Ubuntu

### Distribution version

22.04

### Output of `snap list --all lxd core20 core22 core24 snapd`

```shell
Name    Version         Rev    Tracking       Publisher   Notes
core20  20260105        2717   latest/stable  canonical✓  base,disabled
core20  20260211        2769   latest/stable  canonical✓  base
core22  20260225        2411   latest/stable  canonical✓  base
core24  20260317        1587   latest/stable  canonical✓  base
lxd     5.0.6-e49d9f4   38469  5.21/stable    canonical✓  disabled,in-cohort,held
lxd     5.21.4-1374f39  38368  5.21/stable    canonical✓  in-cohort,held
snapd   2.74.1          26382  latest/stable  canonical✓  snapd
```

### System info

Kernel version: 5.15.0-174-generic
LXC version: 6.0.4
LXD version: 5.21.4
Storage backend: zfs

### Instance log

n/a

### Expected behavior

When sending API request from AMS to LXD to do container copy, the InstancesPost object doesn't have an value for architecture.
```
	req := api.InstancesPost{}
	req.Name = targetName
	req.Source.Type = "copy"
	req.Source.Source = sourceName
	req.Type = api.InstanceTypeContainer
```
The architecture should not be changed during copy, so it is expected that LXD server can retrieve it from the source container, rather than using the value in the request object.

### Actual behavior

An error is returned, showing empt in architecture field.
```
Error: Architecture isn't supported
```

### Steps to reproduce

Use the above code and not set architecture value.

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance configuration (`lxc config show <instance> --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] If a lxc command fails, output of the command with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by tugbataluy**
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md) and attest that all commits in this PR are [signed off](https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md#including-a-signed-off-by-line-in-your-commits), [cryptographically signed](https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md#commit-signature-verification), and follow this project's [commit structure](https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md#commit-structure).
- [x] I have checked and added or updated relevant documentation.

## Description
Copying an instance via the API without specifying Architecture in the request returns an "Architecture is not supported" error as mentioned in #18100. The API should inherit the architecture from the source instance automatically, as it cannot be changed during copy.

## Root cause
In `instancesPost()`, the `SourceTypeCopy` case populates `req.Type` and `req.Profiles` from the source instance but does not populate `req.Architecture`. The `SourceTypeImage` case does set it.

## Fix
Populate `req.Architecture` from the source instance in the `SourceTypeCopy` case, consistent with how `req.Type` is already handled on the line above.

Fixes #18100

### CODE REVIEW

File: test/suites/container_copy.sh [hunk 1]
```diff
@@ -131,6 +131,11 @@ test_container_copy_start() {
   lxc copy c1 c2
   [ "$(lxc list -f csv -c s c2)" = "STOPPED" ]
 
+  sub_test "Copied container inherits the source architecture"
+  source_arch="$(lxc query /1.0/instances/c1 | jq --raw-output '.architecture')"
+  target_arch="$(lxc query /1.0/instances/c2 | jq --raw-output '.architecture')"
+  [ "${source_arch}" = "${target_arch}" ]
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply test/suites/container_copy.sh]: Addressed

File: test/suites/container_copy.sh [hunk 2]
```diff
@@ -131,6 +131,11 @@ test_container_copy_start() {
   lxc copy c1 c2
   [ "$(lxc list -f csv -c s c2)" = "STOPPED" ]
 
+  sub_test "Copied container inherits the source architecture"
+  source_arch="$(lxc query /1.0/instances/c1 | jq --raw-output '.architecture')"
+  target_arch="$(lxc query /1.0/instances/c2 | jq --raw-output '.architecture')"
```
[the remark this answers is not in the document]
Comment (tugbataluy) [reply test/suites/container_copy.sh]: Addressed

File: lxd/instances_post.go [hunk 3]
```diff
@@ -1297,6 +1297,12 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
 
 			req.Type = api.InstanceType(sourceInst.Type.String())
 
+			// Use source instance's architecture.
+			req.Architecture, err = osarch.ArchitectureName(sourceInst.Architecture)
```
Comment (roosterfish) [inline lxd/instances_post.go:1301]: Can this also be an issue for the migration case? Or does it affect copy only?

Comment (tugbataluy) [reply lxd/instances_post.go:1301]: I've  investigated whether this also affects migration. It doesn't. Migration goes through `SuitableArchitectures()` in `lxd/instance/instance_utils.go:562-563`, which explicitly requires architecture in the request:
```
if slices.Contains([]api.SourceType{api.SourceTypeConversion, api.SourceTypeMigration}, req.Source.Type) && req.Architecture == "" {
    return nil, api.StatusErrorf(http.StatusBadRequest, "An architecture must be specified in migration or conversion requests")
}
```
This is intentional, as far as I understand, migrations come from external sources where the server can't look up the source instance locally, so the caller must provide it. Copy doesn't have this constraint since the source instance lives on the same server or cluster.

Comment (roosterfish) [reply lxd/instances_post.go:1301]: And if the migration happens inside a cluster between members?

Comment (tugbataluy) [reply lxd/instances_post.go:1301]: Oh now I got your point. Intra-cluster copy can fall back to migration via `clusterCopyContainerInternal` when the source and destination use different pools or the pool driver isn't remote. That function converts the request to `SourceTypeMigration` and calls `createFromMigration`, which goes through `setupInstanceArgs -> osarch.ArchitectureId(req.Architecture)`. 

The fix covers this scenario, since `req.Architecture` is populated in the transaction before `createFromCopy()` is reached.

Comment (roosterfish) [reply lxd/instances_post.go:1301]: Great thanks!

**Review by roosterfish — APPROVED** [review]
LGTM

**Review by tomponline — APPROVED** [review]
ta
