### PR TITLE
Respect instance-only flag when generating backup.yaml

### LINKED ISSUE #12370: `lxc export --instance-only` becomes useless (snapshout count check during import)
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 23.04
 * The output of "lxc info":
 ``` 
driver: lxc | qemu
  driver_version: 5.0.3 | 8.0.4
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 6.2.0-34-generic
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "23.04"
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_name: otpe.de
  server_pid: 988
  server_version: "5.18"
  storage: btrfs
  storage_version: 5.16.2
  storage_supported_drivers:
  - name: cephobject
    version: 17.2.6
    remote: true
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.11(2) (2021-01-08) / 1.02.175 (2021-01-08) / 4.47.0
    remote: false
  - name: zfs
    version: 2.1.9-2ubuntu1.1
    remote: false
  - name: btrfs

````

# Issue description

The `--instance-only` option becomes useless since a few version as the resulting archive is not importable if a snapshot exist due export time.
If no snapshot exist,  `--instance-only` makes no sense either. 

# Steps to reproduce

 1. `lxc launch images:alpine/3.18 c1`
 2. `lxc snapshot c1`
 3. `lxc export --instance-only c1`
 4. `lxc stop c1`
 5. `lxc rename c1 c2`
 6. `lxc import c1.tar.gz`

# Information to attach
Error message due step 6:
``` 
Error: Failed importing backup: Failed checking snapshots: Snapshot count in backup config and storage device are different: Backup snapshots mismatch
``` 

I think, `lxc export` should write a snapshot count of 0 to the metadata if `--instance-only` is used.

### PR DESCRIPTION
**Pull request by MusicDin**
Snapshots are no longer appended to the `backup.yaml` when instance is exported using `--instance-only` flag.

Fixes #12370

### CODE REVIEW

File: test/suites/backup.sh [hunk 1]
```diff
@@ -990,3 +990,24 @@ EOF
...
 }
+
+test_backup_export_import_instance_only() {
+  poolName=$(lxc profile device get default root pool)
+
+  ensure_import_testimage
+  ensure_has_localhost_remote "${LXD_ADDR}"
+
+  # Create an instance with snapshot.
+  lxc launch testimage c1
```
Comment (tomponline) [inline test/suites/backup.sh:1001]: Do we need to launch it for this test?

File: test/suites/backup.sh [hunk 2]
```diff
@@ -990,3 +990,24 @@ EOF
...
+  lxc snapshot c1
+
+  # Export the instance and remove it.
+  lxc export c1 "${LXD_DIR}/c1.tar.gz" --instance-only
+  lxc delete -f c1
+
+  # Import the instance from tarbll.
```
Comment (tomponline) [inline test/suites/backup.sh:1008]: tarball typo

File: test/suites/backup.sh [hunk 3]
```diff
@@ -990,3 +990,24 @@ EOF
...
+  lxc import "${LXD_DIR}/c1.tar.gz"
+
```
Comment (tomponline) [inline test/suites/backup.sh:1010]: Lets also check here that the imported instance has no snapshots.

File: test/suites/backup.sh [hunk 4]
```diff
@@ -990,3 +990,24 @@ EOF
     lxc rm -f c2
   )
 }
+
+test_backup_export_import_instance_only() {
```
Comment (tomponline) [inline test/suites/backup.sh:994]: How does this function get run?

**Review by tomponline — APPROVED** [review]
