### PR TITLE
Fix OVN leases not showing static IPs

### LINKED ISSUE #12177: Network zone records disappear after container restart when using OVN
# Required information

 * Distribution: **Ubuntu**
 * Distribution version: **22.04**
 * The output of "lxc info" or if that fails:
   * Kernel version: **5.15.0-79-generic**
   * LXC version: **5.15**
   * LXD version: **5.15**
   * Storage backend in use: **btrfs**

# Issue description

When using OVN for networking, when a container is restarted its DNS entry in the relevant network zone is gone.

# Steps to reproduce

 1. `lxc launch images:alpine/edge a1` :ok: 
 2. `lxc network list-leases ovn0` (contains entries for `a1`) :ok: 
 3. `dig @127.0.0.1 -p8853 axfr <zone>` (contains entries for `a1`) :ok: 
 4. `lxc restart a1` :ok: 
 5. `lxc network list-leases ovn0` (entries for `a1` are **gone**) :x: 
 6. `dig @127.0.0.1 -p8853 axfr <zone>` (entries for `a1` are **gone**) :x: 

Note that this behavior does not occur when **not** using OVN for networking.

When trying to troubleshoot this, and in hope that this may help someone narrow down the root of the problem, I noticed that the issue occurs **only** when the container contains a config key named `volatile.eth0.last_state.ip_addresses`.

If this key is missing, everything works as expected. This key is only added when using OVN, to the best of my understanding.
Trying to explain this behavior I can only assume that, because this key is present, the container does not ask for a DHCP lease and network zones population relies on network leases. Maybe I 'm wrong but this is what it feels like it's happening.

I hope someone with knowledge of the inner net-workings of LXD can fix this.
Let me know if you need more info.

### PR DESCRIPTION
**Pull request by MusicDin**
This PR fixes OVN leases not showing static IPs. Due to this error, dynamic leases also disappeared from the list after instance restart.

Fixes #12177

### CODE REVIEW

File: lxd/network/driver_ovn.go [hunk 1]
```diff
@@ -3935,6 +3935,26 @@ func (n *ovn) InstanceDevicePortDynamicIPs(instanceUUID string, deviceName strin
...
+	if instanceUUID == "" {
+		return nil, fmt.Errorf("Instance UUID is required")
+	}
+
+	client, err := openvswitch.NewOVN(n.state)
+	if err != nil {
+		return nil, fmt.Errorf("Failed to get OVN client: %w", err)
+	}
+
+	switchPortIPs, err := client.LogicalSwitchPortIPs(n.getIntSwitchName())
```
Comment (tomponline) [inline lxd/network/driver_ovn.go:3933]: Can we modify  client.LogicalSwitchPortIPs to accept option (if non-empty) logical switch port name that it would filter by in the ovn query, to save pulling all ip info back from ovn?

File: lxd/device/nic_ovn.go [hunk 2]
```diff
@@ -996,7 +996,7 @@ func (d *nicOVN) State() (*api.InstanceStateNetwork, error) {
 	// OVN only supports dynamic IP allocation if neither IPv4 or IPv6 are statically set.
 	if d.config["ipv4.address"] == "" && d.config["ipv6.address"] == "" {
 		instanceUUID := d.inst.LocalConfig()["volatile.uuid"]
-		dynamicIPs, err := d.network.InstanceDevicePortDynamicIPs(instanceUUID, d.name)
+		dynamicIPs, err := d.network.InstanceDevicePortIPs(instanceUUID, d.name)
 		if err == nil {
 			for _, dynamicIP := range dynamicIPs {
```
Comment (tomponline) [inline lxd/device/nic_ovn.go:1001]: logic here needs to exclude any ips that are specified in the static NIC config otherwise we'll end up with duplicates

File: lxd/device/nic_ovn.go [hunk 3]
```diff
@@ -996,7 +996,7 @@ func (d *nicOVN) State() (*api.InstanceStateNetwork, error) {
 	// OVN only supports dynamic IP allocation if neither IPv4 or IPv6 are statically set.
 	if d.config["ipv4.address"] == "" && d.config["ipv6.address"] == "" {
 		instanceUUID := d.inst.LocalConfig()["volatile.uuid"]
-		dynamicIPs, err := d.network.InstanceDevicePortDynamicIPs(instanceUUID, d.name)
+		dynamicIPs, err := d.network.InstanceDevicePortIPs(instanceUUID, d.name)
```
[the remark this answers is not in the document]
Comment (tomponline) [reply lxd/device/nic_ovn.go:999]: suggest devIPs for consistency with other function

File: lxd/device/nic_ovn.go (hunk 2 above)
Comment (MusicDin) [reply lxd/device/nic_ovn.go:1001]: I was looking at this one, but this part of code is executed only if both `ipv4.address` and `ipv6.address` are empty (line 997), so there should be no need for that.

Am I missing something?

Comment (tomponline) [reply lxd/device/nic_ovn.go:1001]: Can you test if that statement: 

> // OVN only supports dynamic IP allocation if neither IPv4 or IPv6 are statically set.

Is still true with sticky IPs in play?

Comment (MusicDin) [reply lxd/device/nic_ovn.go:1001]: Setting only one static IP (either IPv4 or IPv6) results in the IP of the other family to be dynamically set. So, this should no longer be true?

File: lxd/network/driver_ovn.go (hunk 1 above)
Comment (tomponline) [reply lxd/network/driver_ovn.go:3933]: Makes sense to me!

File: lxd/device/nic_ovn.go (hunk 2 above)
Comment (tomponline) [reply lxd/device/nic_ovn.go]: Setting IPv4 to static also sets IPv6 to EU64 statically in OVN:

```
lxc launch ubuntu:jammy c1 --network ovn1 -d eth0,ipv4.address=10.143.147.10

sudo ovn-nbctl list logical_switch_port
addresses           : ["00:16:3e:8b:45:8f 10.143.147.10 fd42:875e:7708:3d62:216:3eff:fe8b:458f"]
```

But setting IPv6 statically without IPv4 results in another bug:

```
lxc launch ubuntu:jammy c1 --network ovn1 -d eth0,ipv6.address=fd42:875e:7708:3d62:216:3eff:fe8b:458f
Creating c1
Starting c1                                 
Error: Failed to start device "eth0": Failed setting up OVN port: Insufficient dynamic addresses allocated
Try `lxc info --show-log local:c1` for more info
```

Please can you look into that also.

File: lxd/network/openvswitch/ovn.go [hunk 4]
```diff
@@ -1195,6 +1195,35 @@ func (o *OVN) LogicalSwitchPortAdd(switchName OVNSwitch, portName OVNSwitchPort,
 	return nil
 }
 
+// LogicalSwitchPortIPs returns a list of IPs for a switch port.
+func (o *OVN) LogicalSwitchPortIPs(portName OVNSwitchPort) ([]net.IP, error) {
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:1199]: This function is inefficient as it makes 2 calls to OVN's northbound (nb) database.

One for `lsp-get-addresses` and agan in `o.LogicalSwitchPortDynamicIPs()`.

It would be more efficient and more consistent to use the same approach used in ` LogicalSwitchIPs` by retrieving both fields in a single request, but just filtered by the port name in question so only a single row is returned.

So you need to change the `--find` argument value so it searches the `name` field I think.

**Review by tomponline — COMMENTED** [review]
This is on the right track, but lets make sure the implementation of the new function is efficient.

**Comment by tomponline** [comment]
@MusicDin once you're happy with this can you also run this script https://github.com/canonical/lxd-ci/blob/main/tests/network-ovn inside a fresh Focal VM, you'll need to modify it slightly so it doesn't remove the lxd snap first, so that you can sideload your custom lxd binary into it.

File: lxd/network/openvswitch/ovn.go [hunk 5]
```diff
@@ -1195,6 +1195,26 @@ func (o *OVN) LogicalSwitchPortAdd(switchName OVNSwitch, portName OVNSwitchPort,
...
+	addressesRaw, err := o.nbctl("--format=table", "--no-headings", "--data=bare", "--column=addresses,dynamic_addresses", "find", "logical_switch_port", fmt.Sprintf("name=%s", string(portName)))
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:1200]: I would encourage you to use the csv format for consistency with other commands, it also helps avoid any misunderstanding of spaces. I did use table in the past and found it had problems parsing it in some cases so generally use csv where possible.

Comment (MusicDin) [reply lxd/network/openvswitch/ovn.go:1200]: Ok, this is what I thought. I will change it.

**Comment by tomponline** [comment]
Converted to draft until testing confirmed.

File: lxd/device/nic_ovn.go (hunk 2 above)
Comment (MusicDin) [reply lxd/device/nic_ovn.go]: If `ipv6.dhcp.stateful` is enabled, setting static IPv4 results in IPv6 (EUI64) not being shown.
```go
// OVN only supports dynamic IP allocation if neither IPv4 or IPv6 are statically set
if d.config["ipv4.address"] == "" && d.config["ipv6.address"] == "" {
   ...
}
```

Because it is listed under leases:
```
$ lxc launch ubuntu:22.04 c2 -n ovn -d eth0,ipv4.address=10.100.100.15

$ lxc ls
+------+---------+----------------------+------------------------------------------------+-----------+-----------+
| NAME |  STATE  |         IPV4         |                      IPV6                      |   TYPE    | SNAPSHOTS |
+------+---------+----------------------+------------------------------------------------+-----------+-----------+
| c2   | RUNNING | 10.100.100.15 (eth0) |                                                | CONTAINER | 0         |
+------+---------+----------------------+------------------------------------------------+-----------+-----------+


$ lxc network list-leases ovn
+----------+-------------------+-----------------------------------------+---------+
| HOSTNAME |    MAC ADDRESS    |               IP ADDRESS                |  TYPE   |
+----------+-------------------+-----------------------------------------+---------+
| c2       | 00:16:3e:86:d5:d5 | 10.100.100.15                           | STATIC  |
+----------+-------------------+-----------------------------------------+---------+
| c2       | 00:16:3e:86:d5:d5 | fd42:1000:1000:1000:216:3eff:fe86:d5d5  | DYNAMIC |
+----------+-------------------+-----------------------------------------+---------+
| ovn.gw   |                   | 10.100.100.1                            | GATEWAY |
+----------+-------------------+-----------------------------------------+---------+
| ovn.gw   |                   | fd42:1000:1000:1000::1                  | GATEWAY |
+----------+-------------------+-----------------------------------------+---------+
```

However, if static IPv6 is set (and IPv4 is not), OVN router does not provide any dynamic IP (even though there is enough IPs available).

Commenting out the error line results in only static IPv6 being generated:
```
lxc launch ubuntu:22.04 c1 -n ovn -d eth0,ipv6.address=fd42:1000:1000:1000:1234:1234:1234:1234

$ lxc ls
+------+---------+----------------------+------------------------------------------------+-----------+-----------+
| NAME |  STATE  |         IPV4         |                      IPV6                      |   TYPE    | SNAPSHOTS |
+------+---------+----------------------+------------------------------------------------+-----------+-----------+
| c1   | RUNNING |                      | fd42:1000:1000:1000:1234:1234:1234:1234 (eth0) | CONTAINER | 0         |
+------+---------+----------------------+------------------------------------------------+-----------+-----------+

$ lxc network list-leases ovn
+----------+-------------------+-----------------------------------------+---------+
| HOSTNAME |    MAC ADDRESS    |               IP ADDRESS                |  TYPE   |
+----------+-------------------+-----------------------------------------+---------+
| c1       | 00:16:3e:06:31:3d | fd42:1000:1000:1000:1234:1234:1234:1234 | STATIC  |
+----------+-------------------+-----------------------------------------+---------+
| ovn.gw   |                   | 10.100.100.1                            | GATEWAY |
+----------+-------------------+-----------------------------------------+---------+
| ovn.gw   |                   | fd42:1000:1000:1000::1                  | GATEWAY |
+----------+-------------------+-----------------------------------------+---------+
```

---

This is actually the case for both IPv6 and IPv4, but when IPv4 is set, EUI64 is generated which prevents the error. 

I'll dive deeper into this after fixing other issues.

**Comment by MusicDin** [comment]
Test `lxd-ci/tests/network-ovn` is passing, however, I would still like to dive deeper into static IP issues before having it reviewed again.

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
> I would still like to dive deeper into static IP issues before having it reviewed again.

It LGTM, we should probably prevent setting `ipv6.address` if `ipv4.address` isnt also set.

**Comment by MusicDin** [comment]
Okey, I'll do it.
