### PR TITLE
LXC: Implement profile expansion on lxc copy

### LINKED ISSUE #13063: lxc copy --device doesn't expand profile devices when overriding config
```
lxc profile show default
name: default
description: Default LXD profile
config: {}
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
used_by:
- /1.0/instances/v1

lxc copy v1 v2  -d eth0,hwaddr=00:16:3e:eb:66:cc
Error: Failed creating instance record: Invalid device type ""
```

Expected result is the same as `lxc init --device`, that if the eth0 device exists in the profile(s) then its equivalent to doing:

```
lxc copy v1 v2
lxc config device override v2 eth0 hwaddr=00:16:3e:eb:66:cc
```

### PR DESCRIPTION
**Pull request by hamistao**
Fixes #13063

### CODE REVIEW

**Comment by hamistao** [comment]
@masnax @tomponline While working on this PR I was discussing with Max the usage of the --device flag on copy, should it indicate device creation as well?
For example, this operation below doesn't work, but maybe it should:
lxc profile device remove myremote:p1 root
lxc copy t1 myremote:t1 -d root,type=disk,pool=default,path=/
Error: Failed instance creation: Can't find a storage pool for the instance to use.
If you think whis makes sense we can discuss and if we agree this makes sense I can create an issue on the subject and start thinking about how to implement it.

**Comment by tomponline** [comment]
> @masnax @tomponline While working on this PR I was discussing with Max the usage of the --device flag on copy, should it indicate device creation as well? For example, this operation below doesn't work, but maybe it should: lxc profile device remove myremote:p1 root lxc copy t1 myremote:t1 -d root,type=disk,pool=default,path=/ Error: Failed instance creation: Can't find a storage pool for the instance to use. If you think whis makes sense we can discuss and if we agree this makes sense I can create an issue on the subject and start thinking about how to implement it.

Suggest for now we keep the functionality aligned with `lxc init` and `lxc import` and do not support adding new devices this way.

**Review by tomponline — CHANGES_REQUESTED** [review]
Please can you add some tests to check for regressions. Thanks

**Comment by tomponline** [comment]
> sorry, I am not sure I understand what you mean by regressions

By adding tests for the functionality you're adding you will ensure any future regressions are caught early.

File: lxc/copy.go [hunk 1]
```diff
@@ -272,21 +300,49 @@ func (c *cmdCopy) copyInstance(conf *config.Config, sourceResource string, destR
 			entry.Profiles = []string{}
 		}
 
+		// If there are device overrides that are expected to be applied to profile devices then load the profiles
```
Comment (tomponline) [inline lxc/copy.go:303]: Can we avoid this duplication by making a temporary function that can be called from both places?

File: test/suites/container_devices_nic_bridged.sh [hunk 2]
```diff
@@ -689,7 +689,14 @@ test_container_devices_nic_bridged() {
   lxc config device get foo eth0 ipv4.address | grep -Fx '192.0.2.233'
   lxc config device get foo eth0 ipv6.address | grep -Fx '2001:db8::3'
   lxc start foo
+
+  # Test container can be copied with device override to fix conflict.
+  lxc copy foo foo-copy --device eth0,ipv4.address=192.0.2.234 --device eth0,ipv6.address=2001:db8::4 --device eth0,hwaddr=0a:92:a7:0d:b7:d8
```
Comment (tomponline) [inline test/suites/container_devices_nic_bridged.sh:694]: Please can you add a test for copying a snapshot with device overrides too.

Comment (hamistao) [reply test/suites/container_devices_nic_bridged.sh]: do you think I should include restoring an instances from the copied snapshots and starting them?

File: lxc/copy.go [hunk 3]
```diff
@@ -33,6 +33,46 @@ type cmdCopy struct {
 	flagAllowInconsistent bool
 }
 
+func expandProfile(destRemote lxd.InstanceServer, serverSideProfiles []string, deviceOverrides map[string]map[string]string) (map[string]map[string]string, error) {
```
Comment (tomponline) [inline lxc/copy.go:36]: Can we use this function in `cmdInit.create` here https://github.com/canonical/lxd/blob/main/lxc/init.go#L303-L325?

Comment (hamistao) [reply lxc/copy.go:36]: Yes, and I think here also https://github.com/canonical/lxd/blob/main/lxd/api_internal.go#L792-L815

File: shared/util.go [hunk 4]
```diff
@@ -1358,3 +1358,35 @@ func TargetDetect(target string) (targetNode string, targetGroup string) {
 
 	return
 }
```
Comment (roosterfish) [inline shared/util.go:1360]: Just a general comment for the commit message. We tend to use the Go package name as the prefix so in this case it would be something like `lxd/shared: ...`.

File: shared/util.go [hunk 5]
```diff
@@ -1358,3 +1358,35 @@ func TargetDetect(target string) (targetNode string, targetGroup string) {
...
+
+// ApplyDeviceOverrides handles the logic for applying device overrides.
+// Receives the profile and local devices and the device overrides.
+// Returns the resulting list of devices.
+func ApplyDeviceOverrides(localDevices map[string]map[string]string, profileDevices map[string]map[string]string, deviceOverrides map[string]map[string]string) (map[string]map[string]string, error) {
+	devicesMap := localDevices
```
Comment (roosterfish) [inline shared/util.go:1366]: Is there a specific reason to reassign the map here? Wouldn't the modification on `devicesMap` still be propagated to `localDevices` as its using the same map underneath?

File: shared/util.go [hunk 6]
```diff
@@ -1358,3 +1358,35 @@ func TargetDetect(target string) (targetNode string, targetGroup string) {
...
+
+	// Allow setting device overrides
```
Comment (roosterfish) [inline shared/util.go:1368]: Dot is missing at the end.

File: lxc/utils.go [hunk 7]
```diff
@@ -39,6 +39,33 @@ func runBatch(names []string, action func(name string) error) []batchResult {
 	return results
 }
 
+// Get devices from a list of profiles.
+func getProfileDevices(destRemote lxd.InstanceServer, serverSideProfiles []string) (map[string]map[string]string, error) {
+	profileDevices := make(map[string]map[string]string)
```
Comment (roosterfish) [inline lxc/utils.go:44]: Can you please move this a bit more down right before the `for` loop as this is the first time it's used. It keeps things together.

File: lxd/api_internal.go [hunk 8]
```diff
@@ -791,28 +791,9 @@ func internalImportFromBackup(s *state.State, projectName string, instName strin
...
-			for k, v := range deviceOverrides[deviceName] {
-				backupConf.Container.Devices[deviceName][k] = v
-			}
-		} else {
-			// Check device exists in expanded profile devices.
-			profileDeviceConfig, found := backupConf.Container.ExpandedDevices[deviceName]
-			if !found {
-				return fmt.Errorf("Cannot override config for device %q: Device not found in profile devices", deviceName)
-			}
+	resultingDevices, err := shared.ApplyDeviceOverrides(backupConf.Container.Devices, backupConf.Container.ExpandedDevices, deviceOverrides)
```
Comment (roosterfish) [inline lxd/api_internal.go:794]: There is a `if err != nil` condition missing.

File: lxc/copy.go [hunk 9]
```diff
@@ -181,23 +181,39 @@ func (c *cmdCopy) copyInstance(conf *config.Config, sourceResource string, destR
...
+		// If there are device overrides that are expected to be applied to profile devices then perform
+		// profile expansion.
+		if needProfileExpansion {
+			profileDevices, err = getProfileDevices(dest, entry.Profiles)
+			if err != nil {
+				return err
 			}
 		}
 
+		// Apply device overrides
```
Comment (roosterfish) [inline lxc/copy.go:206]: Dots missing on the comments.

**Review by roosterfish — CHANGES_REQUESTED** [review]

File: shared/util.go (hunk 5 above)
Comment (hamistao) [reply shared/util.go]: I thought it made sense because now it represents the final list of devices and not the initial local devices but in second thought I agree that it is unnecessary so I removed it

File: lxc/utils.go [hunk 10]
```diff
@@ -39,6 +39,34 @@ func runBatch(names []string, action func(name string) error) []batchResult {
 	return results
 }
 
+// Get devices from a list of profiles.
+func getProfileDevices(destRemote lxd.InstanceServer, serverSideProfiles []string) (map[string]map[string]string, error) {
```
Comment (roosterfish) [inline lxc/utils.go:43]: We usually start the description with the functions name like so: `// getProfileDevices returns devices from a list of profiles.` 
I guess this file is a bad example as the other functions don't do it so it's not a blocker.

File: lxc/init.go [hunk 11]
```diff
@@ -281,47 +282,16 @@ func (c *cmdInit) create(conf *config.Config, args []string) (lxd.InstanceServer
 	// If there are device overrides that are expected to be applied to profile devices then load the profiles
 	// that would be applied server-side.
 	if needProfileExpansion {
-		// If the list of profiles is empty then LXD would apply the default profile on the server side.
```
Comment (roosterfish) [inline lxc/init.go:284]: Don't we want to keep this comment to keep the information on what is happening in case the list of devices is empty?

File: lxc/copy.go [hunk 12]
```diff
@@ -181,23 +181,39 @@ func (c *cmdCopy) copyInstance(conf *config.Config, sourceResource string, destR
 			entry.Profiles = []string{}
 		}
 
-		// Allow setting additional config keys
-		for key, value := range configMap {
-			entry.Config[key] = value
+		// Check to see if any of the overridden devices are for devices that are not yet defined in the
+		// local devices (and thus maybe expected to be coming from profiles).
```
Comment (roosterfish) [inline lxc/copy.go:185]: `and thus may be`?

File: lxc/copy.go [hunk 13]
```diff
@@ -269,23 +285,41 @@ func (c *cmdCopy) copyInstance(conf *config.Config, sourceResource string, destR
...
 			}
 		}
 
+		// Apply device overrides.
+		resultingDevices, err := shared.ApplyDeviceOverrides(entry.Devices, profileDevices, deviceOverrides)
+		if err != nil {
+			return err
+		}
+
+		entry.Devices = resultingDevices
```
Comment (roosterfish) [inline lxc/copy.go:316]: Can you do the same as above and assign `entry.Devices` directly when calling `shared.ApplyDeviceOverrides`?

**Review by roosterfish — CHANGES_REQUESTED** [review]
Looking good, just a few nits.

**Comment by roosterfish** [comment]
And please make sure to remove the `.go` suffixes from the commit messages. See my comment from before https://github.com/canonical/lxd/pull/13118#discussion_r1535956275.

File: lxc/init.go (hunk 11 above)
Comment (hamistao) [reply lxc/init.go:284]: I added this information above getProfileDevices but included it here also

**Review by roosterfish — APPROVED** [review]
LGTM!

**Review by tomponline — APPROVED** [review]
Thanks!
