### PR TITLE
storage: Allow `lost+found` subdirectory when storage pool source is root of the filesystem

### LINKED ISSUE #13630: storage pool create failure due to ext4's lost+found directory
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04 (Jammy)
 * The output of "snap list --all lxd core20 core22 core24 snapd":
 ```
 snap list --all lxd core20 core22 core24 snapd
Name    Version         Rev    Tracking       Publisher   Notes
core20  20240227        2264   latest/stable  canonical✓  base,disabled
core20  20240416        2318   latest/stable  canonical✓  base
core22  20240111        1122   latest/stable  canonical✓  base,disabled
core22  20240408        1380   latest/stable  canonical✓  base
lxd     5.21.1-98dad8f  28323  5.21/stable    canonical✓  disabled
lxd     5.21.1-d46c406  28460  5.21/stable    canonical✓  -
snapd   2.62            21465  latest/stable  canonical✓  snapd,disabled
snapd   2.63            21759  latest/stable  canonical✓  snapd
```
 * The output of "lxc info" or if that fails:
 https://paste.ubuntu.com/p/mK7FsqdP5R/

# Issue description

When an empty ext4 filesystem is created, normally it creates 
a special `lost+found` directory to put broken/recovered data when `fsck` is run.

However, LXD seems to see this file and treat it as a `used` directory, hence
storage creation attempts appear to fail
```
➜  ~ ls -la /iscsistore
drwx------  2 root root 16384 Jun 17 15:48 lost+found

➜  ~ lxc storage create iscsistore dir source=/iscsistore
Error: Source path '/var/lib/snapd/hostfs/iscsistore' isn't empty
```

# Steps to reproduce

 1. Create an empty ext4 filesystem (`mkfs.ext4 /dev/<device>`) and mount it.
 2. Create a `dir` pool on the mount: `lxc storage create iscsistore dir source=/iscsistore`
 3. Observe failure

While one can remove the lost+found directory, it is still a documented function of the filesystem and thus something LXD should be able to be aware of or otherwise ignore.

### PR DESCRIPTION
**Pull request by MusicDin**
Allow `lost+found` subdirectory when storage pool's source is a root of the mounted filesystem.

Fixes #13630

### CODE REVIEW

File: lxd/storage/drivers/driver_dir.go [hunk 1]
```diff
@@ -87,7 +89,22 @@ func (d *dir) Create() error {
...
-		return fmt.Errorf("Source path %q isn't empty", sourcePath)
+		// If directory is not empty, the "lost+found" subdirectory is acceptable when
+		// the source path is the root of a mounted filesystem.
+		if !filesystem.IsMountPoint(sourcePath) {
+			return fmt.Errorf("Source path %q isn't empty", sourcePath)
+		}
+
+		entries, err := os.ReadDir(sourcePath)
+		if err != nil {
+			return fmt.Errorf("Failed to read directory content of source path %q", sourcePath)
```
Comment (tomponline) [inline lxd/storage/drivers/driver_dir.go:100]: We should include the error in the error returned too

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
Thanks!
