### PR TITLE
Auth: TLS driver should return a false permission checker when client is restricted.

### LINKED ISSUE #12846: refreshing or creating lxd vm from maas output error  Certificate is restricted
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version:  6.5.0-15-generic
   * LXC version: "5.20"
   * LXD version: "5.20"
   * Storage backend in use:  pool1   | dir    | /mnt/pool1/       

# Issue description

From Maas creating a VM reports Certificate is restricted. This error appear also if I refresh the KVM from mass

# Steps to reproduce

 1. Step one : MAAS -> Lxd -> Add Lxd Machine -> compose machine.
  2. Step two: Also MAAS gui -> Lxd -> myLxdHost -> refresh host
 

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

From rackd.log 

```
2024-02-09 06:33:53 provisioningserver.rpc.pods: [critical] Failed to discover VM host.
	Traceback (most recent call last):
	  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.10/threading.py", line 953, in run
	    self._target(*self._args, **self._kwargs)
	  File "/snap/maas/32469/usr/lib/python3/dist-packages/twisted/_threads/_threadworker.py", line 47, in work
	    task()
	  File "/snap/maas/32469/usr/lib/python3/dist-packages/twisted/_threads/_team.py", line 182, in doWork
	    task()
	--- <exception caught here> ---
	  File "/snap/maas/32469/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 244, in inContext
	    result = inContext.theWork()  # type: ignore[attr-defined]
	  File "/snap/maas/32469/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 260, in <lambda>
	    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
	  File "/snap/maas/32469/usr/lib/python3/dist-packages/twisted/python/context.py", line 117, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/snap/maas/32469/usr/lib/python3/dist-packages/twisted/python/context.py", line 82, in callWithContext
	    return func(*args, **kw)
	  File "/snap/maas/32469/lib/python3.10/site-packages/provisioningserver/utils/twisted.py", line 203, in wrapper
	    result = func(*args, **kwargs)
	  File "/snap/maas/32469/lib/python3.10/site-packages/provisioningserver/drivers/pod/lxd.py", line 295, in discover
	    discovered_pod = self._discover(client, pod_id, context)
	  File "/snap/maas/32469/lib/python3.10/site-packages/provisioningserver/drivers/pod/lxd.py", line 367, in _discover
	    storage_pools = client.storage_pools.all()
	  File "/snap/maas/32469/usr/lib/python3/dist-packages/pylxd/models/storage_pool.py", line 85, in all
	    response = client.api.storage_pools.get()
	  File "/snap/maas/32469/usr/lib/python3/dist-packages/pylxd/client.py", line 210, in get
	    self._assert_response(
	  File "/snap/maas/32469/usr/lib/python3/dist-packages/pylxd/client.py", line 162, in _assert_response
	    raise exceptions.LXDAPIException(response)
	pylxd.exceptions.LXDAPIException: Certificate is restricted

```

### PR DESCRIPTION
**Pull request by markylaing**
The TLS authorization driver was returning an error on calls to `GetPermissionChecker` when it should have been returning `allowFunc(false)` to indicate the user does not have the given entitlement on any resources of the given type. 

Closes #12846

### CODE REVIEW

File: test/suites/tls_restrictions.sh [hunk 1]
```diff
@@ -30,6 +30,9 @@ test_tls_restrictions() {
   # Confirm no project visible when none listed
   [ "$(lxc_remote project list localhost: --format csv | wc -l)" = 0 ]
 
+  # Confirm we can still view storage pools
+  [ "$(lxc_remote storage list localhost: --format csv | wc -l)" = 1 ]
```
Comment (tomponline) [inline test/suites/tls_restrictions.sh:34]: In a separate PR can you add a check to check config is not accessible please?

**Review by tomponline — APPROVED** [review]
