### PR TITLE
Auth: Use correct entity type when enriching storage pool access entitlements

### LINKED ISSUE #16033: Storage pool list ignores entitlements
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

Ubuntu

### Distribution version

snap

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
latest/edge
```

### Output of "lxc info" or system info if it fails

```shell
-
```

### Issue description

The `GET /1.0/storage-pools?recursion=1&with-access-entitlements=can_edit,can_delete` request does not return any access information on the pools in the response.

When issuing `GET /1.0/storage-pools/lvm1?recursion=1&with-access-entitlements=can_edit,can_delete` on a pool that is also part of the list response, the `access_entitlements` field is filled.

Expectation is for the storage pool list endpoint to also include the `access_entitlements`.

### Steps to reproduce

1. Authenticate with a restricted TLS certificate and have server admin permissions.
2. Create a storage pool.
3. Fetch list of storage pools with entitlements.
4. See the entitlements missing from the api response.

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by markylaing**
The `reportEntitlements` function accepts a `map[*api.URL]auth.EntitlementReporter`. 

If this map contains a single entry, then `(auth.Authorizer).CheckPermission` is called for each requested entitlement against the single URL. `CheckPermission` doesn't need an entity type because this can be derived from the given URL.

If the map contains multiple entries, then `(auth.Authorizer).GetPermissionChecker` is called for each requested entitlement, using the given `entity.Type`. This is done for efficiency.

In this case, the wrong entity type was passed into `reportEntitlements` and subsequently `GetPermissionChecker`. When the permission checker was called with storage pool URLs, it wasn't able to match this against any storage volume URLs that it held internally.

In fact, it was logging an error:
```
ERROR  [2025-07-15T12:17:00Z] Unexpected permission checker input URL       actual_entity_type=storage_pool driver=embedded-openfga entitlement=can_edit entity_type=storage_volume expected_entity_type=storage_volume protocol=oidc url=/1.0/storage-pools/foo username=test-user@example.com
```

This PR changes the entity type in the `reportEntitlements` call to `entity.StoragePool` so that entitlements are reported correctly when listing storage pools. Tests have been added to catch this case.

Closes #16033

### CODE REVIEW

**Comment by tomponline** [comment]
Should that error scenario be changed from a log to an error response?

**Comment by markylaing** [comment]
> Should that error scenario be changed from a log to an error response?

Potentially. That would require changing the `auth.PermissionChecker` signature. Often we're checking these things in a loop like:
```
for _, inst := range instances {
    if !canView(entity.InstanceURL(inst.Project, inst.Name)) {
        continue
    }
    
    /* ... */
}
```
so this would mean an error check on all of those calls. It's annoying but probably better then a silent failure and would be clearer to debug

**Comment by markylaing** [comment]
> Should that error scenario be changed from a log to an error response?

Should this be a follow up? Or would you like me to address it now?

File: test/suites/auth.sh [hunk 1]
```diff
@@ -1221,13 +1221,28 @@ entities_enrichment_with_entitlements() {
...
+
+  # Test multiple pools
+  lxc storage create foo dir
+  lxc auth group permission add test-group storage_pool foo can_edit
   all_storage_pools=$(lxc_remote query "oidc:/1.0/storage-pools?recursion=1&with-access-entitlements=can_edit,can_delete")
-  if ! jq -e -r --arg pool_name "$pool_name" '.[] | select(.name == $pool_name) | .access_entitlements | sort | @csv == "\"can_delete\",\"can_edit\""' <<< "$all_storage_pools";  then
-    echo "Second check failed (or pool not found)!" >&2
-    false
-  fi
+  jq -e -r --arg pool_name "$pool_name" '
```
Comment (tomponline) [inline test/suites/auth.sh]: Please can you use long form flags where they exist, for documentation reasons.

Also can we have a comment explaining this complex command.

**Comment by tomponline** [comment]
> > Should that error scenario be changed from a log to an error response?
> 
> Should this be a follow up? Or would you like me to address it now?

Can we include in this?

File: test/suites/auth.sh (hunk 1 above)
Comment (markylaing) [reply test/suites/auth.sh]: Gabriel added these checks a while ago and this is (almost) a copy/paste. It would be good to do a check of all of them as there was some unnecessary logic I removed.

**Comment by markylaing** [comment]
@tomponline Before I refactor I just want to clarify.

The existing signature for the `PermissionChecker` is:
```go
type PermissionChecker func(entityURL *api.URL) bool
```
Which can only log errors, but has the advantage that it's usage is clean:
```go
if !checkAccess(myurl) {
    continue
}
```

Do you prefer:
```go
type PermissionChecker func(entityURL *api.URL) (bool, error)
```
with usage:
```go
hasAccess, err := checkAccess(myurl)
if err != nil {
    return response.SmartError(err)
} else if !hasAccess {
    continue
}
```

Or 
```go
type PermissionChecker func(entityURL *api.URL) error
```
with usage
```go
err := checkAccess(myurl)
if err != nil {
    if auth.IsDeniedError(err) {
        continue
    }

    return response.SmartError(err)
}
```

I am favouring the second option.

**Comment by tomponline** [comment]
2nd option seems fine to me, both are clear though.

**Comment by markylaing** [comment]
> 2nd option seems fine to me, both are clear though.

I've been working on this for a while now and it doesn't make sense. For these errors to be informative we need to surface the url that we failed to check permission with. We can't do that because we will likely expose URLs of entities that the caller can't view. For now I will leave it as an error log and we can reinvestigate in the future.

**Comment by tomponline** [comment]
> For now I will leave it as an error log and we can reinvestigate in the future.

OK

**Comment by markylaing** [comment]
This PR mainly now consists of improvements to the entitlement reporting tests.

File: test/suites/auth.sh [hunk 2]
```diff
@@ -1199,6 +1199,23 @@ auth_ovn() {
...
+  # 5. Evaluates a conditional (asserting that the access entitlements are correct).
+  #
+  # When performing assertions on an array of responses, the "all" function is used (see https://jqlang.org/manual/#all).
+  # This function evaluates a conditional for all elements of an array, and returns true only if the conditional returns
+  # true for all elements. In all cases, this:
+  # 1. Calls "all".
+  # 2. Performs different assertions (steps 2-5 above) for each element in the array.
+  # 3. Has an "else" condition containing only "false". This asserts that we do not expect any extra array elements.
+  #
+  # Sometimes an --arg is passed into jq. This is to make bash variables referencable within jq.
```
Comment (simondeziel) [inline test/suites/auth.sh]: `s/referencable/referenceable/` I think.

Comment (markylaing) [reply test/suites/auth.sh]: Fixed.

File: test/suites/auth.sh [hunk 3]
```diff
@@ -1446,12 +1508,10 @@ entities_enrichment_with_entitlements() {
...
   lxc auth group permission add test-group network_zone zone2 can_delete project=default
-  [ "$(lxc_remote query "oidc:/1.0/network-zones/zone1?project=default&with-access-entitlements=can_view,can_edit,can_delete" | jq -r '.access_entitlements | sort | @csv')" = '"can_view"' ]
-  [ "$(lxc_remote query "oidc:/1.0/network-zones/zone2?project=default&with-access-entitlements=can_view,can_edit,can_delete" | jq -r '.access_entitlements | sort | @csv')" = '"can_delete","can_edit","can_view"' ]
-  all_network_zones=$(lxc_remote query "oidc:/1.0/network-zones?project=default&recursion=1&with-access-entitlements=can_view,can_edit,can_delete")
-  if ! jq -e -r '
+  lxc_remote query "oidc:/1.0/network-zones/zone1?project=default&with-access-entitlements=can_view,can_edit,can_delete" | jq -e '.access_entitlements | sort | @csv == "\"can_view\""'
+  lxc_remote query "oidc:/1.0/network-zones/zone2?project=default&with-access-entitlements=can_view,can_edit,can_delete" | jq -e '.access_entitlements | sort | @csv == "can_delete","can_edit","can_view"'
+  lxc_remote query "oidc:/1.0/network-zones?project=default&recursion=1&with-access-entitlements=can_view,can_edit,can_delete" | jq -e -r '
```
[the remark this answers is not in the document]
Comment (markylaing) [reply test/suites/auth.sh]: Fixed.

**Comment by tomponline** [comment]
@markylaing ready for review?

**Comment by markylaing** [comment]
Yep good to go :)

File: test/suites/auth.sh
Comment (tomponline) [inline test/suites/auth.sh:1]: Great comment thanks!

**Review by tomponline — APPROVED** [review]
LGTM!
