### PR TITLE
instance_exec: Add contraint validation

### LINKED ISSUE #12216: Instance exec api constraint validation
# Issue description

When getting `1.0/instances/wired-hamster/exec` with an invalid payload, the API should return an error. Specifically, the options `"record-output": true` and `"interactive": true` are mutually exclusive. When both are provided in the payload, the API returns links to web sockets, which fail to connect for VMs. Confusingly, they do work for containers.

We encountered this problem in LXD-UI, see https://github.com/canonical/lxd-ui/issues/450 and the linked PR for more details.

# Steps to reproduce

 1. `POST` to the `1.0/instances/wired-hamster/exec` endpoint
 (replace with a valid, currently running vm based on the jammy cloud image)
 2. Provide as payload 
```
{
  "command": [
    "bash"
  ],
  "record-output": true,
  "wait-for-websocket": true,
  "environment": {
    "TERM": "xterm-256color",
    "HOME": "/root"
  },
  "interactive": true,
  "group": 0,
  "user": 0
}
```
 3. Connecting to the returned websockets will fail: the sockets will be closed after some seconds.
 4. The expectation is that the `POST` request will not succeed, but fail with an error -- something like `record-output cannot be used in combination with wait-for-websocket`.

### PR DESCRIPTION
**Pull request by monstermunchkin**
This returns an error if `record-output` and `wait-for-websocket`, or
`interactive` and `record-output` are used in combination.

Fixes #12216

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

### CODE REVIEW

File: lxd/instance_exec.go [hunk 1]
```diff
@@ -542,6 +542,11 @@ func instanceExecPost(d *Daemon, r *http.Request) response.Response {
 		return response.BadRequest(err)
 	}
 
+	// Contraint validation.
+	if post.RecordOutput && post.WaitForWS {
```
Comment (tomponline) [inline lxd/instance_exec.go:546]: Should we also reject post.Interactive with post.RecordOutput?

Comment (monstermunchkin) [reply lxd/instance_exec.go:546]: Yes, we should.

File: lxd/instance_exec.go [hunk 2]
```diff
@@ -542,6 +542,15 @@ func instanceExecPost(d *Daemon, r *http.Request) response.Response {
 		return response.BadRequest(err)
 	}
 
+	// Contraint validations.
```
Comment (tomponline) [inline lxd/instance_exec.go:545]: Typo

**Review by simondeziel — APPROVED** [review]

File: lxd/instance_exec.go (hunk 2 above)
Comment (monstermunchkin) [reply lxd/instance_exec.go]: Fixed

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
Thanks!
