### PR TITLE
zfs: Support zfs pools containing '/' in the patch

### LINKED ISSUE #12465: ZFS: storage_zfs_drop_block_volume_filesystem_extension is broken on non-trivial pools
https://github.com/canonical/lxd/blob/e186300af4a51f77410bf6d47ade50c1b87d8bf6/lxd/storage/drivers/driver_zfs.go#L688
If I understand this correctly `.Split("/", 3)` in here is too naive, it seems to assume that zfs root dataset == the lxd pool root.
In python, something like `foo.rsplit("/", 3)` (with the r in rsplit meaning the string is split up to 3 times from right to left instead of left to right) would probably suffice to fix this.

Please consider the following ZFS layout:
```
NAME                                            USED  AVAIL     REFER  MOUNTPOINT
zroot/data/lxd_pools/default                    182G  9.04T      192K  legacy
zroot/data/lxd_pools/default/buckets            192K  9.04T      192K  legacy
zroot/data/lxd_pools/default/containers        1.91G  9.04T      192K  legacy
zroot/data/lxd_pools/default/custom             192K  9.04T      192K  legacy
zroot/data/lxd_pools/default/deleted           4.13G  9.04T      192K  legacy
zroot/data/lxd_pools/default/images            1.94G  9.04T      192K  legacy
zroot/data/lxd_pools/default/virtual-machines   174G  9.04T      192K  legacy
```

This nearly leads to dataloss on LXD upgrade:

`lxd.daemon[105748]: Error: Failed applying patch "storage_zfs_drop_block_volume_filesystem_extension": Failed applying patch to pool "default": Failed renaming zfs dataset: Failed to run: zfs rename zroot/data/lxd_pools/default/images/f9fa0af2502c21768df8c327768f2bb78e89fa3ec5994f8872882c1363388458.block zroot/data/lxd_pools/default/images/lxd.block: exit status 1 (cannot rename 'zroot/data/lxd_pools/default/images/f9fa0af2502c21768df8c327768f2bb78e89fa3ec5994f8872882c1363388458.block': dataset already exists)`

(Note how it's trying to rename things *to* `lxd.block`, which is `"lxd_pools".split("_", 1)[0] + ".block"`  (Line 700)
https://github.com/canonical/lxd/blob/e186300af4a51f77410bf6d47ade50c1b87d8bf6/lxd/storage/drivers/driver_zfs.go#L700

I'd appreciate if tests were written to make sure everything works with non-naive pools, i.e. ones that aren't dedicated to LXD or file-backed.

### PR DESCRIPTION
**Pull request by monstermunchkin**
Fixes #12465

### CODE REVIEW

File: lxd/storage/drivers/driver_zfs.go [hunk 1]
```diff
@@ -685,19 +685,21 @@ func (d *zfs) patchDropBlockVolumeFilesystemExtension() error {
 	}
 
 	for _, volume := range strings.Split(out, "\n") {
-		fields := strings.SplitN(volume, "/", 3)
+		fields := strings.Split(volume, "/")
 
-		if len(fields) != 3 {
+		if len(fields) < 3 {
```
Comment (tomponline) [inline lxd/storage/drivers/driver_zfs.go:690]: Doesnt this just now skip volumes that are in a pool which isn't at the root of the zfs hierarchy?
So those image volumes wont get fixed?

Instead would it better to split on the ` fmt.Sprintf("%s/images", poolName)` point of the volume name, and then perform the split on `/` on the right hand part of that?

Comment (monstermunchkin) [reply lxd/storage/drivers/driver_zfs.go]: I don't think the code is wrong, but I've changed it to `strings.SplitN(volume, fmt.Sprintf("%s/images/", poolName), 2)` just to be safe.

**Review by simondeziel — APPROVED** [review]
The commit message says `/` in the "patch"? Is it a typo for "path"?

**Review by tomponline — APPROVED** [review]
