### PR TITLE
Fix QEMU 9.1+ VM starting by syncing caching options and fd flags

### LINKED ISSUE #16348: LXD 6.5 still not working with QEMU 9.2+
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

Arch Linux

### Distribution version

n/a

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
n/a
```

### Output of "lxc info" or system info if it fails

```shell
config:
  core.https_address: 0.0.0.0:8443
  images.auto_update_interval: "0"
  images.remote_cache_expiry: "100000"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- backup_compression
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
- clustering_update_cert
- storage_api_project
- server_instance_driver_operational
- server_supported_storage_drivers
- event_lifecycle_requestor_address
- resources_gpu_usb
- clustering_evacuation
- network_ovn_nat_address
- network_bgp
- network_forward
- custom_volume_refresh
- network_counters_errors_dropped
- metrics
- image_source_project
- clustering_config
- network_peer
- linux_sysctl
- network_dns
- ovn_nic_acceleration
- certificate_self_renewal
- instance_project_move
- storage_volume_project_move
- cloud_init
- network_dns_nat
- database_leader
- instance_all_projects
- clustering_groups
- ceph_rbd_du
- instance_get_full
- qemu_metrics
- gpu_mig_uuid
- event_project
- clustering_evacuation_live
- instance_allow_inconsistent_copy
- network_state_ovn
- storage_volume_api_filtering
- image_restrictions
- storage_zfs_export
- network_dns_records
- storage_zfs_reserve_space
- network_acl_log
- storage_zfs_blocksize
- metrics_cpu_seconds
- instance_snapshot_never
- certificate_token
- instance_nic_routed_neighbor_probe
- event_hub
- agent_nic_config
- projects_restricted_intercept
- metrics_authentication
- images_target_project
- cluster_migration_inconsistent_copy
- cluster_ovn_chassis
- container_syscall_intercept_sched_setscheduler
- storage_lvm_thinpool_metadata_size
- storage_volume_state_total
- instance_file_head
- instances_nic_host_name
- image_copy_profile
- container_syscall_intercept_sysinfo
- clustering_evacuation_mode
- resources_pci_vpd
- qemu_raw_conf
- storage_cephfs_fscache
- network_load_balancer
- vsock_api
- instance_ready_state
- network_bgp_holdtime
- storage_volumes_all_projects
- metrics_memory_oom_total
- storage_buckets
- storage_buckets_create_credentials
- metrics_cpu_effective_total
- projects_networks_restricted_access
- storage_buckets_local
- loki
- acme
- internal_metrics
- cluster_join_token_expiry
- remote_token_expiry
- init_preseed
- storage_volumes_created_at
- cpu_hotplug
- projects_networks_zones
- network_txqueuelen
- cluster_member_state
- instances_placement_scriptlet
- storage_pool_source_wipe
- zfs_block_mode
- instance_generation_id
- disk_io_cache
- amd_sev
- storage_pool_loop_resize
- migration_vm_live
- ovn_nic_nesting
- oidc
- network_ovn_l3only
- ovn_nic_acceleration_vdpa
- cluster_healing
- instances_state_total
- auth_user
- security_csm
- instances_rebuild
- numa_cpu_placement
- custom_volume_iso
- network_allocations
- storage_api_remote_volume_snapshot_copy
- zfs_delegate
- operations_get_query_all_projects
- metadata_configuration
- syslog_socket
- event_lifecycle_name_and_project
- instances_nic_limits_priority
- disk_initial_volume_configuration
- operation_wait
- cluster_internal_custom_volume_copy
- disk_io_bus
- storage_cephfs_create_missing
- instance_move_config
- ovn_ssl_config
- init_preseed_storage_volumes
- metrics_instances_count
- server_instance_type_info
- resources_disk_mounted
- server_version_lts
- oidc_groups_claim
- loki_config_instance
- storage_volatile_uuid
- import_instance_devices
- instances_uefi_vars
- instances_migration_stateful
- container_syscall_filtering_allow_deny_syntax
- access_management
- vm_disk_io_limits
- storage_volumes_all
- instances_files_modify_permissions
- image_restriction_nesting
- container_syscall_intercept_finit_module
- device_usb_serial
- network_allocate_external_ips
- explicit_trust_token
- shared_custom_block_volumes
- instance_import_conversion
- instance_create_start
- instance_protection_start
- devlxd_images_vm
- disk_io_bus_virtio_blk
- metrics_api_requests
- projects_limits_disk_pool
- ubuntu_pro_guest_attach
- metadata_configuration_entity_types
- access_management_tls
- network_allocations_ovn_uplink
- network_ovn_uplink_vlan
- state_logical_cpus
- vm_limits_cpu_pin_strategy
- gpu_cdi
- images_all_projects
- metadata_configuration_scope
- unix_device_hotplug_ownership_inherit
- unix_device_hotplug_subsystem_device_option
- storage_ceph_osd_pool_size
- network_get_target
- network_zones_all_projects
- vm_root_volume_attachment
- projects_limits_uplink_ips
- entities_with_entitlements
- profiles_all_projects
- storage_driver_powerflex
- storage_driver_pure
- cloud_init_ssh_keys
- oidc_scopes
- project_default_network_and_storage
- client_cert_presence
- clustering_groups_used_by
- container_bpf_delegation
- override_snapshot_profiles_on_copy
- resources_device_fs_uuid
- backup_metadata_version
- storage_buckets_all_projects
- network_acls_all_projects
- networks_all_projects
- clustering_restore_skip_mode
- disk_io_threads_virtiofsd
- oidc_client_secret
- pci_hotplug
- device_patch_removal
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
client_certificate: false
auth_user_name: root
auth_user_method: unix
environment:
  addresses:
  - <redacted>
  - 192.168.130.1:8443
  - 192.168.140.1:8443
  architectures:
  - x86_64
  - i686
  backup_metadata_version_range:
  - 1
  - 2
  certificate: |
    <redacted>
  certificate_fingerprint: 7a923cb40a9e3bf60ce70340e78097c049149a9775f64b40ed5bb8552121a721
  driver: lxc | qemu
  driver_version: 6.0.5 | 10.0.3
  instance_types:
  - container
  - virtual-machine
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    bpf_token: "true"
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    uevent_injection: "true"
    unpriv_binfmt: "true"
    unpriv_fscaps: "true"
  kernel_version: 6.16.4-arch1-1
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Arch Linux
  os_version: ""
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_name: IMSERVER3
  server_pid: 1201
  server_version: "6.5"
  server_lts: false
  storage: btrfs
  storage_version: "6.16"
  storage_supported_drivers:
  - name: powerflex
    version: ""
    remote: true
  - name: pure
    version: ""
    remote: true
  - name: btrfs
    version: "6.16"
    remote: false
  - name: dir
    version: "1"
    remote: false
```

### Issue description

I'm sorry for bothering with the same issue again. I cannot make LXD 6.5 working with QEMU 9.1+ (including 10). When I'm trying to start VM, I'm getting the following error:
```
Error: Failed setting up device via monitor: Failed adding block device for disk device "root": Failed adding block device: Failed to find file descriptor with matching flags=0x2
Try `lxc info --show-log test` for more info
```

I already reported this issue here https://github.com/canonical/lxd/issues/15771, but it contained two different issues icluding this one. The second one was fixed, but this one steal appears. It will be ok if this issue will be closed in favour of that.

I still haven't found any soution except this thread on Incus: https://discuss.linuxcontainers.org/t/incus-6-5-incus-vm-not-starting-in-cluster/21538/4 and it has a linked merged PR, which seems to be already applied to LXD (https://github.com/canonical/lxd/blob/8999dcf6fc5b83948234e959bcb7fde208baf4b5/lxd/instance/drivers/driver_qemu.go#L4190), so it appears to be a different error.

The logs don't seem to contain any usefult information. According to code search the error is probably thrown here: https://github.com/canonical/lxd/blob/8999dcf6fc5b83948234e959bcb7fde208baf4b5/lxd/instance/drivers/qmp/commands.go#L482.

For now, the only solution is to keep old QEMU 9.0.x, which is not affected by this bug. Even if we stay away from Arch Linux, the upcoming versions of Ubuntu will include QEMU 10+ which probably will be included into next versions of LXD snap.

### Steps to reproduce

1. Install LXD 6.5 on Arch Linux
2. Install QEMU (the latest version is 10.0.3 at this moment)
3. Try to launch VM instance from any image without eny specific options
    ```
    Error: Failed setting up device via monitor: Failed adding block device for disk device "root": Failed adding block device: Failed to find file descriptor with matching flags=0x2
    Try `lxc info --show-log test` for more info
    ```

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by TheJJ**
This fixes transferred FDs from LXD to QEMU to be consistent with the caching mode and their `O_DIRECT` flag validity and fixes starting VMs with QEMU 9.1+ on btrfs. 

Without this patch (since qemu checks the `O_DIRECT` flag since  qemu/qemu@99c147e2f53726290bbdde795b6efbb4d9138657) files are always opened `O_DIRECT` by lxd, and qemu just accept and uses them, even though this is not consistent with the expected caching behavior (especially LXD's manual override for `btrfs` and `zfs` NOT to use `O_DIRECT` is ignored currently)

VMs on btrfs don't work without this patch because the caching mode is changed via that override, but the file opening flag is not.

This fixes #16348

### CODE REVIEW

**Comment by TheJJ** [comment]
`writeback` can't be set that way unfortunately, I've opened https://gitlab.com/qemu-project/qemu/-/issues/3103

**Comment by tomponline** [comment]
@skozina @TheJJ has kindly put up a fix for the QEMU 9.1+ issue.

File: lxd/instance/drivers/driver_qemu.go [hunk 1]
```diff
@@ -4025,20 +4025,58 @@ func (d *qemu) addDriveConfig(busAllocate busAllocator, bootIndexes map[string]i
 	}
 
 	// QMP uses two separate values for the cache.
-	directCache := true   // Bypass host cache, use O_DIRECT semantics by default.
-	noFlushCache := false // Don't ignore any flush requests for the device.
+	var directCache bool  // True to bypass host cache and use O_DIRECT semantics
+	var noFlushCache bool // True to ignore any flush requests for the device
+	// var writebackCache bool // True to complete writes once they are in the write page cache
```
Comment (tomponline) [inline lxd/instance/drivers/driver_qemu.go:4031]: Would you mind updating the comment to add a link to https://gitlab.com/qemu-project/qemu/-/issues/3103 for us to reference in the future please.

File: lxd/instance/drivers/driver_qemu.go [hunk 2]
```diff
@@ -4025,20 +4025,58 @@ func (d *qemu) addDriveConfig(busAllocate busAllocator, bootIndexes map[string]i
...
+		directCache = true
+		noFlushCache = false
 	case "unsafe":
+		// writebackCache = true
 		directCache = false
 		noFlushCache = true
-	case "writeback":
-		directCache = false
+	default:
+		return nil, fmt.Errorf("unsupported cache= mode: %s", cacheMode)
```
Comment (tomponline) [inline lxd/instance/drivers/driver_qemu.go]: Please can you start the error with a capital letter and use %q for the value, so:

```go
return nil, fmt.Errorf("Unsupported cache mode: %q", cacheMode)
```

File: lxd/instance/drivers/driver_qemu.go [hunk 3]
```diff
@@ -4187,7 +4225,9 @@ func (d *qemu) addDriveConfig(busAllocate busAllocator, bootIndexes map[string]i
 				permissions = unix.O_RDONLY
 			}
 
-			permissions |= unix.O_DIRECT
+			if directCache {
```
Comment (tomponline) [inline lxd/instance/drivers/driver_qemu.go:4232]: Would you mind adding a comment here explaining why this is needed.

**Review by tomponline — CHANGES_REQUESTED** [review]
Thanks for digging and finding the fix.

There's a few small changes, but otherwise this looks great thanks!

**Review by skozina — DISMISSED** [review]

**Comment by skozina** [comment]
Excellent catch that we are always setting the O_DIRECT. Thank you for the PR @TheJJ !

**Comment by TheJJ** [comment]
Adressed comments.
Mind that these caching modes are not actually available to set yet, since the allowed values are checked in some other logic before. So allowing to set them and to update the docs would be a possible next step :)

**Comment by tomponline** [comment]
> Mind that these caching modes are not actually available to set yet, since the allowed values are checked in some other logic before.

I'm not following you? Which cache modes are you referring to?

**Comment by TheJJ** [comment]
disk's `io.cache` https://documentation.ubuntu.com/lxd/latest/reference/devices_disk/#device-disk-device-conf:io.cache which is validated in `lxd/device/disk.go` `validateConfig`.

**Comment by tomponline** [comment]
> disk's `io.cache` https://documentation.ubuntu.com/lxd/latest/reference/devices_disk/#device-disk-device-conf:io.cache which is validated in `lxd/device/disk.go` `validateConfig`.

They can be set to: "none", "writeback", "unsafe"

Why do you think:

> Mind that these caching modes are not actually available to set yet

**Comment by TheJJ** [comment]
Ah, because I added handling more than the currently supported 3, to sync setting the 3 caching parameters like QEMU does:
 `writeback`, `none`, `writethrough`, `directsync`, `unsafe`.

what would be great if QMP provided this information over its API, so we don't have to sync/copy the table but instead get the truth from QEMU directly.

File: lxd/instance/drivers/driver_qemu.go [hunk 4]
```diff
@@ -4025,20 +4025,59 @@ func (d *qemu) addDriveConfig(busAllocate busAllocator, bootIndexes map[string]i
...
+		directCache = true
+		noFlushCache = false
 	case "unsafe":
+		// writebackCache = true
 		directCache = false
 		noFlushCache = true
-	case "writeback":
-		directCache = false
+	default:
+		return nil, fmt.Errorf("Unsupported cache= mode: %q", cacheMode)
```
Comment (tomponline) [inline lxd/instance/drivers/driver_qemu.go]: please drop the "=" thanks

**Review by tomponline — APPROVED** [review]
Excellent! Thanks again.

**Comment by tomponline** [comment]
Oh sorry commits need to be signed (as well as signed off).

**Comment by tomponline** [comment]
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by TheJJ** [comment]
Here you go.
