### PR TITLE
Container: Ignore clean stop of SFTP server

### LINKED ISSUE #15925: Forcibly stopping an instance should not spam logs about leftover `sftp` server
### Steps to reproduce

Create an instance, pull a file from it and immediately stop it with force:

```
$ lxc init ubuntu-minimal-daily:24.04 c1
$ lxc start c1; lxc file pull c1/etc/hostname -; lxc stop --force c1
c1
```

See the log spam:

```
$ journalctl -n 3 -u snap.lxd.daemon
Jul 02 16:48:33 sdeziel-lemur lxd.daemon[767970]: time="2025-07-02T16:48:33-04:00" level=warning msg="SFTP server stopped with error" err="signal: terminated" instance=c1 instanceType=container project=default stderr=
```

This `sftp` server is kept around for a few seconds to avoid spawning a new one for each request, that's good but it shouldn't matter if it's SIGTERM'ed.

### PR DESCRIPTION
**Pull request by simondeziel**
If a SFTP server was spawned and is still around when a container is stopped, it will be `SIGTERM`'ed to do an orderly shutdown. This is perfectly normal so it shouldn't cause any log message.

Fixes #15925

### CODE REVIEW

File: lxd/instance/drivers/driver_lxc.go [hunk 1]
```diff
@@ -5932,6 +5932,18 @@ func (d *lxc) FileSFTPConn() (net.Conn, error) {
 		// Wait for completion.
 		err = forkfile.Wait()
 		if err != nil {
+			// Check if this is an ExitError
+			var exitErr *exec.ExitError
```
Comment (tomponline) [inline lxd/instance/drivers/driver_lxc.go]: Can you use the existing function we have called `ExitStatus()` here?

Comment (simondeziel) [reply lxd/instance/drivers/driver_lxc.go]: Thanks, I didn't know about this handy helper!

Comment (simondeziel) [reply lxd/instance/drivers/driver_lxc.go]: Worked quite well.

**Review by tomponline — APPROVED** [review]
Ta
