### PR TITLE
Optimize dnsmasq log  message creation

### LINKED ISSUE #13220: Creating instances causes excessive logging from dnsmasq
Creating an instance causes `dnsmasq` to log one line for each of the existing/known instances in every projects. This can snowball as you create more instances over time. Here's how to reproduce it:

```
journalctl -f -n0 --grep dnsmasq.hosts & for i in $(seq -w 10); do lxc init --quiet ubuntu-minimal-daily:22.04 "c${i}"; done; kill %1
```

Which causes the following to be logged:

```
[1] 1953
Mar 27 01:36:21 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c01.eth0
Mar 27 01:36:36 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c01.eth0
Mar 27 01:36:36 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c02.eth0
Mar 27 01:36:51 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c01.eth0
Mar 27 01:36:51 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c02.eth0
Mar 27 01:36:51 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c03.eth0
Mar 27 01:37:06 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c01.eth0
Mar 27 01:37:06 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c02.eth0
Mar 27 01:37:06 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c03.eth0
Mar 27 01:37:06 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c04.eth0
Mar 27 01:37:20 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c01.eth0
Mar 27 01:37:20 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c02.eth0
Mar 27 01:37:20 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c03.eth0
Mar 27 01:37:20 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c04.eth0
Mar 27 01:37:20 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c05.eth0
Mar 27 01:37:35 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c01.eth0
Mar 27 01:37:35 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c02.eth0
Mar 27 01:37:35 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c03.eth0
Mar 27 01:37:35 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c04.eth0
Mar 27 01:37:35 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c05.eth0
Mar 27 01:37:35 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c06.eth0
Mar 27 01:37:53 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c01.eth0
Mar 27 01:37:53 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c02.eth0
Mar 27 01:37:53 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c03.eth0
Mar 27 01:37:53 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c04.eth0
Mar 27 01:37:53 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c05.eth0
Mar 27 01:37:53 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c06.eth0
Mar 27 01:37:53 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c07.eth0
Mar 27 01:38:08 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c01.eth0
Mar 27 01:38:08 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c02.eth0
Mar 27 01:38:08 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c03.eth0
Mar 27 01:38:08 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c04.eth0
Mar 27 01:38:08 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c05.eth0
Mar 27 01:38:08 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c06.eth0
Mar 27 01:38:08 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c07.eth0
Mar 27 01:38:08 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c08.eth0
Mar 27 01:38:23 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c01.eth0
Mar 27 01:38:23 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c02.eth0
Mar 27 01:38:23 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c03.eth0
Mar 27 01:38:23 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c04.eth0
Mar 27 01:38:23 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c05.eth0
Mar 27 01:38:23 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c06.eth0
Mar 27 01:38:23 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c07.eth0
Mar 27 01:38:23 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c08.eth0
Mar 27 01:38:23 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c09.eth0
Mar 27 01:38:40 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c01.eth0
Mar 27 01:38:40 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c02.eth0
Mar 27 01:38:40 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c03.eth0
Mar 27 01:38:40 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c04.eth0
Mar 27 01:38:40 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c05.eth0
Mar 27 01:38:40 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c06.eth0
Mar 27 01:38:40 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c07.eth0
Mar 27 01:38:40 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c08.eth0
Mar 27 01:38:40 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c09.eth0
Mar 27 01:38:40 v1 dnsmasq-dhcp[1484]: read /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts/c10.eth0
```

`journald` stores more than just the log message which means more data needs to be saved to disk. While a flawed approximation, the JSON exported logs for that repeated messages alone weights ~100KiB:

```
$ journalctl -o json --grep dnsmasq.hosts > /tmp/dnsmasq-log.json
$ ll -h /tmp/dnsmasq-log.json 
-rw-r--r-- 1 root root 97K Mar 27 01:40 /tmp/dnsmasq-log.json
```

### PR DESCRIPTION
**Pull request by tugbataluy**
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md) and attest that all commits in this PR are [signed off](https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md#including-a-signed-off-by-line-in-your-commits), [cryptographically signed](https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md#commit-signature-verification), and follow this project's [commit structure](https://github.com/canonical/lxd/blob/main/CONTRIBUTING.md#commit-structure).
- [x] I have checked and added or updated relevant documentation.

# Fix excessive dnsmasq logging during instance creation/deletion

## Issue

Fixes #13220

## Problem

When creating or deleting multiple instances, dnsmasq generates excessive log messages that grow quadratically (O(n²)) with the number of instances. This occurs because each instance operation triggers a SIGHUP signal to dnsmasq, causing it to re-read **all** host configuration files and log each one.

## Root Cause

LXD was using `--dhcp-hostsfile` (single file mode) but storing individual files per instance in the `dnsmasq.hosts/` directory. After every `UpdateStaticEntry()` or `RemoveStaticEntry()` call, LXD sent a SIGHUP via `dnsmasq.Kill()`, forcing dnsmasq to reload all configurations.

With N instances:
- Creating instance K triggers SIGHUP → dnsmasq re-reads all K files
- Create total: 1 + 2 + 3 + ... + N = n(n+1)/2 = O(n²)
- Delete total: (N-1) + (N-2) + ... + 0 = n(n-1)/2 = O(n²)

### 1. Switch to `--dhcp-hostsdir` (creation fix)
dnsmasq's directory mode uses inotify to automatically detect file changes without requiring SIGHUP signals. This reduces creation logs from O(n²) to O(n).

### 2. Remove redundant `Kill()` calls (creation fix)
Since inotify handles single-instance operations automatically, SIGHUP signals are removed from:
- `nic_bridged.go`: `rebuildDnsmasqEntry()` and `Remove()`
- `dhcpalloc.go`: `AllocateTask()`

### 3. Add content check in `UpdateStaticEntry()` (creation fix)
Skip writing if file content is unchanged, avoiding unnecessary inotify events when the same entry is written multiple times during instance creation.

### 4. Move file before deletion in `RemoveStaticEntry()` (deletion fix)
With `--dhcp-hostsdir`, deleting a file directly from the watched directory triggers inotify `IN_DELETE` events. Combined with the SIGHUP that `Remove()` sends afterwards, this causes **more** log output than the original code (both inotify events and SIGHUP fire simultaneously).

To prevent this, `RemoveStaticEntry()` now moves the file out of the watched directory using `os.Rename()` before deleting it. `os.Rename()` triggers an `IN_MOVED_FROM` event, which dnsmasq's inotify handler does not react to (it only watches `IN_CLOSE_WRITE` and `IN_MOVED_TO`). This ensures that only the subsequent SIGHUP from `Kill()` causes dnsmasq to re-read, preserving the exact same deletion log behavior as the original `--dhcp-hostsfile` code: n(n-1)/2 lines.

Without this rename trick, switching to `--dhcp-hostsdir` would have **increased** deletion logs because both inotify and SIGHUP events would fire for each deletion.

### 5. Keep `Kill()` for bulk operations
`UpdateDNSMasqStatic()` in `network_utils.go` still uses SIGHUP as it performs bulk rebuilds where a single reload at the end is appropriate.

### Benchmark Results (15 instances)

| Operation | Original | Fixed | Formula | Change |
|-----------|----------|-------|---------|--------|
| Creation  | 120      | 30    | n(n+1)/2 → 2n | **75% reduction** |
| Deletion  | 105      | 105   | n(n-1)/2 → n(n-1)/2 | **No regression** |

### Projected at scale

| Instances | Original Create | Fixed Create | Original Delete | Fixed Delete |
|-----------|----------------|--------------|-----------------|--------------|
| 25        | 325            | 50           | 300             | 300          |
| 50        | 1,275          | 100          | 1,225           | 1,225        |
| 100       | 5,050          | 200          | 4,950           | 4,950        |

## Notes

- Creation logs are clean: each instance produces exactly 2 lines ("inotify: new or modified" + "read").
- Deletion logs are clean: only SIGHUP-triggered "read" lines, no inotify "removed" or "cannot read" noise.
- The `os.Rename()` in `RemoveStaticEntry()` moves the file to a sibling path outside `dnsmasq.hosts/` before removing it. The temp file exists for microseconds and is immediately deleted. If LXD were to crash between the rename and remove (extremely unlikely), the orphaned file would be harmless — it sits outside the watched directory and doesn't affect dnsmasq.
- `--dhcp-hostsdir` has been available since dnsmasq 2.73 (2015), which shipped with Ubuntu 16.04.

## Testing

Tested instance creation and deletion with 15 instances, verifying:
- Log volume reduced as expected for creation
- Deletion log volume unchanged from original (no regression)
- Instances receive correct DHCP leases
- dnsmasq properly tracks host entries
- DNS resolution works correctly for created instances
- No functional regressions

### CODE REVIEW

File: lxd/network/driver_bridge.go [hunk 1]
```diff
@@ -1082,7 +1082,7 @@ func (n *bridge) getDnsmasqArgs(bridge *ip.Bridge) ([]string, error) {
 		dnsmasqCmd = append(dnsmasqCmd, "--listen-address="+ipv4Address.String())
 		if n.DHCPv4Subnet() != nil {
 			if !slices.Contains(dnsmasqCmd, "--dhcp-no-override") {
-				dnsmasqCmd = append(dnsmasqCmd, "--dhcp-no-override", "--dhcp-authoritative", "--dhcp-leasefile="+shared.VarPath("networks", n.name, "dnsmasq.leases"), "--dhcp-hostsfile="+shared.VarPath("networks", n.name, "dnsmasq.hosts"))
+				dnsmasqCmd = append(dnsmasqCmd, "--dhcp-no-override", "--dhcp-authoritative", "--dhcp-leasefile="+shared.VarPath("networks", n.name, "dnsmasq.leases"), "--dhcp-hostsdir="+shared.VarPath("networks", n.name, "dnsmasq.hosts"))
```
Comment (simondeziel) [inline lxd/network/driver_bridge.go]: Could `shared.VarPath("networks", n.name)` be cached to a local var that is then used to build the filepath like: `netPath + "/dnsmasq.leases"`

File: lxd/dnsmasq/dnsmasq.go [hunk 2]
```diff
@@ -29,6 +30,8 @@ type DHCPAllocation struct {
 var ConfigMutex sync.Mutex
 
 // UpdateStaticEntry writes a single dhcp-host line for a network/instance combination.
+// With --dhcp-hostsdir, dnsmasq uses inotify to automatically detect new and changed files,
+// so no SIGHUP is required after calling this function.
```
Comment (simondeziel) [inline lxd/dnsmasq/dnsmasq.go:34]: What a nice finding! In initially worried this was introduced in a recent version of `dnsmasq` but apparently it went in [2.73](https://dnsmasq.org/CHANGELOG#:~:text=Add%20%2D%2Ddhcp%2Dhostsdir%2E%20This%20allows%20addition%20of%20new%20host)

This version is available since Ubuntu 16.04 so all clear!

File: test/suites/dnsmasq_log_scaling.sh [hunk 3]
```diff
@@ -0,0 +1,102 @@
+test_dnsmasq_log_scaling() {
```
Comment (simondeziel) [inline test/suites/dnsmasq_log_scaling.sh]: Thanks for the new test case but, while I'm usually pushing for more cases/coverage, I am not convinced this one is needed. Also, I fear that counting read syscalls from the `dnsmasq` is going to be brittle in CI. Inspecting `dnsmasq` logs sounds more reliable to me.

As such, I'd personally leave it out assuming you've confirmed the bug was fixed. Maybe @tomponline will see it differently though.

File: lxd/dnsmasq/dnsmasq.go (hunk 2 above)
Comment (tomponline) [reply lxd/dnsmasq/dnsmasq.go:34]: @tugbataluy I considered this several years ago, but at the time I found there was a problem with it. If my memory serves correctly, it was that if an entry already exists, modifying the file again doesn't affect it. Or potentially when removing the file it doesn't remove the settings.

So worth considering for sure, but know it has been previously considered and ruled out due to a problem.

File: test/suites/dnsmasq_log_scaling.sh (hunk 3 above)
Comment (tugbataluy) [reply test/suites/dnsmasq_log_scaling.sh]: The challenge with inspecting dnsmasq logs is that the log output is what I was trying to fix, it's inherently noisy and timing-dependent. The syscall counting approach was chosen because it measures actual I/O behavior rather than log strings that can vary (I also tried to read logs but every time I tried to make it I only got 0 line so I decided to go with syscall counting).
That said, I understand the concern about brittleness in CI. I'm happy to drop the test case if you and @tomponline agree it's not necessary. The fix itself is straightforward and the benchmarking I did during development confirmed the O(n²)  ->  O(n) improvement.

File: lxd/dnsmasq/dnsmasq.go (hunk 2 above)
Comment (simondeziel) [reply lxd/dnsmasq/dnsmasq.go:34]: > @tugbataluy I considered this several years ago, but at the time I found there was a problem with it. If my memory serves correctly, it was that if an entry already exists, modifying the file again doesn't affect it.

This makes me wonder if it's not filtering inotify events. Maybe it requires an actual new file (different inode) rather than modifying an existing one?

Comment (simondeziel) [reply lxd/dnsmasq/dnsmasq.go:34]: Forget that, the inotify handling looks sound even for modified files: https://github.com/imp/dnsmasq/blob/1eab169173fc4c8579a3db61186096fe117e6aca/src/inotify.c#L326-L337

Comment (tugbataluy) [reply lxd/dnsmasq/dnsmasq.go:34]: I tested modifying an existing entry:

-Created instance -> file contained 00:16:3e:fa:18:80,test1
-Added static IP via lxc config device override test1 eth0 ipv4.address=10.245.211.20
-File  updated to 00:16:3e:fa:18:80,10.245.211.20,test1
-Started instance -> received correct IP 10.245.211.20

Does this confirm dnsmasq's inotify watches detect modifications to existing files, not just new files?

Comment (tomponline) [reply lxd/dnsmasq/dnsmasq.go:34]: Do we still need to reload dnsmasq for deletions right?

File: lxd/device/nic_bridged.go [hunk 4]
```diff
@@ -920,12 +920,6 @@ func (d *nicBridged) Remove() error {
 		if err != nil {
 			return err
 		}
-
-		// Reload dnsmasq to apply new settings if dnsmasq is running.
```
Comment (tomponline) [inline lxd/device/nic_bridged.go:924]: IIRC this is still needed as removing a file does not trigger config reload when using `dhcp-hostsdir`

File: lxd/device/nic_bridged.go
Comment (tomponline) [inline lxd/device/nic_bridged.go:976]: Please can you add a comment here explaining that due to the use of `--dhcp-hostsdir` the settings should be automatically applied by dnsmasq.

File: lxd/dnsmasq/dnsmasq.go [hunk 5]
```diff
@@ -60,6 +72,9 @@ func UpdateStaticEntry(network string, projectName string, instanceName string,
 }
 
 // RemoveStaticEntry removes a single dhcp-host line for a network/instance combination.
+// With --dhcp-hostsdir, dnsmasq uses inotify to automatically detect removed files,
+// so no SIGHUP is required after calling this function for single instance operations.
+// For bulk operations that modify many files, callers may still send one SIGHUP at the end.
```
Comment (tomponline) [inline lxd/dnsmasq/dnsmasq.go]: > For bulk operations that modify many files, callers may still send one SIGHUP at the end.

why?

File: test/suites/dnsmasq_log_scaling.sh
Comment (tomponline) [inline test/suites/dnsmasq_log_scaling.sh:1]: I would prefer that instead of these tests, we instead confirm that, if not already, that add, update, delete of bridged NIC devices are being reflected in dnsmasq's config (suggest using DNS resolution checks).

Comment (tugbataluy) [reply test/suites/dnsmasq_log_scaling.sh:1]: I can modify the test, or add the confirmation to another suitable test that already exists.

File: lxd/dnsmasq/dnsmasq.go (hunk 5 above)
Comment (tugbataluy) [reply lxd/dnsmasq/dnsmasq.go]: As far as I understand in network_utils.go 
`UpdateDNSMasqStatic()` is a bulk operation that wipes and recreates all host entries. With inotify alone, each file operation would trigger individual log events (~5N lines). One SIGHUP at the end produces fewer logs (~N lines) and ensures dnsmasq sees a consistent state after the full rebuild. For single-instance operations, inotify is more efficient, but for bulk rebuilds, one SIGHUP at the end is cleaner. 

That was my first intention.

 I was thinking removing the Kill() call from Remove() function in `nic_bridged.go` but I realised I have to investigate it further. So this comment might be misleading at this moment, I need to update it.
I'm converting PR to draft. When it's ready I'll reopen it.

File: test/suites/dnsmasq_log_scaling.sh
Comment (tomponline) [reply test/suites/dnsmasq_log_scaling.sh:1]: Thanks, I dont think we need tests for log line output

File: lxd/device/nic_bridged.go (hunk 4 above)
Comment (tugbataluy) [reply lxd/device/nic_bridged.go:924]: I believe there is a trade-off:
With `Kill()`: O(n²) logs, each SIGHUP re-reads all remaining files. For N deletions: (N-1) + (N-2) + ... + 0 = n(n-1)/2
Without `Kill()`: O(n) logs, each delete triggers ~3 inotify lines = 3n total. But DHCP records stay in memory (stale until next SIGHUP/restart).

`--dhcp-hostsdir` ignores IN_DELETE events, records persist in memory until SIGHUP.
I tried to create a conflict (maybe this wasn't the right approach)
Test I ran:

1. Created test1 with IP 10.245.211.217
2. Deleted test1 (without Kill())
3. Created new instance test-clean and assigned ipv4.address=10.245.211.217
4. Started it,successfully got the IP 10.245.211.217, no conflict

The old MAC is gone and won't request that IP again.
My testing showed the stale record didn't cause issues, the IP was successfully reassigned to a new instance.

Is this test accurate? If it is, do stale DHCP records cause any actual problems, or can we leave them until the next network restart/SIGHUP?

Comment (tomponline) [reply lxd/device/nic_bridged.go:924]: Yes it leaves stale leases behind that need clearing up.
As well as DNS names AFAIK.

Comment (tugbataluy) [reply lxd/device/nic_bridged.go:924]: But even if we keep Kill() call in Remove() the main aim was to reduce creation logs so we can keep it as it is. For the deletion part we couldn't get the O(n) lines of entry at worst

Comment (tugbataluy) [reply lxd/device/nic_bridged.go:924]: Also for deletion part, maybe I can add a small delay for sending SIGHUP signal. By doing that I can still reduce the lines if we really want to reduce deletion entries too.

Comment (tomponline) [reply lxd/device/nic_bridged.go:924]: yes

Comment (tomponline) [reply lxd/device/nic_bridged.go:924]: lets not introduce arbitrary delays please

Comment (tugbataluy) [reply lxd/device/nic_bridged.go:924]: OK :D

Comment (tugbataluy) [reply lxd/device/nic_bridged.go:924]: Then I'll proceed with only reducing the creation logs, but I still want to make a little bit more digging if I can reduce the numbers of SIGHUP calls, without using arbitrary delays.

File: lxd/network/driver_bridge.go (hunk 1 above)
Comment (tomponline) [reply lxd/network/driver_bridge.go]: @tugbataluy did you see this comment?

File: lxd/device/nic_bridged.go [hunk 6]
```diff
@@ -921,7 +921,6 @@ func (d *nicBridged) Remove() error {
 			return err
 		}
 
-		// Reload dnsmasq to apply new settings if dnsmasq is running.
```
Comment (tomponline) [inline lxd/device/nic_bridged.go:924]: Why is this comment removed?

File: lxd/dnsmasq/dnsmasq.go [hunk 7]
```diff
@@ -60,13 +72,26 @@ func UpdateStaticEntry(network string, projectName string, instanceName string,
 }
 
 // RemoveStaticEntry removes a single dhcp-host line for a network/instance combination.
-func RemoveStaticEntry(network string, projectName string, instanceName string, deviceName string) error {
+// The file is moved out of the dnsmasq.hosts directory before deletion to avoid triggering
```
Comment (tomponline) [inline lxd/dnsmasq/dnsmasq.go:75]: @tugbataluy do you observe this generating more dnsmasq log files? Or does dnsmasq not respond in any way (including remove the entry) when a file is removed?

I'm not sure what prompted you to make this change?

File: lxd/dnsmasq/dnsmasq.go [hunk 8]
```diff
@@ -60,13 +72,26 @@ func UpdateStaticEntry(network string, projectName string, instanceName string,
...
+	err := os.Rename(filePath, tmpPath)
+	if err != nil {
+		if os.IsNotExist(err) {
+			return nil
+		}
+
 		return err
 	}
 
+	_ = os.Remove(tmpPath)
```
Comment (tomponline) [inline lxd/dnsmasq/dnsmasq.go]: we shouldnt mask the removal error

File: test/suites/container_devices_nic_bridged.sh [hunk 9]
```diff
@@ -544,35 +544,69 @@ test_container_devices_nic_bridged() {
...
+  lxc config device set "${ctName}" eth0 ipv4.address=192.0.2.201 ipv6.address=2001:db8::201
 
-  if grep -F "192.0.2.200" "${LXD_DIR}/networks/${brName}/dnsmasq.hosts/${ctName}.eth0" ; then
-    echo "dnsmasq host config still has old IPv4 address"
+  # Confirm the hosts file is updated with the new addresses and the old ones are gone.
+  grep -F "192.0.2.201" "${LXD_DIR}/networks/${brName}/dnsmasq.hosts/${ctName}.eth0"
+  grep -F "2001:db8::201" "${LXD_DIR}/networks/${brName}/dnsmasq.hosts/${ctName}.eth0"
+  if grep -F "192.0.2.200" "${LXD_DIR}/networks/${brName}/dnsmasq.hosts/${ctName}.eth0"; then
+    echo "dnsmasq host config still contains stale IPv4 address after update"
     false
```
Comment (tomponline) [inline test/suites/container_devices_nic_bridged.sh:590]: what about the old ipv6 address that was previously checked for?

File: lxd/dnsmasq/dnsmasq.go (hunk 7 above)
Comment (tugbataluy) [reply lxd/dnsmasq/dnsmasq.go:75]: Yes, with `--dhcp-hostsdir`, deleting a file directly from the watched directory generates more log output than the original `--dhcp-hostsfile` approach. The file deletion triggers inotify `IN_DELETE` events, and combined with the `SIGHUP from Kill()`, both fire simultaneously, resulting in inotify "removed" lines, "cannot read" errors, and the normal `SIGHUP` "read" lines all at once, it causes n^2 log entries for deletion more than the original behaviour which is (n*(n-1))/2 .

dnsmasq does not remove the entry when a file is deleted from the hostsdir, the man page confirms this: "If a file is deleted after it has been read by dnsmasq, then the host record it contained will remain until dnsmasq receives a SIGHUP." So `Kill()` is still needed, but the inotify noise from the deletion is purely extra log spam.

`os.Rename()` fires `IN_MOVED_FROM`, which dnsmasq's inotify handler ignores (it only watches `IN_CLOSE_WRITE` and `IN_MOVED_TO`). This ensures only the `SIGHUP` triggers the reload, preserving the exact same deletion log count as the original code.

File: lxd/device/nic_bridged.go (hunk 6 above)
Comment (tugbataluy) [reply lxd/device/nic_bridged.go:924]: I forgot to add it back, sorry :melting_face:.

File: lxd/dnsmasq/dnsmasq.go (hunk 7 above)
Comment (tomponline) [reply lxd/dnsmasq/dnsmasq.go:75]: thanks for the explanation, makes sense!

File: lxd/network/driver_bridge.go (hunk 1 above)
Comment (tugbataluy) [reply lxd/network/driver_bridge.go]: Now, I see it :)

File: test/suites/container_devices_nic_bridged.sh (hunk 9 above)
Comment (tugbataluy) [reply test/suites/container_devices_nic_bridged.sh:590]: I've added checks for IPv6 as well.

File: lxd/dnsmasq/dnsmasq.go [hunk 10]
```diff
@@ -60,10 +72,26 @@ func UpdateStaticEntry(network string, projectName string, instanceName string,
...
+// The file is moved out of the dnsmasq.hosts directory before deletion to avoid triggering
+// inotify events. The caller should send SIGHUP via Kill(network, true) to reload dnsmasq.
+func RemoveStaticEntry(network, projectName, instanceName, deviceName string) error {
 	deviceStaticFileName := StaticAllocationFileName(projectName, instanceName, deviceName)
-	err := os.Remove(shared.VarPath("networks", network, "dnsmasq.hosts", deviceStaticFileName))
-	if err != nil && !os.IsNotExist(err) {
+	filePath := shared.VarPath("networks", network, "dnsmasq.hosts", deviceStaticFileName)
+
+	// Sibling path avoids IN_MOVED_TO in dnsmasq's inotify watch on dnsmasq.hosts/.
+	tmpPath := shared.VarPath("networks", network, "dnsmasq.hosts") + "." + deviceStaticFileName + ".removing"
```
Comment (tomponline) [inline lxd/dnsmasq/dnsmasq.go:82]: In case LXD gets stopped after the rename or fails to remove the file after the rename, please can you open a follow up PR that deletes `*.removing` files on the network start up so they will eventually get cleared.

Comment (tugbataluy) [reply lxd/dnsmasq/dnsmasq.go:82]: I'll be working on it :+1:

Comment (tomponline) [reply lxd/dnsmasq/dnsmasq.go:82]: Also so we can see that these concepts are linked together, please can you move the ".removing" string into a constant that is referenced from both here and in the follow up deletion code.

Comment (simondeziel) [inline lxd/dnsmasq/dnsmasq.go:82]: Both `filePath` and `tmpPath`, could have benefit from building on top of:

`netPath := shared.VarPath("networks", network, "dnsmasq.hosts")`

File: lxd/network/driver_bridge.go [hunk 11]
```diff
@@ -19,7 +19,7 @@ import (
 
 	"github.com/mdlayher/netx/eui64"
 
-	"github.com/canonical/lxd/client"
+	lxd "github.com/canonical/lxd/client"
```
Comment (simondeziel) [inline lxd/network/driver_bridge.go:22]: Likely unintentional

Comment (tomponline) [reply lxd/network/driver_bridge.go:22]: Ah yeah @tugbataluy please change your IDE settings so this doesnt keep happening.

Comment (tugbataluy) [reply lxd/network/driver_bridge.go:22]: I'll fix it, on the following PR.
