### PR TITLE
Instance: Initialise UEFI vars NVRAM on first access if needed

### LINKED ISSUE #12935: `lxc config uefi show` errors out if the VM was never started (no `qemu.nvram`)
It seems like the `qemu.nvram` file is created opportunistically but that causes a weird error when trying to show the uefi config:

```
$ lxc init ubuntu-minimal-daily:22.04 m1 --vm
$ lxc config uefi show m1
Error: open /var/snap/lxd/common/lxd/virtual-machines/m1/qemu.nvram: no such file or directory
$ lxc start m1
$ lxc config uefi show m1
variables:
  00163E5FE3A8-5b446ed1-e30b-4faa-871a-3654eca36080:
    data: 3a5001001000afaf040000000100000000000000
    attr: 3
    timestamp: ""
...
```

Returning nothing might be better than providing this error?

Additional information:

```
$ snap list lxd
Name  Version      Rev    Tracking     Publisher   Notes
lxd   git-35aa763  27329  latest/edge  canonical✓  -
```

### PR DESCRIPTION
**Pull request by tomponline**
Fixes #12935
Closes #12940

Tested with:

```
lxc init ubuntu:22.04 v1 --vm
lxc config uefi set v1 SecureBootEnable-f0a30bc7-af08-4556-99c4-001009c93a44=00
lxc config uefi get v1 SecureBootEnable-f0a30bc7-af08-4556-99c4-001009c93a44
00
```

### CODE REVIEW

File: lxd/instance_uefi_vars.go [hunk 1]
```diff
@@ -85,6 +85,15 @@ func instanceUEFIVarsGet(d *Daemon, r *http.Request) response.Response {
 		return resp
 	}
 
+	// The act of getting UEFI vars for an instance can cause them to be generated, so ensure we lock here
+	// as well as in instanceUEFIVarsPut.
+	unlock, err := instanceOperationLock(s.ShutdownCtx, projectName, name)
```
Comment (mihalicyn) [inline lxd/instance_uefi_vars.go:90]: Do I understand correctly, that this lock will protect us from race in this case:
```
# create and start an instance
lxc launch ubuntu:22.04 v1 --vm
# do set while instance IS starting and will call `d.setupNvram` in the middle
lxc config uefi set v1 SecureBootEnable-f0a30bc7-af08-4556-99c4-001009c93a44=00
lxc config uefi get v1 SecureBootEnable-f0a30bc7-af08-4556-99c4-001009c93a44
```

So, after `lxc launch ...` command the instanceOperationLock is taken somewhere until the instance will be fully started, right?

**Review by mihalicyn — APPROVED** [review]
LGTM, except small question

**Review by simondeziel — APPROVED** [review]
