### PR TITLE
Auth: Implement identity deletion

### LINKED ISSUE #13149: Add endpoint to remove OIDC identities
# Required information

 * Distribution: snap
 * Distribution version: 5.21.0-0cbd19b

# Issue description

On log-in of OIDC users, an entry in the identities table gets created. Currently, there is no way to remove those entries. This might be problematic if the user in the external identity provider was removed and an administrator wants to clean up the entries in LXD.

Suggestion is to add an endpoint that allows to remove OIDC identities.

# Steps to reproduce

 1. Configure LXD with OIDC
 2. Login to the UI with an OIDC user foo@bar.com
 3. Remove foo@bar.com from LXDs identities

### PR DESCRIPTION
**Pull request by markylaing**
- Separates identity endpoints by authentication method (instead of having the authentication method as a path argument) in preparation for fine-grained TLS identites. 
- Implements deletion of TLS and OIDC identities (for all current TLS identities, this will be rejected because they are not fine-grained).
- Adds a `access_management_tls` API extension which will apply to all upcoming changes for TLS fine-grained auth.

Note: The licence check was failing in my local static analysis, not sure what's happening there.
Note 2: (I just needed to update it locally :+1:).

Closes #13149

### CODE REVIEW

File: lxc/auth.go [hunk 1]
```diff
@@ -1074,6 +1077,50 @@ func (c *cmdIdentityEdit) run(cmd *cobra.Command, args []string) error {
 	return nil
 }
 
+type cmdIdentityDelete struct {
+	global *cmdGlobal
+}
+
+func (c *cmdIdentityDelete) command() *cobra.Command {
+	cmd := &cobra.Command{}
+	cmd.Use = usage("delete", i18n.G("[<remote>:]<authentication_method>/<name_or_identifier>"))
```
Comment (hamistao) [inline lxc/auth.go:1086]: Since an identifier here can be (if I understood correctly) a certificate fingerprint for TLS or an email for OIDC, I think some examples or a more detailed description would be helpul here.

File: test/suites/auth.sh [hunk 2]
```diff
@@ -143,6 +143,11 @@ EOF
   # Perform access check compatibility with project feature flags
   auth_project_features
 
+  # The OIDC identity should be able to delete themselves without any permissions.
+  lxc auth identity group remove oidc/test-user@example.com test-group
+  lxc_remote auth identity info oidc: | grep -Fq 'effective_permissions: []'
+  lxc_remote auth identity delete oidc:oidc/test-user@example.com
```
Comment (hamistao) [inline test/suites/auth.sh:149]: We could also add some tests to check if the identity was indeed deleted as expected and (maybe) some tests to check that a user without permissions can't delete another. What do you think?

File: lxd/api_1.0.go [hunk 3]
```diff
@@ -128,8 +128,11 @@ var api10 = []APIEndpoint{
 	warningCmd,
 	metricsCmd,
 	identitiesCmd,
-	identitiesByAuthenticationMethodCmd,
-	identityCmd,
```
Comment (hamistao) [inline lxd/api_1.0.go:132]: Sorry for this, I am having a hard time grasping why this separation is needed.
Could you please elaborate more on that?

**Review by hamistao — CHANGES_REQUESTED** [review]
Thanks for this!
Looks good overall, just left some nits and questions.

File: doc/api-extensions.md [hunk 4]
```diff
@@ -2480,3 +2480,24 @@ When set to `on`, if the host has guest attachment enabled, the guest can reques
...
+
+Expands APIs under `/1.0/auth` to include:
+
+1. Creation of fine-grained TLS identities, whose permissions are managed via group membership.
+  This is performed via `POST /1.0/auth/identities/tls`.
+  If the request body contains `{"token": true}`, a token will be returned that may be used by an non-authenticated caller to gain trust with the LXD server (the caller must send their certificate during the TLS handshake).
+  If the request body contains `{"certificate": "<base64 encoded x509 certificate>"}"`, the identity will be created directly.
+  The request body may also specify an array of group names.
+  The caller must have `can_create_identities` on `server`.
+1. Deletion of OIDC and fine-grained TLS identities.
```
[the remark this answers is not in the document]
Comment (markylaing) [reply doc/api-extensions.md:2494]: This is in line with the style guide: https://canonical-documentation-with-sphinx-and-readthedocscom.readthedocs-hosted.com/style-guide-myst/#lists

File: doc/api-extensions.md [hunk 5]
```diff
@@ -2480,3 +2480,24 @@ When set to `on`, if the host has guest attachment enabled, the guest can reques
...
 This adds entity type metadata to `GET /1.0/metadata/configuration`.
 The entity type metadata is a JSON object under the `entities` key.
+
+## `access_management_tls`
+
+Expands APIs under `/1.0/auth` to include:
+
+1. Creation of fine-grained TLS identities, whose permissions are managed via group membership.
+  This is performed via `POST /1.0/auth/identities/tls`.
+  If the request body contains `{"token": true}`, a token will be returned that may be used by an non-authenticated caller to gain trust with the LXD server (the caller must send their certificate during the TLS handshake).
```
[the remark this answers is not in the document]
Comment (markylaing) [reply doc/api-extensions.md:2490]: Yep will fix :+1:

File: lxd/identities.go [hunk 6]
```diff
@@ -233,18 +263,61 @@ func identityAccessHandler(entitlement auth.Entitlement) func(d *Daemon, r *http
...
+//	            [
+//	              "/1.0/auth/identities/oidc/jane.doe@example.com",
+//	              "/1.0/auth/identities/oidc/joe.bloggs@example.com"
+//	            ]
+//	  "403":
+//	    $ref: "#/responses/Forbidden"
+//	  "500":
+//	    $ref: "#/responses/InternalServerError"
+
+// swagger:operation GET /1.0/auth/identities/tls?recursion=1 identities identities_get_tls_recursion1
```
[the remark this answers is not in the document]
Comment (markylaing) [reply lxd/identities.go:324]: No, we use this to separate the API response from the URL listing responses in many places. E.g:
- Projects: https://github.com/canonical/lxd/blob/d7392ca7cc6e91d725481d64f440a926d05d9e9d/lxd/api_project.go#L102
- Certificates: https://github.com/canonical/lxd/blob/d7392ca7cc6e91d725481d64f440a926d05d9e9d/lxd/certificates.go#L98
- Instances: https://github.com/canonical/lxd/blob/d7392ca7cc6e91d725481d64f440a926d05d9e9d/lxd/instances_get.go#L112 & https://github.com/canonical/lxd/blob/d7392ca7cc6e91d725481d64f440a926d05d9e9d/lxd/instances_get.go#L165

File: lxd/lifecycle/identity.go [hunk 7]
```diff
@@ -12,6 +12,7 @@ type IdentityAction string
 const (
 	IdentityCreated = IdentityAction(api.EventLifecycleIdentityCreated)
 	IdentityUpdated = IdentityAction(api.EventLifecycleIdentityUpdated)
+	IdentityDeleted = IdentityAction(api.EventLifecycleIdentityUpdated)
```
[the remark this answers is not in the document]
Comment (markylaing) [reply lxd/lifecycle/identity.go:15]: Whoops! Thanks for catching!

File: lxd/api_1.0.go (hunk 3 above)
Comment (markylaing) [reply lxd/api_1.0.go:132]: I'll add more detail to the commit message but this is so that we can have `POST /1.0/auth/identities/tls` for fine-grained TLS identity creation without `POST /1.0/auth/identities/oidc`

File: test/suites/auth.sh (hunk 2 above)
Comment (markylaing) [reply test/suites/auth.sh:149]: Yep I'll double check that the identity is indeed deleted. As for checking that an identity without sufficient permissions cannot delete another, the difficulty here is that our `mini-oidc` only allows one user at a time. I think we can address this much more easily when the TLS identities are added. We can manage the identities in the testing scripts much more easily at that point.

File: lxc/auth.go (hunk 1 above)
Comment (markylaing) [reply lxc/auth.go:1086]: I've added some examples :)

File: doc/api-extensions.md (hunk 4 above)
[the remark this answers is not in the document]
Comment (hamistao) [reply doc/api-extensions.md:2494]: Oh cool, thanks for the info :)

File: test/suites/auth.sh (hunk 2 above)
Comment (hamistao) [reply test/suites/auth.sh:149]: Ok, I see. Learning a lot from doing this review :))

**Review by hamistao — APPROVED** [review]
LGTM!

File: lxd/identities.go [hunk 8]
```diff
@@ -277,137 +350,198 @@ func identityAccessHandler(entitlement auth.Entitlement) func(d *Daemon, r *http
...
+			if len(identities) == 0 {
+				return nil
+			}
 
-	// Optimisation for user that can only view themselves.
-	if apiIdentity != nil {
-		return response.SyncResponse(true, []api.Identity{*apiIdentity})
-	}
+			if recursion == "1" && len(identities) == 1 {
+				// It's likely that the user can only view themselves. If so we can optimise here by only getting the
```
Comment (tomponline) [inline lxd/identities.go:454]: can we check the contents of identities[0] to be more confident than "likely"?

File: lxd/identities.go [hunk 9]
```diff
@@ -277,137 +350,198 @@ func identityAccessHandler(entitlement auth.Entitlement) func(d *Daemon, r *http
...
-			for _, group := range groups {
-				if canViewGroup(entity.AuthGroupURL(group.Name)) {
-					groupNamesByIdentityID[identityID] = append(groupNamesByIdentityID[identityID], group.Name)
+			return nil
+		})
+		if err != nil {
+			return response.SmartError(err)
+		}
+
+		// Optimisation for user that can only view themselves.
```
Comment (tomponline) [inline lxd/identities.go:474]: adding a *why* here would be useful (why does `apiIdentity != nil ` mean they can only view themselves)?

File: lxc/auth.go [hunk 10]
```diff
@@ -1074,6 +1077,61 @@ func (c *cmdIdentityEdit) run(cmd *cobra.Command, args []string) error {
...
+	cmd.Short = i18n.G("Delete an identity")
+	cmd.Long = cli.FormatSection(i18n.G("Description"), i18n.G(
+		`Delete an identity`))
+	cmd.Example = cli.FormatSection("", `lxc auth identity delete oidc/jane.doe@example.com
+	Delete the OIDC identity with email address "jane.doe@example.com" in the default remote.
+
+lxc auth identity delete oidc/'Jane Doe'
+	Delete the OIDC identity with name "Jane Doe" in the default remote (there must be only one OIDC identity on the server with this name).
+
+lxc auth identity delete bramble-01:tls/12beaccbf9e7b7445185581b70099a5962c927e85006d5883856d909fe79f976
```
Comment (tomponline) [inline lxc/auth.go:1097]: bramble?

File: test/suites/auth.sh [hunk 11]
```diff
@@ -143,6 +143,12 @@ EOF
   # Perform access check compatibility with project feature flags
   auth_project_features
 
+  # The OIDC identity should be able to delete themselves without any permissions.
```
Comment (tomponline) [inline test/suites/auth.sh:146]: Will the tests for TLS fine grained come next?

Comment (markylaing) [reply test/suites/auth.sh:146]: Yep they're in #14207 :)

File: lxc/auth.go (hunk 10 above)
Comment (markylaing) [reply lxc/auth.go:1097]: Not sure what I was thinking here. Raspberry Pi's on the brain I think :laughing: What shall I use as an example remote name?

File: lxd/identities.go (hunk 9 above)
Comment (markylaing) [reply lxd/identities.go:474]: This hasn't changed from before but I'll add a commit to clarify this :+1:

File: lxd/identities.go (hunk 8 above)
Comment (markylaing) [reply lxd/identities.go:454]: The optimisation is for when the caller can only see one identity. It doesn't matter if it is the caller. E.g. the caller may be using the unix socket and there is only one identity in the system. I'll rephrase the comments to make it clear.

Comment (markylaing) [reply lxd/identities.go]: Done.

File: lxd/identities.go (hunk 9 above)
Comment (markylaing) [reply lxd/identities.go]: Done.

File: lxc/auth.go (hunk 10 above)
Comment (markylaing) [reply lxc/auth.go]: Changed to "my-remote".

**Review by tomponline — DISMISSED** [review]

**Comment by tomponline** [comment]
needs a rebase please

**Comment by markylaing** [comment]
Have rebased and will re-trigger the tests when https://github.com/canonical/lxd/pull/14234 is merged.

File: lxd/identities.go [hunk 12]
```diff
@@ -981,6 +989,88 @@ func patchIdentity(d *Daemon, r *http.Request) response.Response {
...
+//	  "501":
+//	    $ref: "#/responses/NotImplemented"
+func deleteIdentity(d *Daemon, r *http.Request) response.Response {
+	id, err := request.GetCtxValue[*dbCluster.Identity](r.Context(), ctxClusterDBIdentity)
+	if err != nil {
+		return response.SmartError(err)
+	}
+
+	if !identity.IsFineGrainedIdentityType(string(id.Type)) {
+		return response.NotImplemented(fmt.Errorf("Identities of type %q cannot be modified via this API", id.Type))
```
Comment (markylaing) [inline lxd/identities.go:1040]: @tomponline I'm just wondering if this check is really necessary for the delete handler. PUT and PATCH have to be disallowed for non- fine-grained certificates because we don't allow them to be added to groups, but DELETE would work just fine...

**Comment by tomponline** [comment]
please can you rebase with fix for tests

File: lxd/identities.go (hunk 12 above)
Comment (tomponline) [reply lxd/identities.go:1040]: I'm not sure of the question. Don't we want to ensure that legacy certificates cannot be managed by the identity endpoints?

Comment (markylaing) [reply lxd/identities.go:1040]: Yeah sorry I'm just having a moment of doubt :laughing:

**Comment by tomponline** [comment]
please can you rebase with the fixes for binfmt misc from main

**Review by tomponline — APPROVED** [review]
