### PR TITLE
Fix migration condition for bridged network devices

### LINKED ISSUE #12174: Issues with member evacuation when using auto mode
There appear to be inconsistencies between evacuating an instance created using a profile and one initialized with the same configuration directly.

# Steps to reproduce

Cluster is deployed on top of 3 virtual machines and is running LXD version `5.16`.

Profile `default`:
```yaml
config: {}
description: Default LXD profile
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by: []
```

Profile `empty`:
```yaml
config: {}
description: ""
devices: {}
name: empty
used_by: []
```

Network `lxdbr0`:
```yaml
config:
  ipv4.address: 10.141.159.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:90d9:c63:4199::1/64
  ipv6.nat: "true"
description: ""
name: lxdbr0
type: bridge
used_by: []
managed: true
status: Created
locations:
- cls-1
- cls-2
- cls-3
```

Create two instances on `cls-1`: one using the default profile and another by defining the storage and network via command flags.:
```
$ lxc launch ubuntu:22.04 c1 --target cls-1 --profile default
$ lxc launch ubuntu:22.04 c2 --target cls-1 --profile empty --storage default --network lxdbr0
$ lxc list

+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
| NAME |  STATE  |         IPV4         |                     IPV6                      |   TYPE    | SNAPSHOTS | LOCATION |
+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
| c1   | RUNNING | 10.222.237.91 (eth0) | fd42:9d34:ca94:de71:216:3eff:fe54:32c8 (eth0) | CONTAINER | 0         | cls-1    |
+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
| c2   | RUNNING | 10.222.237.38 (eth0) | fd42:9d34:ca94:de71:216:3eff:fe38:7f6c (eth0) | CONTAINER | 0         | cls-1    |
+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
```

Evacuate cluster member `cls-1`:
```
$ lxc cluster evacuate cls-1 --force
$ lxc list

+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
| NAME |  STATE  |         IPV4         |                     IPV6                      |   TYPE    | SNAPSHOTS | LOCATION |
+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
| c1   | STOPPED |                      |                                               | CONTAINER | 0         | cls-1    |
+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
| c2   | RUNNING | 10.222.237.38 (eth0) | fd42:9d34:ca94:de71:216:3eff:fe38:7f6c (eth0) | CONTAINER | 0         | cls-2    |
+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
```

Instance `c1` results in `STOPPED` state. This happens only when evacuation is done using `--action auto` and a profile applied to the instance.

---

## Debugging

I've added some logs in [lxd/instance/driver_common.go#canMigrate()](https://github.com/canonical/lxd/blob/8278714c6694491384b2517230f58f13a3e5d7f8/lxd/instance/drivers/driver_common.go#L1091-L1100):

```go
for deviceName, rawConfig := range d.ExpandedDevices() {
	dev, err := device.New(inst, d.state, deviceName, rawConfig, volatileGet, volatileSet)
	if err != nil {
		logger.Warnf("Instance %q cannot be auto migrated. Device %q stopped the migration due to an error: %v", inst.Name(), dev.Name(), err)
		return false, false
	}

	if !dev.CanMigrate() {
		logger.Warnf("Instance %q cannot be auto migrated. Device %q cannot be migrated. Device config: %+v", inst.Name(), dev.Name(), dev.Config())
		return false, false
	}

	logger.Warnf("[Instance %q] Device %q can be migrated. Device config: %+v", inst.Name(), dev.Name(), dev.Config())
}
```

And during evacuation the following output is intercepted:
```
Instance "c1" cannot be auto migrated. Device "eth0" cannot be migrated. 
Device config: map[nictype:bridged parent:lxdbr0 type:nic]

[Instance "c2"] Device "eth0" can be migrated. 
Device config: map[name:eth0 network:lxdbr0 parent:lxdbr0 type:nic]
```

So, the evacuation fails for `c1` because when calling [`dev.CanMigrate()`](https://github.com/canonical/lxd/blob/8278714c6694491384b2517230f58f13a3e5d7f8/lxd/device/nic_bridged.go#L55-L58) for bridged network device `eth0`, the device's config does not contain field `network`. 

---

I assume this is not expected behavior? 

In any case, I propose that we at least add a warning to the log that would indicate why the instance has failed the evacuation.

Any thoughts?

### PR DESCRIPTION
**Pull request by MusicDin**
This PR fixes the migration condition of bridged network device.
It also adds logging to show instances where auto-migration is prevented due to a device's lack of migration support.

Fixes #12174

### CODE REVIEW

File: lxd/device/nic_bridged.go [hunk 1]
```diff
@@ -54,7 +54,7 @@ func (d *nicBridged) CanHotPlug() bool {
 
 // CanMigrate returns whether the device can be migrated to any other cluster member.
 func (d *nicBridged) CanMigrate() bool {
-	return d.config["network"] != ""
+	return d.config["network"] != "" || d.config["parent"] != ""
```
Comment (tomponline) [inline lxd/device/nic_bridged.go:57]: Hrm, no its not that simple, sadly.

The `parent` could be an unmanaged bridge that we dont know is available on any other system (so "cant migrate").
We need to check if the `parent` is the name of a managed bridge.

However this should be easy because validation does this for various reasons and so we should be able to leverage that.

So we should be able to check if d.network != nil and if its non-nil then return true.

See https://github.com/canonical/lxd/blob/main/lxd/device/nic_bridged.go#L251

File: lxd/instance/drivers/driver_common.go [hunk 2]
```diff
@@ -1091,10 +1093,12 @@ func (d *common) canMigrate(inst instance.Instance) (bool, bool) {
 	for deviceName, rawConfig := range d.ExpandedDevices() {
 		dev, err := device.New(inst, d.state, deviceName, rawConfig, volatileGet, volatileSet)
 		if err != nil {
+			logger.Warnf("Instance %q cannot be auto migrated. Device %q stopped the migration due to an error: %v", inst.Name(), dev.Name(), err)
```
Comment (tomponline) [inline lxd/instance/drivers/driver_common.go:1096]: We dont use the `logger.*f()` functions and should instead use contextual logging, so something like:

```go
logger.Warn("Instance will not be migrated during evacuation due to a device error", logger.Ctx{"project": inst.Project().Name, "instance": inst.Name(), "device": dev.Name(), "err": err } )
```

File: lxd/instance/drivers/driver_common.go [hunk 3]
```diff
@@ -1091,10 +1093,12 @@ func (d *common) canMigrate(inst instance.Instance) (bool, bool) {
...
 			return false, false
 		}
 
 		if !dev.CanMigrate() {
+			logger.Warnf("Instance %q cannot be auto migrated. Device %q cannot be migrated.", inst.Name(), dev.Name())
```
Comment (tomponline) [inline lxd/instance/drivers/driver_common.go:1101]: Same point as above please convert to use contextual logging.

File: lxd/instance/drivers/driver_common.go (hunk 2 above)
Comment (MusicDin) [reply lxd/instance/drivers/driver_common.go:1096]: Thanks, will fix that.

File: shared/instance.go [hunk 4]
```diff
@@ -178,7 +178,21 @@ var InstanceConfigKeysAny = map[string]func(value string) error{
 	//  shortdesc: Legacy version of `cloud-init.vendor-data`
 
 	// lxddoc:generate(group=instance-miscellaneous, key=cluster.evacuate)
-	// Possible values are `auto`, `migrate`, `live-migrate`, or `stop`.
+	// The `cluster.evacuate` provides control over how instances are handled when a cluster member is being
+	// evacuated.
+	//
+	// Available Modes:
```
Comment (tomponline) [inline shared/instance.go:184]: Great comments! :)

File: lxd/device/nic_bridged.go (hunk 1 above)
Comment (tomponline) [reply lxd/device/nic_bridged.go:57]: Please test my assumption here though :)

Comment (MusicDin) [reply lxd/device/nic_bridged.go]: I've tested it and it works like a charm 😊

**Review by tomponline — APPROVED** [review]
