### PR TITLE
Require can_view on source for instance copy

### LINKED ISSUE #16982: The source of an instance/volume copy should be checked for CAN_VIEW permission
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

N/A

### Distribution version

N/A

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
N/A
```

### Output of "lxc info" or system info if it fails

```shell
N/A
```

### Issue description

When copying an instance, instance snapshot, volume or volume snapshot we should check that the user performing the operation has CAN_VIEW on the source entity.

This is similar to how you need CAN_VIEW today to export an instance or a volume.

### Steps to reproduce

N/A

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by kadinsayani**
Closes #16982.

Add an authorization check for can_view on the source instance or snapshot before processing POST /1.0/instances copy requests.

### CODE REVIEW

File: test/suites/auth.sh [hunk 1]
```diff
@@ -717,6 +717,28 @@ fine_grained_authorization() {
...
+
+  lxc_remote query --wait -X POST "${remote}:/1.0/instances?project=default" -d '{"name":"copy-target","source":{"type":"copy","source":"copy-source","project":"default"}}'
+  lxc_remote query --wait -X POST "${remote}:/1.0/instances?project=default" -d '{"name":"copy-target-snap","source":{"type":"copy","source":"copy-source/snap0","project":"default"}}'
+
+  lxc auth group permission remove test-group instance copy-source can_view project=default
+  lxc auth group permission remove test-group project default can_create_instances
+  lxc auth group permission remove test-group project default can_view
+  lxc delete copy-target-snap --force
+  lxc delete copy-target --force
+  lxc delete copy-source --force
```
Comment (simondeziel) [inline test/suites/auth.sh]: They were never started so `--force` is unneeded. Also, might worth bulk deleting all 3 at once?

File: lxd/instances_post.go [hunk 2]
```diff
@@ -1198,6 +1199,27 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
...
+
+		if req.Source.Project == "" {
+			req.Source.Project = targetProjectName
+		}
+
+		sourceURL := entity.InstanceURL(req.Source.Project, req.Source.Source)
+		if shared.IsSnapshot(req.Source.Source) {
+			instanceName, _, _ := api.GetParentAndSnapshotName(req.Source.Source)
+			sourceURL = entity.InstanceURL(req.Source.Project, instanceName)
+		}
```
Comment (simondeziel) [inline lxd/instances_post.go:1217]: I don't know if the compiler is smart enough to add an `else` branch so that `sourceURL` is set only once.

File: test/suites/auth.sh (hunk 1 above)
Comment (kadinsayani) [reply test/suites/auth.sh]: Fixed.

File: lxd/instances_post.go (hunk 2 above)
Comment (kadinsayani) [reply lxd/instances_post.go:1217]: Fixed.

File: lxd/instances_post.go [hunk 3]
```diff
@@ -1198,6 +1199,28 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
...
+		if shared.IsSnapshot(req.Source.Source) {
+			instanceName, _, _ = api.GetParentAndSnapshotName(req.Source.Source)
+		}
+
+		sourceURL := entity.InstanceURL(req.Source.Project, instanceName)
+
+		err = s.Authorizer.CheckPermission(r.Context(), sourceURL, auth.EntitlementCanView)
+		if err != nil {
+			return response.SmartError(err)
+		}
```
Comment (markylaing) [inline lxd/instances_post.go:1222]: Technically we should perform an authorization check against the snapshot itself, not just the instance:

```suggestion
        var sourceURL *api.URL
        instanceName, snapshotName, isSnapshot := api.GetParentAndSnapshotName(req.Source.Source)
        if isSnapshot {
                sourceURL = entity.InstanceSnapshotURL(req.Source.Project, instanceName, snapshotName)
        } else {
                sourceURL := entity.InstanceURL(req.Source.Project, instanceName)
        }

		err = s.Authorizer.CheckPermission(r.Context(), sourceURL, auth.EntitlementCanView)
		if err != nil {
			return response.SmartError(err)
		}
```

With that said, `can_view` on the snapshot is inherited from `can_view` on the instance, so this makes no functional difference at the moment. But should the model change, we'd need to check on the snapshot directly.

File: lxd/storage_volumes.go [hunk 4]
```diff
@@ -1063,6 +1063,31 @@ func storagePoolVolumesPost(d *Daemon, r *http.Request) response.Response {
...
+		if err != nil {
+			return response.SmartError(err)
+		}
+
+		sourceVolumeName := req.Source.Name
+		if shared.IsSnapshot(sourceVolumeName) {
+			sourceVolumeName, _, _ = api.GetParentAndSnapshotName(sourceVolumeName)
+		}
+
+		err = s.Authorizer.CheckPermission(r.Context(), entity.StorageVolumeURL(sourceProjectName, req.Source.Location, req.Source.Pool, req.Type, sourceVolumeName), auth.EntitlementCanView)
```
Comment (markylaing) [inline lxd/storage_volumes.go]: As in the previous case, we should technically perform the authorization check against the snapshot URL if it is a snapshot.

**Comment by kadinsayani** [comment]
> We need to use snapshot URLs for the authorization check (if it is a snapshot).
> 
> I think this is a place where the authorization model goes too fine-grained, so I'm open to removing snapshots and backups from it (permissions cannot be directly assigned to them) - however, IIRC this was a request from the UI team in order to use the `with-access-entitlements` query parameter with snapshots.

I've updated both checks to use the snapshot URLs.
