### PR TITLE
Network: Set veth/vtap host interface MTU to the larger of parent bridge or instance MTU

### LINKED ISSUE #18006: OVN VM guest NIC MTU is set correctly, but host-side tap interface stays at default 1500
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

Ubuntu

### Distribution version

24.04.4

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
$ snap list --all lxd core20 core22 core24 snapd
Name    Version         Rev    Tracking       Publisher   Notes
core22  20260225        2411   latest/stable  canonical✓  base
core24  20260211        1499   latest/stable  canonical✓  base,disabled
core24  20260317        1587   latest/stable  canonical✓  base
lxd     5.21.4-1374f39  38368  5.21/stable    canonical✓  in-cohort,held
snapd   2.74.1          26382  latest/stable  canonical✓  snapd
```

### Output of "lxc info" or system info if it fails

```shell
$ lxc info
config:
  cluster.https_address: 10.XX.YY.11:8443
  core.https_address: '[::]:8443'
  instances.migration.stateful: "true"
  network.ovn.northbound_connection: ssl:10.XX.YY.11:6641,ssl:10.XX.YY.12:6641,ssl:10.XX.YY.13:6641
  user.microcloud: 2.1.2
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- backup_compression
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
- clustering_update_cert
- storage_api_project
- server_instance_driver_operational
- server_supported_storage_drivers
- event_lifecycle_requestor_address
- resources_gpu_usb
- clustering_evacuation
- network_ovn_nat_address
- network_bgp
- network_forward
- custom_volume_refresh
- network_counters_errors_dropped
- metrics
- image_source_project
- clustering_config
- network_peer
- linux_sysctl
- network_dns
- ovn_nic_acceleration
- certificate_self_renewal
- instance_project_move
- storage_volume_project_move
- cloud_init
- network_dns_nat
- database_leader
- instance_all_projects
- clustering_groups
- ceph_rbd_du
- instance_get_full
- qemu_metrics
- gpu_mig_uuid
- event_project
- clustering_evacuation_live
- instance_allow_inconsistent_copy
- network_state_ovn
- storage_volume_api_filtering
- image_restrictions
- storage_zfs_export
- network_dns_records
- storage_zfs_reserve_space
- network_acl_log
- storage_zfs_blocksize
- metrics_cpu_seconds
- instance_snapshot_never
- certificate_token
- instance_nic_routed_neighbor_probe
- event_hub
- agent_nic_config
- projects_restricted_intercept
- metrics_authentication
- images_target_project
- cluster_migration_inconsistent_copy
- cluster_ovn_chassis
- container_syscall_intercept_sched_setscheduler
- storage_lvm_thinpool_metadata_size
- storage_volume_state_total
- instance_file_head
- instances_nic_host_name
- image_copy_profile
- container_syscall_intercept_sysinfo
- clustering_evacuation_mode
- resources_pci_vpd
- qemu_raw_conf
- storage_cephfs_fscache
- network_load_balancer
- vsock_api
- instance_ready_state
- network_bgp_holdtime
- storage_volumes_all_projects
- metrics_memory_oom_total
- storage_buckets
- storage_buckets_create_credentials
- metrics_cpu_effective_total
- projects_networks_restricted_access
- storage_buckets_local
- loki
- acme
- internal_metrics
- cluster_join_token_expiry
- remote_token_expiry
- init_preseed
- storage_volumes_created_at
- cpu_hotplug
- projects_networks_zones
- network_txqueuelen
- cluster_member_state
- instances_placement_scriptlet
- storage_pool_source_wipe
- zfs_block_mode
- instance_generation_id
- disk_io_cache
- amd_sev
- storage_pool_loop_resize
- migration_vm_live
- ovn_nic_nesting
- oidc
- network_ovn_l3only
- ovn_nic_acceleration_vdpa
- cluster_healing
- instances_state_total
- auth_user
- security_csm
- instances_rebuild
- numa_cpu_placement
- custom_volume_iso
- network_allocations
- storage_api_remote_volume_snapshot_copy
- zfs_delegate
- operations_get_query_all_projects
- metadata_configuration
- syslog_socket
- event_lifecycle_name_and_project
- instances_nic_limits_priority
- disk_initial_volume_configuration
- operation_wait
- cluster_internal_custom_volume_copy
- disk_io_bus
- storage_cephfs_create_missing
- instance_move_config
- ovn_ssl_config
- init_preseed_storage_volumes
- metrics_instances_count
- server_instance_type_info
- resources_disk_mounted
- server_version_lts
- oidc_groups_claim
- loki_config_instance
- storage_volatile_uuid
- import_instance_devices
- instances_uefi_vars
- instances_migration_stateful
- container_syscall_filtering_allow_deny_syntax
- access_management
- vm_disk_io_limits
- storage_volumes_all
- instances_files_modify_permissions
- image_restriction_nesting
- container_syscall_intercept_finit_module
- device_usb_serial
- network_allocate_external_ips
- explicit_trust_token
- instance_import_conversion
- instance_create_start
- devlxd_images_vm
- instance_protection_start
- disk_io_bus_virtio_blk
- metadata_configuration_entity_types
- network_allocations_ovn_uplink
- network_ovn_uplink_vlan
- shared_custom_block_volumes
- metrics_api_requests
- projects_limits_disk_pool
- access_management_tls
- state_logical_cpus
- vm_limits_cpu_pin_strategy
- gpu_cdi
- metadata_configuration_scope
- unix_device_hotplug_ownership_inherit
- unix_device_hotplug_subsystem_device_option
- storage_ceph_osd_pool_size
- network_get_target
- network_zones_all_projects
- vm_root_volume_attachment
- projects_limits_uplink_ips
- entities_with_entitlements
- profiles_all_projects
- storage_driver_powerflex
- storage_driver_pure
- cloud_init_ssh_keys
- oidc_scopes
- project_default_network_and_storage
- ubuntu_pro_guest_attach
- images_all_projects
- client_cert_presence
- resources_device_fs_uuid
- clustering_groups_used_by
- container_bpf_delegation
- override_snapshot_profiles_on_copy
- backup_metadata_version
- storage_buckets_all_projects
- network_acls_all_projects
- networks_all_projects
- clustering_restore_skip_mode
- disk_io_threads_virtiofsd
- oidc_client_secret
- pci_hotplug
- device_patch_removal
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
client_certificate: false
auth_user_name: ubuntu
auth_user_method: unix
environment:
  addresses:
  - 10.XX.YY.11:8443
  - 10.XX.YY.51:8443
  architectures:
  - x86_64
  - i686
  backup_metadata_version_range:
  - 1
  - 2
  certificate: |
    <TRUNCATED>
  certificate_fingerprint: b55c6edfd6263b3e518c331263cb5da6f0bfc3dd7fb2f37e51b8970aa155f4d3
  driver: lxc | qemu
  driver_version: 6.0.4 | 8.2.2
  instance_types:
  - container
  - virtual-machine
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    bpf_token: "false"
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    uevent_injection: "true"
    unpriv_binfmt: "true"
    unpriv_fscaps: "true"
  kernel_version: 6.8.0-106-generic
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "24.04"
  project: default
  server: lxd
  server_clustered: true
  server_event_mode: full-mesh
  server_name: XX-YY-Z1-IN01
  server_pid: 7395
  server_version: 5.21.4
  server_lts: true
  storage: ceph | cephfs
  storage_version: 17.2.9 | 17.2.9
  storage_supported_drivers:
  - name: btrfs
    version: 5.16.2
    remote: false
  - name: ceph
    version: 17.2.9
    remote: true
  - name: cephfs
    version: 17.2.9
    remote: true
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.11(2) (2021-01-08) / 1.02.175 (2021-01-08) / 4.48.0
    remote: false
  - name: pure
    version: 2.1.9 (iscsiadm) / 1.16 (nvme-cli)
    remote: true
  - name: zfs
    version: 2.2.2-0ubuntu9.4
    remote: false
  - name: cephobject
    version: 17.2.9
    remote: true
  - name: powerflex
    version: 1.16 (nvme-cli)
    remote: true
```

### Issue description

When a VM is created on an OVN network, LXD correctly applies the OVN network MTU to the guest NIC. In this case, the OVN network is configured with `bridge.mtu=8942`, and the guest VM NIC comes up with MTU 8942 as expected.

However, the corresponding host-side `tap*` interface for that VM is created with MTU 1500 instead of the effective OVN/guest NIC MTU. As a result, the VM advertises and transmits with MTU 8942, but traffic hits a 1500-byte bottleneck at the host TAP device.

In a jumbo underlay deployment, this breaks OVN-backed VM connectivity for larger packets even though:
- the physical uplink/underlay is jumbo-capable
- the OVN network MTU is configured correctly
- the guest NIC MTU is configured correctly

Manually changing the host-side TAP MTU to match the OVN/guest MTU immediately fixes the problem.

- This appears specific to VMs, where the host-side endpoint is a TAP device.
- The problem is not with the guest NIC MTU, which is set correctly.
- The problem is not with the physical underlay MTU, which is jumbo-capable.
- The failure is caused by the host-side TAP interface remaining at MTU 1500.
- This also happens when bridge.mtu is set to a different value, e.g. 1442.

Expected behavior:
The host-side TAP interface created for a VM on an OVN network should inherit or be programmed with the effective OVN/NIC MTU, rather than remaining at the default 1500.

### Steps to reproduce

1. Create or use a jumbo-capable uplink/underlay network, for example with MTU 9000.

2. Create an OVN network attached to that uplink, with a reduced OVN MTU to account for encapsulation, for example:
   - uplink MTU: 9000
   - OVN network `bridge.mtu`: 8942

3. Launch a VM on that OVN network.

4. Inside the VM, verify that the guest NIC has the OVN MTU:
   ip link show

5. On the host, identify the corresponding host-side `tap*` interface for that VM and verify its MTU:
   ip link show tapXXXX

6. Observe that:
   - the guest NIC MTU is 8942
   - the host-side tap MTU is 1500

7. Attempt jumbo traffic from the VM, for example with DF set and a payload that fits 8942 but not 1500.

8. Observe that the traffic fails.

9. On the host, manually set the TAP MTU to match the OVN/guest MTU:
   ip link set dev tapXXXX mtu 8942

10. Retry the same traffic.

11. Observe that traffic now succeeds.

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by tomponline**
- De-dupes veth/tap pair MTU logic into `networkCalculatePairMTU` and adds logic to ensure that when devices are attached to a bridge that may do not reduce the bridge's MTU, but only allow a possible increase in the bridge's MTU.
- Use OVN integration bridge interface as `parent` when calculating veth/tap pair MTU.
- Applies the calculated instance NIC MTU value to QEMU's netdev so that even if the host interface's MTU has been set larger that the instance's NIC (to allow it to be safely attached to the bridge) that the instance guest only sees the instance MTU specified.
- Allows using MTUs down to IPv4 minimum (68 bytes).

Fixes https://github.com/canonical/lxd/issues/18006
Fixes https://github.com/canonical/lxd/issues/18068

### CODE REVIEW

File: lxd/device/device_utils_network.go [hunk 1]
```diff
@@ -207,6 +207,45 @@ func networkRestorePhysicalNIC(hostName string, volatile map[string]string) erro
...
+	// If instance MTU is not specified, but host MTU is, then use the host MTU for the instance side to avoid
+	// accidentally lowering the MTU of the parent bridge.
+	if instanceMTU == 0 && hostMTU > 0 {
+		instanceMTU = hostMTU
+	}
+
+	// If host MTU is less than instance MTU then the parent bridge is likely to drop packets from the instance,
+	// so use the instance MTU for the host side to avoid this. This should increase the parent bridge MTU
+	// if needed (for the duration that the instance is connected to the bridge) and if the bridge has not got
+	// an MTU explicitly set.
```
Comment (roosterfish) [inline lxd/device/device_utils_network.go:241]: I assume this is for cases where you want to ensure higher MTU between instances connected to the bridge? So traffic leaving the bridge (not destined for any of the instances) will break if exceeding the bridges actual MTU?

File: lxd/instance/drivers/driver_qemu.go [hunk 2]
```diff
@@ -4727,6 +4727,17 @@ func (d *qemu) addNetDevConfig(busName string, busAllocate busAllocator, bootInd
 			qemuDev["netdev"] = qemuNetDevID
 			qemuDev["mac"] = devHwaddr
 
+			if mtu != "" {
```
Comment (roosterfish) [inline lxd/instance/drivers/driver_qemu.go:4732]: Is this already in place for containers? I remember [this](https://github.com/canonical/lxd/issues/18006#issuecomment-4258301065) comment and wonder if this is the missing bit.

**Review by roosterfish — DISMISSED** [review]
Looking good to me, only a few comments for clarification.

File: lxd/device/device_utils_network.go (hunk 1 above)
Comment (tomponline) [reply lxd/device/device_utils_network.go:241]: Yeah, if a bridge interface doesn't have an explicit MTU set, then its MTU is dynamic based on the smallest interface connected as I understand it.

And its MTU will grow if needed from 1500.

So if you have 2 OVN networks with instances both connecting to the integration OVS bridge and one network has say bridge.mtu=1508 and the other has bridge.mtu=8942, the integration bridge will increase to 1508 when instances from both are connected, but when instances from other the bridge.mtu=8942 are connected it goes up to 8942.

So this logic aims to never reduced the bridge's MTU only grow it if needed.

I need to add some more testing to confirm this, but that has been my observation so far.

However we still dont want the instances from the bridge.mtu=1508 network to get the MTU from the bridge.mtu=8942 network, so we explicitly set the instance interface MTU to 1508 on the host side and pass that into qemu via the `host_mtu` setting.

File: lxd/instance/drivers/driver_qemu.go (hunk 2 above)
Comment (tomponline) [reply lxd/instance/drivers/driver_qemu.go:4732]: Yes thats right, because containers use either a veth pair or a macvlan, and so we setup the MTUs directly on the interface before we pass them into the network namespace.

Whereas with VMs that use tap interfaces, we only directly control the host side interface and we have to instruct qemu to configure the VM guest side device correctly.

Comment (roosterfish) [reply lxd/instance/drivers/driver_qemu.go:4732]: Ack thanks.

File: test/suites/container_devices_nic_macvlan.sh [hunk 3]
```diff
@@ -129,13 +129,12 @@ test_container_devices_nic_macvlan() {
...
   ! lxc network set "${ctName}net" mtu=0 || false
-  ! lxc network set "${ctName}net" mtu=1000 || false
-  ! lxc network set "${ctName}net" mtu=1279 || false
+  ! lxc network set "${ctName}net" mtu=67 || false
   ! lxc network set "${ctName}net" mtu=16385 || false
   ! lxc network set "${ctName}net" mtu=50000 || false
 
   echo "==> Check that setting MTU config value to the boundaries of range (1280-16384) is allowed."
-  lxc network set "${ctName}net" mtu=1280
+  lxc network set "${ctName}net" mtu=68
```
[the remark this answers is not in the document]
Comment (tomponline) [reply test/suites/container_devices_nic_macvlan.sh:137]: fixed

File: shared/validate/validate.go [hunk 4]
```diff
@@ -460,17 +460,17 @@ func IsNetworkVLAN(value string) error {
...
 	mtu, err := strconv.ParseUint(value, 10, 32)
 	if err != nil {
 		return fmt.Errorf("Invalid MTU %q", value)
 	}
 
-	if mtu < 1280 || mtu > 16384 {
-		return fmt.Errorf("Out of MTU range (1280-16384) %q", value)
+	if mtu < 68 || mtu > 16384 {
+		return fmt.Errorf("Out of MTU range (68-16384) %q", value)
 	}
```
[the remark this answers is not in the document]
Comment (tomponline) [reply shared/validate/validate.go:474]: this is expected and can be future work

**Review by roosterfish — APPROVED** [review]
LGTM

**Review by nmezhenskyi — APPROVED** [review]
LGTM!
