### PR TITLE
Apply the `snapshots.pattern` option for manual custom volume snapshot

### LINKED ISSUE #12630: Custom storage volume snapshot naming does not work with `snapshots.pattern` config
# Required information

 * Distribution: Ubuntu snap
 * Distribution version: 5.19

# Issue description

When creating snapshots for custom storage volumes using `lxc storage volume snapshot [<remote>:]<pool> <volume> [<snapshot>] [flags]`, the naming of the snapshots does not respect the `snapshots.pattern` volume configuration if the optional snapshot name argument is not provided.

The expected behaviour is that the snapshot name should adhere to the pattern specified by the `snapshots.pattern` custom storage volume config. This would be particular helpful for scheduling snapshots for custom volume storage.

It should be noted that the `snapshots.pattern` config for instances works as expected when creating instance snapshots. This should motivate that the same behaviour to be supported for storage volume snapshots.

# Steps to reproduce

Refer to the screenshot below:
image

### PR DESCRIPTION
**Pull request by gabrielmougard**
closes #12630

### CODE REVIEW

File: lxd/storage_volumes_snapshot.go [hunk 1]
```diff
@@ -187,13 +181,44 @@ func storagePoolVolumeSnapshotsTypePost(d *Daemon, r *http.Request) response.Res
...
+	err = s.DB.Cluster.Transaction(r.Context(), func(ctx context.Context, tx *db.ClusterTx) error {
+		// Get the parent volume so we can get the config.
+		parentDBVolume, err = tx.GetStoragePoolVolume(ctx, pool.ID(), projectName, volumeType, volumeName, true)
+		if err != nil {
+			return err
+		}
+
+		// We will need the parent volume config to determine the snapshot name.
+		if req.Name == "" {
+			parentVolumeArgs, err = tx.GetStoragePoolVolumeWithID(ctx, int(parentDBVolume.ID))
```
Comment (roosterfish) [inline lxd/storage_volumes_snapshot.go:195]: Can you move this into the `if req.Name == "" {}` block below? This way you also don't have to export `parentVolumeArgs`.

**Review by roosterfish — CHANGES_REQUESTED** [review]

File: lxd/storage_volumes_snapshot.go (hunk 1 above)
Comment (gabrielmougard) [reply lxd/storage_volumes_snapshot.go:195]: This would lead to the creation of a new transaction, so I think this would be slower or cause an issue... Moreover, `volumeDetermineNextSnapshotName` is already creating a transaction internally: these nested transactions will likely cause a deadlock (or in the best scenario slow down the performance). It is also possible that commands like ROLLBACK or COMMIT in the inner transaction might unexpectedly apply to the entire outer transaction.

Comment (roosterfish) [reply lxd/storage_volumes_snapshot.go:195]: Ah yes you still need to access `tx.`. My mistake then :)

**Review by roosterfish — APPROVED** [review]
LGTM!

File: lxd/storage_volumes_snapshot.go (hunk 1 above)
Comment (roosterfish) [reply lxd/storage_volumes_snapshot.go:195]: Ah yes you still need to access `tx.`. My mistake then :)

File: lxd/storage_volumes_snapshot.go [hunk 2]
```diff
@@ -203,17 +228,8 @@ func storagePoolVolumeSnapshotsTypePost(d *Daemon, r *http.Request) response.Res
...
 
-		// Get the parent volume so we can get the config.
-		parentDBVolume, err = tx.GetStoragePoolVolume(ctx, pool.ID(), projectName, volumeType, volumeName, true)
-		if err != nil {
-			return err
-		}
-
 		return nil
 	})
-	if err != nil {
```
Comment (tomponline) [inline lxd/storage_volumes_snapshot.go:214]: why are you removing the error handling from this transaction result here?

**Review by tomponline — APPROVED** [review]
