### PR TITLE
lxd: Start the DNS listener after the networks are started

### LINKED ISSUE #12955: Using `core.dns_address=$LXDBR0_IP` might fail on reboot
# Required information

 * Distribution version: 5.20
 * The output of "snap list --all lxd core20 core22 core24 snapd": see attached snap_list_all.txt
  * The output of "lxc info" or if that fails: see attached lxc_info.txt
   * Kernel version:Linux 6.1.0-1033-oem x86_64
   * LXC version: 5.20
   * LXD version: 5.20
   * Storage backend in use: local SSD

# Issue description

I am consistently running into an issue after configuring the Zone transfer feature with LXD
For the guidelines I use this page and the demo here: https://documentation.ubuntu.com/lxd/en/stable-5.0/howto/network_zones/
I also use the configuration with port 8853 like so:
`lxc config set core.dns_address 10.157.229.1:8853`

My DNS server (I also use NSD) is also deployed locally as a VM on the host machine. And once configured it all works as described.
However, The issue is that once I reboot the host machine, the NSD server fails to connect on the same port. the issue is unrecoverable and requires setup anew.

Here is the `journalctl -f` log fragment from the NSD server:
`Feb 23 01:54:05 ns1 nsd[397]: redistest.com: Could not tcp connect to 10.157.229.1@8853: Connection refused Feb 23 01:54:05 ns1 nsd[397]: 229.157.10.in-addr.arpa: Could not tcp connect to 10.157.229.1@8853: Connection refused `

Please advise if it is a known issue and if workaround is available.

Thanks!

# Attachments:
[snap_list_all.txt](https://github.com/canonical/lxd/files/14391435/snap_list_all.txt)
[lxc_info.txt](https://github.com/canonical/lxd/files/14391439/lxc_info.txt)

### PR DESCRIPTION
**Pull request by escabo**
This should fix #12955. Did not change anything regarding BGP for now as I would like to set a test environment for that first.

### CODE REVIEW

**Review by tomponline — CHANGES_REQUESTED** [review]
Would you be able to add a test for this - to check one can set the DNS listener address on the bridge network IP?

Would be to rework this bit:

https://github.com/canonical/lxd/blob/main/test/suites/network_zone.sh#L7-L15

To setup network first, set the DNS listener to that IP, and then restart LXD and check it was established again.

Using `respawn_lxd "${LXD_DIR}" true`

**Comment by simondeziel** [comment]
Should the BGP listener also be started after the networks have been initialized?

**Comment by escabo** [comment]
> Should the BGP listener also be started after the networks have been initialized?
> 
> Update: looks like Tom had already mentioned this in [#12955 (comment)](https://github.com/canonical/lxd/issues/12955#issuecomment-1999978538)

Yes. I just want to set up a test env before I move the code.

**Comment by tomponline** [comment]
@escabo  are you OK if we close this until the changes can be addressed to get the open PR list down? Thanks

**Comment by tomponline** [comment]
Lets leave open as you're actively working on it thanks

File: test/suites/network_zone.sh [hunk 1]
```diff
@@ -73,14 +69,18 @@ test_network_zone() {
...
 
   # Setup DNS peers
-  lxc network zone set lxd.example.net peers.test.address=127.0.0.1
-  lxc network zone set lxdfoo.example.net peers.test.address=127.0.0.1 --project=foo
-  lxc network zone set 2.0.192.in-addr.arpa peers.test.address=127.0.0.1
-  lxc network zone set 0.1.0.1.2.4.2.4.2.4.2.4.2.4.d.f.ip6.arpa peers.test.address=127.0.0.1
+  lxc network zone set lxd.example.net peers.test.address=192.0.2.1
+  lxc network zone set lxdfoo.example.net peers.test.address=192.0.2.1 --project=foo
+  lxc network zone set 2.0.192.in-addr.arpa peers.test.address=192.0.2.1
+  lxc network zone set 0.1.0.1.2.4.2.4.2.4.2.4.2.4.d.f.ip6.arpa peers.test.address=192.0.2.1
```
Comment (simondeziel) [inline test/suites/network_zone.sh:75]: This `peers.test.address` is AFAIK the receiving end of a zone transfer (AXFR/IXFR) so `127.0.0.1` was a presumably a bogus placeholder that would simply drop those XFRs on the floor. In a real deployment, I'd expect a bind9/nsd server to get them.

Could we leave them at `127.0.0.1`? Or maybe I'm just reading it wrong.

File: test/suites/network_zone.sh [hunk 2]
```diff
@@ -73,14 +69,18 @@ test_network_zone() {
...
+
+  # Enable the DNS listener on the bridge itself
+  lxc config unset core.https_address
+  lxc config set core.dns_address 192.0.2.1:8853
```
Comment (simondeziel) [inline test/suites/network_zone.sh:79]: Since you are using a non-wildcard/non-clashing IP for the DNS address, do we still need to unset/set the `core.https_address` at all?

**Review by simondeziel — COMMENTED** [review]
LGTM with maybe some minor tweaks to reduce the test's diff.

File: test/suites/network_zone.sh (hunk 2 above)
Comment (escabo) [reply test/suites/network_zone.sh:79]: No but should we leave them there for consistency? (I will move the unset back at the top where it belongs)

File: test/suites/network_zone.sh (hunk 1 above)
Comment (escabo) [reply test/suites/network_zone.sh:75]: The transfer does not happen when I use 127.0.0.1

Comment (tomponline) [reply test/suites/network_zone.sh:77]: This makes sense as the source addressed used by `dig` command will be the bridge's own IP and not 127.0.0.1

**Review by tomponline — APPROVED** [review]
Thanks!

File: test/suites/network_zone.sh (hunk 1 above)
Comment (simondeziel) [reply test/suites/network_zone.sh:77]: @tomponline is this because there is an IP ACL that's derived from that `peers.test.address`? If do, would using `dig -b <address>` be a valid way to comply with the ACL?

I'm not trying to advocate to change anything in the test, just trying to wrap my mind around it (to maybe add some explaining notes in the test) :)

Comment (tomponline) [reply test/suites/network_zone.sh:77]: Yeah, peers.test.address sets which peers can request the AXFR transfer.
