### PR TITLE
btrfs: Handle pools whose source is a subvolume outside of the pool mount path

### LINKED ISSUE #12496: lxc storage create btrfs do not work anymore
# Required information

 * Distribution: ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version:6.2.0-36-generic
   * LXC version:
   * LXD version:lxd     5.19-31ff7b6  26093  5.19/stable    canonical✓  -

   * Storage backend in use: btrfs

# Issue description

lxc storage create  GUEST btrfs  source=/mnt/GUEST

worked with no issue before, in 5.19 it fail:

LXDHOST:root@:[~]: lxc storage create  GUEST btrfs  source=/mnt/GUEST
Error: Could not determine if existing btrfs subvolume is empty: "/var/lib/snapd/hostfs/mnt/GUEST" is outside pool mount path "/var/snap/lxd/common/lxd/storage-pools/GUEST"

# Steps to reproduce

create a btrfs volume
mount it
try creating a storage with it

# Information to attach

i eventualy made it work by downgrading to 5.16, create the storage, upgrade to 5.19....

LXDHOST:root@:[~]: lxc storage create  GUEST btrfs  source=/mnt/GUEST
Error: Could not determine if existing btrfs subvolume is empty: "/var/lib/snapd/hostfs/mnt/GUEST" is outside pool mount path "/var/snap/lxd/common/lxd/storage-pools/GUEST"

LXDHOST:root@:[~]: ll /mnt/GUEST
total 0

LXDHOST:root@:[~]: grep /mnt/GUEST /proc/mounts 
/dev/sda5 /mnt/GUEST btrfs rw,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=5,subvol=/ 0 0

LXDHOST:root@:[~]: snap install lxd --channel=5.16/stable
lxd (5.16/stable) 5.16-f2b0200 from Canonical✓ installed

create the storage...

LXDHOST:root@:[~]: snap refresh lxd --channel=5.19/stable
2023-11-02T13:18:57+01:00 INFO Waiting for "snap.lxd.daemon.service" to stop.
lxd (5.19/stable) 5.19-31ff7b6 from Canonical✓ refreshed

LXDHOST:root@:[~]: lxc storage list
To start your first container, try: lxc launch ubuntu:22.04
Or for a virtual machine: lxc launch ubuntu:22.04 --vm

+-------+--------+------------+-------------+---------+---------+
| NAME  | DRIVER |   SOURCE   | DESCRIPTION | USED BY |  STATE  |
+-------+--------+------------+-------------+---------+---------+
| GUEST | btrfs  | /mnt/GUEST |             | 1       | CREATED |

### PR DESCRIPTION
**Pull request by monstermunchkin**
This fixes an issue where btrfs pools whose source is a subvolume outside of the pool mount path would fail being created.
However, as this scenario is totally valid, it should be handled correctly.

Fixes #12496

Fixes regression from https://github.com/canonical/lxd/pull/12258/commits/7ebca54656208a4d24f7fd488271d677b8882c16

### CODE REVIEW

File: lxd/storage/drivers/driver_btrfs_utils.go [hunk 1]
```diff
@@ -124,11 +131,15 @@ func (d *btrfs) getSubvolumes(path string) ([]string, error) {
 			continue
 		}
 
-		if !strings.HasPrefix(fields[8], path) {
+		if !strings.HasPrefix(fields[8], prefix) {
```
Comment (tomponline) [inline lxd/storage/drivers/driver_btrfs_utils.go:134]: Lets extract `fields[8]` into a meaningful variable name to aid reader.

File: lxd/storage/drivers/driver_btrfs_utils.go [hunk 2]
```diff
@@ -96,18 +96,25 @@ func (d *btrfs) isSubvolume(path string) bool {
...
-	}
-
-	path = strings.TrimPrefix(path, poolMountPath+"/")
-
 	// Make sure the path has a trailing slash.
 	if !strings.HasSuffix(path, "/") {
 		path = path + "/"
 	}
 
+	poolMountPath := GetPoolMountPath(d.name)
```
Comment (tomponline) [inline lxd/storage/drivers/driver_btrfs_utils.go:104]: thanks for taking a look at this.

I'm a bit concerned this function is starting to get quite complex to figure out what path to be using.
Is this perhaps an indication that the definition of `path` for this function isn't clear or its being (mis)used in some places?
Should we be doing additional transform outside of the function to path in pool-level situations?

Comment (monstermunchkin) [reply lxd/storage/drivers/driver_btrfs_utils.go:104]: I don't find this too complex, and the definition of `path` is also clear. Switching to `btrfs subvolume` just caused a regression which this PR attempts to fix. We should just handle this special case, and leave the rest as it is.

Comment (tomponline) [reply lxd/storage/drivers/driver_btrfs_utils.go:104]: I'm wondering why the `path` provided to the function isn't always a valid btrfs subvolume?

Comment (monstermunchkin) [reply lxd/storage/drivers/driver_btrfs_utils.go:110]: I've reverted the changes on `getSubvolumes`, and added a new function `hasSubvolumes` as that's what `Create` actually cares about.

**Review by tomponline — APPROVED** [review]
