### PR TITLE
Image synchronization between each node in the cluster

### LINKED ISSUE #5040: LXD should sync manually imported images inside the cluster to a limited number of nodes
# Required information

n/a

# Issue description

We import images manually into an LXD cluster and also create some from existing containers on a regular base. To have them all time available and never loose any of them  (for example when a node with one of the images is removed but it was never used on any of the other nodes yet) it would be nice if LXD can distribute all not cached images onto a limited set of nodes in the cluster (matching the number of database nodes?). 

# Steps to reproduce

n/a

# Information to attach

n/a

### PR DESCRIPTION
**Pull request by adglkh**
The initial implementation of image synchronization between each node in the cluster.
Fix #5040

### CODE REVIEW

**Comment by morphis** [comment]
@stgraber As promised :-)

File: lxd/cluster/config.go [hunk 1]
```diff
@@ -218,6 +223,7 @@ func configGet(cluster *db.Cluster) (*Config, error) {
 var ConfigSchema = config.Schema{
 	"backups.compression_algorithm":  {Default: "gzip", Validator: validateCompression},
 	"cluster.offline_threshold":      {Type: config.Int64, Default: offlineThresholdDefault(), Validator: offlineThresholdValidator},
+	"cluster.image_sync_node_count":  {Type: config.Int64, Default: imageSyncNodeCountDefault(), Validator: imageSyncNodeCountValidator},
```
Comment (stgraber) [inline lxd/cluster/config.go]: How about `cluster.image_minimal_replica`? We don't like `node` being mentioned anywhere outside of internal code.

File: lxd/cluster/config.go [hunk 2]
```diff
@@ -265,6 +275,17 @@ func offlineThresholdValidator(value string) error {
 	return nil
 }
 
+func imageSyncNodeCountValidator(value string) error {
+	imageSyncNodeCount, err := strconv.Atoi(value)
+	if err != nil {
+		return fmt.Errorf("image sync node count is not a number")
```
Comment (stgraber) [inline lxd/cluster/config.go]: All errors must start with a capital letter (yes, I realize the function above this one does it wrong...)

File: lxd/cluster/config.go [hunk 3]
```diff
@@ -265,6 +275,17 @@ func offlineThresholdValidator(value string) error {
...
+	}
+	if imageSyncNodeCount < 0 {
+		return fmt.Errorf("value must be greater than or equal to 0")
```
Comment (stgraber) [inline lxd/cluster/config.go]: Same comment wrt errors

File: lxd/images.go [hunk 4]
```diff
@@ -734,6 +734,11 @@ func imagesPost(d *Daemon, r *http.Request) Response {
 			}
 		}
 
+		// Sync the images between each node in the cluster on demand
+		if err := imageSyncBetweenNodes(d, req, info.Fingerprint, imageUpload, post); err != nil {
+			return errors.Wrapf(err, "Image sync bwtween nodes")
```
Comment (stgraber) [inline lxd/images.go]: typo

File: lxd/images.go [hunk 5]
```diff
@@ -734,6 +734,11 @@ func imagesPost(d *Daemon, r *http.Request) Response {
 			}
 		}
 
+		// Sync the images between each node in the cluster on demand
+		if err := imageSyncBetweenNodes(d, req, info.Fingerprint, imageUpload, post); err != nil {
```
Comment (stgraber) [inline lxd/images.go]: we try to avoid one-line function calls + error check in general, please make this two lines

**Comment by stgraber** [comment]
@freeekanayaka can you take a look at this?

**Comment by stgraber** [comment]
@morphis  @adglkh please see review comments above

File: lxd/db/images.go [hunk 6]
```diff
@@ -889,3 +889,67 @@ func (c *Cluster) ImageUploadedAt(id int, uploadedAt time.Time) error {
 	err := exec(c.db, "UPDATE images SET upload_date=? WHERE id=?", uploadedAt, id)
 	return err
 }
+
+// ImageGetNodesHasImage returns the list of the address of online nodes
+// which already have the image.
+// Note: the local address is not included in the returned address list.
+func (c *Cluster) ImageGetNodesHasImage(fingerprint string) ([]string, error) {
```
Comment (freeekanayaka) [inline lxd/db/images.go]: I'd rename this method to ```ImageGetNodesWithImage```

File: lxd/db/images.go [hunk 7]
```diff
@@ -889,3 +889,67 @@ func (c *Cluster) ImageUploadedAt(id int, uploadedAt time.Time) error {
...
+	return c.getNodesByImageFingerprint(fingerprint, true)
+}
+
+// ImageGetNodesHasNoImage returns the list of the address of online nodes
```
Comment (freeekanayaka) [inline lxd/db/images.go]:
```suggestion
// ImageGetNodesHasNoImage returns the addresses of online nodes
```

File: lxd/db/images.go [hunk 8]
```diff
@@ -889,3 +889,67 @@ func (c *Cluster) ImageUploadedAt(id int, uploadedAt time.Time) error {
...
+// which don't have the image.
+// Note: the local address is not included in the returned address list.
+func (c *Cluster) ImageGetNodesHasNoImage(fingerprint string) ([]string, error) {
+	return c.getNodesByImageFingerprint(fingerprint, false)
+}
+
+func (c *Cluster) getNodesByImageFingerprint(fingerprint string, hasImage bool) ([]string, error) {
+	q := `
+SELECT nodes.address FROM nodes
```
Comment (freeekanayaka) [inline lxd/db/images.go]: I suspect that you need ```DISTINCT``` here, to avoid getting duplicate addresses in case ```hasImage``` is ```false```.

File: lxd/images.go [hunk 9]
```diff
@@ -1907,5 +1912,81 @@ func imageRefresh(d *Daemon, r *http.Request) Response {
...
+
+		for idx := int64(0); idx < min(int64(len(addresses)), nodeCount); idx++ {
+			client, err := cluster.Connect(addresses[idx], d.endpoints.NetworkCert(), false)
+			if err != nil {
+				return errors.Wrap(err, "Failed to connect node for image synchronization")
+			}
+
+			// We spread the image for the nodes inside of cluster and we need to double
+			// check if the image already exists since when one certain node is going to
+			// create an image it will goes into the same routine.
```
Comment (freeekanayaka) [inline lxd/images.go]:
```suggestion
			// create an image it will invoke the same routine.
```

File: lxd/images.go [hunk 10]
```diff
@@ -1907,5 +1912,81 @@ func imageRefresh(d *Daemon, r *http.Request) Response {
...
+			fingerprints, err := client.GetImageFingerprints()
+			if err != nil {
+				return errors.Wrap(err, "Failed to fetch container's all image finger prints")
```
Comment (freeekanayaka) [inline lxd/images.go]:
```suggestion
				return errors.Wrap(err, "Failed to fetch image fingerprints")
```

File: lxd/images.go [hunk 11]
```diff
@@ -1907,5 +1912,81 @@ func imageRefresh(d *Daemon, r *http.Request) Response {
...
+		}
+
+		for idx := int64(0); idx < min(int64(len(addresses)), nodeCount); idx++ {
+			client, err := cluster.Connect(addresses[idx], d.endpoints.NetworkCert(), false)
+			if err != nil {
+				return errors.Wrap(err, "Failed to connect node for image synchronization")
+			}
+
+			// We spread the image for the nodes inside of cluster and we need to double
+			// check if the image already exists since when one certain node is going to
```
Comment (freeekanayaka) [inline lxd/images.go]: I believe that the double check mitigates the race, but does not eliminate it completely. Perhaps having and idempotent client.CreateImage API would be better. @stgraber might give more informed advice about this tho.

**Comment by adglkh** [comment]
Sorry for the late reply. Please take another look.
The potential improvement is to have a task scheduler in place and running on the background for the image synchronization across the nodes in the cluster once the daemon is up. The benefits here is that
1. If we have multiple nodes in place, the image importing takes a long time to complete. Moving the image sync out of the imagePost routine saves a lot of times.
2. The current implementation doesn't cover the case that if we create a node on demand, the image sync won't operate as it only happens when importing an image.

In terms of anbox, having been discussed with @morphis , we need to auto-sync images over each node once a new node is added because it gives a significance optimization on container creation,  as well as for the time-saving purpose. I'd like to hear you guys' opinion on this and will create a separated PR for this once you guys feel happy about the potential improvement.
Thanks!

**Comment by adglkh** [comment]
@stgraber  @freeekanayaka could you help to review this PR? 
Thanks in advance.

File: lxd/cluster/config.go [hunk 12]
```diff
@@ -127,6 +127,11 @@ func (c *Config) OfflineThreshold() time.Duration {
 	return time.Duration(n) * time.Second
 }
 
+// ImageSyncNodeCount returns the numbers of nodes for images synchronization inside of cluster.
+func (c *Config) ImageSyncNodeCount() int64 {
```
Comment (freeekanayaka) [inline lxd/cluster/config.go]: Please change the name of the method to ImageMinimalReplica.

File: lxd/cluster/config.go [hunk 13]
```diff
@@ -252,15 +258,30 @@ func offlineThresholdDefault() string {
 	return strconv.Itoa(db.DefaultOfflineThreshold)
 }
 
+func imageSyncNodeCountDefault() string {
```
Comment (freeekanayaka) [inline lxd/cluster/config.go]: Please change the name of this function to imageMinimalReplicaDefault().

File: lxd/cluster/config.go [hunk 14]
```diff
@@ -252,15 +258,30 @@ func offlineThresholdDefault() string {
...
+		return fmt.Errorf("Offline threshold is not a number")
 	}
 	if threshold <= heartbeatInterval {
-		return fmt.Errorf("value must be greater than '%d'", heartbeatInterval)
+		return fmt.Errorf("Value must be greater than '%d'", heartbeatInterval)
+	}
+	return nil
+}
+
+func imageSyncNodeCountValidator(value string) error {
```
Comment (freeekanayaka) [inline lxd/cluster/config.go]: Please update the name of this function to imageMinimalReplicaValidator.

File: client/interfaces.go [hunk 15]
```diff
@@ -278,6 +278,9 @@ type ImageCreateArgs struct {
 	// Filename for the rootfs file
 	RootfsName string
 
+	// Image creation only for the image synchronization
+	SyncOnly bool
```
Comment (freeekanayaka) [inline client/interfaces.go]: I think you don't need this additional request flag. We already have an HTTP header that we use to tag requests that are coming from within nodes of the LXD cluster itself, rather than from the user. If you use the cluster.Connect() helper, like you do, then this header is set automatically for you, and you can use isClusterNotification(r) to check if it's present, and you can replace the ```shared.IsTrue(r.Header.Get("X-LXD-image-sync"))``` check.

File: test/suites/clustering.sh [hunk 16]
```diff
@@ -1052,3 +1052,113 @@ test_clustering_projects() {
...
+  [ -f "${LXD_ONE_DIR}/images/${fingerprint}" ] || false
+  [ -f "${LXD_TWO_DIR}/images/${fingerprint}" ] || false
+
+  # Delete the imported image
+  LXD_DIR="${LXD_ONE_DIR}" lxc image delete testimage
+  [ ! -f "${LXD_ONE_DIR}/images/${fingerprint}" ] || false
+  [ ! -f "${LXD_TWO_DIR}/images/${fingerprint}" ] || false
+
+  # Import the image from a URL
+  LXD_DIR="${LXD_TWO_DIR}" lxc image import https://dl.stgraber.org/lxd --alias busybox-amd64
```
Comment (freeekanayaka) [inline test/suites/clustering.sh]: I'm not sure we really want to test an actual URL, because it means the test needs to go on the network. At least, this should be executed conditionally only if the ```$LXD_OFFLINE``` environment variable is not ```1```.

@stgraber what do you think? should we keep this particular part of the test or just drop it?

I'd probably drop it.

Comment (stgraber) [reply test/suites/clustering.sh]: Yeah, I'd say let's drop that one. We don't have network access in most cases for our tests and when we do, there's no real guarantee that this particular URL will keep working.

**Comment by stgraber** [comment]
Just a few notes from reading through this.

 - I'm not sure why a custom HTTP header is used for this when we already have the UserAgent trick to detect internal cluster communications like this
 - I'm not a fan of `cluster.image_minimal_replica` as a configuration key name but don't have anything better to offer right now, suggestions welcome
 - The minimal number of copies I think should be equal to the number of database nodes by default (doesn't have to be the same nodes, but the same count would be a good starting point)
 - This branch is missing the usual set of documentation and API extension for such additions:
   - doc/api-extension.md
   - doc/server.md
   - shared/version/api.go
   - lxd/api_1.0.go
   - scripts/bash/lxd-client

**Comment by stgraber** [comment]
@freeekanayaka can you review?

**Comment by freeekanayaka** [comment]
The branch looks good to me. The only two issues that I see are:

1) I think the code would hit a race condition if there are 2 concurrent API requests to download the same image. Probably it would be better to ignore errors when calling ```client.CreateImage(image, createArgs)``` and then ```op.Wait()```, the code could just log a warning instead.

2) The code that checks skips nodes that are offline is doing 1 query per node (```tx.NodeByAddress(address)```), it would be slightly better to fetch the offline information in one query. I don't think we have a convenient database API in place to do that, and probably it's not a big issue in practice. So this is just something to keep in mind.

With all that being said, I'd be fine merging the branch, possibly after fixing 1). @stgraber opinions?

**Comment by morphis** [comment]
@freeekanayaka @stgraber Can you guys comment on the two points @adglkh raised about moving the sync process into the background?

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Branch doesn't build

**Comment by adglkh** [comment]
The branch is updated. 
Meanwhile @stgraber @freeekanayaka for the performance concerns, could you please take a look at my proposal about running task scheduler on the background to manage the image sync
Thanks in advance. 
https://github.com/lxc/lxd/pull/5216#issuecomment-436871905

**Comment by freeekanayaka** [comment]
@adglkh regarding your proposal, I think our original assumption was that it was not too expensive to transfer images between nodes, because they're on local network. However, if in the anbox use case it matters a lot that the image is already available on the target node, I don't see problems implementing the background task that you mention in the proposal.

**Comment by stgraber** [comment]
Yeah, same thought here. Image copies don't include image unpacking, so it should just take as long as is necessary for the tarball to be sent across the network, which on a gigabit network should only take a few seconds.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Code still won't build:

```
lxd/images.go:1961:2: undefined: err
lxd/images.go:1980:5: undefined: err
lxd/images.go:1981:10: undefined: err
```

Would be nice to at least do a test build before pushing to Github :)

**Comment by adglkh** [comment]
My stupid mistakes. It's resolved.
Also Thanks for your guys detailed comments on my proposal. I'll create a separated MP that moving the image sync operations to the background.
For anbox, the application bootup time is really crucial for the user experience, which requires us to have an image as a base, which can be used to create an application image from the container launched from the base image.
Typically, an uncompressed application image is about ~1.1G and when we enable the image sync across the nodes in the cluster, the application image creation would take a long time than expected due to the image size and the numbers of nodes. When we try the different compression algorithms, it yields the following results with a single lxd node on AWS
```
App image creation from the container, application sample: Clash of clan, instance-type: a4.3
1. `none`  compression algorithm, time consuming: 6.302423721s  resulting image size: 1129.17MB
2. `xz`    compression algorithm, time consuming: 8m6.810657366s  resulting image size: 384.40MB
3. `bzip2` compression algorithm, time consuming: 1m58.944791679s resulting image size: 473.01MB
4. `lzma` compression algorithm, time consuming: 8m1.093280862s resulting image size: 385.32MB
5. `gzip` compression algorithm, time consuming: 54.106132546s  resulting image size: 498.15MB
 ```
So having a task scheduler running on the background would be a good fit for us and image upload can be performed as one-shot operation as it does in the past. Moreover,  images would not be out of sync in the cluster if nodes are added/removed dynamically if a scheduler for image sync is supported in the lxd.

**Comment by freeekanayaka** [comment]
Thanks for the benchmarks, that makes sense.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Please rebase

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
This is next on my list to look at, plan is to do any minor fixups needed and get this in time for 3.8.

**Comment by stgraber** [comment]
This branch isn't `go fmt ./...` clean. Please fix.

**Comment by adglkh** [comment]
Resolved. 
Thanks!

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Mostly done with re-organizing the commits and doing a few cosmetic changes.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@adglkh please test your branch in your setup, if this works for you, I'll merge it before tagging LXD 3.8.

**Comment by adglkh** [comment]
Fetching the latest commits and the branch works fine under my local setup.
Thanks.

BTW: One jenkins job hangs somehow for quite a long time while executing the integration test against this branch 
See:
https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5342/arch=amd64,backend=dir,compiler=golang-1.10,restrict=lxd-priv/console
