### PR TITLE
lxd: Update logic for project config patch

### LINKED ISSUE #13632: `PATCH /1.0/projects/<project>` removes existing configuration
When you try to update a specific configuration option for a project using PATCH, existing configuration options are discarded:

```
ubuntu@ru-fu01:~$ lxc project show my-project1
name: my-project1
description: ""
config:
  features.images: "false"
  features.profiles: "false"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
used_by: []
ubuntu@ru-fu01:~$ lxc query --request PATCH /1.0/projects/my-project1 --data '{
  "config": {
    "limits.containers": "5"
  }
}'
Error: Delete project default profile: Profile not found
ubuntu@ru-fu01:~$ lxc query --request PATCH /1.0/projects/my-project1 --data '{
  "config": {
    "limits.containers": "5",
    "features.profiles": "false"
  }
}'
ubuntu@ru-fu01:~$ lxc project show my-project1
name: my-project1
description: ""
config:
  features.profiles: "false"
  limits.containers: "5"
used_by: []
```

This could be regarded as intended behaviour (since you're updating the "config" field - which could mean the FULL "config" field). But this is inconsistent with how PATCH works for, for example, profiles:

```
ubuntu@ru-fu01:~$ lxc profile show testprofile
name: testprofile
description: ""
config:
  limits.cpu: "4"
  limits.memory: 1GiB
devices:
  root:
    path: /
    pool: default
    size: 1GiB
    type: disk
used_by: []
ubuntu@ru-fu01:~$ lxc query --request PATCH /1.0/profiles/testprofile --data '{
  "config": {
    "user.test": "hello"
  }                                 
}'
ubuntu@ru-fu01:~$ lxc profile show testprofile
name: testprofile
description: ""
config:
  limits.cpu: "4"
  limits.memory: 1GiB
  user.test: hello
devices:
  root:
    path: /
    pool: default
    size: 1GiB
    type: disk
used_by: []
```

### PR DESCRIPTION
**Pull request by boltmark**
This PR provides an update to the logic for patching project configurations. Previously, there was an overwrite of the existing project config such that it was updated to consist solely of the data in the patch. With this update we maintain existing key/value pairs, and only overwrite those also present in the patch.

Closes #13632.

### CODE REVIEW

File: lxd/api_project.go [hunk 1]
```diff
@@ -599,16 +599,18 @@ func projectPatch(d *Daemon, r *http.Request) response.Response {
...
+	patches, err := reqRaw.GetMap("config")
+	if err == nil {
+		for k, v := range patches {
+			strVal, ok := v.(string)
+			if ok {
+				req.Config[k] = strVal
 			}
 		}
+	} else {
+		logger.Error("Failed retrieving config map from request", logger.Ctx{"err": err})
```
Comment (tomponline) [inline lxd/api_project.go:613]: Does this fire if no input config is supplied by the request? 

I'm wondering why the current version has:

```go
config, err := reqRaw.GetMap("config")
	if err != nil {
		req.Config = project.Config
```

As I don't think we should be logging an error if a valid request with no config comes in for the patch request, we should just not updating anything in the config part.

**Comment by tomponline** [comment]
@boltmark Please can you add a test for updating projects via PATCH, see `test_certificate_edit` function in the tests dir for an example of patch tests.

```
my_curl -X PATCH -d "{\"certificate\":\"$(sed ':a;N;$!ba;s/\n/\\n/g' "${LXD_CONF}/client-new.crt")\"}" "https://${LXD_ADDR}/1.0/certificates/${FINGERPRINT}"
```

You can add it to the projects.sh file in the `test_projects_crud` function.

File: lxd/api_project.go (hunk 1 above)
Comment (boltmark) [reply lxd/api_project.go:613]: Good point -- with the incoming changes I do see the error logged if no input config is supplied. I agree that it's not a good idea to log an error here since the input is technically valid. Will fix this.

**Comment by boltmark** [comment]
@tomponline Thanks for the comments. I have added testing for updating project configs via PATCH in `projects.sh` under `test_projects_crud`. I have also removed the error logging as per the above comment. This is ready for another review!

**Review by tomponline — APPROVED** [review]
Thanks!
