### PR TITLE
Revert database on joining node if cluster join fails

### LINKED ISSUE #12624: Clean up after cluster join errors
#12571 addressed an issue where dqlite would report back that it was busy, and LXD would error out its attempt to join a cluster. This was a problem in the first place because LXD didn't handle an error at this point very well, and would leave the joining node unrecoverable. 

What we should do here is include some `revert` hooks to clean up a failed attempt at joining a cluster so that the joiner returns back to a state where it can be requested to join a cluster or be initialized.

### PR DESCRIPTION
**Pull request by masnax**
Closes #12624 

Joining dqlite happens in the `Join` function under `lxd/cluster/membership.go` where we lock the global database, create raft node entries in the local database, and reload the gateway. If there's an issue on the dqlite end that prevents us from joining the cluster, we error out and return, but the database is still locked, and the gateway will still behave as though the node has joined the cluster. This leaves the node in an unrecoverable state as the node will perpetually wait for for connections to a cluster that it's not a part of.

To fix that, this adds some revert hooks that ensure the node returns to a state where we can tell it to re-join the cluster with a new join token. In particular, the revert hooks clear out the raft nodes in the local database, refresh the gateway again to pick this up, and unlocks the global database.

### CODE REVIEW

**Comment by masnax** [comment]
Looks like the linter didn't like this one too much. 

I've fixed most of the issues, but I had to add an exception for `deep-exit` which limits calls to `os.Exit()` to the `main` and `init` functions. When we remove a node from a cluster, it tries to re-exec itself, but we just exit if we detect that LXD is using systemd socket activation. Not sure if there's a cleaner way to reconcile this.

File: lxd/cluster/membership.go [hunk 1]
```diff
@@ -401,12 +414,48 @@ func Join(state *state.State, gateway *Gateway, networkCert *shared.CertInfo, se
...
+			return
+		}
+
+		err = gateway.Shutdown()
+		if err != nil {
+			logger.Error("Failed to shutdown gateway after cluster join error", logger.Ctx{"error": err})
+			return
+		}
+
+		err = os.RemoveAll(state.OS.GlobalDatabaseDir())
```
Comment (tomponline) [inline lxd/cluster/membership.go:439]: What happens if the joining server already had data in it?

File: lxd/cluster/membership.go [hunk 2]
```diff
@@ -457,15 +457,15 @@ func Join(state *state.State, gateway *Gateway, networkCert *shared.CertInfo, se
...
 	for _, node := range raftNodes {
 		if node.Address == localClusterAddress {
-			info = &node
+			info = node
 		}
 	}
 
-	if info == nil {
-		panic("Joining member not found")
+	if (db.RaftNode{}) == info {
```
Comment (tomponline) [inline lxd/cluster/membership.go:467]: what was the linter error here?

File: lxd/cluster/membership.go (hunk 1 above)
Comment (masnax) [reply lxd/cluster/membership.go:439]: We`re clearing out the database files so any data would be gone. I thought about preserving the old database files, but then considering that we prompt the user with a warning during init that joining a cluster will wipe existing data, I went went with the simpler choice since the user already consented to sacrificing the data. 

We could just move the old files to a tmpdir and defer the removal.

File: lxd/cluster/membership.go (hunk 2 above)
Comment (masnax) [reply lxd/cluster/membership.go:467]: I can't actually grab the rule for you at the moment since my LXD environment is busted but I recall the error was about assigning to a pointer of a loop var, which always has the same address.

Comment (masnax) [reply lxd/cluster/membership.go:467]: `range-val-address`

File: lxd/cluster/membership.go (hunk 1 above)
Comment (masnax) [reply lxd/cluster/membership.go:439]: For context (since it's hidden in the diff), prior to this change we were already wiping all data on the existing node:

https://github.com/canonical/lxd/blob/0aabb554848e5bc708260a9390eea529551ada0b/lxd/cluster/membership.go#L396-L399

**Review by tomponline — APPROVED** [review]
Would it be possible to add a test for this?
